`timescale 1ns / 1ps
// =============================================================================
// dac_stream_spi.v — AD3552R 파형 재생용 SPI 스트리밍 마스터
// Generated by Claude Code, 2026-09-09
//
//  [무엇인가]
//  AXI4-Stream 으로 들어오는 16비트 DAC 코드를 정확히 PERIOD 클럭 간격으로
//  AD3552R 에 밀어 넣는다. 상류는 AXI DMA(MM2S)가 DDR 에서 읽어 오고, 하류는
//  FMC 커넥터의 SPI 4선이다.
//
//  [왜 axi_quad_spi 로는 안 되나 — 실측 근거]
//    Phase 2.5 에서 axi_quad_spi + CPU 루프로 150,146 SPS 를 실측했다.
//    10 kHz 처프 × 250 점 = 2.5 MSPS 가 필요하므로 17배 부족하다.
//    axi_quad_spi 는 SCK 상한이 ext_spi_clk/2 이고 프레임마다 CPU 또는 AXI
//    트랜잭션이 끼어들어 연속 재생을 못 한다. 그래서 전용 FSM 을 만든다.
//
//  [AD3552R 스트리밍 모드 — 데이터시트 Rev.B p.30 "Streaming Mode"]
//    · SINGLE_INSTRUCTION=0 (기본값) 이면 스트리밍 모드다.
//    · STREAM_MODE(0x0E) = 2 로 두면 데이터 위상에서 2바이트마다 주소가
//      명령 위상에서 준 주소로 되돌아간다 (looping).
//    · TRANSFER_REGISTER(0x0F) 의 STREAM_LENGTH_KEEP_VALUE = 1 이면 CS 가
//      올라가도 STREAM_MODE 값이 유지된다.
//    · 데이터시트 그대로 : "This feature allows writing the same range of
//      registers continuously within the same transaction, which is useful
//      for waveform playback."
//    · 주소 0x29 이상은 반드시 내림차순(descending)이어야 하고, 내림차순에서는
//      MSB 부터 보낸다. 그래서 명령 바이트는 0x2A (= CH0_DAC_16B 의 상위 바이트).
//    · CHx_DAC 레지스터에 쓰면 출력이 즉시 갱신된다 (Table 15 "DAC Update Modes"
//      의 "Quad, Dual and Single SPI / CHx_DAC / Not applicable / Output
//      updates immediately"). LDAC 가 필요 없다.
//
//  [★ 2026-09-09 — 멀티 IO(1/2/4 레인) 지원 추가]
//    데이터시트 Rev.B p.34-36 "SERIAL INTERFACE" 와 Table 14 근거:
//
//    · Dual SPI  : TRANSFER_REGISTER(0x0F) MULTI_IO_MODE=01 **레지스터만으로** 켜진다.
//                  QSPI 핀이 LOW 면 primary 영역(0x00~0x1E)은 classic 을 유지하고
//                  secondary 영역(0x28~0x4B)만 dual 이 된다. 우리가 쓰는 0x2A 는
//                  secondary 라, **설정용 axi_quad_spi 경로를 건드리지 않고** 2배가 된다.
//    · Quad SPI  : Table 14 각주 — "Enabled by the QSPI pin only",
//                  MULTI_IO_MODE 은 "Not applicable". 즉 레지스터로는 못 켠다.
//                  그리고 QSPI 핀이 HIGH 면 "the interface is configured in full quad
//                  SPI mode for any communication to primary or secondary region"
//                  이라 **설정 경로도 quad 가 된다** — axi_quad_spi(단선)로는 더 이상
//                  레지스터를 못 건드린다. 그래서 순서가 중요하다:
//                    (1) QSPI_SEL=0 인 채로 classic 으로 전부 설정
//                    (2) EN=0(=CS 높음) 인 상태에서 QSPI_SEL=1
//                    (3) EN=1 로 재생 시작
//                  ("After changing the SPI mode ... CS must be brought high and a
//                    new access cycle must be started in the appropriate mode")
//    · DDR       : SPI_CONFIG_DDR (INTERFACE_CONFIG_D 0x14). **이 모듈은 지원하지 않는다.**
//                  DDR 은 데이터가 양 에지에서 잡히므로 SCK 를 데이터 눈 가운데에
//                  놓아야 하고(90도 시프트 클럭 + ODDR), 패브릭 플립플롭만으로는
//                  셋업이 0 이 된다. 별도 작업이다.
//
//    [비트 순서] "consecutive bits are serialized in groups of two/four".
//      상위 IO 가 상위 비트다 — quad 첫 클럭은 SDIO3=bit15 … SDIO0=bit12.
//
//    [★ 명령 위상의 레인 수는 확정하지 못했다]
//      데이터시트 본문에 명령 위상만 1선으로 낮춘다는 문구가 없고, 그림(Figure 9)은
//      텍스트 추출로 확인할 수 없었다. 전체 프레임이 같은 폭일 가능성이 높지만
//      확신할 수 없어 CFG.INSTR_X1 레지스터로 양쪽을 다 시도할 수 있게 했다.
//      실물에서 한 번 확인하면 그 값으로 고정할 것.
//
//  [타이밍]
//    SPI mode 0 (CPOL=0, CPHA=0). Phase 1/2 에서 SPICR = 0x086 (bit3 CPOL=0,
//    bit4 CPHA=0) 으로 통신이 확인됐으므로 같은 모드를 쓴다.
//    SCK 반주기 = SCK_DIV × aclk. SCK = aclk / (2 × SCK_DIV).
//    한 샘플 = 16/LANES SCK 사이클 = (32/LANES) × SCK_DIV aclk 클럭.
//      LANES=1 -> 32×DIV     LANES=2 -> 16×DIV     LANES=4 -> 8×DIV
//
//  [검증 상태]  2026-09-09
//    ✅ 시뮬레이션 — Orin 에 iverilog 12.0 을 소스 빌드해 넣고 실제로 돌렸다.
//       sim/run_iverilog.sh 가 회귀 시험이다. 확인된 것:
//         · 샘플 간격이 정확히 PERIOD 클럭 (min==max), 4개 설정에서
//         · 워드 내 SCK 주기 = 2×SCK_DIV×aclk (표본 862개, min==max)
//         · 명령 바이트 0x2A 가 프레임당 한 번만
//         · 슬레이브가 복원한 16비트가 보낸 코드와 일치 (MSB 우선, mode 0)
//         · t2(CS↓→첫 SCK↑) 90~140 ns — 데이터시트 최소 5 ns 충족
//         · 언더런 시 직전 값 유지 + STATUS 의 sticky 비트, CLR_STATUS 로 해제
//         · EN=0 일 때 cfg_* 통과, 정지 시 CS 복귀
//         · 음성 시험 : PERIOD < 32×SCK_DIV 이면 OVERRUN 이 선다
//    ❌ 합성 / 타이밍 / 실물 — 아직 안 했다. 회사 노트북에서 해야 한다.
//
//    ★ RTL 을 고치면 커밋 전에 sim/run_iverilog.sh 를 돌릴 것.
//
//  [★ 브링업은 느린 SCK 부터]
//    SCK 50 MHz 는 FMC 를 지나는 단일종단 신호로 공격적이고 출력 지연 제약이
//    아직 실측 검증되지 않았다. SCK_DIV 를 레지스터로 둔 이유가 이것이다.
//      DIV=6 (8.33 MHz, N=50) -> DIV=3 (16.67 MHz, N=100) -> DIV=1 (50 MHz, N=250)
//
//  [레지스터 맵]  (AXI4-Lite, 32비트, 베이스 0x43C00000)
//    0x00  ID       RO  0x44414333 ("DAC3")
//    0x04  CTRL     RW  [0] EN            1=재생, 0=정지(현재 워드 끝나고 CS↑)
//                       [1] CLR_STATUS    1 쓰면 STATUS 의 sticky 비트 클리어(자동복귀)
//    0x08  CFG      RW  [7:0]   SCK_DIV    SCK 반주기 [aclk], 최소 1
//                       [15:8]  INSTR      명령 바이트, 기본 0x2A
//                       [17:16] LANES      00=1선  01=2선(dual)  10=4선(quad)
//                       [18]    INSTR_X1   1 이면 명령 위상만 1선으로 (미확정 대비)
//    0x0C  PERIOD   RW  [15:0] 샘플 간격 [aclk], (32/LANES)×SCK_DIV 이상이어야 한다
//    0x10  STATUS   RO  [0] RUNNING  [1] UNDERRUN(sticky)  [2] OVERRUN(sticky)
//                       [3] CS_LOW
//    0x14  SAMPCNT  RO  EN 이 올라간 뒤 내보낸 샘플 수 (32비트, 랩어라운드)
//
//    ※ CFG / PERIOD 는 EN 이 올라가는 순간에 래치된다. 재생 중에 써도 다음
//      EN 상승까지 반영되지 않는다 — 주기가 도중에 바뀌면 조용히 틀리기 때문이다.
// =============================================================================

module dac_stream_spi #(
    // ★ 12 = 4 KB. AXI 슬레이브의 최소 어퍼처가 4 KB 라 그보다 작게 잡으면
    //   assign_bd_address 가 거부한다. 레지스터는 맨 아래 0x00~0x14 만 쓴다.
    parameter integer C_S_AXI_ADDR_WIDTH = 12,
    parameter [31:0]  ID_VALUE           = 32'h4441_4333   // "DAC3"
)(
    input  wire                              aclk,
    input  wire                              aresetn,

    // ------------------------------------------------ AXI4-Lite 슬레이브
    input  wire [C_S_AXI_ADDR_WIDTH-1:0]     s_axi_awaddr,
    input  wire [2:0]                        s_axi_awprot,
    input  wire                              s_axi_awvalid,
    output wire                              s_axi_awready,
    input  wire [31:0]                       s_axi_wdata,
    input  wire [3:0]                        s_axi_wstrb,
    input  wire                              s_axi_wvalid,
    output wire                              s_axi_wready,
    output wire [1:0]                        s_axi_bresp,
    output wire                              s_axi_bvalid,
    input  wire                              s_axi_bready,
    input  wire [C_S_AXI_ADDR_WIDTH-1:0]     s_axi_araddr,
    input  wire [2:0]                        s_axi_arprot,
    input  wire                              s_axi_arvalid,
    output wire                              s_axi_arready,
    output wire [31:0]                       s_axi_rdata,
    output wire [1:0]                        s_axi_rresp,
    output wire                              s_axi_rvalid,
    input  wire                              s_axi_rready,

    // ------------------------------------------------ AXI4-Stream 슬레이브 (32비트)
    //  한 beat 에 샘플 두 개. tdata[15:0] 이 먼저, tdata[31:16] 이 나중.
    //  DDR 의 uint16_t 배열을 리틀엔디언으로 읽으면 자연히 이 순서가 된다.
    input  wire [31:0]                       s_axis_tdata,
    input  wire [3:0]                        s_axis_tkeep,
    input  wire                              s_axis_tlast,
    input  wire                              s_axis_tvalid,
    output wire                              s_axis_tready,

    // ------------------------------------------------ 설정용 SPI (axi_quad_spi)
    //  EN=0 일 때 아래 4선이 그대로 핀으로 통과한다. Phase 1/2 에서 검증된
    //  레지스터 읽기·쓰기 경로를 그대로 쓰기 위해서다.
    input  wire                              cfg_sck,
    input  wire                              cfg_cs_n,
    input  wire                              cfg_mosi,
    output wire                              cfg_miso,

    // ------------------------------------------------ FMC 핀
    //  ★ sdio1 만 inout 이다. classic 모드에서는 DAC 의 SDO(출력)이고,
    //    dual/quad 에서는 우리가 미는 SDIO1 이다. 나머지는 단방향으로 충분하다:
    //    쓰기 프레임(R/W=0)만 내보내므로 DAC 가 sdio0/2/3 을 구동하는 경우가 없다.
    output wire                              dac_sck,
    output wire                              dac_cs_n,
    output wire                              dac_sdio0,
    inout  wire                              dac_sdio1,
    output wire                              dac_sdio2,
    output wire                              dac_sdio3
);

    // =========================================================================
    // 1. AXI4-Lite 슬레이브
    // =========================================================================
    localparam ADDR_LSB = 2;   // 32비트 워드 정렬

    reg                              awready_r, wready_r, bvalid_r;
    reg                              arready_r, rvalid_r;
    reg [31:0]                       rdata_r;
    reg [C_S_AXI_ADDR_WIDTH-1:0]     awaddr_r, araddr_r;

    assign s_axi_awready = awready_r;
    assign s_axi_wready  = wready_r;
    assign s_axi_bresp   = 2'b00;
    assign s_axi_bvalid  = bvalid_r;
    assign s_axi_arready = arready_r;
    assign s_axi_rdata   = rdata_r;
    assign s_axi_rresp   = 2'b00;
    assign s_axi_rvalid  = rvalid_r;

    // 쓰기 주소
    always @(posedge aclk) begin
        if (!aresetn) begin
            awready_r <= 1'b0;
        end else if (!awready_r && s_axi_awvalid && s_axi_wvalid && !bvalid_r) begin
            awready_r <= 1'b1;
            awaddr_r  <= s_axi_awaddr;
        end else begin
            awready_r <= 1'b0;
        end
    end

    // 쓰기 데이터
    always @(posedge aclk) begin
        if (!aresetn)
            wready_r <= 1'b0;
        else
            wready_r <= (!wready_r && s_axi_wvalid && s_axi_awvalid && !bvalid_r);
    end

    wire wr_en = awready_r && wready_r;

    // 쓰기 응답
    always @(posedge aclk) begin
        if (!aresetn)            bvalid_r <= 1'b0;
        else if (wr_en)          bvalid_r <= 1'b1;
        else if (s_axi_bready && bvalid_r) bvalid_r <= 1'b0;
    end

    // 읽기 주소
    always @(posedge aclk) begin
        if (!aresetn) begin
            arready_r <= 1'b0;
        end else if (!arready_r && s_axi_arvalid && !rvalid_r) begin
            arready_r <= 1'b1;
            araddr_r  <= s_axi_araddr;
        end else begin
            arready_r <= 1'b0;
        end
    end

    // =========================================================================
    // 2. 레지스터
    // =========================================================================
    reg         ctrl_en;
    reg  [7:0]  cfg_sck_div;      // 최소 1
    reg  [7:0]  cfg_instr;
    reg  [1:0]  cfg_lanes;        // 00=1선 01=2선 10=4선
    reg         cfg_instr_x1;
    reg  [15:0] cfg_period;
    reg         clr_status;

    //  레인 부호 -> 실제 선 수. 11 은 잘못된 값이므로 4 로 접는다.
    function [3:0] lanes_of(input [1:0] code);
        lanes_of = (code == 2'b00) ? 4'd1 : (code == 2'b01) ? 4'd2 : 4'd4;
    endfunction

    reg         st_underrun, st_overrun;
    reg  [31:0] sampcnt;

    // 실행 중 고정되는 래치본
    reg  [7:0]  div_l;
    reg  [7:0]  instr_l;
    reg  [15:0] period_l;

    wire [31:0] status_w;

    always @(posedge aclk) begin
        if (!aresetn) begin
            ctrl_en     <= 1'b0;
            cfg_sck_div <= 8'd6;        // 8.33 MHz — 브링업 기본값 (느린 쪽)
            cfg_instr   <= 8'h2A;       // CH0_DAC_16B 상위 바이트, 내림차순
            cfg_lanes   <= 2'b00;       // 단선 — 검증된 기본값
            cfg_instr_x1<= 1'b0;
            cfg_period  <= 16'd200;     // N=50 @10 kHz
            clr_status  <= 1'b0;
        end else begin
            clr_status <= 1'b0;
            if (wr_en) begin
                case (awaddr_r[C_S_AXI_ADDR_WIDTH-1:ADDR_LSB])
                    6'h01: begin                        // 0x04 CTRL
                        if (s_axi_wstrb[0]) begin
                            ctrl_en    <= s_axi_wdata[0];
                            clr_status <= s_axi_wdata[1];
                        end
                    end
                    6'h02: begin                        // 0x08 CFG
                        if (s_axi_wstrb[0]) cfg_sck_div <= (s_axi_wdata[7:0] == 8'd0)
                                                            ? 8'd1 : s_axi_wdata[7:0];
                        if (s_axi_wstrb[1]) cfg_instr   <= s_axi_wdata[15:8];
                        if (s_axi_wstrb[2]) begin
                            cfg_lanes    <= s_axi_wdata[17:16];
                            cfg_instr_x1 <= s_axi_wdata[18];
                        end
                    end
                    6'h03: begin                        // 0x0C PERIOD
                        if (s_axi_wstrb[0]) cfg_period[7:0]  <= s_axi_wdata[7:0];
                        if (s_axi_wstrb[1]) cfg_period[15:8] <= s_axi_wdata[15:8];
                    end
                    default: ;
                endcase
            end
        end
    end

    // 읽기 데이터
    always @(posedge aclk) begin
        if (!aresetn) begin
            rvalid_r <= 1'b0;
            rdata_r  <= 32'd0;
        end else if (arready_r && s_axi_arvalid && !rvalid_r) begin
            rvalid_r <= 1'b1;
            case (araddr_r[C_S_AXI_ADDR_WIDTH-1:ADDR_LSB])
                6'h00:   rdata_r <= ID_VALUE;
                6'h01:   rdata_r <= {31'd0, ctrl_en};
                6'h02:   rdata_r <= {13'd0, cfg_instr_x1, cfg_lanes, cfg_instr, cfg_sck_div};
                6'h03:   rdata_r <= {16'd0, cfg_period};
                6'h04:   rdata_r <= status_w;
                6'h05:   rdata_r <= sampcnt;
                default: rdata_r <= 32'd0;
            endcase
        end else if (rvalid_r && s_axi_rready) begin
            rvalid_r <= 1'b0;
        end
    end

    // =========================================================================
    // 3. 스트림 입력 버퍼 — 한 beat(32비트)에 샘플 두 개
    // =========================================================================
    reg  [31:0] beat_q;
    reg         beat_full;
    reg         beat_half;      // 0 = 다음에 하위 16비트, 1 = 상위 16비트

    wire        take_sample;    // 이 클럭에 샘플 하나를 소비한다 (아래 FSM 이 낸다)
    wire [15:0] next_sample = beat_half ? beat_q[31:16] : beat_q[15:0];
    wire        sample_avail = beat_full;

    //  ★ ctrl_en 으로 게이트해야 한다. EN=0 일 때 아래 always 가 beat_full 을
    //    매 클럭 0 으로 눌러 두는데, tready 를 !beat_full 로만 두면 tready=1 이
    //    되어 DMA 가 보낸 beat 를 받아 놓고 버린다. 그러면 재생을 켰을 때
    //    파형이 몇 점 밀린 채로 시작한다 — 조용히 틀리는 종류의 버그다.
    assign s_axis_tready = ctrl_en && !beat_full;

    always @(posedge aclk) begin
        if (!aresetn || !ctrl_en) begin
            beat_full <= 1'b0;
            beat_half <= 1'b0;
        end else begin
            // 채우기 : 비어 있을 때만. take_sample 로 비는 것은 다음 클럭에 보인다.
            if (!beat_full && s_axis_tvalid) begin
                beat_q    <= s_axis_tdata;
                beat_full <= 1'b1;
                beat_half <= 1'b0;
            end
            // 꺼내기
            if (take_sample && beat_full) begin
                if (beat_half) begin
                    beat_full <= 1'b0;
                    beat_half <= 1'b0;
                end else begin
                    beat_half <= 1'b1;
                end
            end
        end
    end

    // =========================================================================
    // 4. 재생 FSM
    // =========================================================================
    localparam [2:0] S_IDLE  = 3'd0,   // CS 높음, 아무것도 안 함
                     S_CSLO  = 3'd1,   // CS 내리고 t2(=CS↓ -> 첫 SCK↑) 확보
                     S_INSTR = 3'd2,   // 명령 8비트
                     S_RUN   = 3'd3,   // PERIOD 격자로 16비트씩
                     S_TAIL  = 3'd4;   // t3(마지막 SCK -> CS↑) 확보 후 CS 올림

    reg [2:0]  state;
    reg [7:0]  divcnt;
    reg [15:0] pcnt;               // 샘플 격자 카운터 0..period_l-1
    reg [4:0]  cyccnt;             // 남은 SCK 사이클 수 (비트 수가 아니다)
    reg [15:0] shreg;
    reg        busy;               // 비트 엔진 동작 중
    reg        sck_q, cs_n_q;
    reg [3:0]  dout_q;             // {sdio3, sdio2, sdio1, sdio0}
    reg [3:0]  cur_lanes;          // 지금 내보내는 워드의 선 수 (1/2/4)
    reg [15:0] last_sample;
    reg [2:0]  guard;              // CS 앞뒤 여유 클럭

    reg [3:0]  lanes_l;            // 데이터 위상 선 수 (EN 상승에서 래치)
    reg        instr_x1_l;

    //  EN 상승 시점의 최소 격자 [aclk] = (16/LANES) × 2 × SCK_DIV
    wire [15:0] min_period =
        {11'd0, cyc16(lanes_of(cfg_lanes))} * 16'd2 *
        {8'd0, ((cfg_sck_div == 8'd0) ? 8'd1 : cfg_sck_div)};

    wire div_tick = (divcnt == div_l - 8'd1);

    //  ★ 2026-09-09 — 워드 적재의 1클럭 오버헤드를 없앤다.
    //    [무엇이 문제였나] 워드는 적재 에지 T 에서 시작해 T+2·cyc 에서 마지막
    //    하강으로 끝난다. 그런데 busy<=0 이 바로 그 T+2·cyc 에지에 걸리므로
    //    그 시점에 busy 를 읽으면 아직 1 이다. 그래서 격자를 정확히 2·cyc 로 잡으면
    //    매번 OVERRUN 이 뜨고 한 칸씩 건너뛰었다 (실측: quad 에서 간격이 2배).
    //    단선(2·cyc=32)에서는 격자가 40 이라 안 드러났고, dual/quad 로 내려오면서
    //    비로소 보였다.
    //    [고친 방법] "이번 에지가 엔진의 마지막" 임을 미리 알려 주는 신호를 만들어
    //    그때는 겹치기 적재를 허용한다. case 블록이 엔진 블록보다 뒤에 있으므로
    //    같은 에지에서 적재 대입이 엔진의 busy<=0 을 덮어쓴다.
    //    [효과] 최소 격자 = (32/LANES)×SCK_DIV 가 정확히 성립한다.
    //           quad·DIV=1 이면 8 클럭 -> 10 kHz 에서 1250 점이 딱 맞는다.
    wire eng_last = busy && div_tick && sck_q && (cyccnt == 5'd1);

    //  ★ 멀티 IO 직렬화. "consecutive bits are serialized in groups of two/four"
    //    (데이터시트 p.34-36). 상위 IO 가 상위 비트다 —
    //    quad 첫 클럭은 SDIO3=bit15, SDIO2=bit14, SDIO1=bit13, SDIO0=bit12.
    function [15:0] shl_n(input [15:0] x, input [3:0] n);
        shl_n = (n == 4'd4) ? {x[11:0], 4'd0}
              : (n == 4'd2) ? {x[13:0], 2'd0}
              :               {x[14:0], 1'd0};
    endfunction

    function [3:0] nib_n(input [15:0] x, input [3:0] n);
        nib_n = (n == 4'd4) ? x[15:12]
              : (n == 4'd2) ? {2'b00, x[15:14]}
              :               {3'b000, x[15]};
    endfunction

    //  16비트 / 8비트를 내보내는 데 필요한 SCK 사이클 수
    function [4:0] cyc16(input [3:0] n);
        cyc16 = (n == 4'd4) ? 5'd4 : (n == 4'd2) ? 5'd8 : 5'd16;
    endfunction
    function [4:0] cyc8(input [3:0] n);
        cyc8  = (n == 4'd4) ? 5'd2 : (n == 4'd2) ? 5'd4 : 5'd8;
    endfunction

    // 샘플 소비는 "격자가 도는 순간" 한 클럭만.
    reg  take_r;
    assign take_sample = take_r;

    always @(posedge aclk) begin
        if (!aresetn) begin
            state       <= S_IDLE;
            busy        <= 1'b0;
            sck_q       <= 1'b0;
            cs_n_q      <= 1'b1;
            dout_q      <= 4'd0;
            cur_lanes   <= 4'd1;
            lanes_l     <= 4'd1;
            instr_x1_l  <= 1'b0;
            divcnt      <= 8'd0;
            pcnt        <= 16'd0;
            cyccnt      <= 5'd0;
            shreg       <= 16'd0;
            take_r      <= 1'b0;
            guard       <= 3'd0;
            sampcnt     <= 32'd0;
            st_underrun <= 1'b0;
            st_overrun  <= 1'b0;
            last_sample <= 16'd0;
            div_l       <= 8'd1;
            instr_l     <= 8'h2A;
            period_l    <= 16'd200;
        end else begin
            take_r <= 1'b0;

            if (clr_status) begin
                st_underrun <= 1'b0;
                st_overrun  <= 1'b0;
            end

            // ---- 비트 엔진 (모든 상태 공통) --------------------------------
            //  SPI mode 0 : SCK 유휴 LOW. A반주기(SCK=0)에 데이터를 세우고,
            //  B반주기(SCK=1)에 슬레이브가 샘플한다. B 끝에서 다음 조각으로.
            //  한 사이클에 cur_lanes 비트가 나간다 (1/2/4).
            if (busy) begin
                if (div_tick) begin
                    divcnt <= 8'd0;
                    if (!sck_q) begin
                        sck_q <= 1'b1;                       // 상승 : 슬레이브 샘플
                    end else begin
                        sck_q  <= 1'b0;                      // 하강 : 다음 조각
                        shreg  <= shl_n(shreg, cur_lanes);
                        dout_q <= nib_n(shl_n(shreg, cur_lanes), cur_lanes);
                        cyccnt <= cyccnt - 5'd1;
                        if (cyccnt == 5'd1) begin
                            busy   <= 1'b0;
                            dout_q <= 4'd0;
                        end
                    end
                end else begin
                    divcnt <= divcnt + 8'd1;
                end
            end

            // ---- 상태 기계 --------------------------------------------------
            case (state)
            // -----------------------------------------------------------------
            S_IDLE: begin
                cs_n_q <= 1'b1;
                sck_q  <= 1'b0;
                dout_q <= 4'd0;
                busy   <= 1'b0;
                if (ctrl_en) begin
                    // 설정을 여기서 한 번만 래치한다. 재생 중 변경 금지.
                    div_l      <= (cfg_sck_div == 8'd0) ? 8'd1 : cfg_sck_div;
                    instr_l    <= cfg_instr;
                    lanes_l    <= lanes_of(cfg_lanes);
                    instr_x1_l <= cfg_instr_x1;
                    //  최소 격자 = (32/LANES) × SCK_DIV [aclk].
                    //  ★ 단위 주의 : cyc16() 은 **SCK 사이클** 수다. PERIOD 는 aclk
                    //    클럭 수이므로 ×2×DIV 를 해야 한다. 이걸 빠뜨리면 quad 에서
                    //    하한이 4 로 잡혀 클램프가 무의미해진다.
                    period_l   <= (cfg_period < min_period) ? min_period : cfg_period;
                    sampcnt    <= 32'd0;
                    cs_n_q     <= 1'b0;                      // CS 내림
                    guard      <= 3'd7;
                    state      <= S_CSLO;
                end
            end
            // -----------------------------------------------------------------
            //  t2 (CS↓ -> 첫 SCK↑) 최소 5 ns. 7 클럭 = 70 ns 로 넉넉히 잡는다.
            S_CSLO: begin
                if (guard != 3'd0) begin
                    guard <= guard - 3'd1;
                end else begin
                    //  명령 위상의 선 수. 데이터시트에서 확정하지 못해
                    //  INSTR_X1 로 양쪽을 다 시도할 수 있게 했다 (헤더 참조).
                    cur_lanes <= instr_x1_l ? 4'd1 : lanes_l;
                    shreg     <= {instr_l, 8'h00};
                    dout_q    <= nib_n({instr_l, 8'h00},
                                       instr_x1_l ? 4'd1 : lanes_l);
                    cyccnt    <= cyc8(instr_x1_l ? 4'd1 : lanes_l);
                    divcnt    <= 8'd0;
                    sck_q     <= 1'b0;
                    busy      <= 1'b1;
                    state     <= S_INSTR;
                end
            end
            // -----------------------------------------------------------------
            S_INSTR: begin
                if (!busy) begin
                    pcnt  <= 16'd0;
                    state <= S_RUN;
                end
            end
            // -----------------------------------------------------------------
            //  ★ 여기가 주기의 근거다. pcnt 는 자유 실행이고, 0 이 될 때마다
            //    16비트 전송을 시작한다. 따라서 샘플 간격은 정확히 period_l
            //    클럭이며, 소프트웨어가 뭘 하든 지터가 없다.
            S_RUN: begin
                if (pcnt == period_l - 16'd1) pcnt <= 16'd0;
                else                          pcnt <= pcnt + 16'd1;

                if (pcnt == 16'd0) begin
                    if (busy && !eng_last) begin
                        // 앞 샘플이 아직 안 끝났다 = PERIOD 가 (32/LANES)*DIV 보다 작다.
                        // 소프트웨어 설정 오류. 격자를 지키고 이번 샘플은 버린다.
                        st_overrun <= 1'b1;
                    end else if (!ctrl_en) begin
                        guard <= 3'd7;
                        state <= S_TAIL;
                    end else begin
                        if (sample_avail) begin
                            shreg       <= next_sample;
                            dout_q      <= nib_n(next_sample, lanes_l);
                            last_sample <= next_sample;
                            take_r      <= 1'b1;
                        end else begin
                            // 언더런 : 상류가 못 따라왔다. 직전 값을 다시 보낸다.
                            // (출력 전압 유지 + 스코프에 SCK 가 계속 보여 진단이 쉽다)
                            shreg       <= last_sample;
                            dout_q      <= nib_n(last_sample, lanes_l);
                            st_underrun <= 1'b1;
                        end
                        cur_lanes <= lanes_l;
                        cyccnt    <= cyc16(lanes_l);
                        divcnt    <= 8'd0;
                        sck_q     <= 1'b0;
                        busy      <= 1'b1;
                        sampcnt   <= sampcnt + 32'd1;
                    end
                end
            end
            // -----------------------------------------------------------------
            //  t3 (마지막 SCK 샘플 에지 -> CS↑) 최소 10 ns.
            S_TAIL: begin
                if (guard != 3'd0) guard <= guard - 3'd1;
                else begin
                    cs_n_q <= 1'b1;
                    state  <= S_IDLE;
                end
            end
            // -----------------------------------------------------------------
            default: state <= S_IDLE;
            endcase
        end
    end

    assign status_w = {28'd0, (cs_n_q == 1'b0), st_overrun, st_underrun,
                       (state != S_IDLE)};

    // =========================================================================
    // 5. 핀 먹싱 — EN 이 꺼져 있으면 axi_quad_spi 가 핀을 갖는다
    // =========================================================================
    //  Phase 1/2 에서 검증된 설정 경로(VENDOR 읽기, 레인지 쓰기 …)를 그대로
    //  쓰기 위해서다. 재생 중에는 FSM 이 갖는다.
    //  ★ 2026-09-10 — 선언과 대입을 분리했다.
    //    `wire owned = (state != S_IDLE);` 로 써 두었더니 IP 패키저의 HDL 파서가
    //    이걸 포트/파라미터로 오인해 경고를 냈다:
    //      WARNING: [IP_Flow 19-587] HDL port or parameter 'owned' has a
    //      dependency on the module local parameter or undefined parameter 'S_IDLE'.
    //    합성은 멀쩡했지만 XSA 메타데이터가 어긋나면 Vitis 의 디바이스 트리
    //    생성이 넘어질 수 있어 정리했다.
    wire owned;
    assign owned = (state != S_IDLE);

    //  ★ sdio1 만 삼상이다.
    //    classic 모드에서 sdio1 은 **DAC 의 출력**(SDO)이다 — 그때 우리가 구동하면
    //    양쪽이 맞붙는다. 그래서 dual/quad 재생 중에만 구동한다.
    //    (데이터시트 p.34 "In single SPI (classic) mode, the SDI/SDIO0 and
    //     SDO/SDIO1 data lines are unidirectional")
    wire sdio1_oe = owned && (cur_lanes >= 4'd2);

    // -------------------------------------------------------------------------
    //  ★★ 2026-09-09 — 출력 단을 한 번 더 등록해 IOB 플립플롭에 싣는다.
    //
    //  [무엇이 문제였나]  첫 구현에서 WNS = -4.992 ns 였다. 리포트를 보니
    //    에지 관계(Requirement 10.000 ns)는 정확했고, 문제는 데이터 경로였다:
    //      Data Path Delay 17.553 ns  (logic 3.005 / route 14.548 = 83 %)
    //      FSM_state_reg[0]/Q -> net(fo=66) 5.689 -> LUT5 -> net 8.859 -> OBUFT -> P18
    //    플립플롭 뒤에 통과 먹스 LUT 가 붙어 있고, 그 LUT 에서 FMC 패드까지
    //    8.9 ns 를 배선으로 갔다. state 레지스터가 66 개 부하를 몰고 있어
    //    배치기가 패드 근처로 끌어다 놓을 수도 없었다.
    //
    //  [고친 방법]  먹스 결과를 **출력 전용 플립플롭**에 한 번 더 받고 그 플립플롭을
    //    IOB(I/O 타일)에 packing 한다. 그러면 플립플롭에서 패드까지 배선이 사실상
    //    0 이 되고 논리 단도 사라진다. 남는 것은 clock-to-out + OBUF 뿐이다.
    //    (* IOB = "TRUE" *) 로 RTL 에 직접 붙였다 — XDC 에 두면 계층 이름이
    //    바뀔 때마다 깨진다.
    //
    //  [지연이 한 클럭 늘어난다 — 괜찮다]
    //    SCK / CS / 데이터 / 삼상제어가 **전부 같은 클럭으로 같이** 밀리므로
    //    서로의 상대 관계가 그대로다. 샘플 격자도, t2/t3 여유도 변하지 않는다.
    //    설정용 SPI(6.25 MHz)에 10 ns 가 더 붙는 것도 무의미하다.
    //
    //  [리셋을 동기로 둔 이유]  7-series 의 OLOGIC 플립플롭은 비동기 리셋이면
    //    IOB packing 이 거부된다. 아래는 전부 동기 리셋이다.
    // -------------------------------------------------------------------------
    (* IOB = "TRUE" *) reg       sck_o_r;
    (* IOB = "TRUE" *) reg       cs_n_o_r;
    (* IOB = "TRUE" *) reg       sdio1_t_r;    // 1 = Hi-Z (입력)
    (* IOB = "TRUE" *) reg [3:0] sdio_o_r;

    always @(posedge aclk) begin
        if (!aresetn) begin
            sck_o_r   <= 1'b0;
            cs_n_o_r  <= 1'b1;
            sdio_o_r  <= 4'd0;
            sdio1_t_r <= 1'b1;
        end else begin
            sck_o_r     <= owned ? sck_q     : cfg_sck;
            cs_n_o_r    <= owned ? cs_n_q    : cfg_cs_n;
            sdio_o_r[0] <= owned ? dout_q[0] : cfg_mosi;
            sdio_o_r[1] <= dout_q[1];
            sdio_o_r[2] <= owned ? dout_q[2] : 1'b0;
            sdio_o_r[3] <= owned ? dout_q[3] : 1'b0;
            sdio1_t_r   <= ~sdio1_oe;
        end
    end

    assign dac_sck   = sck_o_r;
    assign dac_cs_n  = cs_n_o_r;
    assign dac_sdio0 = sdio_o_r[0];
    assign dac_sdio2 = sdio_o_r[2];
    assign dac_sdio3 = sdio_o_r[3];
    assign dac_sdio1 = sdio1_t_r ? 1'bz : sdio_o_r[1];
    assign cfg_miso  = dac_sdio1;

    // 미사용 입력 — 합성 경고 방지
    wire _unused = &{1'b0, s_axi_awprot, s_axi_arprot, s_axis_tkeep,
                     s_axis_tlast, s_axi_wstrb[3], 1'b0};

endmodule
