`timescale 1ns / 1ps
// =============================================================================
// dac_chirp_engine.v — AD3552R 처프 재생기 (온칩 BRAM 핑퐁, DMA 없음)
// Generated by Claude Code, 2026-09-09
//
//  [무엇인가]
//  온칩 BRAM 두 장(핑퐁)에 든 처프 파형을 정확히 PERIOD 클럭 간격으로
//  AD3552R 에 밀어 넣는다. PS 는 AXI4-Lite 로 파형을 써 넣고 ON/OFF 만 한다.
//
//  [★★ 2026-09-10 — DDR + DMA 구조에서 온칩 BRAM 구조로 바꿨다]
//    전 : DDR -> axi_dma(SG 순환) -> axis FIFO -> 이 모듈(AXI4-Stream 슬레이브)
//    후 : PS 가 AXI-Lite 로 BRAM 에 파형 기록 -> 이 모듈이 BRAM 을 직접 읽음
//
//    [왜 바꾸나]
//    (1) 파형이 1024점 × 2 B = 2 KB 다. DDR 을 쓸 이유가 없다. BRAM 두 장이면
//        핑퐁까지 된다.
//    (2) DMA 를 쓰려면 PS 의 S_AXI_HP0 를 켜야 하는데, 그것이 2026-09-10 에
//        PS 디버그를 통째로 죽인 원인이었다 (§11). PL 이 PS 슬레이브 포트를
//        건드리지 않으면 그 위험 자체가 없어진다.
//    (3) 블록디자인이 Phase 2.5 의 검증된 구조에 가까워진다 — axi_dma,
//        axis_data_fifo, icn_hp, S_AXI_HP0 가 전부 빠진다.
//
//    ★ SPI 시프트 엔진과 IOB 출력단은 그대로다. iverilog 회귀 9 개를 통과한
//      부분이라 손대지 않았다.
//
//  [왜 axi_quad_spi 로는 안 되나 — 실측 근거]
//    Phase 2.5 에서 axi_quad_spi + CPU 루프로 150,146 SPS 를 실측했다.
//    10 kHz 처프 × 250 점 = 2.5 MSPS 가 필요하므로 17배 부족하다.
//    axi_quad_spi 는 SCK 상한이 ext_spi_clk/2 이고 프레임마다 CPU 또는 AXI
//    트랜잭션이 끼어들어 연속 재생을 못 한다. 그래서 전용 FSM 을 만든다.
//
//  [AD3552R 스트리밍 모드 — 데이터시트 Rev.B p.30 "Streaming Mode"]
//    · SINGLE_INSTRUCTION=0 (기본값) 이면 스트리밍 모드다.
//    · STREAM_MODE(0x0E) = 2 로 두면 데이터 위상에서 2바이트마다 주소가
//      명령 위상에서 준 주소로 되돌아간다 (looping).
//    · TRANSFER_REGISTER(0x0F) 의 STREAM_LENGTH_KEEP_VALUE = 1 이면 CS 가
//      올라가도 STREAM_MODE 값이 유지된다.
//    · 데이터시트 그대로 : "This feature allows writing the same range of
//      registers continuously within the same transaction, which is useful
//      for waveform playback."
//    · 주소 0x29 이상은 반드시 내림차순(descending)이어야 하고, 내림차순에서는
//      MSB 부터 보낸다. 그래서 명령 바이트는 0x2A (= CH0_DAC_16B 의 상위 바이트).
//    · CHx_DAC 레지스터에 쓰면 출력이 즉시 갱신된다 (Table 15 "DAC Update Modes"
//      의 "Quad, Dual and Single SPI / CHx_DAC / Not applicable / Output
//      updates immediately"). LDAC 가 필요 없다.
//
//  [★ 2026-09-09 — 멀티 IO(1/2/4 레인) 지원 추가]
//    데이터시트 Rev.B p.34-36 "SERIAL INTERFACE" 와 Table 14 근거:
//
//    · Dual SPI  : TRANSFER_REGISTER(0x0F) MULTI_IO_MODE=01 **레지스터만으로** 켜진다.
//                  QSPI 핀이 LOW 면 primary 영역(0x00~0x1E)은 classic 을 유지하고
//                  secondary 영역(0x28~0x4B)만 dual 이 된다. 우리가 쓰는 0x2A 는
//                  secondary 라, **설정용 axi_quad_spi 경로를 건드리지 않고** 2배가 된다.
//    · Quad SPI  : Table 14 각주 — "Enabled by the QSPI pin only",
//                  MULTI_IO_MODE 은 "Not applicable". 즉 레지스터로는 못 켠다.
//                  그리고 QSPI 핀이 HIGH 면 "the interface is configured in full quad
//                  SPI mode for any communication to primary or secondary region"
//                  이라 **설정 경로도 quad 가 된다** — axi_quad_spi(단선)로는 더 이상
//                  레지스터를 못 건드린다. 그래서 순서가 중요하다:
//                    (1) QSPI_SEL=0 인 채로 classic 으로 전부 설정
//                    (2) EN=0(=CS 높음) 인 상태에서 QSPI_SEL=1
//                    (3) EN=1 로 재생 시작
//                  ("After changing the SPI mode ... CS must be brought high and a
//                    new access cycle must be started in the appropriate mode")
//    · DDR       : SPI_CONFIG_DDR (INTERFACE_CONFIG_D 0x14). **이 모듈은 지원하지 않는다.**
//                  DDR 은 데이터가 양 에지에서 잡히므로 SCK 를 데이터 눈 가운데에
//                  놓아야 하고(90도 시프트 클럭 + ODDR), 패브릭 플립플롭만으로는
//                  셋업이 0 이 된다. 별도 작업이다.
//
//    [비트 순서] "consecutive bits are serialized in groups of two/four".
//      상위 IO 가 상위 비트다 — quad 첫 클럭은 SDIO3=bit15 … SDIO0=bit12.
//
//    [★ 명령 위상의 레인 수는 확정하지 못했다]
//      데이터시트 본문에 명령 위상만 1선으로 낮춘다는 문구가 없고, 그림(Figure 9)은
//      텍스트 추출로 확인할 수 없었다. 전체 프레임이 같은 폭일 가능성이 높지만
//      확신할 수 없어 CFG.INSTR_X1 레지스터로 양쪽을 다 시도할 수 있게 했다.
//      실물에서 한 번 확인하면 그 값으로 고정할 것.
//
//  [타이밍]
//    SPI mode 0 (CPOL=0, CPHA=0). Phase 1/2 에서 SPICR = 0x086 (bit3 CPOL=0,
//    bit4 CPHA=0) 으로 통신이 확인됐으므로 같은 모드를 쓴다.
//    SCK 반주기 = SCK_DIV × aclk. SCK = aclk / (2 × SCK_DIV).
//    한 샘플 = 16/LANES SCK 사이클 = (32/LANES) × SCK_DIV aclk 클럭.
//      LANES=1 -> 32×DIV     LANES=2 -> 16×DIV     LANES=4 -> 8×DIV
//
//  [검증 상태]  2026-09-09
//    ✅ 시뮬레이션 — Orin 에 iverilog 12.0 을 소스 빌드해 넣고 실제로 돌렸다.
//       sim/run_iverilog.sh 가 회귀 시험이다. 확인된 것:
//         · 샘플 간격이 정확히 PERIOD 클럭 (min==max), 4개 설정에서
//         · 워드 내 SCK 주기 = 2×SCK_DIV×aclk (표본 862개, min==max)
//         · 명령 바이트 0x2A 가 프레임당 한 번만
//         · 슬레이브가 복원한 16비트가 보낸 코드와 일치 (MSB 우선, mode 0)
//         · t2(CS↓→첫 SCK↑) 90~140 ns — 데이터시트 최소 5 ns 충족
//         · 언더런 시 직전 값 유지 + STATUS 의 sticky 비트, CLR_STATUS 로 해제
//         · EN=0 일 때 cfg_* 통과, 정지 시 CS 복귀
//         · 음성 시험 : PERIOD < 32×SCK_DIV 이면 OVERRUN 이 선다
//    ❌ 합성 / 타이밍 / 실물 — 아직 안 했다. 회사 노트북에서 해야 한다.
//
//    ★ RTL 을 고치면 커밋 전에 sim/run_iverilog.sh 를 돌릴 것.
//
//  [★ 브링업은 느린 SCK 부터]
//    SCK 50 MHz 는 FMC 를 지나는 단일종단 신호로 공격적이고 출력 지연 제약이
//    아직 실측 검증되지 않았다. SCK_DIV 를 레지스터로 둔 이유가 이것이다.
//      DIV=6 (8.33 MHz, N=50) -> DIV=3 (16.67 MHz, N=100) -> DIV=1 (50 MHz, N=250)
//
//  [레지스터 맵]  (AXI4-Lite, 32비트, 베이스 0x43C00000)
//    0x00  ID       RO  0x44414333 ("DAC3")
//    0x04  CTRL     RW  [0] EN            1=재생, 0=정지(현재 워드 끝나고 CS↑)
//                       [1] CLR_STATUS    1 쓰면 STATUS 의 sticky 비트 클리어(자동복귀)
//    0x08  CFG      RW  [7:0]   SCK_DIV    SCK 반주기 [aclk], 최소 1
//                       [15:8]  INSTR      명령 바이트, 기본 0x2A
//                       [17:16] LANES      00=1선  01=2선(dual)  10=4선(quad)
//                       [18]    INSTR_X1   1 이면 명령 위상만 1선으로 (미확정 대비)
//    0x0C  PERIOD   RW  [15:0] 샘플 간격 [aclk], (32/LANES)×SCK_DIV 이상이어야 한다
//    0x10  STATUS   RO  [0] RUNNING  [1] UNDERRUN(sticky)  [2] OVERRUN(sticky)
//                       [3] CS_LOW
//    0x14  SAMPCNT  RO  EN 이 올라간 뒤 내보낸 샘플 수 (32비트, 랩어라운드)
//
//    ※ CFG / PERIOD 는 EN 이 올라가는 순간에 래치된다. 재생 중에 써도 다음
//      EN 상승까지 반영되지 않는다 — 주기가 도중에 바뀌면 조용히 틀리기 때문이다.
// =============================================================================

module dac_chirp_engine #(
    // ★ 14 = 16 KB. 레지스터 + 파형 버퍼 두 장이 들어간다.
    //     0x0000~0x0FFF  레지스터
    //     0x1000~0x1FFF  버퍼 A (1024 워드, 하위 16비트만 사용)
    //     0x2000~0x2FFF  버퍼 B
    //   한 워드에 샘플 하나만 담는다. 절반을 버리지만 PS 코드가 단순해지고,
    //   4 KB × 2 = 8 KB 는 BRAM 두 장이라 아깝지 않다.
    parameter integer C_S_AXI_ADDR_WIDTH = 14,
    // ★ 2026-09-10 : $clog2 를 쓰지 않는다.
    //   Vivado 의 IP 패키저 HDL 파서가 $clog2 를 못 넘겨 모듈 파싱 자체가
    //   실패했고, 그 결과 버스 인터페이스가 하나도 추론되지 않았다:
    //     BD interface pin 'S_AXI' not found on 'dac_spi_0'. Available: (없음)
    //   모듈 참조로 써도 같은 파서를 타므로 마찬가지였다.
    //   주소 비트를 파라미터로 직접 준다. 아래 둘은 반드시 짝이 맞아야 한다:
    //     NPOINTS_MAX = 2**ADDR_BITS
    parameter integer NPOINTS_MAX        = 1024,
    parameter integer ADDR_BITS          = 10,
    parameter [31:0]  ID_VALUE           = 32'h4441_4333   // "DAC3"
)(
    input  wire                              aclk,
    input  wire                              aresetn,

    // ------------------------------------------------ AXI4-Lite 슬레이브
    input  wire [C_S_AXI_ADDR_WIDTH-1:0]     s_axi_awaddr,
    input  wire [2:0]                        s_axi_awprot,
    input  wire                              s_axi_awvalid,
    output wire                              s_axi_awready,
    input  wire [31:0]                       s_axi_wdata,
    input  wire [3:0]                        s_axi_wstrb,
    input  wire                              s_axi_wvalid,
    output wire                              s_axi_wready,
    output wire [1:0]                        s_axi_bresp,
    output wire                              s_axi_bvalid,
    input  wire                              s_axi_bready,
    input  wire [C_S_AXI_ADDR_WIDTH-1:0]     s_axi_araddr,
    input  wire [2:0]                        s_axi_arprot,
    input  wire                              s_axi_arvalid,
    output wire                              s_axi_arready,
    output wire [31:0]                       s_axi_rdata,
    output wire [1:0]                        s_axi_rresp,
    output wire                              s_axi_rvalid,
    input  wire                              s_axi_rready,

    // ------------------------------------------------ 설정용 SPI (axi_quad_spi)
    //  EN=0 일 때 아래 4선이 그대로 핀으로 통과한다. Phase 1/2 에서 검증된
    //  레지스터 읽기·쓰기 경로를 그대로 쓰기 위해서다.
    input  wire                              cfg_sck,
    input  wire                              cfg_cs_n,
    input  wire                              cfg_mosi,
    output wire                              cfg_miso,

    // ------------------------------------------------ FMC 핀
    //  ★ sdio1 만 inout 이다. classic 모드에서는 DAC 의 SDO(출력)이고,
    //    dual/quad 에서는 우리가 미는 SDIO1 이다. 나머지는 단방향으로 충분하다:
    //    쓰기 프레임(R/W=0)만 내보내므로 DAC 가 sdio0/2/3 을 구동하는 경우가 없다.
    output wire                              dac_sck,
    output wire                              dac_cs_n,
    output wire                              dac_sdio0,
    inout  wire                              dac_sdio1,
    output wire                              dac_sdio2,
    output wire                              dac_sdio3
);

    // =========================================================================
    // 1. AXI4-Lite 슬레이브
    // =========================================================================
    localparam ADDR_LSB = 2;   // 32비트 워드 정렬

    reg                              awready_r, wready_r, bvalid_r;
    reg                              arready_r, rvalid_r;
    reg [31:0]                       rdata_r;
    reg [C_S_AXI_ADDR_WIDTH-1:0]     awaddr_r, araddr_r;

    assign s_axi_awready = awready_r;
    assign s_axi_wready  = wready_r;
    assign s_axi_bresp   = 2'b00;
    assign s_axi_bvalid  = bvalid_r;
    assign s_axi_arready = arready_r;
    assign s_axi_rdata   = rdata_r;
    assign s_axi_rresp   = 2'b00;
    assign s_axi_rvalid  = rvalid_r;

    // 쓰기 주소
    always @(posedge aclk) begin
        if (!aresetn) begin
            awready_r <= 1'b0;
        end else if (!awready_r && s_axi_awvalid && s_axi_wvalid && !bvalid_r) begin
            awready_r <= 1'b1;
            awaddr_r  <= s_axi_awaddr;
        end else begin
            awready_r <= 1'b0;
        end
    end

    // 쓰기 데이터
    always @(posedge aclk) begin
        if (!aresetn)
            wready_r <= 1'b0;
        else
            wready_r <= (!wready_r && s_axi_wvalid && s_axi_awvalid && !bvalid_r);
    end

    wire wr_en = awready_r && wready_r;

    // 쓰기 응답
    always @(posedge aclk) begin
        if (!aresetn)            bvalid_r <= 1'b0;
        else if (wr_en)          bvalid_r <= 1'b1;
        else if (s_axi_bready && bvalid_r) bvalid_r <= 1'b0;
    end

    // 읽기 주소
    always @(posedge aclk) begin
        if (!aresetn) begin
            arready_r <= 1'b0;
        end else if (!arready_r && s_axi_arvalid && !rvalid_r) begin
            arready_r <= 1'b1;
            araddr_r  <= s_axi_araddr;
        end else begin
            arready_r <= 1'b0;
        end
    end

    // =========================================================================
    // 2. 레지스터
    // =========================================================================
    reg         ctrl_en;
    reg  [7:0]  cfg_sck_div;      // 최소 1
    reg  [7:0]  cfg_instr;
    reg  [1:0]  cfg_lanes;        // 00=1선 01=2선 10=4선
    reg         cfg_instr_x1;
    //  ★ 2026-09-11 : DDR. 데이터 위상에서만 쓴다.
    //    데이터시트 : "DDR is only usable in the data phase during write
    //    operations" — 명령 위상은 반드시 SDR 이다.
    reg         cfg_ddr;

    //  ★ 2026-09-11 : 선언을 위로 올렸다. 297행에서 먼저 읽는데 아래에
    //    선언돼 있어 xvlog 가 거부했다. Vivado 합성은 통과시켜서 그동안
    //    드러나지 않았다. 시뮬레이터가 더 엄격하다.
    reg         swap_done;  // 처프 경계에서 활성 버퍼를 바꿨다는 통지
    reg  [15:0] cfg_period;
    reg         clr_status;

    //  레인 부호 -> 실제 선 수. 11 은 잘못된 값이므로 4 로 접는다.
    function [3:0] lanes_of(input [1:0] code);
        lanes_of = (code == 2'b00) ? 4'd1 : (code == 2'b01) ? 4'd2 : 4'd4;
    endfunction

    reg         st_underrun, st_overrun;
    reg  [31:0] sampcnt;
    reg  [31:0] chirpcnt;
    reg  [15:0] cfg_npoints;      // 처프당 점 수
    reg         swap_req;         // CTRL.SWAP_REQ (FSM 이 경계에서 소비)
    reg         soft_rst;

    // 실행 중 고정되는 래치본
    reg  [7:0]  div_l;
    reg  [7:0]  instr_l;
    reg  [15:0] period_l;

    wire [31:0] status_w;

    always @(posedge aclk) begin
        if (!aresetn) begin
            ctrl_en     <= 1'b0;
            cfg_sck_div <= 8'd6;        // 8.33 MHz — 브링업 기본값 (느린 쪽)
            cfg_instr   <= 8'h2A;       // CH0_DAC_16B 상위 바이트, 내림차순
            cfg_lanes   <= 2'b00;       // 단선 — 검증된 기본값
            cfg_ddr     <= 1'b0;        // SDR — 검증된 기본값
            cfg_instr_x1<= 1'b0;
            cfg_period  <= 16'd200;     // N=50 @10 kHz
            cfg_npoints <= 16'd50;
            swap_req    <= 1'b0;
            soft_rst    <= 1'b0;
            clr_status  <= 1'b0;
        end else begin
            clr_status <= 1'b0;
            soft_rst   <= 1'b0;
            //  FSM 이 처프 경계에서 갈아타면 요청을 내린다.
            if (swap_done) swap_req <= 1'b0;
            if (wr_en) begin
                case (awaddr_r[C_S_AXI_ADDR_WIDTH-1:ADDR_LSB])
                    6'h01: begin                        // 0x04 CTRL
                        if (s_axi_wstrb[0]) begin
                            ctrl_en    <= s_axi_wdata[0];   // CHIRP_ON
                            soft_rst   <= s_axi_wdata[1];   // 자동 클리어
                            clr_status <= s_axi_wdata[2];
                            if (s_axi_wdata[3]) swap_req <= 1'b1;
                        end
                    end
                    6'h02: begin                        // 0x08 CFG
                        if (s_axi_wstrb[0]) cfg_sck_div <= (s_axi_wdata[7:0] == 8'd0)
                                                            ? 8'd1 : s_axi_wdata[7:0];
                        if (s_axi_wstrb[1]) cfg_instr   <= s_axi_wdata[15:8];
                        if (s_axi_wstrb[2]) begin
                            cfg_lanes    <= s_axi_wdata[17:16];
                            cfg_instr_x1 <= s_axi_wdata[18];
                            cfg_ddr      <= s_axi_wdata[19];
                        end
                    end
                    6'h03: begin                        // 0x0C PERIOD
                        if (s_axi_wstrb[0]) cfg_period[7:0]  <= s_axi_wdata[7:0];
                        if (s_axi_wstrb[1]) cfg_period[15:8] <= s_axi_wdata[15:8];
                    end
                    6'h06: begin                        // 0x18 NPOINTS
                        if (s_axi_wstrb[0]) cfg_npoints[7:0]  <= s_axi_wdata[7:0];
                        if (s_axi_wstrb[1]) cfg_npoints[15:8] <= s_axi_wdata[15:8];
                    end
                    default: ;
                endcase
            end
        end
    end

    // 읽기 데이터
    always @(posedge aclk) begin
        if (!aresetn) begin
            rvalid_r <= 1'b0;
            rdata_r  <= 32'd0;
        end else if (arready_r && s_axi_arvalid && !rvalid_r) begin
            rvalid_r <= 1'b1;
            case (araddr_r[C_S_AXI_ADDR_WIDTH-1:ADDR_LSB])
                6'h00:   rdata_r <= ID_VALUE;
                6'h01:   rdata_r <= {31'd0, ctrl_en};
                6'h02:   rdata_r <= {12'd0, cfg_ddr, cfg_instr_x1, cfg_lanes, cfg_instr, cfg_sck_div};
                6'h03:   rdata_r <= {16'd0, cfg_period};
                6'h04:   rdata_r <= status_w;
                6'h05:   rdata_r <= sampcnt;
                6'h06:   rdata_r <= {16'd0, cfg_npoints};
                6'h07:   rdata_r <= chirpcnt;
                default: rdata_r <= 32'd0;
            endcase
        end else if (rvalid_r && s_axi_rready) begin
            rvalid_r <= 1'b0;
        end
    end

    // =========================================================================
    // 3. 파형 저장소 — 핑퐁 BRAM 두 장
    // =========================================================================
    //  PS 가 AXI-Lite 로 쓰고(포트 A), FSM 이 읽는다(포트 B). 같은 aclk 이라
    //  클럭 도메인 교차가 없다.
    //
    //  [핑퐁을 왜 두나]  지금은 연산 로직이 없어 두 장에 같은 파형이 들어가지만,
    //  나중에 TDC 측정으로 보정한 파형을 **재생 중에** 비활성 버퍼에 써 넣고
    //  처프 경계에서 갈아타기 위해서다. 그래야 출력이 끊기지 않는다.
    //
    //  [갈아타는 방법]  PS 가 CTRL.SWAP_REQ 를 세우면 FSM 이 **다음 처프
    //  경계에서** 활성 버퍼를 바꾸고 그 비트를 스스로 내린다. 처프 도중에
    //  바뀌면 파형 중간이 이어 붙어 버리므로 경계에서만 바꾼다.
    localparam integer AW = ADDR_BITS;

    (* ram_style = "block" *) reg [15:0] buf_a [0:NPOINTS_MAX-1];
    (* ram_style = "block" *) reg [15:0] buf_b [0:NPOINTS_MAX-1];

    reg          active_buf;      // 0 = A 재생, 1 = B 재생
    reg [AW-1:0] rd_addr;
    reg [15:0]   rd_a, rd_b;

    wire [15:0] next_sample = active_buf ? rd_b : rd_a;

    //  ---- 쓰기 (AXI-Lite) ----
    //  0x1000~ -> 버퍼 A,  0x2000~ -> 버퍼 B.  하위 16비트만 쓴다.
    wire        buf_wr   = wr_en && (awaddr_r[13:12] != 2'b00);
    wire        buf_sel  = awaddr_r[13];                 // 0 = A(0x1xxx), 1 = B(0x2xxx)
    wire [AW-1:0] buf_wa = awaddr_r[AW+1:2];

    always @(posedge aclk) begin
        if (buf_wr && !buf_sel) buf_a[buf_wa] <= s_axi_wdata[15:0];
        if (buf_wr &&  buf_sel) buf_b[buf_wa] <= s_axi_wdata[15:0];
    end

    //  ---- 읽기 (FSM) ----
    //  BRAM 은 읽기 지연이 1클럭이다. 그래서 **다음에 쓸 주소를 미리** 걸어 둔다.
    //  샘플을 실을 때는 이미 rd_a/rd_b 에 값이 나와 있다.
    always @(posedge aclk) begin
        rd_a <= buf_a[rd_addr];
        rd_b <= buf_b[rd_addr];
    end

    // =========================================================================
    // 4. 재생 FSM
    // =========================================================================
    localparam [2:0] S_IDLE  = 3'd0,   // CS 높음, 아무것도 안 함
                     S_CSLO  = 3'd1,   // CS 내리고 t2(=CS↓ -> 첫 SCK↑) 확보
                     S_INSTR = 3'd2,   // 명령 8비트
                     S_RUN   = 3'd3,   // PERIOD 격자로 16비트씩
                     S_TAIL  = 3'd4;   // t3(마지막 SCK -> CS↑) 확보 후 CS 올림

    reg [2:0]  state;
    reg [7:0]  divcnt;
    reg [15:0] pcnt;               // 샘플 격자 카운터 0..period_l-1
    reg [4:0]  cyccnt;             // 남은 SCK 사이클 수 (비트 수가 아니다)
    reg [15:0] shreg;
    reg        busy;               // 비트 엔진 동작 중
    reg        sck_q, cs_n_q;
    reg [3:0]  dout_q;             // {sdio3, sdio2, sdio1, sdio0}
    reg [3:0]  cur_lanes;          // 지금 내보내는 워드의 선 수 (1/2/4)
    reg [15:0] last_sample;
    reg [2:0]  guard;              // CS 앞뒤 여유 클럭

    reg [3:0]  lanes_l;            // 데이터 위상 선 수 (EN 상승에서 래치)
    reg        instr_x1_l;
    reg        ddr_l;              // 데이터 위상 DDR (EN 상승에서 래치)
    reg        cur_ddr;            // 지금 내보내는 워드가 DDR 인가

    //  EN 상승 시점의 최소 격자 [aclk] = (16/LANES) × 2 × SCK_DIV
    wire [15:0] min_period =
        {11'd0, cyc16_m(lanes_of(cfg_lanes), cfg_ddr)} * 16'd2 *
        {8'd0, ((cfg_sck_div == 8'd0) ? 8'd1 : cfg_sck_div)};

    wire div_tick = (divcnt == div_l - 8'd1);

    //  ★ 2026-09-09 — 워드 적재의 1클럭 오버헤드를 없앤다.
    //    [무엇이 문제였나] 워드는 적재 에지 T 에서 시작해 T+2·cyc 에서 마지막
    //    하강으로 끝난다. 그런데 busy<=0 이 바로 그 T+2·cyc 에지에 걸리므로
    //    그 시점에 busy 를 읽으면 아직 1 이다. 그래서 격자를 정확히 2·cyc 로 잡으면
    //    매번 OVERRUN 이 뜨고 한 칸씩 건너뛰었다 (실측: quad 에서 간격이 2배).
    //    단선(2·cyc=32)에서는 격자가 40 이라 안 드러났고, dual/quad 로 내려오면서
    //    비로소 보였다.
    //    [고친 방법] "이번 에지가 엔진의 마지막" 임을 미리 알려 주는 신호를 만들어
    //    그때는 겹치기 적재를 허용한다. case 블록이 엔진 블록보다 뒤에 있으므로
    //    같은 에지에서 적재 대입이 엔진의 busy<=0 을 덮어쓴다.
    //    [효과] 최소 격자 = (32/LANES)×SCK_DIV 가 정확히 성립한다.
    //           quad·DIV=1 이면 8 클럭 -> 10 kHz 에서 1250 점이 딱 맞는다.
    wire eng_last = busy && div_tick && sck_q && (cyccnt == 5'd1);

    //  ★ 멀티 IO 직렬화. "consecutive bits are serialized in groups of two/four"
    //    (데이터시트 p.34-36). 상위 IO 가 상위 비트다 —
    //    quad 첫 클럭은 SDIO3=bit15, SDIO2=bit14, SDIO1=bit13, SDIO0=bit12.
    function [15:0] shl_n(input [15:0] x, input [3:0] n);
        shl_n = (n == 4'd4) ? {x[11:0], 4'd0}
              : (n == 4'd2) ? {x[13:0], 2'd0}
              :               {x[14:0], 1'd0};
    endfunction

    function [3:0] nib_n(input [15:0] x, input [3:0] n);
        nib_n = (n == 4'd4) ? x[15:12]
              : (n == 4'd2) ? {2'b00, x[15:14]}
              :               {3'b000, x[15]};
    endfunction

    //  16비트 / 8비트를 내보내는 데 필요한 SCK 사이클 수
    function [4:0] cyc16(input [3:0] n);
        cyc16 = (n == 4'd4) ? 5'd4 : (n == 4'd2) ? 5'd8 : 5'd16;
    endfunction
    function [4:0] cyc8(input [3:0] n);
        cyc8  = (n == 4'd4) ? 5'd2 : (n == 4'd2) ? 5'd4 : 5'd8;
    endfunction

    //  ★ 2026-09-11 : DDR 이면 한 SCK 사이클에 두 조각이 나가므로 절반이다.
    //    quad DDR : 16비트 / (4선 x 2모서리) = 2 SCK 사이클.
    //    명령 위상은 항상 SDR 이라 cyc8 은 그대로 쓴다 (데이터시트 : DDR 은
    //    쓰기의 데이터 위상에서만 유효).
    function [4:0] cyc16_m(input [3:0] n, input d);
        cyc16_m = d ? ((n == 4'd4) ? 5'd2 : (n == 4'd2) ? 5'd4 : 5'd8)
                    : ((n == 4'd4) ? 5'd4 : (n == 4'd2) ? 5'd8 : 5'd16);
    endfunction

    //  ★ 처프 진행 상태.
    //    pt_idx  : 이번 처프에서 몇 번째 점인가 (0 .. npoints_l-1)
    //    npoints_l : EN 상승에서 래치한 처프당 점 수
    //    swap_done : 처프 경계에서 활성 버퍼를 바꿨다고 레지스터 블록에 알림
    reg  [15:0] pt_idx;
    reg  [15:0] npoints_l;

    always @(posedge aclk) begin
        if (!aresetn) begin
            state       <= S_IDLE;
            busy        <= 1'b0;
            sck_q       <= 1'b0;
            cs_n_q      <= 1'b1;
            dout_q      <= 4'd0;
            cur_lanes   <= 4'd1;
            lanes_l     <= 4'd1;
            ddr_l       <= 1'b0;
            cur_ddr     <= 1'b0;
            instr_x1_l  <= 1'b0;
            divcnt      <= 8'd0;
            pcnt        <= 16'd0;
            cyccnt      <= 5'd0;
            shreg       <= 16'd0;
            guard       <= 3'd0;
            sampcnt     <= 32'd0;
            chirpcnt    <= 32'd0;
            pt_idx      <= 16'd0;
            npoints_l   <= 16'd50;
            active_buf  <= 1'b0;
            swap_done   <= 1'b0;
            rd_addr     <= {AW{1'b0}};
            st_underrun <= 1'b0;
            st_overrun  <= 1'b0;
            last_sample <= 16'd0;
            div_l       <= 8'd1;
            instr_l     <= 8'h2A;
            period_l    <= 16'd200;
        end else begin
            swap_done <= 1'b0;

            //  ★ 소프트 리셋 — 처프를 처음부터 다시. CS 는 S_IDLE 에서 올라간다.
            if (soft_rst) begin
                state      <= S_IDLE;
                busy       <= 1'b0;
                pt_idx     <= 16'd0;
                rd_addr    <= {AW{1'b0}};
                chirpcnt   <= 32'd0;
                active_buf <= 1'b0;
            end

            if (clr_status) begin
                st_underrun <= 1'b0;
                st_overrun  <= 1'b0;
            end

            // ---- 비트 엔진 (모든 상태 공통) --------------------------------
            //  SPI mode 0 : SCK 유휴 LOW. A반주기(SCK=0)에 데이터를 세우고,
            //  B반주기(SCK=1)에 슬레이브가 샘플한다. B 끝에서 다음 조각으로.
            //  한 사이클에 cur_lanes 비트가 나간다 (1/2/4).
            if (busy) begin
                if (div_tick) begin
                    divcnt <= 8'd0;
                    if (!sck_q) begin
                        sck_q <= 1'b1;                       // 상승 : 슬레이브 샘플
                        //  ★ DDR : 슬레이브가 양쪽 모서리에서 샘플하므로
                        //    상승 직후에도 다음 조각을 세워 둔다. SDR 이면
                        //    여기서 아무것도 하지 않는다 (기존 동작 그대로).
                        if (cur_ddr) begin
                            shreg  <= shl_n(shreg, cur_lanes);
                            dout_q <= nib_n(shl_n(shreg, cur_lanes), cur_lanes);
                        end
                    end else begin
                        sck_q  <= 1'b0;                      // 하강 : 다음 조각
                        shreg  <= shl_n(shreg, cur_lanes);
                        dout_q <= nib_n(shl_n(shreg, cur_lanes), cur_lanes);
                        cyccnt <= cyccnt - 5'd1;
                        if (cyccnt == 5'd1) begin
                            busy   <= 1'b0;
                            dout_q <= 4'd0;
                        end
                    end
                end else begin
                    divcnt <= divcnt + 8'd1;
                end
            end

            // ---- 상태 기계 --------------------------------------------------
            case (state)
            // -----------------------------------------------------------------
            S_IDLE: begin
                cs_n_q <= 1'b1;
                sck_q  <= 1'b0;
                dout_q <= 4'd0;
                busy   <= 1'b0;
                if (ctrl_en) begin
                    // 설정을 여기서 한 번만 래치한다. 재생 중 변경 금지.
                    div_l      <= (cfg_sck_div == 8'd0) ? 8'd1 : cfg_sck_div;
                    instr_l    <= cfg_instr;
                    lanes_l    <= lanes_of(cfg_lanes);
                    instr_x1_l <= cfg_instr_x1;
                    ddr_l      <= cfg_ddr;
                    //  최소 격자 = (32/LANES) × SCK_DIV [aclk].
                    //  ★ 단위 주의 : cyc16() 은 **SCK 사이클** 수다. PERIOD 는 aclk
                    //    클럭 수이므로 ×2×DIV 를 해야 한다. 이걸 빠뜨리면 quad 에서
                    //    하한이 4 로 잡혀 클램프가 무의미해진다.
                    period_l   <= (cfg_period < min_period) ? min_period : cfg_period;
                    npoints_l  <= (cfg_npoints == 16'd0) ? 16'd1
                                : (cfg_npoints > NPOINTS_MAX) ? NPOINTS_MAX[15:0]
                                : cfg_npoints;
                    sampcnt    <= 32'd0;
                    pt_idx     <= 16'd0;
                    rd_addr    <= {AW{1'b0}};
                    cs_n_q     <= 1'b0;                      // CS 내림
                    guard      <= 3'd7;
                    state      <= S_CSLO;
                end
            end
            // -----------------------------------------------------------------
            //  t2 (CS↓ -> 첫 SCK↑) 최소 5 ns. 7 클럭 = 70 ns 로 넉넉히 잡는다.
            S_CSLO: begin
                if (guard != 3'd0) begin
                    guard <= guard - 3'd1;
                end else begin
                    //  명령 위상의 선 수. 데이터시트에서 확정하지 못해
                    //  INSTR_X1 로 양쪽을 다 시도할 수 있게 했다 (헤더 참조).
                    cur_lanes <= instr_x1_l ? 4'd1 : lanes_l;
                    cur_ddr   <= 1'b0;          // 명령 위상은 항상 SDR
                    shreg     <= {instr_l, 8'h00};
                    dout_q    <= nib_n({instr_l, 8'h00},
                                       instr_x1_l ? 4'd1 : lanes_l);
                    cyccnt    <= cyc8(instr_x1_l ? 4'd1 : lanes_l);
                    divcnt    <= 8'd0;
                    sck_q     <= 1'b0;
                    busy      <= 1'b1;
                    state     <= S_INSTR;
                end
            end
            // -----------------------------------------------------------------
            S_INSTR: begin
                if (!busy) begin
                    //  BRAM 읽기 지연이 1클럭이다. 여기서 rd_addr=0 이 이미 걸려
                    //  있으므로 S_RUN 첫 격자에서는 rd_a/rd_b 가 준비돼 있다.
                    pcnt  <= 16'd0;
                    state <= S_RUN;
                end
            end
            // -----------------------------------------------------------------
            //  ★ 여기가 주기의 근거다. pcnt 는 자유 실행이고, 0 이 될 때마다
            //    16비트 전송을 시작한다. 따라서 샘플 간격은 정확히 period_l
            //    클럭이며, 소프트웨어가 뭘 하든 지터가 없다.
            S_RUN: begin
                if (pcnt == period_l - 16'd1) pcnt <= 16'd0;
                else                          pcnt <= pcnt + 16'd1;

                if (pcnt == 16'd0) begin
                    if (busy && !eng_last) begin
                        // 앞 샘플이 아직 안 끝났다 = PERIOD 가 (32/LANES)*DIV 보다 작다.
                        // 소프트웨어 설정 오류. 격자를 지키고 이번 샘플은 버린다.
                        st_overrun <= 1'b1;
                    end else if (!ctrl_en) begin
                        guard <= 3'd7;
                        state <= S_TAIL;
                    end else begin
                        //  BRAM 에서 이미 읽혀 나온 값을 싣는다. 언더런이라는
                        //  개념이 없다 — 상류가 없고 데이터는 항상 거기 있다.
                        shreg       <= next_sample;
                        dout_q      <= nib_n(next_sample, lanes_l);
                        last_sample <= next_sample;

                        cur_lanes <= lanes_l;
                        cur_ddr   <= ddr_l;
                        cyccnt    <= cyc16_m(lanes_l, ddr_l);
                        divcnt    <= 8'd0;
                        sck_q     <= 1'b0;
                        busy      <= 1'b1;
                        sampcnt   <= sampcnt + 32'd1;

                        //  ---- 처프 경계 ----
                        if (pt_idx == npoints_l - 16'd1) begin
                            pt_idx   <= 16'd0;
                            rd_addr  <= {AW{1'b0}};
                            chirpcnt <= chirpcnt + 32'd1;
                            //  ★ 버퍼 교체는 여기서만 한다. 처프 도중에 바꾸면
                            //    파형 중간이 이어 붙어 버린다.
                            if (swap_req) begin
                                active_buf <= ~active_buf;
                                swap_done  <= 1'b1;
                            end
                        end else begin
                            pt_idx  <= pt_idx + 16'd1;
                            rd_addr <= rd_addr + 1'b1;
                        end
                    end
                end
            end
            // -----------------------------------------------------------------
            //  t3 (마지막 SCK 샘플 에지 -> CS↑) 최소 10 ns.
            S_TAIL: begin
                if (guard != 3'd0) guard <= guard - 3'd1;
                else begin
                    cs_n_q <= 1'b1;
                    state  <= S_IDLE;
                end
            end
            // -----------------------------------------------------------------
            default: state <= S_IDLE;
            endcase
        end
    end

    //  [0]   RUNNING   재생 중
    //  [1]   UNDERRUN  (BRAM 구조에서는 항상 0 — 자리만 남겨 둔다)
    //  [2]   OVERRUN   PERIOD 가 너무 작다
    //  [3]   CS_LOW
    //  [6:4] STATE     FSM 상태 (S_IDLE=0 … S_TAIL=4)
    //  [7]   ACTIVE_BUF 0=A 재생, 1=B 재생
    //  [8]   SWAP_PENDING
    assign status_w = {23'd0, swap_req, active_buf, state,
                       (cs_n_q == 1'b0), st_overrun, st_underrun,
                       (state != S_IDLE)};

    // =========================================================================
    // 5. 핀 먹싱 — EN 이 꺼져 있으면 axi_quad_spi 가 핀을 갖는다
    // =========================================================================
    //  Phase 1/2 에서 검증된 설정 경로(VENDOR 읽기, 레인지 쓰기 …)를 그대로
    //  쓰기 위해서다. 재생 중에는 FSM 이 갖는다.
    //  ★ 2026-09-10 — 선언과 대입을 분리했다.
    //    `wire owned = (state != S_IDLE);` 로 써 두었더니 IP 패키저의 HDL 파서가
    //    이걸 포트/파라미터로 오인해 경고를 냈다:
    //      WARNING: [IP_Flow 19-587] HDL port or parameter 'owned' has a
    //      dependency on the module local parameter or undefined parameter 'S_IDLE'.
    //    합성은 멀쩡했지만 XSA 메타데이터가 어긋나면 Vitis 의 디바이스 트리
    //    생성이 넘어질 수 있어 정리했다.
    wire owned;
    assign owned = (state != S_IDLE);

    //  ★ sdio1 만 삼상이다.
    //    classic 모드에서 sdio1 은 **DAC 의 출력**(SDO)이다 — 그때 우리가 구동하면
    //    양쪽이 맞붙는다. 그래서 dual/quad 재생 중에만 구동한다.
    //    (데이터시트 p.34 "In single SPI (classic) mode, the SDI/SDIO0 and
    //     SDO/SDIO1 data lines are unidirectional")
    wire sdio1_oe = owned && (cur_lanes >= 4'd2);

    // -------------------------------------------------------------------------
    //  ★★ 2026-09-09 — 출력 단을 한 번 더 등록해 IOB 플립플롭에 싣는다.
    //
    //  [무엇이 문제였나]  첫 구현에서 WNS = -4.992 ns 였다. 리포트를 보니
    //    에지 관계(Requirement 10.000 ns)는 정확했고, 문제는 데이터 경로였다:
    //      Data Path Delay 17.553 ns  (logic 3.005 / route 14.548 = 83 %)
    //      FSM_state_reg[0]/Q -> net(fo=66) 5.689 -> LUT5 -> net 8.859 -> OBUFT -> P18
    //    플립플롭 뒤에 통과 먹스 LUT 가 붙어 있고, 그 LUT 에서 FMC 패드까지
    //    8.9 ns 를 배선으로 갔다. state 레지스터가 66 개 부하를 몰고 있어
    //    배치기가 패드 근처로 끌어다 놓을 수도 없었다.
    //
    //  [고친 방법]  먹스 결과를 **출력 전용 플립플롭**에 한 번 더 받고 그 플립플롭을
    //    IOB(I/O 타일)에 packing 한다. 그러면 플립플롭에서 패드까지 배선이 사실상
    //    0 이 되고 논리 단도 사라진다. 남는 것은 clock-to-out + OBUF 뿐이다.
    //    (* IOB = "TRUE" *) 로 RTL 에 직접 붙였다 — XDC 에 두면 계층 이름이
    //    바뀔 때마다 깨진다.
    //
    //  [지연이 한 클럭 늘어난다 — 괜찮다]
    //    SCK / CS / 데이터 / 삼상제어가 **전부 같은 클럭으로 같이** 밀리므로
    //    서로의 상대 관계가 그대로다. 샘플 격자도, t2/t3 여유도 변하지 않는다.
    //    설정용 SPI(6.25 MHz)에 10 ns 가 더 붙는 것도 무의미하다.
    //
    //  [리셋을 동기로 둔 이유]  7-series 의 OLOGIC 플립플롭은 비동기 리셋이면
    //    IOB packing 이 거부된다. 아래는 전부 동기 리셋이다.
    // -------------------------------------------------------------------------
    (* IOB = "TRUE" *) reg       cs_n_o_r;
    (* IOB = "TRUE" *) reg       sdio1_t_r;    // 1 = Hi-Z (입력)
    (* IOB = "TRUE" *) reg [3:0] sdio_o_r;

    always @(posedge aclk) begin
        if (!aresetn) begin
            cs_n_o_r  <= 1'b1;
            sdio_o_r  <= 4'd0;
            sdio1_t_r <= 1'b1;
        end else begin
            cs_n_o_r    <= owned ? cs_n_q    : cfg_cs_n;
            sdio_o_r[0] <= owned ? dout_q[0] : cfg_mosi;
            sdio_o_r[1] <= dout_q[1];
            sdio_o_r[2] <= owned ? dout_q[2] : 1'b0;
            sdio_o_r[3] <= owned ? dout_q[3] : 1'b0;
            sdio1_t_r   <= ~sdio1_oe;
        end
    end


    // -------------------------------------------------------------------------
    //  ★★ 2026-09-11 : SCK 를 ODDR 로 내보낸다 — DDR 에서 반 클럭 밀기 위해서다.
    //
    //  [왜 필요한가]  quad DDR + DIV=1 이면 aclk 102.4 MHz 에서 데이터가 매
    //    클럭 바뀌고 SCK 도 매 클럭 토글한다. 둘 다 aclk 상승에서 움직이면
    //    SCK 모서리가 데이터 천이와 겹쳐 셋업도 홀드도 0 이 된다.
    //    ODDR 로 SCK 를 aclk **하강**에 걸면 모서리가 데이터 눈 정중앙에 온다.
    //    9.77 ns 주기의 절반인 4.88 ns 씩 양쪽에 남는다. AD3552R 요구는
    //    t7/t8 = 2 ns 이므로 여유가 있다.
    //
    //  [SDR 은 그대로]  D1 과 D2 에 같은 값을 주면 출력은 aclk 상승에서만
    //    바뀐다. 지금까지 검증된 단선/듀얼/쿼드 SDR 동작이 보존된다.
    //
    //  [지연]  sck_pipe 는 데이터용 IOB 레지스터와 같은 클럭 수만큼 밀린다.
    //    SCK 와 데이터의 상대 관계만 중요하므로 절대 지연은 무의미하다.
    //  ★ ODDR 자체가 레지스터다. 앞에 파이프 단을 하나 더 두면 SCK 가
    //    데이터보다 한 클럭 늦어져 샘플이 통째로 한 비트 밀린다.
    //    2026-09-11 에 그렇게 넣었다가 시뮬레이션에서 바로 잡혔다
    //    (기대 0xA000, 관측 0x4000 = 한 비트 왼쪽으로 밀린 값).
    //    그래서 D2 는 sck_q 를 그대로 받는다. 데이터의 IOB 레지스터와
    //    레지스터 단 수가 같아진다.
    wire sck_src = owned ? sck_q : cfg_sck;
    reg  sck_src_d;
    always @(posedge aclk) begin
        if (!aresetn) sck_src_d <= 1'b0;
        else          sck_src_d <= sck_src;
    end

    //  ★ 2026-09-11 : DDR 에서 SCK 를 반 클럭 **당긴다**.
    //    [왜 당기나] 데이터는 sdio_o_r 한 단을 거쳐 aclk 상승에서 바뀐다.
    //      cycle n 의 데이터는 그 cycle 에 해당하는 조각이다. 그 조각을 샘플할
    //      SCK 모서리는 같은 cycle 의 한가운데 있어야 한다.
    //      D1 에 앞 값(sck_src_d)을 쓰면 SCK 가 1.5 클럭 늦어져 모서리가
    //      다음다음 조각 위에 떨어진다. 시뮬레이션에서 값이 한 니블씩
    //      회전해 나온 것이 그 증거였다 (0xA000 -> 0x000A).
    //    [어떻게] D1 에 현재 값, D2 에 **다음 값**을 실으면 천이가 cycle
    //      한가운데로 온다. sck_q 는 div_tick 에서 뒤집히므로 다음 값은
    //      조합으로 알 수 있다.
    //    [SDR 은 그대로] D1 = D2 = sck_src 라 aclk 상승에서만 바뀐다.
    wire sck_ddr_mode = owned && cur_ddr;
    wire sck_nxt      = (busy && div_tick) ? ~sck_q : sck_q;
    wire sck_d1 = sck_src;
    wire sck_d2 = sck_ddr_mode ? (owned ? sck_nxt : cfg_sck) : sck_src;

`ifdef DAC_SIM_NO_UNISIM
    //  iverilog 용 행동 모델. xsim/Vivado 에서는 진짜 ODDR 을 쓴다.
    reg sck_beh_r, sck_beh_f;
    always @(posedge aclk) sck_beh_r <= sck_d1;
    always @(posedge aclk) sck_beh_f <= sck_d2;
    assign dac_sck = aclk ? sck_beh_r : sck_beh_f;
`else
    ODDR #(
        .DDR_CLK_EDGE ("SAME_EDGE"),
        .INIT         (1'b0),
        .SRTYPE       ("SYNC")
    ) u_sck_oddr (
        .Q  (dac_sck),
        .C  (aclk),
        .CE (1'b1),
        .D1 (sck_d1),
        .D2 (sck_d2),
        .R  (~aresetn),
        .S  (1'b0)
    );
`endif

    assign dac_cs_n  = cs_n_o_r;
    assign dac_sdio0 = sdio_o_r[0];
    assign dac_sdio2 = sdio_o_r[2];
    assign dac_sdio3 = sdio_o_r[3];
    assign dac_sdio1 = sdio1_t_r ? 1'bz : sdio_o_r[1];
    assign cfg_miso  = dac_sdio1;

    // 미사용 입력 — 합성 경고 방지
    wire _unused = &{1'b0, s_axi_awprot, s_axi_arprot, s_axi_wstrb[3], 1'b0};

endmodule
