# =============================================================================
# dac_test.xdc — EVAL-AD3552RFMCZ on ZedBoard FMC-LPC
# Generated by Claude Code, 2026-09-08
#
#  ★ 2026-09-08 실물 검증 완료 — 구현 후 report_io 로 확인:
#    8개 핀 전부 LVCMOS18, 전부 뱅크 34, Bank 34 VCCO = 1.80.
#
#  [핀 배치 출처]
#    ADI 레퍼런스 hdl/projects/ad35xxr_evb/zed/system_constr.xdc (main 브랜치) 를
#    그대로 따랐다. FMC 신호명과 패키지 핀 대응은 Parts/Zedboard-Master.xdc 로
#    교차 확인했다 (LA00_CC=M19/M20, LA02=P17/P18, LA03=N22/P22, LA04=M21/M22,
#    LA05=J18/K18).
#
#  [★ IOSTANDARD 를 LVCMOS18 로 바꾼 이유]
#    ADI 원본은 LVCMOS25 인데, 같은 저장소의 zed/README.md 는 "VADJ 1.8V 로
#    검증했다" 고 적고 있어 서로 모순이다. 평가보드 규격도 VADJ 1.2~1.8V 다.
#    실제 레일에 맞추는 쪽이 옳으므로 1.8V 로 간다.
#    ※ Vivado 는 J18 점퍼 위치를 모른다. 2.5V 제약으로 두어도 비트스트림은
#      조용히 생성되고, 실물에서만 틀린다.
#
#  [★★ 하드웨어 안전 — J18 점퍼는 1.8V]
#    ZedBoard Bank34/35 VCCO = VADJ, 점퍼 J18 로 선택 (기본 1.8V).
#    AD3552R 디지털입력 절대최대정격은 DVDD+0.3V 또는 +2.1V 중 작은 값
#    (ad3552r.pdf Table 5). 2.5V 는 절대최대정격 초과이며 소자가 깨질 수 있다.
#    ※ 아래 dac_ldacn 의 패키지 핀 이름이 우연히 "J18" 인데, 이것은 FMC_LA05_P 의
#      FPGA 패키지 핀이지 VADJ 점퍼 J18 이 아니다. 완전히 다른 것이다.
#
#  [포트 이름 주의]
#    아래 이름들은 tcl/bd_dac_sys.tcl 이 블록디자인 인터페이스를 외부로 뺄 때
#    Vivado 가 붙이는 이름을 전제로 한다. 첫 합성에서
#      report_io  또는  get_ports *
#    로 실제 포트명을 확인하고 다를 경우 여기를 맞출 것.
# =============================================================================

# ---------------------------------------------------------------- SPI
#  ★★ 2026-09-09 변경 — 포트가 삼상(inout)에서 단방향으로 바뀌었다.
#    전에는 axi_quad_spi 의 SPI_0 인터페이스를 그대로 외부로 빼서 Vivado 가
#    IOBUF 를 넣고 dac_spi_*_io 라는 inout 포트를 만들었다. 이제는
#    dac_stream_spi(FSM)가 핀을 갖고, 우리는 항상 마스터이므로 삼상이 필요 없다.
#      dac_spi_sck_io   -> dac_sck   (output)
#      dac_spi_ss_io[0] -> dac_cs_n  (output)
#      dac_spi_io0_io   -> dac_mosi  (output)
#      dac_spi_io1_io   -> dac_miso  (input)
#    패키지 핀은 그대로다.
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS18 SLEW FAST DRIVE 8} [get_ports dac_sck]   ;# FMC_LA00_CC_P
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS18 SLEW FAST DRIVE 8} [get_ports dac_cs_n]  ;# FMC_LA00_CC_N
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS18 SLEW FAST DRIVE 8} [get_ports dac_sdio0] ;# FMC_LA02_P
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS18 SLEW FAST DRIVE 8} [get_ports dac_sdio1] ;# FMC_LA02_N
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS18 SLEW FAST DRIVE 8} [get_ports dac_sdio2] ;# FMC_LA03_P
set_property -dict {PACKAGE_PIN P22 IOSTANDARD LVCMOS18 SLEW FAST DRIVE 8} [get_ports dac_sdio3] ;# FMC_LA03_N

#  ★★ 2026-09-09 — 멀티 IO(dual/quad) 확장. 바뀐 것 두 가지.
#
#   (1) sdio1 이 inout 이 됐다 (전에는 dac_miso 입력).
#       classic 모드에서는 DAC 의 SDO(출력)이고, dual/quad 에서는 우리가 미는
#       SDIO1 이다. dac_stream_spi 안에서 `assign dac_sdio1 = oe ? d : 1'bz;`
#       로 삼상을 만들고 Vivado 가 IOBUF 를 추론한다.
#
#   (2) sdio2/sdio3 을 살렸다 (전에는 주석). quad 전용이며 쓰기 프레임만
#       내보내므로 단방향 출력으로 충분하다 — DAC 가 이 선을 구동하는 경우가 없다.
#
#  [★ 미검증 — LA03 과 QSPI_SEL]
#    LA00_CC / LA02 / LA04 / LA05 는 Phase 1 이 실물에서 통과했으므로 확인된
#    핀이다. **LA03(sdio2/3)은 같은 ADI 제약 파일에서 가져왔을 뿐 실물 확인이
#    없다.** QSPI_SEL(M22) 도 마찬가지로 "0 으로 두는 것" 만 확인됐고 1 로 올려
#    실제로 DAC 에 닿는지는 확인되지 않았다.
#    확인 방법 : QSPI_SEL=1 로 올린 뒤 classic SPI 로 VENDOR 를 읽어 보아
#    **실패해야 정상**이다 (인터페이스가 quad 로 바뀌었으므로). 그대로 0x0456 이
#    읽히면 QSPI_SEL 이 DAC 에 안 닿고 있는 것이다.

#  SLEW FAST / DRIVE 8 은 SCK 50 MHz 를 FMC 커넥터 너머로 보내기 위한 것이다.
#  브링업 초기(SCK 8.33 MHz)에는 없어도 되지만, 두고 나쁠 것이 없다.

# ---------------------------------------------------------------- 정적 제어선 (axi_gpio)
#  dac_ctrl_tri_io[0] = RESETn    : HIGH 유지. LOW 로 떨어뜨리면 전체 리셋
#  dac_ctrl_tri_io[1] = QSPI_SEL  : ★ LOW = classic SPI, HIGH = Quad SPI
#                                   Phase 1/2 는 반드시 LOW
#  dac_ctrl_tri_io[2] = LDACn     : HIGH 유지. Phase 1/2 는 SW LDAC 를 쓴다
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS18} [get_ports {dac_ctrl_tri_io[0]}] ;# FMC_LA05_N  RESETn
set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS18} [get_ports {dac_ctrl_tri_io[1]}] ;# FMC_LA04_N  QSPI_SEL
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS18} [get_ports {dac_ctrl_tri_io[2]}] ;# FMC_LA05_P  LDACn
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS18} [get_ports {dac_ctrl_tri_io[3]}] ;# FMC_LA04_P  ALERTn (입력)

# ---------------------------------------------------------------- 타이밍
#  ★★ 2026-09-09 추가 — Phase 3(50 MHz SCK)용. **이 절은 검증되지 않았다.**
#
#  [AD3552R 요구값 — ad3552r.pdf Rev.B Table 4]
#     fSCLK  최대 66 MHz          t1  SCLK 주기 최소 15.2 ns
#     t7     데이터 셋업 최소 2 ns
#     t8     데이터 홀드 최소 2 ns
#     t2     CS↓ -> 첫 SCK↑ 최소 5 ns   (FSM 이 7 aclk = 70 ns 확보)
#     t3     마지막 SCK -> CS↑ 최소 10 ns (FSM 이 7 aclk = 70 ns 확보)
#   -> 보드 배선 편차를 1 ns 로 보고 셋업/홀드 예산을 각각 3 ns 로 잡는다.
#
#  [SCK 는 패브릭에서 만든다]
#   dac_stream_spi 가 sck_q 플립플롭으로 SCK 를 만든다. ODDR 클럭 포워딩이
#   정석이지만, SCK_DIV 가 런타임 레지스터라 ODDR 로는 DIV=1 밖에 못 만든다.
#   대신 세 출력(SCK/CS/MOSI)을 전부 출력 플립플롭에서 내보내 지연을 맞춘다.
#
#  [★ 여기서 타이밍이 안 맞으면]
#   1순위 : SCK_DIV 를 2 로 (25 MHz, N=125). 성능은 절반이지만 즉시 해결된다.
#   2순위 : ODDR 클럭 포워딩으로 바꾸고 SCK_DIV 를 컴파일 타임 상수로 고정한다.
#   브링업 사다리를 DIV=6(8.33 MHz)부터 올라가라고 한 이유가 이것이다 —
#   느린 쪽에서는 이 제약이 맞든 틀리든 100 ns 이상 여유가 있다.

#  ★★ 2026-09-09 — 이 자리에 있던 create_generated_clock / set_output_delay 를
#    RTL/dac_timing.tcl 로 옮겼다.
#
#    [무엇이 문제였나] 계층 경로를 박지 않으려고 get_pins 결과를 if 로 검사했는데,
#    Vivado 가 이렇게 거부했다:
#        [Designutils 20-1307] Command 'if' is not supported in the xdc
#        constraint file. ["RTL/dac_test.xdc":109]
#      XDC 는 제한된 인터프리터로 읽혀 제어문을 쓸 수 없다.
#
#    [무엇이 위험했나] 에러가 아니라 **경고**로 지나갔다. if 블록 전체가 조용히
#    건너뛰어져 SPI 출력에 제약이 하나도 안 걸린 채 비트스트림이 나왔고,
#    타이밍 리포트는 "위반 없음" 으로 보였다 — 볼 것이 없었으니 당연하다.
#    2026-09-09 첫 합성에서 실제로 이렇게 됐다.
#
#    [고친 방법] 제약 파일셋에 .tcl 을 넣으면 **완전한 Tcl 인터프리터**로 실행된다.
#    조건문이 필요한 제약은 전부 그쪽으로 보낸다.
#    tcl/build_dac_test.tcl 이 dac_test.xdc 다음에 dac_timing.tcl 을 추가한다.

#  sdio1 의 **입력 방향**(classic MISO)은 설정용 axi_quad_spi(6.25 MHz)만 쓰고
#  재생 중에는 읽지 않는다. 느리므로 입력 경로는 타이밍 분석에서 뺀다.
#  (출력 방향은 위 set_output_delay 로 잡혀 있다)
set_false_path -from [get_ports dac_sdio1]

#  DDR / FIXED_IO 는 Zynq 전용 핀이라 위치 제약을 쓰지 않는다 (Vivado 가 자동 매핑).
