# =============================================================================
# dac_timing.tcl — 조건문이 필요한 제약 (제약 파일셋에 .tcl 로 추가)
# Generated by Claude Code, 2026-09-09
#
#  [왜 XDC 가 아니라 .tcl 인가]
#    XDC 는 제한된 인터프리터로 읽혀 if / foreach 같은 제어문을 쓸 수 없다.
#    2026-09-09 첫 합성에서 이렇게 거부됐다:
#        [Designutils 20-1307] Command 'if' is not supported in the xdc
#        constraint file. ["RTL/dac_test.xdc":109]
#    ★ 에러가 아니라 경고였다. if 블록이 통째로 건너뛰어져 SPI 출력 타이밍
#      제약이 하나도 안 걸린 채 비트스트림이 나왔고, 타이밍 리포트는 깨끗해
#      보였다 — 검사할 제약이 없었으니 당연하다. 조용히 틀리는 종류다.
#    제약 파일셋에 넣은 .tcl 은 완전한 Tcl 로 실행되므로 제어문을 쓸 수 있다.
#
#  [실패해도 빌드를 죽이지 않는다 — 대신 눈에 띄게 알린다]
#    25 분짜리 합성을 제약 하나 때문에 버리는 것은 손해다. 그렇다고 조용히
#    넘어가면 위와 같은 일이 또 생긴다. 그래서 catch 로 잡고 !!!! 로 찍는다.
#    합성 로그에서 "!!!!" 를 검색할 것.
#
#  ★ 미검증 — 실제 Vivado 에서 돌려 본 적이 없다.
# =============================================================================

proc dac_warn {msg} {
    puts "!!!! \[dac_timing\] $msg"
}

# -----------------------------------------------------------------------------
# 1. SPI 출력 타이밍
# -----------------------------------------------------------------------------
#  [AD3552R 요구값 — ad3552r.pdf Rev.B Table 4]
#    fSCLK 최대 66 MHz,  t7 데이터 셋업 최소 2 ns,  t8 데이터 홀드 최소 2 ns
#    -> 보드 배선 편차를 1 ns 로 보고 예산을 각각 3 ns 로 잡는다.
#
#  [SCK 는 패브릭에서 만든다] dac_stream_spi 의 sck_q 플립플롭이 만든다.
#  ODDR 클럭 포워딩이 정석이지만 SCK_DIV 가 런타임 레지스터라 ODDR 로는 DIV=1
#  밖에 못 만든다. 대신 세 출력을 전부 출력 플립플롭에서 내보내 지연을 맞춘다.
#
#  [★ 타이밍이 안 맞으면]
#    1순위 : SCK_DIV 를 올린다 (2 -> 25 MHz). 즉시 해결되고 성능만 절반이다.
#    2순위 : ODDR 클럭 포워딩으로 바꾸고 SCK_DIV 를 컴파일 타임 상수로 고정.
#  브링업 사다리를 DIV=6(8.33 MHz)부터 올라가라고 한 이유가 이것이다 —
#  느린 쪽에서는 이 제약이 맞든 틀리든 100 ns 이상 여유가 있다.

set _sck_reg [get_pins -quiet -hierarchical -filter {NAME =~ */sck_q_reg/C}]

if {[llength $_sck_reg] != 1} {
    dac_warn "sck_q_reg/C not found or ambiguous ([llength $_sck_reg] matches)."
    dac_warn "SPI output timing is UNCONSTRAINED. The timing report means nothing"
    dac_warn "for dac_sck/dac_sdio*/dac_cs_n. Do not raise SCK above ~10 MHz."
    if {[llength $_sck_reg] > 1} {
        foreach p $_sck_reg { dac_warn "  match: $p" }
    }
} else {
    puts "\[dac_timing\] SCK source pin : [lindex $_sck_reg 0]"

    if {[catch {
        create_generated_clock -name dac_sck_gen -source [lindex $_sck_reg 0] \
            -divide_by 2 [get_ports dac_sck]
    } _e]} {
        dac_warn "create_generated_clock failed: $_e"
        dac_warn "SPI output timing is UNCONSTRAINED."
    } else {
        set _dq {dac_sdio0 dac_sdio1 dac_sdio2 dac_sdio3 dac_cs_n}
        if {[catch {
            set_output_delay -clock dac_sck_gen -max  3.0 [get_ports $_dq]
            set_output_delay -clock dac_sck_gen -min -3.0 [get_ports $_dq]
        } _e]} {
            dac_warn "set_output_delay failed: $_e"
        } else {
            puts "\[dac_timing\] dac_sck_gen + output delay applied to: $_dq"
        }
    }
}

# -----------------------------------------------------------------------------
# 2. axi_quad_spi 의 IOB=TRUE 를 푼다
# -----------------------------------------------------------------------------
#  [무엇이 문제였나] 2026-09-09 첫 합성에서:
#      [Place 30-73] Invalid constraint on register
#      'dac_sys_i/spi_0/U0/.../SCK_O_NE_4_FDRE_INST'. It has the property
#      IOB=TRUE, but it is not driving or driven by any IO element.
#
#  [원인] axi_quad_spi IP 는 자기 출력이 곧바로 핀으로 나가는 것을 전제로
#    출력 플립플롭에 IOB=TRUE 를 걸어 둔다. 그런데 2026-09-09 부터 spi_0 의
#    출력은 핀이 아니라 dac_stream_spi 의 통과 먹스로 들어간다. IOB 패킹 대상이
#    없어져 이 속성이 무의미해졌다.
#
#  [영향] 기능에는 영향이 없다. 배치 힌트를 못 지킨다는 뜻일 뿐이고, spi_0 는
#    6.25 MHz 설정 전용이라 IOB 패킹이 필요 없다. 다만 critical warning 으로
#    남아 진짜 문제를 가리므로 명시적으로 풀어 준다.
#  ★★ 2026-09-09 (2) — 패턴을 */spi_0/U0/* 로 좁혔다.
#    [무엇이 문제였나] 처음엔 {IOB == "TRUE" && NAME =~ *spi_0*} 로 잡았는데,
#    이 glob 은 dac_sys_i/**dac_spi_0**/inst/... 에도 걸린다. 그래서 바로 위에서
#    IOB 로 실으려고 만든 우리 출력 레지스터 7 개의 IOB 를 도로 FALSE 로 꺼 버렸다.
#    결과 : 배치가 SLICE_X113Y60 같은 엉뚱한 곳으로 가고 WNS 가 -3.442 ns 로 남았다.
#    ★ 주소 세그먼트에서 SEG_spi_0_Reg 와 SEG_dac_spi_0_reg0 이 겹쳤던 것과
#      **완전히 같은 실수**다. 이 설계에는 spi_0 과 dac_spi_0 이 함께 있다는 것을
#      잊지 말 것. 부분 일치 패턴을 쓸 때는 반드시 경계(/)를 포함시킨다.
set _iob [get_cells -quiet -hierarchical -filter {IOB == "TRUE" && NAME =~ */spi_0/U0/*}]
if {[llength $_iob] > 0} {
    foreach c $_iob {
        puts "\[dac_timing\]   clearing IOB on $c"
        if {[catch { set_property IOB FALSE $c } _e]} {
            dac_warn "could not clear IOB on $c : $_e"
        }
    }
    puts "\[dac_timing\] cleared IOB=TRUE on [llength $_iob] cell(s) inside axi_quad_spi"
} else {
    puts "\[dac_timing\] no IOB=TRUE cells inside axi_quad_spi (nothing to clear)"
}

# -----------------------------------------------------------------------------
# 3. SPI 출력 레지스터를 IOB 에 싣는다 (RTL 속성 보강)
# -----------------------------------------------------------------------------
#  RTL 에 (* IOB = "TRUE" *) 를 붙여 두었지만, 위 2 번 같은 사고로 꺼질 수 있고
#  합성 옵션에 따라 속성이 전달되지 않는 경우도 있다. 제약 단계에서 한 번 더
#  못박는다. 여기서 실제로 몇 개에 걸렸는지 찍히므로 진단도 된다.
#
#  ★ 이게 왜 중요한가 : 안 실리면 플립플롭에서 FMC 패드까지 배선이 길어진다.
#    첫 구현에서 route 만 14.5 ns 였고 WNS -4.992 ns 였다.
#  ★ 2026-09-10 — 플립플롭만 고른다. 합성이 삼상 반전용으로 만드는 LUT
#    (sdio1_t_r_inv_i_1)가 이름에 걸리는데, LUT 에 IOB 를 걸어 봐야 의미가 없다.
#    REF_NAME 이 아직 FD* 가 아닌 단계(합성 전)라면 아래 fallback 으로 넘어간다.
set _outregs [get_cells -quiet -hierarchical -filter {
    REF_NAME =~ FD* &&
    NAME =~ */dac_spi_0/* &&
    (NAME =~ *sck_o_r_reg* || NAME =~ *cs_n_o_r_reg* ||
     NAME =~ *sdio_o_r_reg* || NAME =~ *sdio1_t*)
}]
if {[llength $_outregs] == 0} {
    #  합성 이전 단계에서는 REF_NAME 이 FD* 가 아닐 수 있다. 이름만으로 다시 본다.
    set _outregs [get_cells -quiet -hierarchical -filter {
        NAME =~ */dac_spi_0/* &&
        (NAME =~ *sck_o_r_reg* || NAME =~ *cs_n_o_r_reg* ||
         NAME =~ *sdio_o_r_reg* || NAME =~ *sdio1_t*)
    }]
}
if {[llength $_outregs] == 0} {
    dac_warn "SPI output registers not found - they will not pack into the IOB."
    dac_warn "Expected names like */dac_spi_0/inst/sck_o_r_reg."
} else {
    foreach c $_outregs {
        if {[catch { set_property IOB TRUE $c } _e]} {
            dac_warn "could not set IOB on $c : $_e"
        } else {
            puts "\[dac_timing\]   IOB TRUE -> $c"
        }
    }
    puts "\[dac_timing\] requested IOB packing for [llength $_outregs] output register(s)"
}
