# =============================================================================
# eopll_testpins.xdc  —  ★★ 시험 전용 임시 핀 배치. 실제 보드 핀맵이 아니다 ★★
# Generated by Claude Code, 2026-09-21
#
#  [무엇을 위한 것인가]
#    합친 설계(TDC + DAC)에서 **TDC 가 예전처럼 도는지**만 확인하려고 비트스트림을
#    뽑기 위한 파일이다. 합친 보드의 FMC 핀맵이 아직 없어서 DAC 핀에 LOC 가 없고,
#    LOC 가 없으면 Vivado 가 write_bitstream 을 DRC(UCIO-1)로 막는다.
#
#  [왜 PMOD 인가 — 안전 때문이다]
#    ZedBoard 의 PMOD JA~JD 는 전부 **뱅크 13** 이고 VCCO 가 3.3 V 로 고정이다
#    (Parts/Zedboard-Master.xdc, "JB Pmod - Bank 13").
#    즉 J18(VADJ)과 아무 관계가 없다. FMC 쪽은 건드리지 않으므로,
#    FMC 에 무엇이 꽂혀 있든(비교기든 EVAL-AD3552RFMCZ 든) 이 파일이 만드는
#    출력이 그쪽으로 나가지 않는다.
#    ★ 대신 전제가 하나 있다 : **PMOD JB 와 JC 에 아무것도 꽂혀 있으면 안 된다.**
#      이 빌드는 그 핀들을 구동한다. 리셋 직후 값은 cs_n = 1, sck = 0,
#      dac_ctrl(axi_gpio) = 0 이다.
#
#  [쓰면 안 되는 때]
#    실제 보드 핀맵이 정해진 뒤에는 이 파일을 빼고 새 XDC 를 쓸 것.
#    이 파일을 남겨 두면 실제 DAC 배선과 충돌한다.
#
#  [TDC 쪽과 충돌하지 않는가]
#    RTL/tdc_zedboard.xdc 가 쓰는 핀은 P16(BTNC), T18(BTNU), T22/T21/U22/U21(LED),
#    E21/D21(FMC LA27 LVDS) 뿐이다. PMOD 핀은 하나도 쓰지 않는다. 충돌 없음.
#
#  [PMOD JA 를 피한 이유]
#    예전에 STM32 임시 신호원을 JA1(Y11)에 물렸던 이력이 있다
#    (../TDC : 2026-09-06 zed_uart). 배선이 남아 있을 수 있어 JA 는 비워 둔다.
# =============================================================================

# ---- DAC SPI 4선 + 멀티IO : PMOD JB (뱅크 13, 3.3 V) ----
#  JB1 W12 / JB2 W11 / JB3 V10 / JB4 W8 / JB7 V12 / JB8 W10   (JB9 V9, JB10 V8 미사용)
set_property PACKAGE_PIN W12 [get_ports dac_sck]
set_property PACKAGE_PIN W11 [get_ports dac_cs_n]
set_property PACKAGE_PIN V10 [get_ports dac_sdio0]
set_property PACKAGE_PIN W8  [get_ports dac_sdio1]
set_property PACKAGE_PIN V12 [get_ports dac_sdio2]
set_property PACKAGE_PIN W10 [get_ports dac_sdio3]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sck]
set_property IOSTANDARD LVCMOS33 [get_ports dac_cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sdio0]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sdio1]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sdio2]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sdio3]

# ---- 정적 제어선 (axi_gpio) : PMOD JC (뱅크 13, 3.3 V) ----
#  [0]=RESETn [1]=QSPI_SEL [2]=LDACn [3]=ALERTn(입력)
#  JC1_N AB6 / JC1_P AB7 / JC2_N AA4 / JC2_P Y4
set_property PACKAGE_PIN AB6 [get_ports {dac_ctrl_tri_io[0]}]
set_property PACKAGE_PIN AB7 [get_ports {dac_ctrl_tri_io[1]}]
set_property PACKAGE_PIN AA4 [get_ports {dac_ctrl_tri_io[2]}]
set_property PACKAGE_PIN Y4  [get_ports {dac_ctrl_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ctrl_tri_io[*]}]

# ---- 구동 세기는 기본값보다 약하게 ----
#  [왜] 시험용이라 아무것도 안 달려 있다. 필요 이상으로 세게 구동할 이유가 없고,
#    동시 스위칭 잡음을 줄이는 편이 TDC 지연선에 유리하다 (TDC 는 뱅크가 다르지만
#    전원·그라운드는 공유한다).
#  ★ 2026-09-21 : SLEW SLOW 는 출력 버퍼를 느리게 만든다. 첫 시험 빌드(eopll_tp2)에서
#    setup WNS -3.587 ns 가 났고 위반 경로 5개가 전부 clk_fpga_0 -> dac_sck_gen 이었는데,
#    이 느린 버퍼가 한몫했다 (생성 클럭 dac_sck_gen 이 그 버퍼 뒤 패드에서 정의된다).
#    이제 build_eopll.tcl 이 시험 핀맵일 때 RTL/dac_timing.tcl 을 아예 넣지 않으므로
#    DAC 출력이 무제약이 되어 이 문제가 사라진다. 잡음 쪽 이유만 남으므로 SLOW 를 유지한다.
set_property DRIVE 4 [get_ports {dac_sck dac_cs_n dac_sdio0 dac_sdio2 dac_sdio3}]
set_property SLEW SLOW [get_ports {dac_sck dac_cs_n dac_sdio0 dac_sdio1 dac_sdio2 dac_sdio3}]
