`timescale 1ns / 1ps
// =============================================================================
// tdc_calib_ram.v  —  교정표 RAM (PS 가 쓰고, 타임스탬프 파이프라인이 읽는다)
// Generated by Claude Code, 2026-09-15
//
//  [무엇을 대체하나]
//    tdc_calib_rom (Block Memory Generator IP, COE 로 초기화, 쓰기 불가).
//    교정표를 바꾸려면 COE 를 새로 만들어 재빌드해야 했고, 재빌드는 place & route 를
//    바꿔 히트가 찍히는 탭 범위(창)를 옮긴다 (2026-09-05 : 탭 2~321 -> 24~348).
//    즉 표를 만든 조건이 표를 넣는 순간 달라지는 구조였다.
//    이제 PS 가 Mode 1 히스토그램으로 표를 계산해 AXI(0x2000 + i*4)로 여기에 쓴다.
//
//  [포트]
//    Port A : s_axi_aclk (100 MHz). tdc_axi_regs 가 쓰고 되읽는다. 읽기 지연 1클럭.
//    Port B : tdc_clk (200 MHz). tdc_timestamp_calc 가 매 클럭 읽는다.
//             ★ 읽기 지연 2클럭 (주소 샘플 1 + 출력 레지스터 1) — 반드시 2.
//               tdc_timestamp_calc 의 Stage 3 가 fine 번호 인가 후 세 번째 에지에서
//               이 출력을 잡는다. 1 이나 3 이면 앞뒤 다른 히트의 교정값이 섞인다.
//
//  [깊이 512 인 이유]
//    fine 번호는 384비트 온도계 코드의 popcount 라 0..384 (385가지)다.
//    384칸이면 384 가 주소 범위 밖이 된다. 9비트 주소 전체(512칸)를 잡아 경계 문제를 없앤다.
//    512 x 13 = 6,656 비트라 RAMB18 하나(18 Kb)에 들어간다.
//
//  [초기값 — 선형 램프]
//    mem[i] = round(i x 5000 / NUM_TAPS)   (i < NUM_TAPS)
//    mem[i] = mem[NUM_TAPS-1] = 4987       (i >= NUM_TAPS, 384탭 기준)
//    ★ 반올림은 0.5 를 짝수 쪽으로 보낸다 (numpy np.round 와 같다).
//      근거 : 2026-09-06 캡처(Data/20260906_zed_pmod_stm32.zip, capture.csv)에서 하드웨어가
//      뺀 값을 역산하면 312, 2812, 4062 가 나온다. 각각 탭 24·216·312 의 312.5·2812.5·4062.5 를
//      짝수로 내린 값이다. 즉 그 빌드의 COE 는 이 규칙으로 만들어졌다.
//    PS 가 교정표를 쓰기 전에는 종전 빌드와 같은 선형 램프로 동작한다.
//
//  [두 포트 클럭이 다를 때의 충돌]
//    Port A 가 어떤 칸을 쓰는 바로 그 순간 Port B 가 같은 칸을 읽으면 그 한 번의 읽기값은
//    정해지지 않는다. tdc_axi_regs 가 시퀀서 BUSY 중에는 교정표 쓰기를 무시하고,
//    PS 는 측정이 끝난 뒤에만 쓴다.
// =============================================================================
module tdc_calib_ram #(
    parameter integer NUM_TAPS = 384
)(
    input  wire        clk_a,
    input  wire        we_a,
    input  wire [8:0]  addr_a,
    input  wire [12:0] din_a,
    output reg  [12:0] dout_a,

    input  wire        clk_b,
    input  wire [8:0]  addr_b,
    output reg  [12:0] dout_b
);
    (* ram_style = "block" *) reg [12:0] mem [0:511];
    reg [12:0] rd_b;

    // round(k x 5000 / NUM_TAPS), 0.5 는 짝수 쪽으로 (위 [초기값] 주석 참조)
    function [12:0] ramp_val(input integer k);
        integer num, q, r;
        begin
            num = k * 5000;
            q   = num / NUM_TAPS;
            r   = num % NUM_TAPS;
            if ((2 * r > NUM_TAPS) || ((2 * r == NUM_TAPS) && (q % 2 == 1)))
                q = q + 1;
            ramp_val = q[12:0];
        end
    endfunction

    integer i;
    initial begin
        for (i = 0; i < 512; i = i + 1)
            mem[i] = ramp_val((i < NUM_TAPS) ? i : (NUM_TAPS - 1));
        dout_a = 13'd0;
        dout_b = 13'd0;
        rd_b   = 13'd0;
    end

    // Port A : 쓰기 + 되읽기 (read-first. 같은 사이클에 쓰면 옛값이 나온다)
    always @(posedge clk_a) begin
        if (we_a) mem[addr_a] <= din_a;
        dout_a <= mem[addr_a];
    end

    // Port B : 읽기 전용, 지연 2클럭. dout_b 는 Vivado 가 BRAM 출력 레지스터(DOB_REG)로 흡수한다.
`ifdef CAL_LAT3_NEGATIVE_TEST
    // 시뮬레이션 전용 : 일부러 지연을 3 으로 만들어 테스트벤치가 어긋남을 잡는지 확인한다.
    reg [12:0] rd_b2 = 13'd0;
    always @(posedge clk_b) begin
        rd_b   <= mem[addr_b];
        rd_b2  <= rd_b;
        dout_b <= rd_b2;
    end
`else
    always @(posedge clk_b) begin
        rd_b   <= mem[addr_b];
        dout_b <= rd_b;
    end
`endif
endmodule
