# =============================================================================
# bd_dac_sys.tcl — PS7 + AXI Quad SPI + AXI GPIO 블록 디자인
# Generated by Claude Code, 2026-09-08
#
#  ★ 2026-09-08 실물 검증 완료 — Vivado 2024.1 에서 BD 생성·검증·합성 통과.
#
#  [이 블록 디자인에 든 것]
#    processing_system7  : Zynq PS (ARM). M_AXI_GP0 만 사용
#    proc_sys_reset      : FCLK_RESET0_N 을 동기 리셋으로 정리
#    axi_interconnect    : PS 의 AXI3 -> AXI4-Lite 변환 + 주소 디코딩 (MI 2개)
#    axi_quad_spi        : AD3552R 과의 SPI. Phase 1/2 는 standard(단선) 모드
#    axi_gpio            : RESETn / QSPI_SEL / LDACn 출력 + ALERTn 입력
#
#  [왜 Phase 1 에 커스텀 RTL 이 없나]
#    Phase 1 의 목적은 배선·전원·프로토콜 확인뿐이고 속도가 무의미하다.
#    스톡 IP 로 끝내면 검증할 변수가 줄어든다. 자작 SPI 마스터는 Phase 3
#    (처프 스트리밍) 에서 처음 필요해진다.
#
#  ─────────────────────────────────────────────────────────────────────────
#  [★ PS7 설정은 ../TDC/tcl/bd_ps_sys.tcl 에서 가져왔다]
#    아래 세 값은 TDC 저장소에서 실물로 확인된 것이다. 근거 전문은 그쪽 주석에
#    있으니 의심이 들면 그 파일을 먼저 읽을 것. 요약만 적는다:
#
#    (1) PCW_CRYSTAL_PERIPHERAL_FREQMHZ = 33.333333
#        ZedBoard 의 PS_CLK 발진기 주파수. 이 값이 틀리면 FCLK_CLK0 이 100 MHz 가
#        아니게 되는데, Vivado 는 검증할 방법이 없어 합성·비트스트림이 전부 통과한다.
#        즉 틀려도 조용히 틀린다.
#
#    (2) PCW_PRESET_BANK1_VOLTAGE = LVCMOS 1.8V
#        ★ 이걸 빠뜨리면 UART 송신은 되는데 수신이 완전히 죽는다.
#        ZedBoard 매뉴얼 Table 21 : MIO Bank 0/500 = 3.3V, Bank 1/501 = 1.8V.
#        UART1 은 MIO[48:49] 로 Bank 1 에 있는데 PS7 IP 기본값은 두 뱅크 모두
#        3.3V 라, 입력 판정 문턱이 2.0V 로 잡혀 1.8V 신호를 영원히 인식 못 한다.
#
#    (3) DDR 파라미터는 기본값 그대로 둔다.
#        보드 파일이 없어 손으로 넣으면 틀리기 쉽고, 틀리면 조용히 동작하다 깨진다.
#        ★★ 2026-09-11 실측 : 조용히 깨지는 것이 아니라 처음부터 깨져 있다.
#          전원 직후 ps7_init 을 한 번만 돌린 상태에서 0x00100000 / 0x08000000 /
#          0x1C000000 세 구간 512 워드를 시험해 각각 68 / 48 / 85 워드가 틀렸다.
#          읽은 값이 옆 주소의 값이거나 두 워드가 섞인다. 바이트 레인이 어긋난다.
#          같은 코드를 OCM 에서 돌리면 완벽하게 돌았다. tcl/xsct_ddr_test.tcl 참조.
#          고치려면 ZedBoard 보드 파일을 깔고 프리셋을 적용해야 한다.
#        ★ Vitis 앱의 링커 스크립트를 ps7_ram_0 (OCM, 256 KB) 로 지정할 것.
#          Phase 1/2 는 레지스터 몇 개라 OCM 으로 충분하다.
#          Phase 3 의 처프 테이블도 1024×16bit = 2 KB 라 문제없다.
#
#    ※ 이 설정을 여기서 바꾸면 TDC 쪽 사본도 같이 봐야 한다. 두 저장소가
#      조용히 갈라질 수 있는 유일한 지점이다.
#  ─────────────────────────────────────────────────────────────────────────
#
#  [사용법]  build_dac_test.tcl 이 source 한다. Vivado Tcl Console 에서 단독으로도:
#    cd <repo> ; source tcl/bd_dac_sys.tcl
# =============================================================================

if {[llength [get_projects -quiet]] == 0} {
    create_project -in_memory -part xc7z020clg484-1
}

set BD_NAME dac_sys

create_bd_design $BD_NAME
current_bd_design [get_bd_designs $BD_NAME]

# ---------------------------------------------------------------- 이름 조회 헬퍼
#  ★★ 2026-09-10 — 인터페이스/핀 이름을 대소문자 무시로 찾는다.
#    [무엇이 문제였나]
#      ERROR: [BD 5-106] Arguments to the connect_bd_intf_net command cannot be empty.
#        connect_bd_intf_net ... [get_bd_intf_pins dac_spi_0/S_AXI]
#    모듈 참조일 때는 Vivado 가 추론해 만든 이름이 S_AXI 였는데, 정식 IP 로
#    패키징하면 component.xml 에 적힌 이름을 그대로 쓴다. ipx::package_project 는
#    포트 접두어에서 이름을 따오므로 **소문자 s_axi** 가 된다.
#    (패키징 로그의 "Inferred bus interface 's_axi'" 가 그 증거였다)
#    이름을 박아 두면 패키징 방식이 조금만 달라져도 깨지므로 찾아서 쓴다.
proc dac_dump_cell {cell} {
    puts "!!!! ---- what is actually on '$cell' ----"
    if {[llength [get_bd_cells -quiet $cell]] == 0} {
        puts "!!!!   the cell does not exist at all."
        puts "!!!!   cells in this design:"
        foreach c [get_bd_cells -quiet /*] { puts "!!!!       $c" }
        return
    }
    puts "!!!!   VLNV : [get_property -quiet VLNV [get_bd_cells $cell]]"
    set ifs [get_bd_intf_pins -quiet "$cell/*"]
    puts "!!!!   interface pins ([llength $ifs]) :"
    foreach q $ifs { puts "!!!!       [file tail $q]   ([get_property -quiet VLNV $q])" }
    set pins [get_bd_pins -quiet "$cell/*"]
    puts "!!!!   plain pins ([llength $pins]) :"
    foreach q $pins { puts "!!!!       [file tail $q]" }
}

proc dac_intf {cell name} {
    set p [get_bd_intf_pins -quiet "$cell/$name"]
    if {[llength $p] == 1} { return $p }
    foreach q [get_bd_intf_pins -quiet "$cell/*"] {
        if {[string equal -nocase [file tail $q] $name]} { return $q }
    }
    dac_dump_cell $cell
    error "BD interface pin '$name' not found on '$cell' - see the dump above."
}

proc dac_pin {path} {
    set p [get_bd_pins -quiet $path]
    if {[llength $p] == 1} { return $p }
    #  대소문자만 다른 경우를 구제한다 (위 dac_intf 와 같은 이유).
    set cell [file dirname $path]
    set name [file tail $path]
    foreach q [get_bd_pins -quiet "$cell/*"] {
        if {[string equal -nocase [file tail $q] $name]} { return $q }
    }
    if {[llength $p] == 0} {
        error "BD pin not found: $path\n\
               The axi_quad_spi interface member pin names may differ in this Vivado\n\
               version. Run 'get_bd_pins spi_0/*' to see the real names."
    }
    return $p
}


# ---------------------------------------------------------------- PS7
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7 ps7_0

# ---------------------------------------------------------- ZedBoard 프리셋
#  ★★ 2026-09-11 : 이것이 빠져 있어 DDR 이 동작하지 않았다.
#    부품번호(-part)만 주면 PS7 의 DDR 컨트롤러는 Vivado 기본값으로 남는다.
#    부품 번호, 타이밍, 바이트 레인별 보드 지연이 전부 다른 보드 값이라
#    쓰기 레벨링이 수렴할 수 없다. 칩은 정상이고 설정이 틀렸던 것이다.
#
#    ★ 보드 파일(board_part)은 필요 없다. ZedBoard 프리셋은 PS7 IP 자체가
#      들고 있다. 2026-09-11 집 PC 에서 확인한 경로:
#        <Vivado>/data/ip/xilinx/processing_system7_v5_5/preset/ZedBoard.tcl
#      DDR 파라미터 27 개가 들어 있다. 바이트 레인별 보드 지연
#      (BOARD_DELAY0..3 = 0.41 / 0.411 / 0.341 / 0.358) 과 DQS-클럭 지연
#      (0.025 / 0.028 / 0.001 / 0.001) 까지 포함한다.
#      부품은 MT41J128M16, 2048 Mbit, DDR3_1066F, 533.333313 MHz.
#
#      Avnet 보드 파일의 preset.xml 을 열어 보면 내용이 딱 한 줄
#      CONFIG.preset = ZedBoard 다. 보드 파일도 결국 이 프리셋을 가리킬
#      뿐이다. 그래서 board_part 를 요구하지 않는다 — 회사 노트북에 보드
#      파일이 깔려 있는지 확인된 바 없고, 확인 못 한 것을 전제로 빌드를
#      막으면 안 된다.
#
#    ★ 프리셋이 아래 네 가지를 이미 잡아 준다. 손으로 넣던 값들이다:
#        PCW_UART1_PERIPHERAL_ENABLE {1}
#        PCW_UART1_UART1_IO {MIO 48 .. 49}
#        PCW_PRESET_BANK0_VOLTAGE {LVCMOS 3.3V}
#        PCW_PRESET_BANK1_VOLTAGE {LVCMOS 1.8V}
#      아래 set_property 는 그래도 그대로 둔다. 프리셋이 바뀌어도 우리가
#      무엇에 의존하는지 코드에 남아 있어야 한다.
#
#    ※ 순서가 중요하다. 프리셋을 먼저 적용해야 우리 개별 설정이 덮어쓴다.
#      반대로 하면 프리셋이 GP0 이나 FCLK 설정을 되돌린다.
set ::DAC_PRESET_OK 0
if {[catch {set_property CONFIG.preset {ZedBoard} [get_bd_cells ps7_0]} e]} {
    puts "\[X\] ZedBoard preset could not be applied: $e"
} else {
    set ::DAC_PRESET_OK 1
    puts "\[*\] ZedBoard preset applied to ps7_0"
}

set_property -dict [list \
    CONFIG.PCW_CRYSTAL_PERIPHERAL_FREQMHZ {33.333333} \
    CONFIG.PCW_USE_M_AXI_GP0              {1} \
    CONFIG.PCW_EN_CLK0_PORT               {1} \
    CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ   {100} \
    \
    CONFIG.PCW_UART1_PERIPHERAL_ENABLE    {1} \
    CONFIG.PCW_UART1_UART1_IO             {MIO 48 .. 49} \
    CONFIG.PCW_UART1_BAUD_RATE            {115200} \
    \
    CONFIG.PCW_PRESET_BANK0_VOLTAGE       {LVCMOS 3.3V} \
    CONFIG.PCW_PRESET_BANK1_VOLTAGE       {LVCMOS 1.8V} \
] [get_bd_cells ps7_0]

# ★★ 2026-09-10 : S_AXI_HP0 를 다시 껐다.
#   구조를 DDR+DMA 에서 온칩 BRAM 핑퐁으로 바꿨으므로 PL 이 PS 슬레이브 포트를
#   건드릴 일이 없다. 그리고 이 포트가 PS 디버그를 통째로 죽인 원인이었다
#   (설계문서 §11 — Cannot reset APU / APB AP transaction error).
#   이제 PS7 은 TDC 설계와 같은 모양이다 — GP0 하나뿐.
#
#   ※ DDR 파라미터가 기본값인 것은 그대로지만 이제 무관하다. DMA 가 DDR 을
#     읽지 않고, 파형은 PL 안의 BRAM 에 있다.

# DDR / FIXED_IO 는 반드시 외부로 뺀다. 안 빼면 PS 의 클럭·리셋이 어디에도
# 연결되지 않아 실물에서 PS 가 뜨지 않는다. Zynq 전용 핀이라 XDC 는 불필요.
#  자동화가 이미 만들었으면 다시 만들지 않는다.
if {[llength [get_bd_intf_ports -quiet DDR]] == 0} {
    make_bd_intf_pins_external -name DDR      [get_bd_intf_pins ps7_0/DDR]
}
if {[llength [get_bd_intf_ports -quiet FIXED_IO]] == 0} {
    make_bd_intf_pins_external -name FIXED_IO [get_bd_intf_pins ps7_0/FIXED_IO]
}

#  ★ DDR 파라미터가 정말 들어갔는지 값까지 대조한다.
#    조용히 기본값인 채 빌드가 끝까지 통과하는 것이 2026-09-11 의 문제였다.
#    이름만 찍어 보는 것으로는 부족하다. 기대값은 ZedBoard.tcl 프리셋에서
#    그대로 가져왔다. 바이트 레인별 보드 지연이 핵심이다 — 이 네 값이
#    다른 보드 것이면 쓰기 레벨링이 수렴하지 못한다.
set ddr_expect [list \
    PCW_UIPARAM_DDR_DEVICE_CAPACITY  {2048 MBits} \
    PCW_UIPARAM_DDR_SPEED_BIN        {DDR3_1066F} \
    PCW_UIPARAM_DDR_BOARD_DELAY0     {0.41} \
    PCW_UIPARAM_DDR_BOARD_DELAY1     {0.411} \
    PCW_UIPARAM_DDR_BOARD_DELAY2     {0.341} \
    PCW_UIPARAM_DDR_BOARD_DELAY3     {0.358} \
]
set ddr_bad 0
puts ""
puts "    ---- DDR parameters on ps7_0 ----"
foreach {k want} $ddr_expect {
    if {[catch {set got [get_property CONFIG.$k [get_bd_cells ps7_0]]}]} {
        puts [format "    %-32s = <cannot read>" $k]
        incr ddr_bad
        continue
    }
    if {$got eq $want} {
        puts [format "    %-32s = %s" $k $got]
    } else {
        puts [format "    %-32s = %s   <<<< expected %s" $k $got $want]
        incr ddr_bad
    }
}
foreach k {PCW_UIPARAM_DDR_PARTNO PCW_UIPARAM_DDR_FREQ_MHZ} {
    if {![catch {set v [get_property CONFIG.$k [get_bd_cells ps7_0]]}]} {
        puts [format "    %-32s = %s" $k $v]
    }
}
if {$ddr_bad || !$::DAC_PRESET_OK} {
    puts ""
    puts "\[X\] the ZedBoard DDR parameters are NOT in place ($ddr_bad mismatched)."
    puts "    The DDR will not work. Measured 2026-09-11 with default parameters:"
    puts "    68 / 48 / 85 wrong words out of 512 at 0x00100000 / 0x08000000 / 0x1C000000."
    puts "    Link applications into ps7_ram_0 (OCM), never ps7_ddr_0, and re-measure"
    puts "    with tcl/xsct_ddr_test.tcl before trusting the DDR."
} else {
    puts "    all checked DDR parameters match the ZedBoard preset"
}

# ---------------------------------------------------------------- 리셋 / 인터커넥트
create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset rst_0

#  제어용 AXI4-Lite 인터커넥트. 슬레이브 3개 :
#    M00 spi_0(설정용 SPI)  M01 gpio_0  M02 dac_spi_0(처프 엔진)
#  ★ 2026-09-10 : DMA 가 빠져 4 -> 3.
create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect icn_0
set_property -dict [list CONFIG.NUM_SI {1} CONFIG.NUM_MI {3}] [get_bd_cells icn_0]

# ---------------------------------------------------------------- AXI Quad SPI
#  [설정 근거]
#   C_SPI_MODE 0        : standard(단선) SPI. Phase 1/2 는 io0=MOSI, io1=MISO 만 쓴다
#   C_SPI_MEMORY 0      : 상대가 SPI 플래시가 아니라 일반 슬레이브
#   C_NUM_SS_BITS 1     : 슬레이브 1개
#   C_NUM_TRANSFER_BITS 8 : AD3552R 프레임이 바이트 단위 (명령 1B + 데이터 NB)
#   C_SCK_RATIO 16      : SCK = ext_spi_clk / 16 = 100 MHz / 16 = 6.25 MHz
#                         ★ 2026-09-08 수정 : 처음에 32 를 넣었는데 Vivado 2024.1 이
#                           거부했다 —
#                             ERROR [IP_Flow 19-3461] Value '32' is out of the range
#                             for parameter 'SCK Ratio(C_SCK_RATIO)'.
#                             Valid values are - 2, 4, 8, 16
#                           허용값이 {2,4,8,16} 뿐이라 최대인 16 으로 내렸다.
#                           6.25 MHz 는 AD3552R 상한 66 MHz 에 한참 못 미치므로
#                           Phase 1/2 에는 아무 문제가 없다.
#   C_FIFO_DEPTH 16     : CPU 가 바이트를 밀어 넣는 방식. 깊이는 무관
#
#  ★ CPOL/CPHA 는 소프트웨어(SPICR 레지스터)에서 정한다. 본 설계는 SPI mode 0 을
#    가정하지만 데이터시트 Fig.2/3 로 아직 확인하지 않았다 (미검증 항목).
create_bd_cell -type ip -vlnv xilinx.com:ip:axi_quad_spi spi_0
set_property -dict [list \
    CONFIG.C_SPI_MODE          {0} \
    CONFIG.C_SPI_MEMORY        {0} \
    CONFIG.C_NUM_SS_BITS       {1} \
    CONFIG.C_NUM_TRANSFER_BITS {8} \
    CONFIG.C_SCK_RATIO         {16} \
    CONFIG.C_FIFO_DEPTH        {16} \
    CONFIG.C_USE_STARTUP       {0} \
    CONFIG.C_TYPE_OF_AXI4_INTERFACE {0} \
] [get_bd_cells spi_0]

# ---------------------------------------------------------------- AXI GPIO (정적 제어선)
#  채널1 (출력 3비트) : [0]=RESETn  [1]=QSPI_SEL  [2]=LDACn
#  채널2 (입력 1비트) : ALERTn
#
#  ★ 리셋 직후 GPIO 출력은 0 이다. 즉 RESETn=0(리셋 걸림), LDACn=0 이 된다.
#    소프트웨어가 가장 먼저 할 일이 이 둘을 1 로 올리는 것이다. Phase 1 코드에서
#    빠뜨리면 SPI 가 아무리 맞아도 응답이 없다.
#  ★ QSPI_SEL 은 0(=classic SPI) 이 맞으므로 그대로 두면 된다.
create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio gpio_0
set_property -dict [list \
    CONFIG.C_IS_DUAL          {0} \
    CONFIG.C_GPIO_WIDTH       {4} \
    CONFIG.C_ALL_OUTPUTS      {0} \
    CONFIG.C_ALL_INPUTS       {0} \
] [get_bd_cells gpio_0]

# ---------------------------------------------------------------- 파형 재생 (2026-09-10)
#
#  PS ──(AXI-Lite)──> dac_spi_0 ─┬─ 레지스터 (CTRL/CFG/PERIOD/NPOINTS/STATUS)
#                                 ├─ 버퍼 A BRAM (0x1000~)
#                                 ├─ 버퍼 B BRAM (0x2000~)
#                                 └─ SPI 시프트 엔진 ──> FMC 4선
#
#  [★ DDR + DMA 구조를 걷어냈다]
#    전 : DDR ─(S_AXI_HP0)─ icn_hp ─ axi_dma(SG 순환) ─ axis FIFO ─ FSM
#    후 : PS 가 AXI-Lite 로 BRAM 에 직접 기록, FSM 이 BRAM 을 읽음
#    빠진 것 : axi_dma, axis_data_fifo, icn_hp, S_AXI_HP0
#
#    (1) 파형이 1024점 × 2 B = 2 KB 다. DDR 을 쓸 이유가 없다.
#    (2) S_AXI_HP0 가 PS 디버그를 죽인 원인이었다 (설계문서 §11).
#    (3) BD 가 Phase 2.5 의 검증된 구조로 돌아간다.
#
#  ★ 핑퐁은 그대로다. BRAM 두 장이 IP 안에 있고, PS 가 재생 중에 비활성 버퍼를
#    갱신한 뒤 CTRL.SWAP_REQ 를 세우면 **처프 경계에서** 갈아탄다. 나중에 TDC
#    보정 파형을 끊김 없이 넣는 경로가 이것이다.

# -----------------------------------------------------------------------------
#  ★★ 2026-09-10 — 이 블록이 통째로 사라져 있었다.
#    DDR+DMA 구간을 잘라낼 때 잘라낼 범위의 끝을 "#  spi_0 의 미사용 입력 종단."
#    으로 잡았는데, 그 사이에 dac_spi_0 셀 생성 코드가 있었다. 그래서 셀이 아예
#    안 만들어진 채로 아래에서 연결을 시도했고, 계속 이렇게 죽었다:
#      BD interface pin 'S_AXI' not found on 'dac_spi_0'.  Available: (비어 있음)
#    "인터페이스가 없다" 가 아니라 "셀이 없다" 였는데, 메시지가 그것을 구분해
#    주지 않아 세 번 헛짚었다 (대소문자 / infer_bus_interfaces / $clog2).
#    그래서 dac_dump_cell 을 만들어 셀 존재 여부부터 찍게 했다.
# -----------------------------------------------------------------------------
if {[info exists ::DAC_IP_VLNV] && $::DAC_IP_VLNV ne ""} {
    puts "\[*\] dac_spi_0 from packaged IP : $::DAC_IP_VLNV"
    create_bd_cell -type ip -vlnv $::DAC_IP_VLNV dac_spi_0
} else {
    puts "\[*\] dac_spi_0 as a module reference"
    if {[llength [get_files -quiet dac_chirp_engine.v]] == 0} {
        set _rtl [file normalize [file join [file dirname [info script]] .. RTL dac_chirp_engine.v]]
        if {![file exists $_rtl]} { error "RTL not found: $_rtl" }
        add_files -norecurse $_rtl
        update_compile_order -fileset sources_1
    }
    if {[catch {create_bd_cell -type module -reference dac_chirp_engine dac_spi_0} _e]} {
        puts "!!!! create_bd_cell (module reference) failed:"
        puts "!!!!   $_e"
        error "cannot create dac_spi_0"
    }
    catch { set_property CONFIG.FREQ_HZ 100000000 [get_bd_pins dac_spi_0/aclk] }
    catch { set_property CONFIG.ASSOCIATED_BUSIF {s_axi} [get_bd_pins dac_spi_0/aclk] }
}

#  만들어진 직후에 무엇이 생겼는지 그대로 찍는다. 인터페이스 추론이 실패해도
#  로그만 보면 바로 알 수 있다.
dac_dump_cell dac_spi_0

#  spi_0 의 미사용 입력 종단. BD 에서 입력 핀을 띄워 두면 CRITICAL WARNING 이 난다.
create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant gnd_0
set_property -dict [list CONFIG.CONST_WIDTH {1} CONFIG.CONST_VAL {0}] [get_bd_cells gnd_0]

# ---------------------------------------------------------------- 연결
connect_bd_intf_net [get_bd_intf_pins ps7_0/M_AXI_GP0] [get_bd_intf_pins icn_0/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins icn_0/M00_AXI]   [get_bd_intf_pins spi_0/AXI_LITE]
connect_bd_intf_net [get_bd_intf_pins icn_0/M01_AXI]   [get_bd_intf_pins gpio_0/S_AXI]
connect_bd_intf_net [get_bd_intf_pins icn_0/M02_AXI]   [dac_intf dac_spi_0 S_AXI]

# 클럭 : FCLK_CLK0(100 MHz) 하나로 AXI 도메인과 SPI 기준클럭을 모두 돌린다.
#  ★ TDC 와 달리 여기서는 MMCM 이 필요 없다. 200 MHz TDL 도, 위상 시프터도 없다.
set fclk [get_bd_pins ps7_0/FCLK_CLK0]
foreach p {ps7_0/M_AXI_GP0_ACLK rst_0/slowest_sync_clk
           icn_0/ACLK icn_0/S00_ACLK icn_0/M00_ACLK icn_0/M01_ACLK icn_0/M02_ACLK
           spi_0/s_axi_aclk spi_0/ext_spi_clk gpio_0/s_axi_aclk
           dac_spi_0/aclk} {
    connect_bd_net $fclk [get_bd_pins $p]
}

connect_bd_net [get_bd_pins ps7_0/FCLK_RESET0_N] [get_bd_pins rst_0/ext_reset_in]

# -----------------------------------------------------------------------------
#  ★ 2026-09-10 — 한때 여기에 util_vector_logic 두 개(and_icn / and_per)가 있었다.
#    proc_sys_reset 출력을 FCLK_RESET0_N 과 AND 해서 PL 리셋에 걸었다.
#
#    [왜 넣었었나] Vitis 가 FPGA 를 ps7_init 보다 먼저 굽는데, 그 시점에는
#    FCLK_CLK0 이 없어 proc_sys_reset 이 리셋을 못 만든다. 그러면 icn_hp 와
#    dma_0 가 리셋 없이 PS 의 S_AXI_HP0 포트를 건드리고, 끝나지 않는 트랜잭션이
#    PS 인터커넥트를 멈춰 디버그까지 죽였다.
#
#    [왜 뺐나] 같은 날 구조를 바꾸면서 S_AXI_HP0 도 icn_hp 도 dma_0 도 전부
#    없앴다. **PL 이 PS 슬레이브 포트를 건드릴 경로 자체가 사라졌으므로**
#    이 게이트가 막을 것이 없다. 이유가 없어진 물건을 남겨 두면 다음 사람이
#    왜 있는지 몰라 못 건드린다.
#
#    ※ FMC 핀 쪽도 안전하다. 출력 플립플롭이 동기 리셋이라 cs_n 은 1(해제)로
#      올라오고, DAC 의 RESETn 은 axi_gpio 출력이 리셋 직후 0 이라 눌려 있다.
# -----------------------------------------------------------------------------
set arstn [get_bd_pins rst_0/interconnect_aresetn]
foreach p {icn_0/ARESETN icn_0/S00_ARESETN icn_0/M00_ARESETN icn_0/M01_ARESETN
           icn_0/M02_ARESETN} {
    connect_bd_net $arstn [get_bd_pins $p]
}
set prstn [get_bd_pins rst_0/peripheral_aresetn]
foreach p {spi_0/s_axi_aresetn gpio_0/s_axi_aresetn dac_spi_0/aresetn} {
    connect_bd_net $prstn [get_bd_pins $p]
}

# ---------------------------------------------------------------- 외부 포트
#  ★★ 2026-09-09 변경 — SPI 4선의 주인이 바뀌었다.
#
#    [전]  spi_0/SPI_0 인터페이스를 그대로 외부로 빼서 Vivado 가 IOBUF 를 넣고
#          dac_spi_sck_io / dac_spi_io0_io / dac_spi_io1_io / dac_spi_ss_io[0]
#          라는 inout 포트를 만들었다.
#    [후]  dac_spi_0(FSM)이 핀을 갖는다. spi_0 는 FSM 의 cfg_* 입력으로 들어가고,
#          FSM 의 CTRL.EN 이 0 이면 그대로 통과한다.
#
#    [왜 이렇게 하나]
#      설정(레인지 쓰기, VENDOR 읽기)은 Phase 1/2 에서 검증된 axi_quad_spi 경로를
#      그대로 쓰고 싶고, 재생은 전용 FSM 이 해야 한다. 두 마스터가 같은 4선을
#      쓰므로 어딘가에 먹스가 있어야 하는데, FSM 안에 두는 것이 가장 단순하다.
#
#    [부수 효과 — XDC 를 고쳐야 한다]
#      우리가 항상 마스터이므로 삼상(inout)이 필요 없다. 포트가 단방향이 되고
#      이름도 바뀐다:
#        dac_spi_sck_io    -> dac_sck    (output)
#        dac_spi_ss_io[0]  -> dac_cs_n   (output)
#        dac_spi_io0_io    -> dac_mosi   (output)
#        dac_spi_io1_io    -> dac_miso   (input)
#      RTL/dac_test.xdc 를 여기에 맞춰 이미 고쳐 두었다.
#
#    ※ 미검증 : axi_quad_spi 의 SPI_0 인터페이스 멤버 핀(sck_o, io0_o, ss_o …)에
#      개별로 접속하는 방식이다. Vivado 에서 통상 되는 방법이지만 이 스크립트로
#      돌려 본 적은 없다. get_bd_pins 가 못 찾으면 아래에서 명확히 죽는다.
# 설정용 SPI (axi_quad_spi) -> FSM 의 통과 입력
connect_bd_net [dac_pin spi_0/sck_o] [dac_pin dac_spi_0/cfg_sck]
connect_bd_net [dac_pin spi_0/io0_o] [dac_pin dac_spi_0/cfg_mosi]
connect_bd_net [dac_pin spi_0/ss_o]  [dac_pin dac_spi_0/cfg_cs_n]
connect_bd_net [dac_pin dac_spi_0/cfg_miso] [dac_pin spi_0/io1_i]

# axi_quad_spi 의 미사용 입력을 0 으로 묶는다 (슬레이브 모드용 핀들)
foreach q {spi_0/sck_i spi_0/io0_i spi_0/ss_i} {
    connect_bd_net [get_bd_pins gnd_0/dout] [dac_pin $q]
}

# 실제 FMC 핀
#  ★ 2026-09-09 : 멀티 IO 로 4선이 됐다. sdio1 은 inout (classic MISO / dual·quad 출력).
foreach q {dac_sck dac_cs_n dac_sdio0 dac_sdio1 dac_sdio2 dac_sdio3} {
    make_bd_pins_external -name $q [dac_pin dac_spi_0/$q]
}

#  gpio_rtl 은 그대로 dac_ctrl_tri_io[3:0] 이 된다.
make_bd_intf_pins_external -name dac_ctrl [get_bd_intf_pins gpio_0/GPIO]

# ---------------------------------------------------------------- 주소 배정
#  자동 배정에 맡기지 않고 고정한다. XSCT / Vitis 코드가 이 상수를 그대로 쓴다.
assign_bd_address

#  ★ 세그먼트 이름을 하드코딩하지 않는다.
#    SEG_<cell>_Reg 규칙이 Vivado 버전·IP 에 따라 SEG_<cell>_<if>_Reg 등으로
#    달라진다. 이름을 박아 두면 못 찾아 죽는다. 셀 이름으로 검색해서 붙인다.
#    못 찾으면 assign_bd_address 가 준 자동 배정값을 그대로 쓰고 경고만 낸다 —
#    여기서 스크립트를 죽일 이유는 없다. 실제 주소는 아래에서 출력한다.
#  ★ 2026-09-09 : 패턴을 "*SEG_<cell>_*" 로 좁혔다.
#    전에는 "*<cell>*" 였는데, 셀이 spi_0 과 dac_spi_0 둘이 되면서 spi_0 패턴이
#    dac_spi_0 의 세그먼트에도 걸린다. foreach 순서는 보장되지 않으므로
#    두 주소가 서로 뒤바뀔 수 있었다 — 빌드는 통과하고 실물에서만 틀리는 종류다.
proc dac_set_addr {cell off {rng 64K}} {
    foreach s [get_bd_addr_segs -quiet -of_objects [get_bd_addr_spaces ps7_0/Data]] {
        if {[string match "*SEG_${cell}_*" $s]} {
            set_property offset $off $s
            set_property range  $rng $s
            return 1
        }
    }
    puts "\[!\] address segment for '$cell' not found; keeping auto-assigned value."
    return 0
}
dac_set_addr spi_0      0x41E00000
dac_set_addr gpio_0     0x41200000
dac_set_addr dac_spi_0  0x43C00000 16K  ;# 주소폭 14비트 = 16 KB (레지스터 + 버퍼 2장)

#  ★ 2026-09-10 : DMA 가 없어져 PS 슬레이브 주소공간은 ps7_0/Data 하나뿐이다.

regenerate_bd_layout
validate_bd_design
save_bd_design

puts "\[*\] block design '$BD_NAME' created"
puts "\[*\] assigned addresses - XSCT/Vitis code must match these:"
foreach s [get_bd_addr_segs -quiet -of_objects [get_bd_addr_spaces ps7_0/Data]] {
    puts [format "    %-46s offset=%s  range=%s" $s \
          [get_property offset $s] [get_property range $s]]
}

#  ★ 2026-09-11 : 집 PC 에서 실제로 돌렸다. 주소 배정과 ZedBoard 프리셋이
#    적용되는 것까지 확인했다. 더 이상 미검증이 아니다.
puts "\[*\] verified in Vivado 2024.1 on 2026-09-11 (addresses + ZedBoard DDR preset)"
