# =============================================================================
# bd_eopll_sys.tcl  —  EOPLL 통합 블록 디자인 (PS7 하나에 TDC + DAC 를 함께)
# Generated by Claude Code, 2026-09-21
#
#  [무엇을 합쳤나]
#    TDC 저장소의 tcl/bd_ps_sys.tcl  (커밋 f935720) : PS7 + 리셋 + 인터커넥트,
#      우리 RTL 은 BD 밖에 두고 AXI4-Lite 마스터 하나만 외부로 냈다.
#    DAC 저장소의 tcl/bd_dac_sys.tcl (커밋 dd1c23f) : PS7 + 리셋 + 인터커넥트 +
#      axi_quad_spi(설정) + axi_gpio(정적 제어선) + dac_chirp_engine(BD 안).
#
#    두 BD 가 각각 PS7 을 갖고 있었다. 여기서는 PS7 하나에 인터커넥트 하나,
#    마스터 포트 4 개로 합친다.
#
#      ps7_0/M_AXI_GP0 ─ icn_0 ┬ M00 ─ spi_0      (axi_quad_spi, DAC 설정용)
#                               ├ M01 ─ gpio_0     (axi_gpio, RESETn/QSPI_SEL/LDACn/ALERTn)
#                               ├ M02 ─ dac_spi_0  (dac_chirp_engine, BD 안)
#                               └ M03 ─ M_AXI      (외부로 나가 top 에서 tdc_axi_regs 에 붙는다)
#
#    ★ 왜 TDC 쪽만 BD 밖인가 — bd_ps_sys.tcl 의 판단을 그대로 유지한 것이다.
#      tdc_axi_regs 는 레지스터가 계속 늘어나므로 BD 안에 넣으면 그때마다 BD 를
#      다시 만들어야 한다. dac_chirp_engine 은 DAC 저장소에서 이미 BD 안에 있고
#      레지스터 맵이 고정돼 있어 그대로 뒀다.
#
#  [★ 주소 충돌 — 반드시 읽을 것]
#    합치기 전 두 설계가 **같은 주소 0x43C0_0000 을 쓰고 있었다**.
#      TDC : ../TDC/vitis/tdc_app.c:88   #define TDC_BASE  0x43C00000u  (64 KB)
#      DAC : ../DAC/vitis/dac_chirp.c:73 #define FSM_BASE  0x43C00000u  (16 KB)
#    TDC 를 0x43C0_0000 에 그대로 두고 DAC 처프 엔진을 0x43C1_0000 으로 옮겼다.
#    TDC 아퍼처가 64 KB(0x43C0_0000~0x43C0_FFFF)이므로 바로 뒤가 빈 자리다.
#    [왜 DAC 쪽을 옮겼나] 두 소프트웨어 중 하나는 고쳐야 한다. TDC 앱은 측정
#      절차 전체(메뉴, 캡처, 교정)가 이 상수에 얽혀 있고, DAC 쪽은 #define 한 줄이다.
#    ★ 그러므로 EOPLL 용 DAC 소프트웨어는 FSM_BASE 를 0x43C1_0000 으로 고쳐야 한다.
#      안 고치면 DAC 레지스터 접근이 TDC 레지스터를 때린다 — 빌드는 통과하고
#      실물에서만 틀리는 종류다.
#
#  [클럭 — 2026-09-21 사용자 결정]
#    FCLK_CLK0(100 MHz) 하나로 AXI 도메인과 DAC 를 전부 돌린다. clk_wiz 는
#    BD 에 없다 — TDC 의 200 MHz MMCM 은 예전처럼 top 의 clk_wiz_0 이 만든다.
#    ★ DAC 용 별도 SPI 도메인(132 MHz -> SCK 66 MHz)은 넣지 않았다. 사용자 결정 :
#      66 MHz SCK 를 쓸 일이 없다. 따라서 DAC 재생 상한은 aclk 100 MHz 기준
#      quad 12.5 MSPS 다 (../DAC/sim 회귀 실측값).
#
#  [아직 안 된 것]
#    · 핀 배치(XDC). 합친 보드의 FMC 핀맵이 미정이라 dac_* 포트에 LOC 가 없다.
#      RTL/dac_test.xdc 는 EVAL 보드 기준이므로 그대로 쓰면 안 된다.
#    · EOPLL 루프(타임스탬프 -> 오차 -> 루프필터 -> DAC 코드) RTL. 미정.
#
#  [검증 상태]
#    ★ 이 스크립트는 **아직 Vivado 에서 한 번도 돌려 보지 않았다.** Orin 에는
#      Vivado 가 없다. Vivado GUI 의 Tcl Console 에서 source 해서 확인할 것.
#      특히 아래 두 가지는 실행해 봐야만 안다:
#        (1) 외부 마스터 포트 M_AXI 의 주소 세그먼트 이름 (eopll_set_addr 가 찾는다)
#        (2) axi_quad_spi 인터페이스 멤버 핀 이름 (dac_pin 이 대소문자까지 구제한다)
#
#  [사용법]  Vivado Tcl Console 에서
#      source <저장소>/tcl/bd_eopll_sys.tcl
#    또는 tcl/build_eopll.tcl 이 source 한다.
# =============================================================================

if {[llength [get_projects -quiet]] == 0} {
    create_project -in_memory -part xc7z020clg484-1
}

set BD_NAME eopll_sys

create_bd_design $BD_NAME
current_bd_design [get_bd_designs $BD_NAME]

# ---------------------------------------------------------------- 이름 조회 헬퍼
#  bd_dac_sys.tcl 에서 그대로 가져왔다. 이유는 그쪽 주석 참조 :
#  모듈 참조로 넣으면 S_AXI, 정식 IP 로 패키징하면 s_axi 가 되어 이름이 흔들린다.
proc dac_dump_cell {cell} {
    puts "!!!! ---- what is actually on '$cell' ----"
    if {[llength [get_bd_cells -quiet $cell]] == 0} {
        puts "!!!!   the cell does not exist at all."
        puts "!!!!   cells in this design:"
        foreach c [get_bd_cells -quiet /*] { puts "!!!!       $c" }
        return
    }
    puts "!!!!   VLNV : [get_property -quiet VLNV [get_bd_cells $cell]]"
    set ifs [get_bd_intf_pins -quiet "$cell/*"]
    puts "!!!!   interface pins ([llength $ifs]) :"
    foreach q $ifs { puts "!!!!       [file tail $q]   ([get_property -quiet VLNV $q])" }
    set pins [get_bd_pins -quiet "$cell/*"]
    puts "!!!!   plain pins ([llength $pins]) :"
    foreach q $pins { puts "!!!!       [file tail $q]" }
}

proc dac_intf {cell name} {
    set p [get_bd_intf_pins -quiet "$cell/$name"]
    if {[llength $p] == 1} { return $p }
    foreach q [get_bd_intf_pins -quiet "$cell/*"] {
        if {[string equal -nocase [file tail $q] $name]} { return $q }
    }
    dac_dump_cell $cell
    error "BD interface pin '$name' not found on '$cell' - see the dump above."
}

proc dac_pin {path} {
    set p [get_bd_pins -quiet $path]
    if {[llength $p] == 1} { return $p }
    set cell [file dirname $path]
    set name [file tail $path]
    foreach q [get_bd_pins -quiet "$cell/*"] {
        if {[string equal -nocase [file tail $q] $name]} { return $q }
    }
    if {[llength $p] == 0} {
        error "BD pin not found: $path\n\
               The axi_quad_spi interface member pin names may differ in this Vivado\n\
               version. Run 'get_bd_pins spi_0/*' to see the real names."
    }
    return $p
}

# ---------------------------------------------------------------- PS7
#  설정은 bd_dac_sys.tcl 쪽(프리셋 + 개별 설정 + DDR 값 대조)을 따랐다.
#  bd_ps_sys.tcl 은 프리셋을 안 쓰고 손으로만 넣었는데, DDR 파라미터가 조용히
#  기본값인 채 빌드가 통과하는 사고가 DAC 쪽에서 있었다 (2026-09-11).
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7 ps7_0

#  ※ 순서가 중요하다. 프리셋을 먼저 적용해야 아래 개별 설정이 덮어쓴다.
set ::EOPLL_PRESET_OK 0
if {[catch {set_property CONFIG.preset {ZedBoard} [get_bd_cells ps7_0]} e]} {
    puts "\[X\] ZedBoard preset could not be applied: $e"
} else {
    set ::EOPLL_PRESET_OK 1
    puts "\[*\] ZedBoard preset applied to ps7_0"
}

#  PCW_CRYSTAL_PERIPHERAL_FREQMHZ = 33.333333 은 ZedBoard 의 PS_CLK 오실레이터다.
#  틀리면 FCLK_CLK0 이 100 MHz 가 아니게 되는데 Vivado 는 검증할 방법이 없어
#  합성·타이밍·비트스트림이 전부 통과한다. 즉 틀려도 조용히 틀린다.
#  (TDC 쪽에서 2026-09-05 에 문서 + MMCM lock 실측으로 확인한 값이다)
#  MIO 뱅크 전압을 빠뜨리면 UART TX 는 되고 RX 만 죽는다 — bd_ps_sys.tcl 주석 참조.
set_property -dict [list \
    CONFIG.PCW_CRYSTAL_PERIPHERAL_FREQMHZ {33.333333} \
    CONFIG.PCW_USE_M_AXI_GP0              {1} \
    CONFIG.PCW_EN_CLK0_PORT               {1} \
    CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ   {100} \
    \
    CONFIG.PCW_UART1_PERIPHERAL_ENABLE    {1} \
    CONFIG.PCW_UART1_UART1_IO             {MIO 48 .. 49} \
    CONFIG.PCW_UART1_BAUD_RATE            {115200} \
    \
    CONFIG.PCW_PRESET_BANK0_VOLTAGE       {LVCMOS 3.3V} \
    CONFIG.PCW_PRESET_BANK1_VOLTAGE       {LVCMOS 1.8V} \
] [get_bd_cells ps7_0]

#  ★ S_AXI_HP0 는 켜지 않는다. DAC 가 DDR+DMA 를 버리고 온칩 BRAM 핑퐁으로
#    바뀌면서 PL 이 PS 슬레이브 포트를 건드릴 경로가 없어졌고, 이 포트가 2026-09-10 에
#    PS 디버그를 통째로 죽인 원인이었다. PS7 은 GP0 하나뿐이다.

if {[llength [get_bd_intf_ports -quiet DDR]] == 0} {
    make_bd_intf_pins_external -name DDR      [get_bd_intf_pins ps7_0/DDR]
}
if {[llength [get_bd_intf_ports -quiet FIXED_IO]] == 0} {
    make_bd_intf_pins_external -name FIXED_IO [get_bd_intf_pins ps7_0/FIXED_IO]
}

#  DDR 파라미터가 정말 들어갔는지 값까지 대조한다 (이름만 찍는 것으로는 부족).
set ddr_expect [list \
    PCW_UIPARAM_DDR_DEVICE_CAPACITY  {2048 MBits} \
    PCW_UIPARAM_DDR_SPEED_BIN        {DDR3_1066F} \
    PCW_UIPARAM_DDR_BOARD_DELAY0     {0.41} \
    PCW_UIPARAM_DDR_BOARD_DELAY1     {0.411} \
    PCW_UIPARAM_DDR_BOARD_DELAY2     {0.341} \
    PCW_UIPARAM_DDR_BOARD_DELAY3     {0.358} \
]
set ddr_bad 0
puts ""
puts "    ---- DDR parameters on ps7_0 ----"
foreach {k want} $ddr_expect {
    if {[catch {set got [get_property CONFIG.$k [get_bd_cells ps7_0]]}]} {
        puts [format "    %-32s = <cannot read>" $k]
        incr ddr_bad
        continue
    }
    if {$got eq $want} {
        puts [format "    %-32s = %s" $k $got]
    } else {
        puts [format "    %-32s = %s   <<<< expected %s" $k $got $want]
        incr ddr_bad
    }
}
if {$ddr_bad || !$::EOPLL_PRESET_OK} {
    puts ""
    puts "\[X\] the ZedBoard DDR parameters are NOT in place ($ddr_bad mismatched)."
    puts "    Link applications into ps7_ram_0 (OCM), never ps7_ddr_0."
} else {
    puts "    all checked DDR parameters match the ZedBoard preset"
}

# ---------------------------------------------------------------- 리셋 / 인터커넥트
create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset rst_0

#  슬레이브 4개 : M00 spi_0 / M01 gpio_0 / M02 dac_spi_0 / M03 외부(tdc_axi_regs)
create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect icn_0
set_property -dict [list CONFIG.NUM_SI {1} CONFIG.NUM_MI {4}] [get_bd_cells icn_0]

# ---------------------------------------------------------------- AXI Quad SPI (DAC 설정용)
#  C_SCK_RATIO 의 허용값은 {2,4,8,16} 뿐이라 최대 16 을 쓴다 (SCK = 100/16 = 6.25 MHz).
#  설정(레인지 쓰기, VENDOR 읽기)에만 쓰므로 느려도 무방하다.
create_bd_cell -type ip -vlnv xilinx.com:ip:axi_quad_spi spi_0
set_property -dict [list \
    CONFIG.C_SPI_MODE          {0} \
    CONFIG.C_SPI_MEMORY        {0} \
    CONFIG.C_NUM_SS_BITS       {1} \
    CONFIG.C_NUM_TRANSFER_BITS {8} \
    CONFIG.C_SCK_RATIO         {16} \
    CONFIG.C_FIFO_DEPTH        {16} \
    CONFIG.C_USE_STARTUP       {0} \
    CONFIG.C_TYPE_OF_AXI4_INTERFACE {0} \
] [get_bd_cells spi_0]

# ---------------------------------------------------------------- AXI GPIO (정적 제어선)
#  [0]=RESETn  [1]=QSPI_SEL  [2]=LDACn  [3]=ALERTn(입력)
#  ★ 리셋 직후 출력이 0 이라 RESETn=0(리셋 걸림), LDACn=0 이다. 소프트웨어가
#    가장 먼저 이 둘을 1 로 올려야 한다.
create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio gpio_0
set_property -dict [list \
    CONFIG.C_IS_DUAL          {0} \
    CONFIG.C_GPIO_WIDTH       {4} \
    CONFIG.C_ALL_OUTPUTS      {0} \
    CONFIG.C_ALL_INPUTS       {0} \
] [get_bd_cells gpio_0]

# ---------------------------------------------------------------- 처프 엔진 (BD 안)
if {[info exists ::DAC_IP_VLNV] && $::DAC_IP_VLNV ne ""} {
    puts "\[*\] dac_spi_0 from packaged IP : $::DAC_IP_VLNV"
    create_bd_cell -type ip -vlnv $::DAC_IP_VLNV dac_spi_0
} else {
    puts "\[*\] dac_spi_0 as a module reference"
    if {[llength [get_files -quiet dac_chirp_engine.v]] == 0} {
        set _rtl [file normalize [file join [file dirname [info script]] .. RTL dac_chirp_engine.v]]
        if {![file exists $_rtl]} { error "RTL not found: $_rtl" }
        add_files -norecurse $_rtl
        update_compile_order -fileset sources_1
    }
    if {[catch {create_bd_cell -type module -reference dac_chirp_engine dac_spi_0} _e]} {
        puts "!!!! create_bd_cell (module reference) failed:"
        puts "!!!!   $_e"
        error "cannot create dac_spi_0"
    }
    catch { set_property CONFIG.FREQ_HZ 100000000 [get_bd_pins dac_spi_0/aclk] }
    catch { set_property CONFIG.ASSOCIATED_BUSIF {s_axi} [get_bd_pins dac_spi_0/aclk] }
}
dac_dump_cell dac_spi_0

#  spi_0 의 미사용 입력 종단 (BD 에서 입력 핀을 띄우면 CRITICAL WARNING).
create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant gnd_0
set_property -dict [list CONFIG.CONST_WIDTH {1} CONFIG.CONST_VAL {0}] [get_bd_cells gnd_0]

# ---------------------------------------------------------------- AXI 연결
connect_bd_intf_net [get_bd_intf_pins ps7_0/M_AXI_GP0] [get_bd_intf_pins icn_0/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins icn_0/M00_AXI]   [get_bd_intf_pins spi_0/AXI_LITE]
connect_bd_intf_net [get_bd_intf_pins icn_0/M01_AXI]   [get_bd_intf_pins gpio_0/S_AXI]
connect_bd_intf_net [get_bd_intf_pins icn_0/M02_AXI]   [dac_intf dac_spi_0 S_AXI]

#  M03 은 외부로 낸다. top 에서 tdc_axi_regs 에 붙는다.
#  ★ PROTOCOL 을 AXI4LITE 로 명시해야 한다. 안 하면 인터커넥트가 PS 의 AXI3 신호
#    (arlen/arid/wlast/rlast ...)를 그대로 내보내고, tdc_axi_regs 는 AXI4-Lite 라 못 받는다.
make_bd_intf_pins_external -name M_AXI [get_bd_intf_pins icn_0/M03_AXI]
set_property -dict [list CONFIG.PROTOCOL {AXI4LITE} \
                         CONFIG.DATA_WIDTH {32} \
                         CONFIG.ADDR_WIDTH {32}] [get_bd_intf_ports M_AXI]

# ---------------------------------------------------------------- 클럭
#  FCLK_CLK0(100 MHz) 하나. TDC 의 200 MHz 는 top 의 clk_wiz_0 이 이 클럭에서 만든다.
set fclk [get_bd_pins ps7_0/FCLK_CLK0]
foreach p {ps7_0/M_AXI_GP0_ACLK rst_0/slowest_sync_clk
           icn_0/ACLK icn_0/S00_ACLK
           icn_0/M00_ACLK icn_0/M01_ACLK icn_0/M02_ACLK icn_0/M03_ACLK
           spi_0/s_axi_aclk spi_0/ext_spi_clk gpio_0/s_axi_aclk
           dac_spi_0/aclk} {
    connect_bd_net $fclk [get_bd_pins $p]
}

# ---------------------------------------------------------------- 리셋
connect_bd_net [get_bd_pins ps7_0/FCLK_RESET0_N] [get_bd_pins rst_0/ext_reset_in]

set arstn [get_bd_pins rst_0/interconnect_aresetn]
foreach p {icn_0/ARESETN icn_0/S00_ARESETN
           icn_0/M00_ARESETN icn_0/M01_ARESETN icn_0/M02_ARESETN icn_0/M03_ARESETN} {
    connect_bd_net $arstn [get_bd_pins $p]
}
set prstn [get_bd_pins rst_0/peripheral_aresetn]
foreach p {spi_0/s_axi_aresetn gpio_0/s_axi_aresetn dac_spi_0/aresetn} {
    connect_bd_net $prstn [get_bd_pins $p]
}

# ---------------------------------------------------------------- DAC SPI 4선
#  설정용 axi_quad_spi 는 FSM 의 통과(cfg_*) 입력으로 들어간다. FSM 의 CTRL.EN 이
#  0 이면 그대로 통과하고, 1 이면 FSM 이 핀을 잡는다. 두 마스터의 먹스는 FSM 안에 있다.
connect_bd_net [dac_pin spi_0/sck_o] [dac_pin dac_spi_0/cfg_sck]
connect_bd_net [dac_pin spi_0/io0_o] [dac_pin dac_spi_0/cfg_mosi]
connect_bd_net [dac_pin spi_0/ss_o]  [dac_pin dac_spi_0/cfg_cs_n]
connect_bd_net [dac_pin dac_spi_0/cfg_miso] [dac_pin spi_0/io1_i]

foreach q {spi_0/sck_i spi_0/io0_i spi_0/ss_i} {
    connect_bd_net [get_bd_pins gnd_0/dout] [dac_pin $q]
}

#  실제 FMC 핀. sdio1 은 inout (classic MISO / dual·quad 출력).
#  ★ 핀 배치는 아직 없다 — 합친 보드의 핀맵이 정해지면 XDC 에 LOC 를 넣을 것.
foreach q {dac_sck dac_cs_n dac_sdio0 dac_sdio1 dac_sdio2 dac_sdio3} {
    make_bd_pins_external -name $q [dac_pin dac_spi_0/$q]
}
make_bd_intf_pins_external -name dac_ctrl [get_bd_intf_pins gpio_0/GPIO]

# ---------------------------------------------------------------- top 으로 낼 클럭/리셋
#  make_bd_pins_external 이 이미 여러 곳에 연결된 출력 핀에 대해 포트를 만들지
#  않는 경우가 있었다 (bd_ps_sys.tcl 주석). 포트를 직접 만들어 잇는다.
create_bd_port -dir O -type clk fclk_clk0
connect_bd_net [get_bd_ports fclk_clk0] $fclk
create_bd_port -dir O -type rst peripheral_arstn
connect_bd_net [get_bd_ports peripheral_arstn] [get_bd_pins rst_0/peripheral_aresetn]

#  클럭 포트에 AXI 인터페이스를 연관시킨다. 안 하면
#  "AXI interface port /M_AXI is not associated to any clock port" CRITICAL WARNING.
set_property CONFIG.ASSOCIATED_BUSIF {M_AXI} [get_bd_ports fclk_clk0]

# ---------------------------------------------------------------- 주소 배정
assign_bd_address

#  세그먼트 이름을 하드코딩하지 않는다 — SEG_<cell>_Reg 규칙이 Vivado 버전·IP 에
#  따라 달라진다. 패턴을 "*SEG_<cell>_*" 로 좁혀야 한다. 전에 "*<cell>*" 를 쓰다
#  spi_0 패턴이 dac_spi_0 세그먼트에도 걸려 두 주소가 뒤바뀔 수 있었다.
proc eopll_set_addr {cell off {rng 64K}} {
    foreach s [get_bd_addr_segs -quiet -of_objects [get_bd_addr_spaces ps7_0/Data]] {
        if {[string match "*SEG_${cell}_*" $s]} {
            set_property offset $off $s
            set_property range  $rng $s
            return 1
        }
    }
    puts "\[!\] address segment for '$cell' not found; keeping auto-assigned value."
    return 0
}

eopll_set_addr spi_0      0x41E00000
eopll_set_addr gpio_0     0x41200000
eopll_set_addr dac_spi_0  0x43C10000 16K   ;# ★ 0x43C00000 에서 옮김 (TDC 와 충돌)
eopll_set_addr M_AXI      0x43C00000 64K   ;# 외부 마스터 -> tdc_axi_regs

#  ★ 외부 마스터 포트의 세그먼트는 Vivado 버전에 따라 이름이 다르다.
#    위 eopll_set_addr M_AXI 가 "not found" 를 찍으면 아래 목록에서 실제 이름을
#    확인하고 set_property offset/range 를 직접 줄 것. 0x43C0_0000 / 64K 여야 한다.
puts ""
puts "    ---- address segments ----"
foreach seg [get_bd_addr_segs -quiet -of_objects [get_bd_addr_spaces ps7_0/Data]] {
    puts [format "    %-48s offset %s  range %s" \
        $seg [get_property offset $seg] [get_property range $seg]]
}
puts ""
puts "    소프트웨어가 써야 할 값 :"
puts "      TDC_BASE  0x43C00000  (64K)  <- ../TDC/vitis/tdc_app.c 그대로"
puts "      FSM_BASE  0x43C10000  (16K)  <- ../DAC/vitis/dac_chirp.c 는 0x43C00000 이므로 고칠 것"
puts "      SPI_BASE  0x41E00000 / GPIO_BASE 0x41200000  <- DAC 쪽 그대로"

regenerate_bd_layout
validate_bd_design
save_bd_design

puts "\[*\] 블록 디자인 '$BD_NAME' 생성 완료"
