# =============================================================================
# check_build.tcl  —  열려 있는 합성/구현 디자인에서 TDC 빌드 확인 항목을 PASS/FAIL 로 판정
# Generated by Claude Code, 2026-09-15
#
#  [왜 만들었나]
#    build_zedboard.tcl 은 합성 뒤에 숫자만 찍고 판정을 사람에게 맡겼는데, 그 기대값이 틀렸고
#    (Markdown/2026-09-15_report.md §6-4 : 이름 필터에 먹스 LUT 이 걸려 CARRY4 가 97,
#    FLAT_PIN_COUNT 는 구동 핀까지 세서 2), 탭 0 샘플링 FF 가 제자리(SLICE_X42Y0 AFF)에서
#    SLICE_X44Y0 로 밀려난 문제(§6-5)는 어떤 확인에도 걸리지 않았다.
#    09-06 zed_uart 빌드는 u_ff_0 이 밀려나 있었는데도 synth_1 / impl_1 의 runme.log 에
#    CRITICAL WARNING 12-2285 가 0 건이었다 (2026-09-15 집 PC 에서 grep). 이 경고는 GUI 에서
#    합성 디자인을 열 때만 뜬다. 그래서 경고 문구가 아니라 **실제 배치**를 본다.
#
#  [사용법]  디자인(합성 또는 구현)이 열린 Vivado GUI Tcl Console 에서
#      set CHECK_STAGE impl
#      source C:/Work/FPGA/Project/Source/TDC/tcl/check_build.tcl
#    build_zedboard.tcl 은 세 번째 인자가 1 이면 합성 뒤(synth)·구현 뒤(impl)에 자동으로 부른다.
#
#  [입력 변수]  CHECK_STAGE   synth | impl   (기본 impl)
#               CHECK_OUT     결과를 덧붙여 쓸 파일 (기본 "" = 화면만)
#               CHAIN_STAGES  지연선 CARRY4 단수 (기본 96)
#  [출력 변수]  CHECK_FAIL       FAIL 개수
#               CHECK_HARD_FAIL  그중 구조 FAIL(S1, S2) 개수. 지연선이 제대로 안 들어갔다는 뜻이라
#                                build_zedboard.tcl 은 합성 뒤 이 값이 0 이 아니면 구현을 멈춘다.
#
#  [항목]  S = 구조 (synth·impl 둘 다)   P = 배치 (impl)   T = 타이밍 (impl)   I = 설정 (impl)
#    S1  지연선 CARRY4 개수 = CHAIN_STAGES        REF_NAME 으로 센다 (이름 필터는 97 이 됐다)
#    S2  탭 샘플링 FF(taps_sampled_d1) 개수 = CHAIN_STAGES x 4
#    S3  히트 네트(CYINIT) 입력 핀 = 1            다른 부하가 붙으면 진입 slew 악화 (led[2] 사례)
#    S4  히트 먹스 u_hit_mux 가 LUT4 로 있다      2026-09-15 RTL 부터
#    S5  교정표 RAM u_lut_ram 이 BRAM(RAMB*)으로 추론됐다
#    P1  탭 0 FF u_ff_0..3 이 SLICE_X42Y0 의 A/B/C/DFF   CO->D 배선 SLOW_MAX 도 함께 찍는다
#        (09-06·09-15 두 빌드 모두 u_ff_0 = SLICE_X44Y0, 793 / 91 / 91 / 336 이었다)
#    P2  u_hit_mux 가 SLICE_X41Y0 에 있다         (tdc_zedboard.xdc 의 LOC)
#    R1  RO LUT 31개가 pblock_ro 안에 있다         ★ 2026-09-15 추가 (tdc_zedboard.xdc §2)
#    R2  RO 고리 안 LUT->LUT 배선 SLOW_MAX 합     ★ 2026-09-15 추가. 판정 아닌 기록 (빌드마다 비교)
#    T1  WNS >= 0 (setup)    T2  WHS >= 0 (hold)
#    I1  구현 전략 = Performance_ExplorePostRoutePhysOpt   (체크포인트만 열었으면 N/A)
#
#  ★ 화면·파일 출력은 ASCII 다 (Windows Vivado Tcl Console 의 CP949 문제,
#    sim/run_iverilog.sh 와 같은 규칙).
# =============================================================================

if {![info exists CHECK_STAGE]}  { set CHECK_STAGE impl }
if {![info exists CHECK_OUT]}    { set CHECK_OUT "" }
if {![info exists CHAIN_STAGES]} { set CHAIN_STAGES 96 }

namespace eval tdcchk {
    variable fh    ""
    variable nfail 0
    variable nhard 0
}

proc tdcchk::out {s} {
    variable fh
    puts $s
    if {$fh ne ""} { puts $fh $s ; flush $fh }
}

# ok : 1 = PASS, 0 = FAIL, NA = 판정 불가 (대상이 없는 경우 등)
proc tdcchk::judge {id hard ok what got want} {
    variable nfail
    variable nhard
    if {$ok eq "NA"} {
        set r "N/A "
    } elseif {$ok} {
        set r "PASS"
    } else {
        set r "FAIL"
        incr nfail
        if {$hard} { incr nhard }
    }
    tdcchk::out [format "  %s  %-5s %-38s got : %s" $r $id $what $got]
    tdcchk::out [format "              %-38s want: %s" "" $want]
}

proc tdcchk::one {objs} { return [lindex $objs 0] }

set tdcchk::nfail 0
set tdcchk::nhard 0
set tdcchk::fh ""
if {$CHECK_OUT ne ""} { set tdcchk::fh [open $CHECK_OUT a] }

tdcchk::out ""
tdcchk::out "================================================================"
tdcchk::out " TDC build check   stage = $CHECK_STAGE   [clock format [clock seconds] -format {%Y-%m-%d %H:%M:%S}]"
tdcchk::out "================================================================"

# ---------------------------------------------------------------- S : 구조
set nt [expr {$CHAIN_STAGES * 4}]

set n [llength [get_cells -quiet -hier -filter {REF_NAME == CARRY4 && NAME =~ *CARRY_CHAIN*}]]
tdcchk::judge S1 1 [expr {$n == $CHAIN_STAGES}] "delay-line CARRY4 count (REF_NAME)" $n $CHAIN_STAGES

set n [llength [get_cells -quiet -hier -filter {NAME =~ *taps_sampled_d1_reg*}]]
tdcchk::judge S2 1 [expr {$n == $nt}] "tap sampling FF count (taps_sampled_d1)" $n $nt

set c4 [tdcchk::one [get_cells -quiet -hier -filter {REF_NAME == CARRY4 && NAME =~ *CARRY_CHAIN[0].STAGE_0*}]]
if {$c4 eq ""} {
    tdcchk::judge S3 0 NA "hit net (CYINIT) in-pins" "stage-0 CARRY4 not found" "1 (CYINIT only)"
} else {
    set hn  [get_nets -of [get_pins -of $c4 -filter {REF_PIN_NAME == CYINIT}]]
    set nin [llength [get_pins -quiet -leaf -of $hn -filter {DIRECTION == IN}]]
    set dc  [tdcchk::one [get_cells -quiet -of [get_pins -quiet -leaf -of $hn -filter {DIRECTION == OUT}]]]
    if {$dc eq ""} { set dn "none" } else { set dn "[get_property REF_NAME $dc] $dc" }
    tdcchk::judge S3 0 [expr {$nin == 1}] "hit net (CYINIT) in-pins" "$nin   driver: $dn" "1 (CYINIT only)"
}

set mx [tdcchk::one [get_cells -quiet -hier -filter {NAME =~ *u_hit_mux}]]
# ★ 2026-09-16 : LUT4 -> LUT4 또는 LUT5 를 받는다.
#   [왜] Mode 0 내부 루프백 히트 생성기(m0_hit)가 먹스 입력으로 들어와 LUT5 가 됐다
#        (tdc_test_top.v, INIT 32'hCFA0C0A0). 여기를 LUT4 로 못박아 두면 새 RTL 이 FAIL 로 잡힌다.
#   [바뀌지 않는 것] 이 LUT 이 캐리 슬라이스 밖(SLICE_X41Y0)에 있어야 한다는 조건(P2)은 그대로다.
if {$mx eq ""} {
    tdcchk::judge S4 0 0 "hit mux u_hit_mux present" "not found" "LUT4/LUT5 u_hit_mux"
} else {
    set rn [get_property REF_NAME $mx]
    tdcchk::judge S4 0 [expr {$rn eq "LUT4" || $rn eq "LUT5"}] "hit mux u_hit_mux present" \
        "$rn $mx" "LUT4 (2026-09-15) or LUT5 (2026-09-16, with DPS input)"
}

# ★ 2026-09-16 : S6 — MMCM 의 fine phase shift 가 clk_out2 에만 켜져 있는가.
#   [왜 보나] 안 켜져 있으면 위상 이동이 아무 효과가 없는데, psdone 이 정상적으로 돌아와
#     소프트웨어는 성공으로 본다 (2026-09-16 zed_m0b 에서 실제로 그랬다). 둘 다 켜져 있어도
#     VCO 위상이 함께 움직여 상대 위상이 안 변한다. 넷리스트에서 바로 확인할 수 있다.
#   [이름] MMCME2_ADV 의 CLKOUT0 = clk_out1(샘플링), CLKOUT1 = clk_out2(히트 생성기).
set mmcm [tdcchk::one [get_cells -quiet -hier -filter {REF_NAME == MMCME2_ADV}]]
if {$mmcm eq ""} {
    tdcchk::judge S6 0 NA "MMCM fine phase shift (clk_out2 only)" "no MMCME2_ADV found" "CLKOUT1 TRUE, CLKOUT0 FALSE"
} else {
    set f0 [get_property CLKOUT0_USE_FINE_PS $mmcm]
    set f1 [get_property CLKOUT1_USE_FINE_PS $mmcm]
    # ★ 2026-09-16 (2차) : 넷리스트는 이 속성을 TRUE/FALSE 가 아니라 1/0 으로 돌려준다
    #   (zed_m0c 빌드에서 확인 : CLKOUT0=0, CLKOUT1=1 인데 문자열 비교가 FAIL 을 냈다).
    #   두 표기를 모두 받도록 참/거짓 판정을 따로 만든다.
    proc tdcchk::is_true {v} {
        return [expr {[string match -nocase "true" $v] || [string match -nocase "1" $v] ||
                      [string match -nocase "yes"  $v]}]
    }
    set ok [expr {[tdcchk::is_true $f1] && ![tdcchk::is_true $f0]}]
    tdcchk::judge S6 0 $ok "MMCM fine phase shift (clk_out2 only)" \
        "CLKOUT0(sampling)=$f0  CLKOUT1(hit gen)=$f1" "CLKOUT0 false/0, CLKOUT1 true/1"
}

set rams [get_cells -quiet -hier -filter {NAME =~ *u_lut_ram* && REF_NAME =~ RAMB*}]
if {[llength $rams]} {
    set g "[llength $rams] cell(s), [get_property REF_NAME [tdcchk::one $rams]]"
} else {
    set g "0 BRAM cells"
}
tdcchk::judge S5 0 [expr {[llength $rams] > 0}] "calib RAM u_lut_ram inferred as BRAM" $g "RAMB18E1 (09-15 zed_cal)"

# ---------------------------------------------------------------- P / T / I : 구현 뒤에만
if {$CHECK_STAGE eq "impl"} {
    foreach {k bel} {0 AFF 1 BFF 2 CFF 3 DFF} {
        set f [tdcchk::one [get_cells -quiet -hier -filter [string map [list K $k] {NAME =~ *CARRY_CHAIN[0]*u_ff_K}]]]
        if {$f eq ""} {
            tdcchk::judge P1.$k 0 NA "tap0 FF u_ff_$k placement" "not found" "SLICE_X42Y0 *.$bel"
            continue
        }
        set loc [get_property LOC $f]
        set b   [get_property BEL $f]
        set d   "?"
        catch {
            set dp [get_pins -of $f -filter {REF_PIN_NAME == D}]
            set d  [get_property SLOW_MAX [get_net_delays -of_objects [get_nets -of $dp] -to $dp]]
        }
        set ok [expr {$loc eq "SLICE_X42Y0" && [string match "*.$bel" $b]}]
        tdcchk::judge P1.$k 0 $ok "tap0 FF u_ff_$k placement" "$loc $b   CO->D route SLOW_MAX=$d" "SLICE_X42Y0 *.$bel"
    }

    if {$mx eq ""} {
        tdcchk::judge P2 0 NA "u_hit_mux placement" "no u_hit_mux in this design" "SLICE_X41Y0"
    } else {
        set loc [get_property LOC $mx]
        tdcchk::judge P2 0 [expr {$loc eq "SLICE_X41Y0"}] "u_hit_mux placement" "$loc [get_property BEL $mx]" "SLICE_X41Y0"
    }

    # ★ 2026-09-15 : RO 배치 확인 추가 (R1, R2).
    #   [왜] 제약이 없던 빌드에서 RO LUT 31개가 매번 다른 곳에 놓였다 — 09-06 zed_uart X44..55 Y46..65,
    #     09-15 zed_fmc X37..51 Y47..67, 고리 안 LUT->LUT 배선 SLOW_MAX 합 12,423 vs 17,058.
    #     보드 RO 주파수도 빌드마다 67.28 / 52.68 / 49.32 MHz 로 달랐다 (배치가 원인이라는 것은 가설).
    #     그래서 tdc_zedboard.xdc 에 pblock_ro 와 LUT 별 LOC/BEL 을 걸었다. 그것이 먹었는지 본다.
    #   R1 : RO LUT 31개(RO_LOOP[*].u_lut_inv + u_lut_inv_fb)가 전부 pblock_ro 의 GRID_RANGES 안
    #   R2 : 고리 안 LUT->LUT 배선 지연 합 — 판정이 아니라 기록이다. 31개 넷이 다 재지면 PASS.
    set roc [get_cells -quiet -hier -filter {NAME =~ *RO_LOOP*u_lut_inv || NAME =~ *u_lut_inv_fb}]
    set pb  [get_pblocks -quiet pblock_ro]
    if {$pb eq ""} {
        tdcchk::judge R1 0 0 "ring osc LUTs inside pblock_ro" "no pblock_ro in this design ([llength $roc] RO LUTs)" "31 LUTs inside pblock_ro"
    } else {
        set gr [get_property GRID_RANGES $pb]
        set inside 0
        set outside {}
        foreach c $roc {
            set loc [get_property LOC $c]
            set hit 0
            if {[regexp {SLICE_X(\d+)Y(\d+)} $loc -> cx cy]} {
                foreach rg $gr {
                    if {[regexp {SLICE_X(\d+)Y(\d+):SLICE_X(\d+)Y(\d+)} $rg -> x0 y0 x1 y1]} {
                        if {$cx >= $x0 && $cx <= $x1 && $cy >= $y0 && $cy <= $y1} { set hit 1 }
                    }
                }
            }
            if {$hit} { incr inside } else { lappend outside "[file tail $c]@$loc" }
        }
        tdcchk::judge R1 0 [expr {$inside == 31 && [llength $roc] == 31}] "ring osc LUTs inside pblock_ro" \
            "$inside / [llength $roc] inside $gr  [lrange $outside 0 3]" "31 / 31"
    }
    set rsum 0
    set rnn  0
    foreach c $roc {
        set n [get_nets -of [get_pins -of $c -filter {DIRECTION == OUT}]]
        foreach lp [get_pins -quiet -leaf -of $n -filter {DIRECTION == IN}] {
            if {[string match "*u_lut_inv*" [get_cells -of $lp]]} {
                if {![catch {set d [get_property SLOW_MAX [get_net_delays -of_objects $n -to $lp]]}]} {
                    set rsum [expr {$rsum + $d}]
                    incr rnn
                }
            }
        }
    }
    tdcchk::judge R2 0 [expr {$rnn == 31}] "ring osc loop route SLOW_MAX sum (record)" \
        "$rsum over $rnn LUT->LUT nets" "31 nets measured (unconstrained: 09-06 12423, 09-15 zed_fmc 17058)"

    set wns [get_property SLACK [get_timing_paths -delay_type max]]
    set whs [get_property SLACK [get_timing_paths -delay_type min]]
    tdcchk::judge T1 0 [expr {$wns >= 0}] "setup WNS (ns)" $wns ">= 0"
    if {$wns < 0} {
        tdcchk::out "        -> setup: a path does not fit in 5 ns. Add a pipeline stage (popcount tree) or move compare logic later."
    }
    tdcchk::judge T2 0 [expr {$whs >= 0}] "hold WHS (ns)" $whs ">= 0"
    if {$whs < 0} {
        tdcchk::out "        -> hold: skew problem. Check the implementation strategy (I1) first. A pipeline stage makes hold WORSE."
    }

    # ★ 2026-09-15 : 구현 실행 이름을 CHECK_RUN 으로 받는다 (기본 impl_1).
    #   [무엇이 틀렸나] 전략을 get_runs impl_1 로 고정해 읽었다. 흔들기 시험에서 impl_pt
    #     (Performance_ExtraTimingOpt)를 열어 검사했는데 I1 이 impl_1 의 전략을 읽어 PASS 로 찍었다.
    #     build_zedboard.tcl 은 항상 impl_1 이라 그 흐름의 결과는 틀리지 않았다.
    if {![info exists CHECK_RUN]} { set CHECK_RUN impl_1 }
    set st "?"
    catch { set st [get_property STRATEGY [get_runs $CHECK_RUN]] }
    if {$st eq "?"} { set ok NA } else { set ok [expr {$st eq "Performance_ExplorePostRoutePhysOpt"}] }
    tdcchk::judge I1 0 $ok "implementation strategy ($CHECK_RUN)" $st "Performance_ExplorePostRoutePhysOpt"
}

tdcchk::out "----------------------------------------------------------------"
tdcchk::out [format " stage %s : FAIL %d  (structural %d)" $CHECK_STAGE $tdcchk::nfail $tdcchk::nhard]
tdcchk::out "================================================================"

set CHECK_FAIL      $tdcchk::nfail
set CHECK_HARD_FAIL $tdcchk::nhard
if {$tdcchk::fh ne ""} { close $tdcchk::fh ; set tdcchk::fh "" }
