# =============================================================================
# xsct_run_app.tcl  —  비트스트림을 굽고 tdc_app.elf 를 올려 실행한다 (XSCT)
#  ★ 2026-09-21 : EOPLL 저장소 사본. ../TDC/tcl/xsct_run_app.tcl (커밋 f935720) 에서
#    블록 디자인 이름(ps_sys -> eopll_sys)과 기본 프로젝트 이름만 바꿨다.
# Generated by Claude Code, 2026-09-15
#
#  [순서]  tcl/xsct_mode2_check.tcl 과 같다 :
#      ARM 정지 -> ps7_init -> ps7_post_config -> fpga -file -> dow ELF -> con
#    ps7_init 이 비트스트림보다 먼저여야 한다 (PS 의 PLL 이 서야 FCLK 와 AXI 가 돈다).
#    2026-09-15 집 PC 에서 이 순서로 zed_fmc / zed_ro 앱을 실행해 UART '1' 까지 확인했다.
#
#  [실행]  ★ UART 터미널(115200-8-N-1)을 먼저 열어 둘 것 — 배너를 놓치지 않으려면.
#      set argv {zed_dither}
#      source <저장소>/tcl/xsct_run_app.tcl
#
#  [입력]  vivado/<프로젝트>/<프로젝트>.runs/impl_1/*.bit
#          vivado/<프로젝트>/<프로젝트>.gen/.../ps_sys_ps7_0_0/ps7_init.tcl
#          vivado/<프로젝트>/vitis_cls/tdc_app/Debug/tdc_app.elf   (tcl/xsct_build_app.tcl 결과)
#
#  ★ 화면 출력은 ASCII.
# =============================================================================

set REPO     [file normalize [file join [file dirname [info script]] ..]]
set PRJ_NAME eopll_m1
if {[info exists argv] && [llength $argv] >= 1} { set PRJ_NAME [lindex $argv 0] }
set PRJ $REPO/vivado/$PRJ_NAME

set BIT [lindex [glob -nocomplain $PRJ/$PRJ_NAME.runs/impl_1/*.bit] 0]
set PS7 [lindex [glob -nocomplain $PRJ/$PRJ_NAME.gen/sources_1/bd/eopll_sys/ip/*ps7_0_0/ps7_init.tcl] 0]
set ELF ""
foreach d {Debug build Release} {
    if {[file exists $PRJ/vitis_cls/tdc_app/$d/tdc_app.elf]} { set ELF $PRJ/vitis_cls/tdc_app/$d/tdc_app.elf ; break }
}
puts "\[*\] bit : $BIT"
puts "\[*\] ps7 : $PS7"
puts "\[*\] elf : $ELF"
if {$BIT eq ""} { error "bitstream not found under $PRJ/$PRJ_NAME.runs/impl_1" }
if {$PS7 eq ""} { error "ps7_init.tcl not found under $PRJ/$PRJ_NAME.gen" }
if {$ELF eq ""} { error "tdc_app.elf not found - run tcl/xsct_build_app.tcl first" }

connect
after 3000
targets -set -nocase -filter {name =~ "*Cortex-A9*#0*"}
catch {stop}
after 200
source $PS7
ps7_init
ps7_post_config
targets -set -nocase -filter {name =~ "xc7z020"}
fpga -file $BIT
after 500
targets -set -nocase -filter {name =~ "*Cortex-A9*#0*"}
dow $ELF
con
after 1000
puts "\[*\] app started. In the UART terminal press  1  (Mode 1 + danger + calibration table)."
disconnect
