# =============================================================================
# xsct_build_app.tcl  —  XSA 로 Vitis 플랫폼 + tdc_app 를 만든다 (classic XSCT, GUI 없이)
#  ★ 2026-09-21 : EOPLL 저장소 사본. ../TDC/tcl/xsct_build_app.tcl (커밋 f935720) 에서
#    XSA 이름(tdc_zedboard_top -> eopll_zedboard_top)과 기본 프로젝트 이름만 바꿨다.
#    앱 소스 vitis/tdc_app.c 는 그대로다 — TDC_BASE 0x43C0_0000 이 통합 후에도 같기 때문이다.
# Generated by Claude Code, 2026-09-15
#
#  [왜 만들었나]
#    Vitis GUI 로 플랫폼·앱을 만들고 링커를 OCM 으로 손으로 바꾸는 절차가 길고 실수가 났다.
#    또 DAC 저장소(../DAC/tcl/xsct_build_vitis.tcl 주석)에서 회사 노트북의 Unified IDE 가
#    플랫폼 생성 단계에서 "System DTS File does not exist" 로 실패했다. classic XSCT 의
#    platform create / app create 는 다른 경로라 그 문제를 피한다.
#    2026-09-15 집 PC 에서 같은 흐름으로 zed_fmc, zed_ro 앱을 만들어 보드에서 '1' 까지 돌렸다.
#
#  [실행]  XSCT 프롬프트에서 (슬래시 방향 주의)
#      set argv {zed_dither}
#      source <저장소>/tcl/xsct_build_app.tcl
#    XSCT 여는 법 :
#      집 PC      : C:\Xilinx\Vitis\2024.1\bin\xsct.bat
#      회사 노트북 : D:\Study\Programming\Xilinx\Vitis\2024.1\bin\loader.bat -exec rdi_xsct
#                   (DAC 기록 : 그 PC 의 xsct.bat 은 0 바이트라 창만 떴다 닫힌다)
#
#  [입력]  vivado/<프로젝트>/tdc_zedboard_top.xsa   (build_zedboard.tcl 세 번째 인자 1 이면 자동 생성)
#  [결과]  vivado/<프로젝트>/vitis_cls/tdc_app/Debug/tdc_app.elf
#          vivado/<프로젝트>/vitis_build.log
#
#  [링커]  모든 섹션을 ps7_ram_0(OCM) 으로 옮긴다. 블록 디자인의 PS7 DDR 파라미터가 ZedBoard
#          값이 아니라 DDR 에 올리면 조용히 깨진다 (DAC 2026-09-11 실측 : 512 워드 중 수십 개 불일치).
#
#  ★ 화면 출력은 ASCII (Windows 콘솔 CP949 문제).
# =============================================================================

set REPO     [file normalize [file join [file dirname [info script]] ..]]
set PRJ_NAME eopll_m1
if {[info exists argv] && [llength $argv] >= 1} { set PRJ_NAME [lindex $argv 0] }
set PRJ      $REPO/vivado/$PRJ_NAME
set XSA      $PRJ/eopll_zedboard_top.xsa
set WS       $PRJ/vitis_cls
set PLATFORM tdc_plat
set APP      tdc_app
set PROC     ps7_cortexa9_0

set ::XBLOG [open $PRJ/vitis_build.log w]
proc xb {s} { puts $s ; puts $::XBLOG $s ; flush $::XBLOG }

xb "\[*\] repo    : $REPO"
xb "\[*\] project : $PRJ"
if {![file exists $XSA]} {
    close $::XBLOG
    error "XSA not found: $XSA  -- build with  set argv {2 $PRJ_NAME 1} ; source build_eopll.tcl  first"
}

file mkdir $WS
setws $WS
# XSA 가 바뀌었는데 옛 플랫폼을 쓰면 주소맵이 조용히 어긋난다 — 매번 새로 만든다.
foreach d [list $APP $PLATFORM] {
    if {[file exists $WS/$d]} {
        catch {app remove -name $d}
        catch {platform remove -name $d}
        file delete -force $WS/$d
    }
}

xb "\[*\] platform create ..."
platform create -name $PLATFORM -hw $XSA -proc $PROC -os standalone -out $WS
platform generate
set DOMAIN standalone_domain
if {![catch {set doms [domain list]}]} {
    foreach ln [split $doms \n] {
        set tok [lindex [split [string trim $ln]] 0]
        if {[string match "standalone*" $tok]} { set DOMAIN $tok ; break }
    }
}
xb "\[*\] domain  : $DOMAIN"

app create -name $APP -platform $PLATFORM -domain $DOMAIN -template {Empty Application(C)}
set APPSRC $WS/$APP/src
foreach f [glob -nocomplain $APPSRC/*.c] { file delete -force $f }
file copy -force $REPO/vitis/tdc_app.c $APPSRC
xb "\[*\] source  : vitis/tdc_app.c"

set LD $APPSRC/lscript.ld
set lf [open $LD r] ; set t [read $lf] ; close $lf
set n [regsub -all {>\s*ps7_ddr_0} $t {> ps7_ram_0} t]
set lf [open $LD w] ; puts -nonewline $lf $t ; close $lf
set left [regexp -all {>\s*ps7_ddr_0} $t]
xb "\[*\] linker  : moved $n sections to ps7_ram_0 (OCM), DDR references left = $left"

xb "\[*\] app build ..."
if {[catch {app build -name $APP} err]} { xb "\[X\] build error: $err" }

set ELF ""
foreach d {Debug build Release} {
    if {[file exists $WS/$APP/$d/$APP.elf]} { set ELF $WS/$APP/$d/$APP.elf ; break }
}
xb ""
if {$ELF ne ""} {
    xb "BUILD OK   ELF = $ELF   ([expr {[file size $ELF] / 1024}] KB)"
    xb "Next : open the UART terminal (115200-8-N-1) FIRST, then"
    xb "       set argv {$PRJ_NAME} ; source $REPO/tcl/xsct_run_app.tcl"
} else {
    xb "\[X\] no ELF produced - see the messages above and $PRJ/vitis_build.log"
}
close $::XBLOG
