# =============================================================================
# build_eopll.tcl  —  EOPLL 통합 프로젝트 생성 (ZedBoard XC7Z020-CLG484-1)
# Generated by Claude Code, 2026-09-21
#
#  TDC 저장소의 build_zedboard.tcl (커밋 f935720) 에서 아래만 바꾼 것이다.
#  IP 설정·구현 전략·확인 절차는 한 글자도 손대지 않았다 — 그 값들이 왜 그래야
#  하는지는 원문 주석에 그대로 남아 있다.
#
#    (1) 최상위      tdc_zedboard_top -> eopll_zedboard_top
#    (2) 블록 디자인 ps_sys (tcl/bd_ps_sys.tcl) -> eopll_sys (tcl/bd_eopll_sys.tcl)
#    (3) 소스에 RTL/dac_chirp_engine.v 추가 (BD 가 모듈 참조로 쓴다)
#    (4) 비트스트림 단계에 안전장치 추가 — 아래 [★ 핀 배치가 아직 없다] 참조
#
#  [★ 핀 배치가 아직 없다 — 2026-09-21 사용자 결정으로 보류]
#    합친 보드의 FMC 핀맵이 정해지지 않았다. 그래서 XDC 는 RTL/tdc_zedboard.xdc
#    하나만 넣는다. dac_sck / dac_cs_n / dac_sdio0..3 / dac_ctrl_tri_io 에는 LOC 가
#    없다. RTL/dac_test.xdc 는 EVAL-AD3552RFMCZ 기준이라 **쓰면 안 된다** —
#    합친 보드는 배선이 다르다.
#    Vivado 는 핀이 안 박힌 I/O 가 있으면 write_bitstream 에서 DRC(UCIO-1)로 멈춘다.
#    그것이 맞는 동작이다. 핀이 없는 채로 비트스트림을 뽑으면 Vivado 가 아무 핀에나
#    배치하고, 그 비트스트림을 실물에 올리면 엉뚱한 핀이 구동된다.
#    그래서 이 스크립트는 세 번째 인자가 1 이어도 **합성과 구조 확인까지만** 하고
#    멈춘다. 핀맵이 정해져 XDC 에 들어가면 EOPLL_PINMAP_READY 를 1 로 두면 된다.
#
#  [AXI 주소 — 합치면서 바뀐 것]
#    tdc_axi_regs     0x43C0_0000 (64K)  그대로
#    dac_chirp_engine 0x43C1_0000 (16K)  ★ 0x43C0_0000 에서 옮겼다 (TDC 와 겹쳤다)
#    axi_quad_spi     0x41E0_0000 / axi_gpio 0x4120_0000  그대로
#    -> ../DAC/vitis/dac_chirp.c:73 의 FSM_BASE 를 0x43C1_0000 으로 고쳐야 한다.
#
#  [사용법]  ★ Vivado GUI 의 Tcl Console 에서
#      cd <저장소 경로>
#      set argv 1 ; source build_eopll.tcl
#    ※ 경로 구분자는 '/' 다. Tcl 에서 '\' 는 이스케이프 문자다.
#
#    argv 첫 번째 = OPERATION_MODE (0/1/2, 기본 1)
#         두 번째 = 프로젝트 폴더 이름 (기본 vivado/eopll_mode<N>)
#         세 번째 = 1 이면 합성까지 이어서 실행 (핀맵 전까지는 비트스트림 안 만든다)
#
#  ▼ 아래는 원본 build_zedboard.tcl 의 설명이다 (그대로 보존).
# =============================================================================
#
#  [만들어지는 것]
#    - 소스를 **참조로** 추가 (복사 안 함 -> 이 저장소를 고치면 바로 반영)
#    - IP 2개 : clk_wiz_0 / xadc_wiz_0
#    - 최상위 eopll_zedboard_top, generic 으로 OPERATION_MODE 전달
#
#  ★ 주의 — IP 프로퍼티 이름은 Vivado 버전에 따라 조금씩 다르다.
#    이 스크립트는 2024.1 기준으로 썼다.
#
#  [검증 상태]
#    ★ 이 스크립트는 **아직 Vivado 에서 한 번도 돌려 보지 않았다** (Orin 에 Vivado 가 없다).
#      RTL 쪽은 sim/run_iverilog_eopll.sh 로 최상위 엘러보레이션까지 통과했다.
# =============================================================================

# ---------------------------------------------------------------- 인자 처리
set OP_MODE 1
if {[info exists argv] && [llength $argv] >= 1} { set OP_MODE [lindex $argv 0] }
if {$OP_MODE < 0 || $OP_MODE > 2} { error "OPERATION_MODE 는 0/1/2 여야 한다: $OP_MODE" }

set SRC_ROOT [file normalize [file dirname [info script]]]
set PRJ_NAME "eopll_mode$OP_MODE"
if {[info exists argv] && [llength $argv] >= 2} { set PRJ_NAME [lindex $argv 1] }
set PRJ_DIR  [file join $SRC_ROOT vivado $PRJ_NAME]

# ★ 2026-09-15 : 네 번째 인자 HIT_INPUT(0=FMC LVDS / 1=PMOD 단선 Y11) 처리 삭제.
#   2026-09-05 에 STM32 임시 신호원용으로 넣었으나 Mode 2 신호원이 LVDS 비교기 하나로
#   확정됐다. 인자를 빠뜨리면 의도와 다른 입력으로 빌드되는 실수만 남았다
#   (2026-09-06 zed_uart). tdc_zedboard_top.v 의 파라미터 삭제 주석 참조.

# 384탭(96단) 기준. 체인 단수를 바꾸면 python/gen_chain_xdc.py 와 함께 여기도 고칠 것.
set CHAIN_STAGES 96
set NUM_TAPS     [expr {$CHAIN_STAGES * 4}]
# ★ 2026-09-15 : COE_FILE 제거. 교정표는 이제 PS 가 Mode 1 히스토그램으로 계산해
#   tdc_calib_ram(RTL)에 AXI 로 쓴다. 빌드에 COE 가 필요 없다.

puts "=========================================================="
puts " ZedBoard 프로젝트 생성"
puts "   소스 루트     : $SRC_ROOT"
puts "   프로젝트      : $PRJ_DIR"
puts "   OPERATION_MODE: $OP_MODE   (0=DPS스윕 / 1=링오실레이터 / 2=외부입력)"
puts "   히트 입력     : FMC LVDS E21/D21 (J18 = 2.5 V)"
# ★ 2026-09-15 : HIT_INPUT 출력 삭제 (변수 자체를 없앴다).
puts "   캐리체인      : ${CHAIN_STAGES}단 = ${NUM_TAPS}탭"
puts "=========================================================="


# ---------------------------------------------------------------- 프로젝트
# ★ 2026-09-21 추가 — 열려 있는 것을 먼저 닫는다 (CLAUDE.md 의 Tcl 규칙 3).
#   GUI Tcl Console 에서 이어서 돌릴 때, 앞 프로젝트가 열려 있으면 Windows 가 파일을
#   잠그고 있어 create_project 가 실패한다. 열린 것이 없으면 catch 가 조용히 넘어간다.
catch { close_design }
catch { close_project }

if {[file exists $PRJ_DIR]} {
    error "이미 있다: $PRJ_DIR\n  지우거나 두 번째 인자로 다른 이름을 줄 것."
}
create_project $PRJ_NAME $PRJ_DIR -part xc7z020clg484-1 -force
set_property target_language Verilog [current_project]

# ---------------------------------------------------------------- 소스 추가
# ★ 복사하지 않고 참조로 넣는다. 저장소의 .v 를 고치면 프로젝트에 바로 반영된다.
set VSRC [list \
    [file join $SRC_ROOT RTL eopll_zedboard_top.v] \
    [file join $SRC_ROOT RTL tdc_test_top.v]       \
    [file join $SRC_ROOT RTL tdc_fmcw_core_co.v]   \
    [file join $SRC_ROOT RTL tdc_timestamp_calc.v] \
    [file join $SRC_ROOT RTL tdc_calib_ram.v]      \
    [file join $SRC_ROOT RTL tdc_histogram.v]      \
    [file join $SRC_ROOT RTL phase_shifter.v]      \
    [file join $SRC_ROOT RTL dna_reader.v]         \
    [file join $SRC_ROOT RTL tdc_axi_regs.v]       \
    [file join $SRC_ROOT RTL tdc_seq.v]            \
    [file join $SRC_ROOT RTL tdc_capture.v]        \
    [file join $SRC_ROOT RTL dac_chirp_engine.v]   \
]
# ★ dac_stream_spi.v 는 넣지 않는다. AXI4-Stream 을 받던 예전 판이고,
#   지금 구조(PS 가 온칩 BRAM 에 파형을 쓰고 dac_chirp_engine 이 읽는다)에서는
#   어디에도 인스턴스되지 않는다. 참고용으로 RTL/ 에 두기만 한다.
foreach f $VSRC { if {![file exists $f]} { error "소스 없음: $f" } }
add_files -norecurse -fileset sources_1 $VSRC
set_property is_global_include false [get_files $VSRC]

set XDCF [file join $SRC_ROOT RTL tdc_zedboard.xdc]
if {![file exists $XDCF]} { error "XDC 없음: $XDCF" }
add_files -norecurse -fileset constrs_1 $XDCF
# ★ RTL/dac_test.xdc 는 일부러 넣지 않는다 — EVAL-AD3552RFMCZ 기준이라
#   합친 보드에서는 틀린 핀이다. 핀맵이 정해지면 새 XDC 를 만들어 여기 추가할 것.
puts "\[!\] DAC 핀(dac_sck/dac_cs_n/dac_sdio0..3/dac_ctrl_tri_io)에 LOC 가 없다 — 핀맵 미정"

# ---------------------------------------------------------------- 블록 디자인
#  ★ 2026-09-04 추가 : PS7 + proc_sys_reset + AXI 인터커넥트.
#    TDC 의 클럭(FCLK_CLK0)도 여기서 나온다. 상세는 tcl/bd_ps_sys.tcl 참조.
source [file join $SRC_ROOT tcl bd_eopll_sys.tcl]
make_wrapper -files [get_files eopll_sys.bd] -top
add_files -norecurse [file join $PRJ_DIR ${PRJ_NAME}.gen sources_1 bd eopll_sys hdl eopll_sys_wrapper.v]
puts "\[*\] 블록 디자인 eopll_sys 생성 + 래퍼 추가"

set_property top eopll_zedboard_top [current_fileset]
# ★ 2026-09-15 : generic 에서 HIT_INPUT 삭제 (top 에 그 파라미터가 없어졌다).
set_property generic "OPERATION_MODE=$OP_MODE" [current_fileset]
update_compile_order -fileset sources_1
puts "\[*\] 소스 [llength $VSRC]개 + XDC 1개 추가 완료. 최상위 = eopll_zedboard_top, OPERATION_MODE=$OP_MODE"

# =============================================================================
# IP 1/4 — clk_wiz_0
#   ★ 이 프로젝트에서 제일 중요한 설정이다.
#     phase_shifter.v 의 위상 스텝 = VCO 주기의 1/56 = 17.857 ps 이고,
#     이 값이 Mode 0 의 '참 시간축' 이다. VCO 가 1000 MHz 가 아니면 교정 계산이
#     전부 틀어진다. 100 MHz x 10 / 1 = 1000 MHz, ÷5 = 200 MHz.
#     Vivado 가 다른 M/D 조합을 제안해도 아래 값이 우선이다.
# =============================================================================
#   ★ 2026-09-04 : PRIM_SOURCE 가 Global_buffer 다. 입력이 Y9 외부 핀에서
#     PS 의 FCLK_CLK0(내부 클럭)으로 바뀌었기 때문이다. 핀용 설정을 그대로
#     두면 쓸데없는 IBUF 가 끼어든다.
create_ip -name clk_wiz -vendor xilinx.com -library ip -module_name clk_wiz_0
set_property -dict [list \
    CONFIG.PRIM_IN_FREQ                {100.000} \
    CONFIG.PRIM_SOURCE                 {Global_buffer} \
    CONFIG.PRIMITIVE                   {MMCM} \
    CONFIG.NUM_OUT_CLKS                {2} \
    CONFIG.CLKOUT2_USED                {true} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ  {200.000} \
    CONFIG.CLKOUT2_REQUESTED_OUT_FREQ  {200.000} \
    CONFIG.MMCM_DIVCLK_DIVIDE          {1} \
    CONFIG.MMCM_CLKFBOUT_MULT_F        {10.000} \
    CONFIG.MMCM_CLKOUT0_DIVIDE_F       {5.000} \
    CONFIG.MMCM_CLKOUT1_DIVIDE         {5} \
    CONFIG.USE_DYN_PHASE_SHIFT         {true} \
    CONFIG.CLK_OUT2_USE_FINE_PS_GUI    {true} \
    CONFIG.USE_RESET                   {true} \
    CONFIG.RESET_TYPE                  {ACTIVE_HIGH} \
    CONFIG.USE_LOCKED                  {true} \
] [get_ips clk_wiz_0]

# ★ 2026-09-16 : fine phase shift 를 clk_out2 에만 켠다 — 안 켜면 위상이 전혀 안 움직인다.
#   [무엇이 문제였나] 2026-09-03 이 스크립트가 IP 를 만들기 시작한 뒤로 USE_DYN_PHASE_SHIFT
#     만 true 였고, 출력별 USE_FINE_PS 는 전부 false 였다 (2026-09-16 zed_m0b 프로젝트에서
#     get_property 로 확인). MMCM 의 fine phase shift 는 USE_FINE_PS 가 켜진 출력에만
#     반영되므로, psen 을 넣어도 클럭은 그대로였다. 그런데 psdone 은 정상적으로 돌아와서
#     phase_shifter.v 도 앱도 "이동 성공" 으로 보였다 (phase_cur 는 명령한 스텝을 세는
#     카운터일 뿐이다). 그래서 2026-09-16 키 3 측정에서 위상 0/70/140/210 스텝의
#     timestamp mod 5000 이 전부 2123~2152 ps 로 같았다 (기대는 1250 ps 씩 이동).
#   [왜 clk_out2 만인가] 히트 생성기가 clk_200_shifted(clk_out2)에서 돌고 샘플링은
#     clk_200_fixed(clk_out1)로 한다. 둘 다 켜면 VCO 위상이 함께 움직여 상대 위상이
#     그대로다 — 즉 아무것도 안 켠 것과 같은 결과가 된다.
#   [스텝 크기] VCO 주기의 1/56 = 17.857 ps (phase_shifter.v 의 전제).
set _fps2 [get_property CONFIG.MMCM_CLKOUT1_USE_FINE_PS [get_ips clk_wiz_0]]
set _fps1 [get_property CONFIG.MMCM_CLKOUT0_USE_FINE_PS [get_ips clk_wiz_0]]
puts "\[*\] fine PS : clk_out2(MMCM_CLKOUT1) = $_fps2,  clk_out1(MMCM_CLKOUT0) = $_fps1"
if {![string match -nocase "true" $_fps2]} {
    error "clk_out2 에 fine phase shift 가 안 켜졌다 ($_fps2). 이러면 위상 이동이 아무 효과가 없다."
}
if {[string match -nocase "true" $_fps1]} {
    error "clk_out1(샘플링 클럭)에도 fine PS 가 켜졌다. 둘 다 켜지면 상대 위상이 안 움직인다."
}

set _m [get_property CONFIG.MMCM_CLKFBOUT_MULT_F [get_ips clk_wiz_0]]
set _d [get_property CONFIG.MMCM_DIVCLK_DIVIDE   [get_ips clk_wiz_0]]
set _vco [expr {100.0 * $_m / $_d}]
puts "\[*\] clk_wiz_0 : M=$_m D=$_d  ->  VCO = $_vco MHz"
if {abs($_vco - 1000.0) > 0.001} {
    error "VCO 가 $_vco MHz 다. 1000 MHz 여야 한다 — phase_shifter.v 의 17.857 ps 가 깨진다."
}
puts "\[*\] 위상 스텝 = 1000/56 = [format %.4f [expr {1000.0/56.0}]] ps  (Mode 0 참 시간축) OK"

# =============================================================================
# ★ 2026-09-15 — tdc_calib_rom (Block Memory Generator ROM, COE 초기화) 제거
#   [무엇이 있었나] 384 x 13bit ROM, Register_PortA_Output_of_Memory_Primitives /
#     _Core 둘 다 true, COE = python/tdc_calib_mode0_rom.coe.
#   [왜 뺐나] 교정표를 바꾸려면 COE 를 새로 만들어 재빌드해야 했고, 재빌드가 창을 옮겨
#     표를 만든 조건을 깨뜨렸다. RTL/tdc_calib_ram.v (512 x 13bit, 쓰기 가능)로 바꾸고
#     PS 가 Mode 1 히스토그램으로 계산해 0x2000 + i*4 에 쓴다.
#   [되살리려면] 이 블록과 tdc_timestamp_calc.v 의 u_lut_rom 인스턴스를 함께 복원할 것.
# =============================================================================

# =============================================================================
# =============================================================================
# ★ 2026-09-05 — ila_0 (universal_ila) 제거
#   [무엇이 있었나] probe 10개(1,1,9,48,9,32,32,1,16,32 = 181비트), depth 8192,
#     자격저장(C_EN_STRG_QUAL=1) 켠 ILA IP.
#   [왜 뺐나] AXI 2단계에서 히스토그램을 0x43C0_1000+탭*4 로, RO 카운트·온도·DNA 를
#     레지스터로 읽게 되어 ILA 로만 볼 수 있던 값이 남지 않았다. 또 ILA 를 쓰려면
#     Vivado Hardware Manager 를 띄우고 사람이 BTNU 를 눌러야 했는데, Vitis 에서
#     레지스터만으로 측정을 끝내는 것이 목표다.
#     덤으로 2026-09-04 빌드의 타이밍 임계경로가 ILA IP 안에 있었으니 여유가 는다.
#   [되살리려면] 여기 create_ip 블록과 tdc_test_top.v §7 의 인스턴스를 함께 복원할 것.
#     둘 중 하나만 되살리면 포트 폭이 어긋나 합성이 깨진다.
#     지운 설정은 git 이력(커밋 dd02425 이전)에 그대로 있다.
# =============================================================================

# =============================================================================
# IP 4/4 — xadc_wiz_0  (다이 온도)
#   RTL 이 daddr_in=0x00(on-chip temperature) 을 DRP 로 직접 읽는다.
# =============================================================================
#   ★ 2026-09-03 : 처음에 ENABLE_TEMPERATURE_ALARM / ENABLE_VCCINT_ALARM /
#     ENABLE_VCCAUX_ALARM 을 껐다가 "Cannot find parameter" 로 실패했다.
#     2024.1 의 xadc_wiz 에는 그 이름이 없다(VCCPINT/VCCPAUX/VBRAM/VCCDDRO 만 있음).
#     그리고 나머지 기본값이 이미 우리가 원하는 것이라 건드릴 게 거의 없다 —
#     INTERFACE_SELECTION=ENABLE_DRP, XADC_STARUP_SELECTION=single_channel,
#     SINGLE_CHANNEL_SELECTION=TEMPERATURE 가 전부 기본값이다.
#     DCLK 만 200 MHz(clk_200_fixed)로 맞춘다.
#     alarm_out 계열은 RTL 에서 미연결(.alarm_out())이라 켜져 있어도 무해하다.
create_ip -name xadc_wiz -vendor xilinx.com -library ip -module_name xadc_wiz_0
set_property -dict [list \
    CONFIG.INTERFACE_SELECTION      {ENABLE_DRP} \
    CONFIG.XADC_STARUP_SELECTION    {single_channel} \
    CONFIG.SINGLE_CHANNEL_SELECTION {TEMPERATURE} \
    CONFIG.DCLK_FREQUENCY           {200} \
] [get_ips xadc_wiz_0]
puts "\[*\] xadc_wiz_0 : DRP, 온칩 온도, DCLK 200 MHz"

# ---------------------------------------------------------------- 출력 생성
puts "\[*\] IP 출력물 생성 중 (몇 분 걸린다)..."
# ★ 2026-09-04 : get_ips 는 블록 디자인 안에 들어 있는 IP 까지 전부 잡는다.
#   그걸 개별로 generate 하면 "Nested sub-design can only be generated by its
#   parent sub-design" 에러가 난다. 우리가 직접 만든 4개만 대상으로 하고,
#   블록 디자인은 .bd 파일 단위로 따로 생성한다.
set MY_IPS [get_ips clk_wiz_0 xadc_wiz_0]   ;# ★ 2026-09-05 : ila_0 제거 / ★ 2026-09-15 : tdc_calib_rom 제거
generate_target all $MY_IPS
catch { config_ip_cache -export $MY_IPS }
export_ip_user_files -of_objects $MY_IPS -no_script -sync -force -quiet
# create_ip_run 은 컬렉션을 안 받는다 ("A collection of objects is currently not
# supported"). IP 하나씩 돌려야 OOC 합성 run 이 만들어진다.
foreach ip $MY_IPS { create_ip_run $ip }

# 블록 디자인은 통째로 생성한다 (내부 IP 는 BD 가 알아서 만든다)
generate_target all [get_files eopll_sys.bd]
export_ip_user_files -of_objects [get_files eopll_sys.bd] -no_script -sync -force -quiet
puts "\[*\] IP [llength [get_ips]] 개 생성 완료 : [get_ips]"

# ---------------------------------------------------------------- 구현 전략
# ★ 2026-09-15 : 구현 전략 설정을 DO_BUILD 블록 밖으로 뺐다. 예전에는 세 번째 인자가 1 일 때만
#   걸려서, 0 으로 프로젝트만 만든 뒤 GUI 버튼으로 구현하면 기본 전략으로 돌아 hold 가 깨질 수
#   있었다(가이드 §5 에서 손으로 걸라고 따로 적어야 했던 이유). 이제 항상 걸어 둔다.
# ★ 2026-09-05 : 구현 전략을 기본값에서 Performance_ExplorePostRoutePhysOpt 로 바꾼다.
#   [무엇이 문제였나] PS7 + AXI 를 넣은 뒤 기본 전략으로는 hold 가 깨진다.
#     WHS = -0.045 ns, 위반 경로 captured_c0_stg2 -> stg3 (같은 clk_200_fixed 도메인).
#     원인은 지연이 아니라 스큐다 : 캐리체인 pblock 을 384탭 때문에 Y140 까지 넓히면서
#     체인 양끝의 클럭 도착 시각 차이(스큐 0.298 ns)가 데이터 지연(0.266 ns)을 넘어섰다.
#   [왜 이 전략인가] 이 전략은 route 뒤에 post_route_phys_opt_design 단계를 켠다
#     (EnableStepBool=1). 라우팅이 끝난 실제 지연을 보고 레지스터를 재배치·복제해
#     스큐를 줄이므로, 배치 단계의 추정치로만 판단하는 기본 전략이 못 잡는 hold 를 잡는다.
#   [결과] 2026-09-05 zed_axi 빌드 : WNS +0.089 / WHS +0.034 ns, 비트스트림 정상 생성.
#   [대가] 구현 시간이 늘어난다(단계가 하나 더 붙는다). 타이밍이 필수라 감수한다.
set_property strategy Performance_ExplorePostRoutePhysOpt [get_runs impl_1]
puts "\[*\] 구현 전략 : [get_property strategy [get_runs impl_1]]"

# ---------------------------------------------------------------- 합성 ~ 비트스트림 (선택)
# 세 번째 인자가 1 이면 합성 -> 구조 확인 -> 구현·비트스트림 -> 배치·타이밍 확인까지 이어서 한다.
set DO_BUILD 0
if {[info exists argv] && [llength $argv] >= 3} { set DO_BUILD [lindex $argv 2] }

# ★ 2026-09-15 : 확인 항목을 tcl/check_build.tcl 로 옮기고 PASS/FAIL 로 자동 판정한다 (사용자 요청).
#   [무엇이 문제였나] 여기서 찍던 "CARRY4 = N (기대 96)", "hit 네트 fanout = N" 은 숫자만 찍고
#     판정을 사람에게 맡겼는데 기대값이 틀렸다 (2026-09-15 보고서 §6-4 : 이름 필터에 먹스 LUT 이
#     걸려 97, FLAT_PIN_COUNT 는 구동 핀까지 세서 2). 그리고 탭 0 FF 가 제자리에서 밀려난 문제
#     (§6-5)는 어떤 확인에도 걸리지 않았다 — 09-06 빌드의 synth_1/impl_1 runme.log 에
#     CRITICAL WARNING 12-2285 는 0 건이었다 (GUI 에서 합성 디자인을 열 때만 뜬다).
#   [어떻게 바꿨나] 합성 뒤 구조(S1~S5), 구현 뒤 배치·타이밍(P1, P2, T1, T2, I1)을 판정해
#     vivado/<프로젝트>/build_check.txt 에 남긴다. 지연선 단수·탭 수(S1, S2)가 틀리면 비트스트림이
#     의미가 없으므로 구현을 돌리지 않고 멈춘다. 나머지 FAIL 은 비트스트림까지 가서 보고한다.
if {$DO_BUILD} {
    set CHECK_OUT [file join $PRJ_DIR build_check.txt]
    catch { file delete $CHECK_OUT }

    puts "\[*\] 합성 시작..."
    launch_runs synth_1 -jobs 8
    wait_on_run synth_1
    if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
        error "합성 실패 — vivado/<프로젝트>/…/runs/synth_1/runme.log 확인"
    }
    open_run synth_1 -name synth_1

    set CHECK_STAGE synth
    source [file join $SRC_ROOT tcl check_build.tcl]
    if {$CHECK_HARD_FAIL > 0} {
        error "구조 확인 실패 $CHECK_HARD_FAIL 건 (지연선 단수 또는 탭 수) — 비트스트림이 의미가 없어 구현을 돌리지 않는다. $CHECK_OUT 참조"
    }

    # =========================================================================
    # ★ 2026-09-21 — 핀맵 안전장치 (EOPLL 에서 추가한 유일한 절차 변경)
    #   DAC 핀에 LOC 가 없는 동안에는 구현·비트스트림으로 넘어가지 않는다.
    #   [왜] Vivado 는 핀이 안 박힌 I/O 를 write_bitstream 의 DRC(UCIO-1)로 막는데,
    #     그 DRC 를 낮춰서 통과시키면 Vivado 가 남는 핀에 임의로 배치한다. 그 비트스트림을
    #     실물에 올리면 어떤 핀이 구동될지 모른다 — 합친 보드에서는 DAC 나 비교기 입력에
    #     신호를 밀어 넣을 수도 있다. 그래서 통과시키지 않고 여기서 멈춘다.
    #   [푸는 법] 합친 보드 핀맵이 정해져 새 XDC 가 constrs_1 에 들어가면
    #     이 스크립트를 source 하기 전에  set EOPLL_PINMAP_READY 1  을 하면 된다.
    # =========================================================================
    set PINMAP_READY 0
    if {[info exists EOPLL_PINMAP_READY]} { set PINMAP_READY $EOPLL_PINMAP_READY }
    if {!$PINMAP_READY} {
        puts ""
        puts "=========================================================="
        puts " 합성과 구조 확인까지 끝냈다. 구현·비트스트림은 하지 않는다."
        puts "   이유 : DAC 핀(dac_sck/dac_cs_n/dac_sdio0..3/dac_ctrl_tri_io)에 LOC 가 없다."
        puts "          합친 보드의 FMC 핀맵이 아직 정해지지 않았다 (2026-09-21 보류)."
        puts "   확인 결과 : $CHECK_OUT"
        puts "   핀맵이 생기면 : set EOPLL_PINMAP_READY 1 ; set argv ... ; source build_eopll.tcl"
        puts "=========================================================="
        return
    }

    puts "\[*\] 구현 + 비트스트림 시작..."
    launch_runs impl_1 -to_step write_bitstream -jobs 8
    wait_on_run impl_1
    if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
        error "구현/비트스트림 실패 — vivado/<프로젝트>/…/runs/impl_1/runme.log 확인"
    }
    # ★ 2026-09-15 : 합성 디자인이 열린 채 open_run 을 또 부르면 오류가 날 수 있다 (CLAUDE.md Tcl 규칙 3).
    catch { close_design }
    open_run impl_1

    set CHECK_STAGE impl
    source [file join $SRC_ROOT tcl check_build.tcl]

    report_timing_summary -delay_type min_max -max_paths 5 \
        -file [file join $PRJ_DIR timing_summary.rpt]
    report_utilization -file [file join $PRJ_DIR utilization.rpt]

    # ★ 2026-09-15 : XSA 내보내기와 UART 뱅크 전압 확인까지 자동으로 한다 (회사 가이드용).
    #   [왜] 빌드 뒤 GUI 에서 File -> Export Hardware 를 손으로 하고, cmd 에서 findstr 로
    #     0x12E0 을 따로 확인하던 두 단계를 없앤다. 다음 단계(tcl/xsct_build_app.tcl)가
    #     vivado/<프로젝트>/tdc_zedboard_top.xsa 를 그대로 읽는다.
    #   [뱅크 전압] MIO48(UART1 TX) 설정 레지스터 0xF80007C0 의 값이 0x12E0(LVCMOS18)이어야 한다.
    #     0x16E0(LVCMOS33)이면 UART 수신이 죽는다 (2026-09-06, tcl/bd_ps_sys.tcl 주석).
    set XSA [file join $PRJ_DIR eopll_zedboard_top.xsa]
    if {[catch {write_hw_platform -fixed -include_bit -force -file $XSA} err]} {
        puts "\[!\] XSA 내보내기 실패 : $err"
        set XSA "(실패)"
    }
    set MIO_OK "확인 못 함"
    set p7 [lindex [glob -nocomplain [file join $PRJ_DIR ${PRJ_NAME}.gen sources_1 bd eopll_sys ip *ps7_0_0 ps7_init.tcl]] 0]
    if {$p7 ne ""} {
        set f7 [open $p7 r] ; set t7 [read $f7] ; close $f7
        if {[string match "*0XF80007C0 0x00003FFF 0x000012E0*" $t7]} {
            set MIO_OK "OK (0x12E0, LVCMOS18)"
        } else {
            set MIO_OK "★ 0x12E0 이 아니다 — UART 수신이 안 된다. tcl/bd_eopll_sys.tcl 의 뱅크 전압 확인"
        }
    }

    set BIT [lindex [glob -nocomplain [file join $PRJ_DIR ${PRJ_NAME}.runs impl_1 *.bit]] 0]
    puts ""
    puts "=========================================================="
    puts " 빌드 끝"
    puts "   비트스트림 : $BIT"
    puts "   XSA        : $XSA"
    puts "   UART 전압  : $MIO_OK"
    puts "   확인 결과  : $CHECK_OUT   (FAIL $CHECK_FAIL 건)"
    puts "   리포트     : $PRJ_DIR/timing_summary.rpt , utilization.rpt"
    if {$CHECK_FAIL > 0} {
        puts "   ★ FAIL 이 있다. 위 표(또는 build_check.txt)에서 FAIL 줄을 확인할 것."
    }
    puts " 보드에 올린 뒤 '1' 키로 교정표를 다시 만들 것 (측정 창이 빌드마다 옮겨간다)."
    puts "=========================================================="
} else {
    # ------------------------------------------------------------ 마무리 안내
    puts ""
    puts "=========================================================="
    puts " 프로젝트 생성 완료 : $PRJ_DIR"
    puts "=========================================================="
    puts " 다음 순서 (구현 전략은 이미 걸어 두었다):"
    puts "   1) Generate Bitstream (GUI 버튼)"
    puts "   2) Open Implemented Design 후 Tcl Console 에:"
    puts "        set CHECK_STAGE impl ; source $SRC_ROOT/tcl/check_build.tcl"
    puts "      FAIL 줄이 없어야 한다 (지연선 수, 탭 0 FF 위치, 먹스 위치, WNS/WHS 등)."
    puts ""
    puts " 하드웨어 확인 (J18 점퍼): FMC 뱅크 VCCO 를 2.5V 로 둘 것 (LVDS_25 + DIFF_TERM)"
    puts "=========================================================="
}
