`timescale 1ns / 1ps
// =============================================================================
// elab_stubs.v  —  최상위 엘러보레이션 전용 스텁 (Xilinx 프리미티브 / IP / 블록 디자인)
// Generated by Claude Code, 2026-09-15
//
//  [왜 있나]
//    tdc_zedboard_top 전체를 iverilog 로 엘러보레이션해 포트 이름·폭 연결 오타를 잡으려면
//    Vivado 라이브러리 모듈이 필요하다. Orin 에는 Vivado 가 없으므로 포트만 맞춘 빈 모듈을 둔다.
//  [★ 동작 없음]
//    출력은 전부 상수이거나 입력을 그대로 넘긴다. 이 파일로 시뮬레이션 결과를 판단하지 말 것.
//  [포트 출처]
//    RTL 의 인스턴스 연결에서 옮겼다 (2026-09-15) : tdc_fmcw_core_co.v (CARRY4, FDC),
//    dna_reader.v (DNA_PORT), tdc_zedboard_top.v (IBUFDS, ps_sys_wrapper),
//    tdc_test_top.v (BUFG, LUT1, LUT2, clk_wiz_0, xadc_wiz_0).
//    IP 설정을 바꿔 포트가 늘거나 줄면 여기도 고칠 것.
// =============================================================================
module CARRY4 (output [3:0] CO, output [3:0] O, input CI, input CYINIT, input [3:0] DI, input [3:0] S);
    assign CO = 4'd0; assign O = 4'd0;
endmodule

module FDC #(parameter INIT = 1'b0) (output reg Q, input C, input CLR, input D);
    always @(posedge C) Q <= D;
endmodule

module DNA_PORT #(parameter SIM_DNA_VALUE = 57'h0) (output DOUT, input CLK, input DIN, input READ, input SHIFT);
    assign DOUT = 1'b0;
endmodule

module IBUFDS #(parameter DIFF_TERM = "FALSE", parameter IBUF_LOW_PWR = "TRUE", parameter IOSTANDARD = "DEFAULT")
    (output O, input I, input IB);
    assign O = I;
endmodule

module BUFG (output O, input I);
    assign O = I;
endmodule

// ★ 2026-09-16 : LUT1 / LUT2 는 일부러 상수 0 으로 둔다.
//   이 둘은 링 오실레이터 고리(RO_LOOP 의 인버터 31개)에 쓰인다. INIT 대로 동작시키면
//   지연이 0 인 조합 고리가 되어 시뮬레이터가 같은 시각에 무한히 돈다 (멈추지 않는다).
//   RO 히트는 이 파일을 쓰는 시험의 대상이 아니므로 상수로 두는 편이 안전하다.
module LUT1 #(parameter INIT = 2'h0) (output O, input I0);
    assign O = 1'b0;
endmodule

module LUT2 #(parameter INIT = 4'h0) (output O, input I0, input I1);
    assign O = 1'b0;
endmodule

// ★ 2026-09-15 : 추가. tdc_test_top.v 의 히트 먹스(RO / LVDS 런타임 선택)를 추론 LUT 대신
//   LUT4 프리미티브 u_hit_mux 로 명시했다 (XDC 로 캐리 슬라이스 밖에 고정하려고).
// ★ 2026-09-16 : LUT4 / LUT5 는 INIT 대로 동작시킨다. 히트 먹스(u_hit_mux)가 이 둘 중
//   하나라, 상수 0 으로 두면 먹스 뒤(지연선 입구)를 시뮬레이션에서 볼 수 없다.
//   고리에 들어가지 않으므로 무한 루프 걱정도 없다.
module LUT4 #(parameter [15:0] INIT = 16'h0000) (output O, input I0, input I1, input I2, input I3);
    assign O = INIT[{I3, I2, I1, I0}];
endmodule

// ★ 2026-09-16 : 추가. 히트 먹스가 LUT4 -> LUT5 가 됐다 (DPS 히트 입력 하나가 늘었다).
module LUT5 #(parameter [31:0] INIT = 32'h00000000) (output O, input I0, input I1, input I2, input I3, input I4);
    assign O = INIT[{I4, I3, I2, I1, I0}];
endmodule

module clk_wiz_0 (input clk_in1, input reset, output clk_out1, output clk_out2, input psclk,
                  input psen, input psincdec, output psdone, output locked);
    assign clk_out1 = clk_in1; assign clk_out2 = clk_in1; assign psdone = 1'b0; assign locked = 1'b1;
endmodule

module xadc_wiz_0 (input [6:0] daddr_in, input dclk_in, input den_in, input [15:0] di_in, input dwe_in,
                   output [15:0] do_out, output drdy_out, input reset_in, input vp_in, input vn_in,
                   output busy_out, output [4:0] channel_out, output eoc_out, output eos_out, output alarm_out);
    assign do_out = 16'd0; assign drdy_out = 1'b0; assign busy_out = 1'b0; assign channel_out = 5'd0;
    assign eoc_out = 1'b0; assign eos_out = 1'b0; assign alarm_out = 1'b0;
endmodule

module ps_sys_wrapper (
    inout [14:0] DDR_addr, inout [2:0] DDR_ba, inout DDR_cas_n, inout DDR_ck_n, inout DDR_ck_p,
    inout DDR_cke, inout DDR_cs_n, inout [3:0] DDR_dm, inout [31:0] DDR_dq, inout [3:0] DDR_dqs_n,
    inout [3:0] DDR_dqs_p, inout DDR_odt, inout DDR_ras_n, inout DDR_reset_n, inout DDR_we_n,
    inout FIXED_IO_ddr_vrn, inout FIXED_IO_ddr_vrp, inout [53:0] FIXED_IO_mio, inout FIXED_IO_ps_clk,
    inout FIXED_IO_ps_porb, inout FIXED_IO_ps_srstb,
    output [31:0] M_AXI_awaddr, output [2:0] M_AXI_awprot, output M_AXI_awvalid, input M_AXI_awready,
    output [31:0] M_AXI_wdata, output [3:0] M_AXI_wstrb, output M_AXI_wvalid, input M_AXI_wready,
    input [1:0] M_AXI_bresp, input M_AXI_bvalid, output M_AXI_bready,
    output [31:0] M_AXI_araddr, output [2:0] M_AXI_arprot, output M_AXI_arvalid, input M_AXI_arready,
    input [31:0] M_AXI_rdata, input [1:0] M_AXI_rresp, input M_AXI_rvalid, output M_AXI_rready,
    output fclk_clk0, output [0:0] peripheral_arstn);
    assign M_AXI_awaddr = 32'd0; assign M_AXI_awprot = 3'd0; assign M_AXI_awvalid = 1'b0;
    assign M_AXI_wdata = 32'd0;  assign M_AXI_wstrb = 4'd0;  assign M_AXI_wvalid = 1'b0;
    assign M_AXI_bready = 1'b0;  assign M_AXI_araddr = 32'd0; assign M_AXI_arprot = 3'd0;
    assign M_AXI_arvalid = 1'b0; assign M_AXI_rready = 1'b0;
    assign fclk_clk0 = 1'b0;     assign peripheral_arstn = 1'b1;
endmodule

// -----------------------------------------------------------------------------
// eopll_sys_wrapper — 통합 블록 디자인(tcl/bd_eopll_sys.tcl)의 래퍼 스텁
//   2026-09-21 추가. ps_sys_wrapper 와 같은 포트에 DAC 핀 7 개가 더 붙는다.
//   포트 이름·폭 오타만 잡기 위한 것이다. 동작은 없다.
//   ★ dac_ctrl_tri_io 는 BD 가 GPIO 인터페이스를 외부로 낼 때 래퍼가 IOBUF 를
//     끼우며 만드는 inout 포트다 (dac_ctrl_tri_i/o/t 가 아니라 _tri_io 하나).
// -----------------------------------------------------------------------------
module eopll_sys_wrapper (
    inout [14:0] DDR_addr, inout [2:0] DDR_ba, inout DDR_cas_n, inout DDR_ck_n, inout DDR_ck_p,
    inout DDR_cke, inout DDR_cs_n, inout [3:0] DDR_dm, inout [31:0] DDR_dq, inout [3:0] DDR_dqs_n,
    inout [3:0] DDR_dqs_p, inout DDR_odt, inout DDR_ras_n, inout DDR_reset_n, inout DDR_we_n,
    inout FIXED_IO_ddr_vrn, inout FIXED_IO_ddr_vrp, inout [53:0] FIXED_IO_mio, inout FIXED_IO_ps_clk,
    inout FIXED_IO_ps_porb, inout FIXED_IO_ps_srstb,
    output [31:0] M_AXI_awaddr, output [2:0] M_AXI_awprot, output M_AXI_awvalid, input M_AXI_awready,
    output [31:0] M_AXI_wdata, output [3:0] M_AXI_wstrb, output M_AXI_wvalid, input M_AXI_wready,
    input [1:0] M_AXI_bresp, input M_AXI_bvalid, output M_AXI_bready,
    output [31:0] M_AXI_araddr, output [2:0] M_AXI_arprot, output M_AXI_arvalid, input M_AXI_arready,
    input [31:0] M_AXI_rdata, input [1:0] M_AXI_rresp, input M_AXI_rvalid, output M_AXI_rready,
    output fclk_clk0, output [0:0] peripheral_arstn,
    output dac_sck, output dac_cs_n, output dac_sdio0, inout dac_sdio1,
    output dac_sdio2, output dac_sdio3, inout [3:0] dac_ctrl_tri_io);
    assign M_AXI_awaddr = 32'd0; assign M_AXI_awprot = 3'd0; assign M_AXI_awvalid = 1'b0;
    assign M_AXI_wdata = 32'd0;  assign M_AXI_wstrb = 4'd0;  assign M_AXI_wvalid = 1'b0;
    assign M_AXI_bready = 1'b0;  assign M_AXI_araddr = 32'd0; assign M_AXI_arprot = 3'd0;
    assign M_AXI_arvalid = 1'b0; assign M_AXI_rready = 1'b0;
    assign fclk_clk0 = 1'b0;     assign peripheral_arstn = 1'b1;
    assign dac_sck = 1'b0; assign dac_cs_n = 1'b1; assign dac_sdio0 = 1'b0;
    assign dac_sdio2 = 1'b0; assign dac_sdio3 = 1'b0;
endmodule
