#!/bin/bash
# =============================================================================
# run_iverilog_eopll.sh — EOPLL 통합 최상위 엘러보레이션 시험 (Icarus Verilog)
# Generated by Claude Code, 2026-09-21
#
#  [왜 이게 있나]
#    RTL/eopll_zedboard_top.v 는 TDC 의 tdc_zedboard_top.v 에서 블록 디자인 래퍼를
#    eopll_sys_wrapper 로 바꾸고 DAC 핀 7 개를 추가한 것이다. 그 배선이 맞는지는
#    Vivado 없이도 확인할 수 있다 — 포트 이름과 폭만 보면 된다.
#    ★ eopll_zedboard_top.v / elab_stubs.v / tcl/bd_eopll_sys.tcl 의 포트를 고치면
#      반드시 같이 돌릴 것. BD 래퍼의 포트 이름이 어긋나면 Vivado 합성에서야 걸린다.
#
#  [무엇을 보나]
#    1) eopll_zedboard_top 전체 엘러보레이션. BD 래퍼는 sim/elab_stubs.v 의
#       eopll_sys_wrapper 스텁으로 대신한다.
#    2) dac_chirp_engine 단독 엘러보레이션은 하지 않는다 — ODDR 프리미티브 스텁이
#       없어 컴파일되지 않는다. 이것은 DAC 저장소에서도 같고(2026-09-21 확인),
#       sim/run_iverilog_dac.sh 가 같은 이유로 처프 엔진 항목에서 실패한다.
#
#  [검증 범위 밖]
#    실제 BD 래퍼의 포트 이름(Vivado 가 생성한다), 주소 디코딩, 타이밍, 핀 배치.
#
#  [사용법]  저장소 루트에서
#      sim/run_iverilog_eopll.sh
# =============================================================================
set -u
export PATH=$HOME/.local/bin:$PATH
cd "$(dirname "$0")/.."
OUT=$(mktemp -d)
trap 'rm -rf "$OUT"' EXIT

command -v iverilog >/dev/null || { echo "iverilog 를 못 찾았다 (~/.local/bin)"; exit 1; }
echo "$(iverilog -V 2>/dev/null | head -1)"
echo

fail=0
TOP_SRC="RTL/eopll_zedboard_top.v RTL/tdc_test_top.v RTL/tdc_fmcw_core_co.v RTL/tdc_timestamp_calc.v
         RTL/tdc_calib_ram.v RTL/tdc_histogram.v RTL/phase_shifter.v RTL/dna_reader.v
         RTL/tdc_axi_regs.v RTL/tdc_seq.v RTL/tdc_capture.v sim/elab_stubs.v"

echo "[최상위 eopll_zedboard_top 엘러보레이션 — 포트 연결만]"
printf "  %-40s " "OPERATION_MODE=2"
if iverilog -g2005 -Wall -t null -s eopll_zedboard_top \
        -Peopll_zedboard_top.OPERATION_MODE=2 \
        $TOP_SRC 2>"$OUT/e.err" && [ ! -s "$OUT/e.err" ]; then
    echo "통과"
else
    echo "실패"; head -20 "$OUT/e.err" | sed 's/^/      /'; fail=1
fi

echo
if [ $fail -eq 0 ]; then echo "==== 통합 최상위 통과 ===="; else echo "==== 통합 최상위 실패 ===="; fi
exit $fail
