#!/bin/bash
# =============================================================================
# run_iverilog.sh — TDC 교정표 RAM(4단계) 회귀 시험 (Icarus Verilog)
# Generated by Claude Code, 2026-09-15
#
#  [왜 이게 있나]
#    2026-09-15 에 교정 ROM IP(tdc_calib_rom, COE)를 PS 가 쓰는 RAM(tdc_calib_rom ->
#    tdc_calib_ram)으로 바꿨다. 타임스탬프 파이프라인은 그 RAM 의 읽기 지연이 정확히 2 여야
#    맞게 도는데, 이것은 Vivado 없이도 확인할 수 있다. Orin 의 iverilog 12.0(~/.local)으로 돈다.
#    ★ tdc_calib_ram.v / tdc_axi_regs.v / tdc_timestamp_calc.v 를 고치면 커밋 전에 돌릴 것.
#
#  [무엇을 보나]
#    1) 기능 시험 : sim/tb_tdc_calib.v 의 T0~T7 (AXI 쓰기·되읽기, 주소 겹침, BUSY 게이트,
#       동시 요청, timestamp = coarse*5000 - 교정표[fine])
#    2) 음성 시험 : RAM 지연을 일부러 3 으로 만들어 T7 이 실패하는지 — 테스트가 지연 어긋남을
#       실제로 잡는다는 증거
#    3) 최상위 엘러보레이션 : tdc_zedboard_top 전체 (★ 2026-09-15 : HIT_INPUT 삭제로 한 번). Xilinx 라이브러리는
#       sim/elab_stubs.v 의 빈 모듈. 포트 이름·폭 연결 오타만 본다.
#    각 줄이 "통과" 여야 하고 마지막이 "회귀 전부 통과" 여야 한다.
#
#  [검증 범위 밖 — Vivado 에서만 확인되는 것]
#    BRAM 추론(initial 초기값, 출력 레지스터 흡수), 타이밍, 실제 IP 포트.
#
#  ★ 테스트벤치 화면 출력은 ASCII 다 (Windows Vivado Tcl Console 의 CP949 문제,
#    DAC 저장소와 같은 규칙). 이 스크립트 자신의 출력은 리눅스 터미널 전용이라 한글이다.
#
#  [사용법]  저장소 루트에서
#      sim/run_iverilog.sh
# =============================================================================
set -u
export PATH=$HOME/.local/bin:$PATH
cd "$(dirname "$0")/.."
OUT=$(mktemp -d)
trap 'rm -rf "$OUT"' EXIT

command -v iverilog >/dev/null || { echo "iverilog 를 못 찾았다 (~/.local/bin)"; exit 1; }
echo "$(iverilog -V 2>/dev/null | head -1)"
echo

fail=0
SRC="RTL/tdc_calib_ram.v RTL/tdc_axi_regs.v RTL/tdc_timestamp_calc.v sim/tb_tdc_calib.v"

echo "[교정표 RAM + AXI + 타임스탬프]"
printf "  %-40s " "기능 시험 T0~T7"
if ! iverilog -g2005 -Wall -o "$OUT/ok.vvp" $SRC 2>"$OUT/c.err"; then
    echo "컴파일 실패"; cat "$OUT/c.err"; fail=1
elif [ -s "$OUT/c.err" ]; then
    echo "컴파일 경고"; cat "$OUT/c.err"; fail=1
else
    timeout 300 vvp -n "$OUT/ok.vvp" > "$OUT/ok.log" 2>&1
    if grep -q "ALL PASS" "$OUT/ok.log"; then
        echo "통과   $(grep -o 'hits in [0-9]*, out [0-9]*, mismatches [0-9]*' "$OUT/ok.log")"
    else
        echo "실패"; grep -E '\*\*\*|mismatch|====' "$OUT/ok.log" | head -10 | sed 's/^/      /'; fail=1
    fi
fi

printf "  %-40s " "음성 시험 (RAM 지연 3 이면 T7 실패해야)"
if ! iverilog -g2005 -DCAL_LAT3_NEGATIVE_TEST -o "$OUT/lat3.vvp" $SRC 2>"$OUT/c.err"; then
    echo "컴파일 실패"; cat "$OUT/c.err"; fail=1
else
    timeout 300 vvp -n "$OUT/lat3.vvp" > "$OUT/lat3.log" 2>&1
    if grep -q "FAIL : T7" "$OUT/lat3.log" && ! grep -q "ALL PASS" "$OUT/lat3.log"; then
        echo "통과   (어긋남 검출 : $(grep -o 'mismatches [0-9]*' "$OUT/lat3.log" | tail -1))"
    else
        echo "실패   (지연 3 을 못 잡았다)"; fail=1
    fi
fi

echo
echo "[Mode 0 히트 생성기 — sim/tb_m0_gen.v]"
# ★ 2026-09-16 : 키 3(내부 루프백)이 쓰는 주기 50/80/140/230 을 실제로 만들어 내는지,
#   그리고 DPS 가 아닐 때 새어나가지 않는지 본다. 먹스(LUT5)까지 함께 시험된다.
#   ※ clk_wiz 스텁은 두 클럭을 같은 위상으로 내보내므로 위상 시프트 효과는 여기서 안 보인다.
GEN_SRC="RTL/tdc_test_top.v RTL/tdc_fmcw_core_co.v RTL/tdc_timestamp_calc.v RTL/tdc_calib_ram.v
         RTL/tdc_histogram.v RTL/phase_shifter.v RTL/dna_reader.v RTL/tdc_seq.v RTL/tdc_capture.v
         sim/elab_stubs.v sim/tb_m0_gen.v"
printf "  %-40s " "주기 50/80/140/230 + 정지 조건"
if ! iverilog -g2005 -Wall -o "$OUT/gen.vvp" $GEN_SRC 2>"$OUT/g.err"; then
    echo "컴파일 실패"; cat "$OUT/g.err"; fail=1
elif [ -s "$OUT/g.err" ]; then
    echo "컴파일 경고"; cat "$OUT/g.err"; fail=1
else
    timeout 300 vvp -n "$OUT/gen.vvp" > "$OUT/gen.log" 2>&1
    if grep -q "ALL PASS" "$OUT/gen.log"; then
        echo "통과   ($(grep -c 'gaps measured' "$OUT/gen.log") 조건)"
    else
        echo "실패"; grep -E '\*\*\*|mismatch|want' "$OUT/gen.log" | head -8 | sed 's/^/      /'; fail=1
    fi
fi

echo
echo "[최상위 tdc_zedboard_top 엘러보레이션 — 포트 연결만]"
TOP_SRC="RTL/tdc_zedboard_top.v RTL/tdc_test_top.v RTL/tdc_fmcw_core_co.v RTL/tdc_timestamp_calc.v
         RTL/tdc_calib_ram.v RTL/tdc_histogram.v RTL/phase_shifter.v RTL/dna_reader.v
         RTL/tdc_axi_regs.v RTL/tdc_seq.v RTL/tdc_capture.v sim/elab_stubs.v"
# ★ 2026-09-15 : HIT_INPUT 0/1 두 번 돌리던 것을 한 번으로 줄였다. HIT_INPUT 파라미터가
#   없어졌다 (Mode 2 신호원 = FMC LVDS 하나). 없는 파라미터를 -P 로 주면 경고가 난다.
printf "  %-40s " "OPERATION_MODE=2"
if iverilog -g2005 -Wall -t null -s tdc_zedboard_top \
        -Ptdc_zedboard_top.OPERATION_MODE=2 \
        $TOP_SRC 2>"$OUT/e.err" && [ ! -s "$OUT/e.err" ]; then
    echo "통과"
else
    echo "실패"; head -10 "$OUT/e.err" | sed 's/^/      /'; fail=1
fi

echo
if [ $fail -eq 0 ]; then echo "==== 회귀 전부 통과 ===="; else echo "==== 회귀 실패 ===="; fi
exit $fail
