#!/bin/bash
# =============================================================================
# run_iverilog.sh — dac_stream_spi 회귀 시험 (Icarus Verilog)
# Generated by Claude Code, 2026-09-09
#
#  [왜 이게 있나]
#    2026-09-09 에 Orin 에 iverilog 12.0 을 소스 빌드해 넣었다 (~/.local).
#    그 전까지 RTL 검증은 회사 노트북의 xsim 까지 git 왕복을 해야 했는데,
#    이제 RTL 을 고친 자리에서 바로 돌릴 수 있다.
#    ★ RTL 을 고치면 커밋 전에 반드시 이걸 돌릴 것.
#
#  [설치되어 있지 않다면]
#    sudo 없이 소스 빌드했다. gperf 3.1 -> iverilog 12.0, 둘 다 --prefix=$HOME/.local
#
#  [무엇을 보나]
#    각 줄이 "통과" 여야 하고 마지막이 "회귀 전부 통과" 여야 한다.
#    dac_stream_spi(구 DMA 구조)와 dac_chirp_engine(신 BRAM 구조) 양쪽을 돈다.
#
#  ★ 테스트벤치의 화면 출력은 ASCII(영문) 다. Windows 의 Vivado Tcl Console 이
#    UTF-8 한글을 CP949 로 읽어 깨지기 때문이다 (2026-09-09 실물 확인).
#    그래서 아래 grep 패턴도 영문이다. 이 스크립트 자신의 출력은 리눅스 터미널
#    전용이라 한글 그대로 둔다.
#
#  [사용법]  저장소 루트에서
#      sim/run_iverilog.sh
# =============================================================================
set -u
export PATH=$HOME/.local/bin:$PATH
cd "$(dirname "$0")/.."
OUT=$(mktemp -d)
trap 'rm -rf "$OUT"' EXIT

command -v iverilog >/dev/null || { echo "iverilog 를 못 찾았다 (~/.local/bin)"; exit 1; }
echo "$(iverilog -V 2>/dev/null | head -1)"
echo

fail=0

run() {   # run <CLKP> <PERIOD> <DIV> <LANES> <IX1> <설명>
    local clkp=$1 per=$2 div=$3 lanes=$4 ix1=$5 desc=$6
    printf "  %-38s " "$desc"
    iverilog -g2005 -Wall \
        -Ptb_dac_stream_spi.CLKP=$clkp -Ptb_dac_stream_spi.PERIOD=$per \
        -Ptb_dac_stream_spi.DIV=$div -Ptb_dac_stream_spi.LANES=$lanes \
        -Ptb_dac_stream_spi.IX1=$ix1 \
        -o "$OUT/tb.vvp" RTL/dac_stream_spi.v sim/tb_dac_stream_spi.v 2>"$OUT/c.err" \
        || { echo "컴파일 실패"; cat "$OUT/c.err"; fail=1; return; }
    [ -s "$OUT/c.err" ] && { echo "컴파일 경고"; cat "$OUT/c.err"; fail=1; return; }
    timeout 180 vvp "$OUT/tb.vvp" > "$OUT/r.log" 2>&1
    if grep -q "ALL PASS" "$OUT/r.log"; then
        echo "통과   $(grep -o 'sample rate [0-9.]* MSPS' "$OUT/r.log" | head -1)"
    else
        echo "실패"
        grep -E "\*\*\*|====" "$OUT/r.log" | sed 's/^/      /'
        fail=1
    fi
}

echo "[단선 — 브링업 사다리 (aclk 100 MHz)]"
run 10.0 200 6 1 0 "1단계  N=50   SCK 8.33 MHz"
run 10.0 100 3 1 0 "2단계  N=100  SCK 16.67 MHz"
run 10.0  40 1 1 0 "3단계  N=250  SCK 50 MHz"
run 10.0  32 1 1 0 "단선 한계  격자 32 (연속)"

echo
echo "[멀티 IO — 최소 격자 = (32/LANES)x DIV, 유휴 0]"
run 10.0  16 1 2 0 "dual  N=625   격자 16 (연속)"
run 10.0   8 1 4 0 "quad  N=1250  격자 8  (연속)"
run 10.0   8 1 4 1 "quad + 명령만 1선 (INSTR_X1)"

echo
echo "[더 빠른 SPI 도메인 — clk_wiz + 비동기 FIFO 를 가정]"
run 7.576  8 1 4 0 "quad  aclk 132 MHz -> SCK 66 MHz"

echo
echo "[처프 엔진 — 온칩 BRAM 핑퐁 (2026-09-10 신규 구조)]"
#  25 kHz 는 aclk 100 MHz 에서 주기당 4000 클럭이다. NPOINTS x PERIOD = 4000.
runc() {   # runc <PERIOD> <DIV> <LANES> <NPTS> <설명>
    local per=$1 div=$2 lanes=$3 npts=$4 desc=$5
    printf "  %-38s " "$desc"
    iverilog -g2005 -Wall \
        -Ptb_dac_chirp_engine.PERIOD=$per -Ptb_dac_chirp_engine.DIV=$div \
        -Ptb_dac_chirp_engine.LANES=$lanes -Ptb_dac_chirp_engine.NPTS=$npts \
        -o "$OUT/c.vvp" RTL/dac_chirp_engine.v sim/tb_dac_chirp_engine.v 2>"$OUT/c.err" \
        || { echo "컴파일 실패"; cat "$OUT/c.err"; fail=1; return; }
    [ -s "$OUT/c.err" ] && { echo "컴파일 경고"; cat "$OUT/c.err"; fail=1; return; }
    timeout 300 vvp "$OUT/c.vvp" > "$OUT/r.log" 2>&1
    if grep -q "ALL PASS" "$OUT/r.log"; then
        echo "통과"
    else
        echo "실패"
        grep -E "\*\*\*|====" "$OUT/r.log" | head -6 | sed 's/^/      /'
        fail=1
    fi
}
runc 200 6 1  20 "25 kHz 브링업1 단선 20점 SCK 8.33 MHz"
runc  40 1 1   8 "PERIOD=40 단선 8점"
runc  32 1 1  16 "단선 연속격자 16점"
runc  16 1 2  16 "dual  16점"
runc   8 1 4  16 "quad  16점 (격자 8, 유휴 0)"
runc  32 1 1 125 "25 kHz 단선 125점 (3.125 MSPS)"
runc  16 1 2 250 "25 kHz dual  250점 (6.25 MSPS)"
runc   8 1 4 500 "25 kHz quad  500점 (12.5 MSPS)"

echo
echo "[음성 시험 — 잘못된 설정을 막는가]"
printf "  %-38s " "PERIOD=7, quad (최소 8 미만)"
iverilog -g2005 -Ptb_dac_stream_spi.PERIOD=7 -Ptb_dac_stream_spi.LANES=4 \
    -o "$OUT/tb.vvp" RTL/dac_stream_spi.v sim/tb_dac_stream_spi.v 2>/dev/null
timeout 180 vvp "$OUT/tb.vvp" > "$OUT/r.log" 2>&1
#  RTL 이 period_l 을 최소값으로 클램프하므로 OVERRUN 이 아니라 **격자 8 로 보정**
#  되는 것이 정답이다. 잘못된 값을 그대로 쓰면 파형 주기가 조용히 틀린다.
if grep -q "word interval min/max : 80.000 / 80.000" "$OUT/r.log"; then
    echo "통과   (7 -> 8 로 클램프됨)"
else
    echo "실패   (클램프가 안 걸렸다)"
    grep -E "word interval" "$OUT/r.log" | sed 's/^/      /'
    fail=1
fi

echo
if [ $fail -eq 0 ]; then echo "==== 회귀 전부 통과 ===="; else echo "==== 회귀 실패 ===="; fi
exit $fail
