`timescale 1ns / 1ps
// =============================================================================
// tb_dac_chirp_engine.v - testbench for the BRAM ping-pong chirp engine
// Generated by Claude Code, 2026-09-10
//
//  [WHAT IT CHECKS]
//    1. sample interval is exactly PERIOD aclk cycles
//    2. SCK period inside a word is 2 x SCK_DIV x aclk
//    3. the instruction byte 0x2A goes out once per frame
//    4. the bytes the slave reconstructs equal what the PS wrote into BRAM,
//       in order, wrapping at NPOINTS
//    5. CTRL.SWAP_REQ switches buffers at a CHIRP BOUNDARY, not mid-chirp
//    6. the config-SPI passthrough still works when the chirp is off
//
//  ★ 출력은 전부 영문이다 — Windows 의 Vivado 콘솔이 UTF-8 한글을 깨뜨린다.
// =============================================================================

module tb_dac_chirp_engine #(
    parameter integer PERIOD = 40,
    parameter integer DIV    = 1,
    parameter integer LANES  = 1,
    parameter integer NPTS   = 8,
    parameter real    CLKP   = 10.0
);
    localparam [1:0] LCODE = (LANES == 4) ? 2'b10 : (LANES == 2) ? 2'b01 : 2'b00;

    reg aclk = 0, aresetn = 0;
    always #(CLKP/2.0) aclk = ~aclk;

    // ---------------- AXI4-Lite ----------------
    reg  [13:0] awaddr = 0;  reg awvalid = 0;  wire awready;
    reg  [31:0] wdata  = 0;  reg wvalid  = 0;  wire wready;
    wire [1:0]  bresp;       wire bvalid;      reg bready = 1;
    reg  [13:0] araddr = 0;  reg arvalid = 0;  wire arready;
    wire [31:0] rdata;       wire rvalid;      reg rready = 1;
    wire [1:0]  rresp;

    // ---------------- pins ----------------
    wire dac_sck, dac_cs_n, dac_sdio0, dac_sdio2, dac_sdio3;
    wire dac_sdio1;
    reg  slave_sdio1 = 1'bz;
    assign dac_sdio1 = slave_sdio1;
    pulldown pd1(dac_sdio1);
    wire [3:0] sdio = {dac_sdio3, dac_sdio2, dac_sdio1, dac_sdio0};

    reg  cfg_sck = 0, cfg_cs_n = 1, cfg_mosi = 0;
    wire cfg_miso;

    dac_chirp_engine #(.C_S_AXI_ADDR_WIDTH(14), .NPOINTS_MAX(1024)) dut (
        .aclk(aclk), .aresetn(aresetn),
        .s_axi_awaddr(awaddr), .s_axi_awprot(3'd0), .s_axi_awvalid(awvalid),
        .s_axi_awready(awready),
        .s_axi_wdata(wdata), .s_axi_wstrb(4'hF), .s_axi_wvalid(wvalid),
        .s_axi_wready(wready),
        .s_axi_bresp(bresp), .s_axi_bvalid(bvalid), .s_axi_bready(bready),
        .s_axi_araddr(araddr), .s_axi_arprot(3'd0), .s_axi_arvalid(arvalid),
        .s_axi_arready(arready),
        .s_axi_rdata(rdata), .s_axi_rresp(rresp), .s_axi_rvalid(rvalid),
        .s_axi_rready(rready),
        .cfg_sck(cfg_sck), .cfg_cs_n(cfg_cs_n), .cfg_mosi(cfg_mosi), .cfg_miso(cfg_miso),
        .dac_sck(dac_sck), .dac_cs_n(dac_cs_n),
        .dac_sdio0(dac_sdio0), .dac_sdio1(dac_sdio1),
        .dac_sdio2(dac_sdio2), .dac_sdio3(dac_sdio3)
    );

    // =========================================================================
    task axi_wr(input [13:0] a, input [31:0] d);
    begin
        @(posedge aclk);
        awaddr <= a; wdata <= d; awvalid <= 1; wvalid <= 1;
        wait (awready && wready);
        @(posedge aclk);
        awvalid <= 0; wvalid <= 0;
        wait (bvalid);
        @(posedge aclk);
    end
    endtask

    reg [31:0] rd_val;
    task axi_rd(input [13:0] a);
    begin
        @(posedge aclk);
        araddr <= a; arvalid <= 1;
        wait (arready);
        @(posedge aclk);
        arvalid <= 0;
        wait (rvalid);
        rd_val = rdata;
        @(posedge aclk);
    end
    endtask

    // =========================================================================
    //  waveform written into the two buffers
    // =========================================================================
    //  ★ 2026-09-10 : 256 -> 1024. NPOINTS_MAX 와 같아야 한다.
    //    처음에 256 으로 잡았더니 500점 시험에서 wave_a[k] 가 배열 밖으로 나가
    //    0xxxxx 를 기대값으로 비교했다. TB 배열 크기는 파라미터 상한을 따라야 한다.
    reg [15:0] wave_a [0:1023];
    reg [15:0] wave_b [0:1023];
    integer i;
    initial begin
        for (i = 0; i < 1024; i = i + 1) begin
            wave_a[i] = 16'hA000 + i[15:0];      // A : 0xA000, 0xA001, ...
            wave_b[i] = 16'hB000 + i[15:0];      // B : 0xB000, 0xB001, ...
        end
    end

    // =========================================================================
    //  SPI slave monitor
    // =========================================================================
    reg          mon_en = 1'b1;
    reg [15:0]   sh = 0;
    integer      phase_bits = 0;
    reg          got_instr = 0;
    reg [7:0]    instr_rx = 0;
    integer      nsample = 0;
    //  ★ 512 -> 8192. 500점 × 6 처프이면 3000 샘플이 넘는다. 작으면 스왑
    //    확인 구간이 통째로 잘려 "no buffer-B sample seen" 이 난다.
    reg [15:0]   sample_rx [0:8191];
    integer      errors = 0;

    real         t_word = 0.0, t_prev = 0.0;
    integer      ngap = 0;
    real         gap_min = 0.0, gap_max = 0.0;
    real         t_rise = 0.0, per_min = 0.0, per_max = 0.0;
    integer      nper = 0;

    function automatic isclose(input real a, input real b);
        isclose = ((a - b) < 0.002) && ((b - a) < 0.002);
    endfunction

    always @(posedge dac_sck) if (mon_en && !dac_cs_n) begin
        case (got_instr ? LANES : LANES)
            4:       sh = {sh[11:0], sdio[3:0]};
            2:       sh = {sh[13:0], sdio[1:0]};
            default: sh = {sh[14:0], sdio[0]};
        endcase

        if (t_rise != 0.0) begin
            if (nper == 0) begin per_min = $realtime - t_rise; per_max = per_min; end
            else begin
                if (($realtime - t_rise) < per_min) per_min = $realtime - t_rise;
                if (($realtime - t_rise) > per_max) per_max = $realtime - t_rise;
            end
            nper = nper + 1;
        end
        t_rise = $realtime;

        if (phase_bits == 0 && got_instr) begin
            t_prev = t_word;
            t_word = $realtime;
            if (t_prev != 0.0) begin
                if (ngap == 0) begin gap_min = t_word - t_prev; gap_max = gap_min; end
                else begin
                    if ((t_word - t_prev) < gap_min) gap_min = t_word - t_prev;
                    if ((t_word - t_prev) > gap_max) gap_max = t_word - t_prev;
                end
                ngap = ngap + 1;
            end
        end
        phase_bits = phase_bits + LANES;

        if (!got_instr) begin
            if (phase_bits >= 8) begin
                instr_rx = sh[7:0]; got_instr = 1; phase_bits = 0; t_rise = 0.0;
                $display("[%0t] instruction byte = 0x%02X (must be 0x2A)", $time, instr_rx);
                if (instr_rx !== 8'h2A) begin
                    $display("  *** instruction byte mismatch"); errors = errors + 1;
                end
            end
        end else if (phase_bits == 16) begin
            if (nsample < 8192) sample_rx[nsample] = sh;
            nsample = nsample + 1;
            phase_bits = 0; t_rise = 0.0;
        end
    end

    always @(negedge dac_cs_n) if (mon_en) begin
        phase_bits = 0; got_instr = 0; sh = 0; t_rise = 0.0;
        $display("[%0t] CS low - frame start", $time);
    end

    // =========================================================================
    integer k, base;
    integer n_at_swap;
    initial begin
        $display("=================================================");
        $display(" dac_chirp_engine testbench");
        $display("   PERIOD=%0d SCK_DIV=%0d LANES=%0d NPOINTS=%0d", PERIOD, DIV, LANES, NPTS);
        $display("=================================================");

        repeat (10) @(posedge aclk);
        aresetn = 1;
        repeat (10) @(posedge aclk);

        // ---- ID ----
        axi_rd(14'h000);
        $display("  ID = 0x%08X (must be 0x44414333)", rd_val);
        if (rd_val !== 32'h44414333) begin $display("  *** ID mismatch"); errors = errors + 1; end

        // ---- fill both buffers over AXI-Lite ----
        for (k = 0; k < NPTS; k = k + 1) begin
            axi_wr(14'h1000 + k*4, {16'd0, wave_a[k]});
            axi_wr(14'h2000 + k*4, {16'd0, wave_b[k]});
        end
        $display("  wrote %0d points into buffer A and B", NPTS);

        // ---- configure ----
        axi_wr(14'h008, (LCODE << 16) | (32'h2A << 8) | DIV);   // CFG
        axi_wr(14'h00C, PERIOD);                                // PERIOD
        axi_wr(14'h018, NPTS);                                  // NPOINTS
        axi_wr(14'h004, 32'h4);                                 // CLR_STATUS
        axi_wr(14'h004, 32'h1);                                 // CHIRP_ON

        repeat (PERIOD * (NPTS*3 + 4)) @(posedge aclk);

        // ---- status ----
        axi_rd(14'h010);
        $display("");
        $display("  STATUS = 0x%08X  RUNNING=%0d OVERRUN=%0d CS_LOW=%0d STATE=%0d ACTIVE_BUF=%0d",
                 rd_val, rd_val[0], rd_val[2], rd_val[3], rd_val[6:4], rd_val[7]);
        if (rd_val[0] !== 1'b1) begin $display("  *** not running"); errors = errors + 1; end
        if (rd_val[2] !== 1'b0) begin $display("  *** OVERRUN"); errors = errors + 1; end
        if (rd_val[7] !== 1'b0) begin $display("  *** should still be on buffer A"); errors = errors + 1; end

        axi_rd(14'h01C);
        $display("  CHIRPCNT = %0d  (about %0d expected)", rd_val, 3);

        // ---- samples must repeat buffer A, wrapping at NPTS ----
        $display("");
        $display("---- buffer A playback ----");
        for (k = 0; k < NPTS*2 && k < nsample; k = k + 1) begin
            if (sample_rx[k] !== wave_a[k % NPTS]) begin
                $display("  *** sample[%0d] = 0x%04X, expected 0x%04X",
                         k, sample_rx[k], wave_a[k % NPTS]);
                errors = errors + 1;
            end
        end
        $display("  first %0d samples match buffer A and wrap at %0d", NPTS*2, NPTS);

        // ---- swap at a chirp boundary ----
        $display("");
        $display("---- swap to buffer B ----");
        n_at_swap = nsample;
        axi_wr(14'h004, 32'h9);              // CHIRP_ON | SWAP_REQ
        repeat (PERIOD * (NPTS*3)) @(posedge aclk);

        axi_rd(14'h010);
        $display("  STATUS = 0x%08X  ACTIVE_BUF=%0d SWAP_PENDING=%0d",
                 rd_val, rd_val[7], rd_val[8]);
        if (rd_val[7] !== 1'b1) begin
            $display("  *** did not switch to buffer B"); errors = errors + 1;
        end
        if (rd_val[8] !== 1'b0) begin
            $display("  *** SWAP_REQ was not cleared"); errors = errors + 1;
        end

        //  ★ the switch must land on a chirp boundary: find the first B sample
        //    and check its index is a multiple of NPTS since the swap request.
        base = -1;
        for (k = n_at_swap; k < nsample && k < 8192; k = k + 1) begin
            if (base < 0 && sample_rx[k][15:12] === 4'hB) base = k;
        end
        if (base < 0) begin
            $display("  *** no buffer-B sample seen"); errors = errors + 1;
        end else begin
            $display("  first B sample at index %0d, value 0x%04X", base, sample_rx[base]);
            if (sample_rx[base] !== wave_b[0]) begin
                $display("  *** swap happened mid-chirp - first B sample should be wave_b[0]");
                errors = errors + 1;
            end
            for (k = base; k < nsample && k < 8192; k = k + 1) begin
                if (sample_rx[k] !== wave_b[(k - base) % NPTS]) begin
                    $display("  *** after swap sample[%0d] = 0x%04X, expected 0x%04X",
                             k, sample_rx[k], wave_b[(k - base) % NPTS]);
                    errors = errors + 1;
                end
            end
            $display("  buffer B plays cleanly from its first point");
        end

        // ---- stop ----
        axi_wr(14'h004, 32'h0);
        repeat (200) @(posedge aclk);
        if (dac_cs_n !== 1'b1) begin $display("  *** CS not released"); errors = errors + 1; end

        // ---- passthrough ----
        mon_en = 1'b0;
        $display("");
        $display("---- config-SPI passthrough (chirp off) ----");
        cfg_cs_n = 0; cfg_sck = 1; cfg_mosi = 1;
        repeat (2) @(posedge aclk); #1;
        if (dac_cs_n !== 1'b0 || dac_sck !== 1'b1 || dac_sdio0 !== 1'b1) begin
            $display("  *** passthrough failed: cs_n=%b sck=%b sdio0=%b",
                     dac_cs_n, dac_sck, dac_sdio0);
            errors = errors + 1;
        end
        slave_sdio1 = 1'b1; #1;
        if (cfg_miso !== 1'b1) begin $display("  *** MISO passthrough failed"); errors = errors + 1; end
        slave_sdio1 = 1'bz;
        cfg_cs_n = 1; cfg_sck = 0; cfg_mosi = 0;
        $display("  passthrough OK");

        // ---- results ----
        $display("");
        $display("---- results ----");
        $display("  samples received      : %0d", nsample);
        $display("  word interval min/max : %0.3f / %0.3f ns   (expect %0.3f)",
                 gap_min, gap_max, PERIOD * CLKP);
        if (!isclose(gap_min, gap_max) || !isclose(gap_min, PERIOD * CLKP)) begin
            $display("  *** sample interval wrong"); errors = errors + 1;
        end
        $display("  SCK period min/max    : %0.3f / %0.3f ns   (expect %0.3f, n=%0d)",
                 per_min, per_max, 2.0 * DIV * CLKP, nper);
        if (!isclose(per_min, per_max) || !isclose(per_min, 2.0 * DIV * CLKP)) begin
            $display("  *** SCK period wrong"); errors = errors + 1;
        end

        $display("");
        if (errors == 0) $display("  ==== ALL PASS ====");
        else             $display("  ==== FAIL: %0d ====", errors);
        $finish;
    end

    initial begin
        #5_000_000;
        $display("*** TIMEOUT");
        $finish;
    end
endmodule
