`timescale 1ns / 1ps
// =============================================================================
// tb_dac_stream_spi.v — dac_stream_spi 테스트벤치 (Vivado xsim 용)
// Generated by Claude Code, 2026-09-09
//
//  [왜 이 파일이 있나]
//  이 RTL 은 Vivado 도 iverilog 도 없는 Orin 에서 작성됐다. 합성 전에 회사
//  노트북에서 이걸 먼저 돌려서 아래 네 가지를 확인할 것.
//
//    1. 샘플 간격이 정확히 PERIOD 클럭인가          (처프 주기의 근거)
//    2. 샘플당 SCK 상승에지가 정확히 16개인가        (비트 누락/중복 없음)
//    3. 슬레이브가 받은 16비트가 보낸 코드와 같은가  (MSB 우선, mode 0)
//    4. 명령 바이트가 0x2A 로 한 번만 나가는가       (스트리밍 모드 전제)
//
//  [돌리는 법]  회사 노트북, 저장소 루트에서
//      vivado -mode batch -source tcl/run_sim.tcl
//  또는 GUI 프로젝트에서 sim/tb_dac_stream_spi.v 를 시뮬레이션 최상위로.
//
//  ※ AXI4-Lite 는 최소한의 쓰기 태스크만 흉내 낸다. 프로토콜 준수 검사가
//    아니라 FSM 동작 확인이 목적이다.
// =============================================================================

//  ★ 2026-09-09 : PERIOD / SCK_DIV 를 파라미터로 뺐다. 브링업 사다리 세 단을
//    한 파일로 돌리기 위해서다.  iverilog 예:
//      iverilog -Ptb_dac_stream_spi.PERIOD=200 -Ptb_dac_stream_spi.DIV=6 ...
module tb_dac_stream_spi #(
    parameter integer PERIOD = 40,      // aclk/샘플
    parameter integer DIV    = 1,       // SCK 반주기 [aclk]
    parameter integer LANES  = 1,       // 데이터 위상 선 수 : 1 / 2 / 4
    parameter integer IX1    = 0,       // 1 이면 명령 위상만 1선
    //  ★ FSM 클럭 주기 [ns]. 기본 10.0 = 100 MHz (= PS7 FCLK_CLK0).
    //    비동기 FIFO 를 끼우고 clk_wiz 로 SPI 도메인을 따로 올리는 경우를
    //    미리 확인하려고 파라미터로 뺐다. 7.576 = 132 MHz -> SCK 66 MHz(DAC 상한).
    parameter real    CLKP   = 10.0
);
    localparam integer ILANES = IX1 ? 1 : LANES;
    localparam [1:0]   LCODE  = (LANES == 4) ? 2'b10 : (LANES == 2) ? 2'b01 : 2'b00;

    reg aclk = 0, aresetn = 0;
    always #(CLKP/2.0) aclk = ~aclk;

    // ---------------- AXI4-Lite ----------------
    reg  [11:0] awaddr = 0;  reg awvalid = 0;  wire awready;
    reg  [31:0] wdata  = 0;  reg wvalid  = 0;  wire wready;
    wire [1:0]  bresp;       wire bvalid;      reg bready = 1;
    reg  [11:0] araddr = 0;  reg arvalid = 0;  wire arready;
    wire [31:0] rdata;       wire rvalid;      reg rready = 1;
    wire [1:0]  rresp;

    // ---------------- AXI4-Stream ----------------
    reg  [31:0] tdata = 0;   reg tvalid = 0;   wire tready;

    // ---------------- 핀 ----------------
    wire dac_sck, dac_cs_n, dac_sdio0, dac_sdio2, dac_sdio3;
    wire dac_sdio1;                     // inout — dual/quad 에서만 DUT 가 구동
    reg  slave_sdio1 = 1'bz;            // classic 에서 DAC 가 SDO 를 미는 것을 흉내
    assign dac_sdio1 = slave_sdio1;

    //  DUT 도 TB 도 안 밀 때 z 가 퍼지지 않게 약한 풀다운
    pulldown pd_sdio1(dac_sdio1);

    //  현재 프레임에서 유효한 선들 (모니터가 쓴다)
    wire [3:0] sdio = {dac_sdio3, dac_sdio2, dac_sdio1, dac_sdio0};

    // ---------------- 설정용 SPI (통과 경로 확인용) ----------------
    reg  cfg_sck = 0, cfg_cs_n = 1, cfg_mosi = 0;
    wire cfg_miso;

    dac_stream_spi #(.C_S_AXI_ADDR_WIDTH(12)) dut (
        .aclk(aclk), .aresetn(aresetn),
        .s_axi_awaddr(awaddr), .s_axi_awprot(3'd0), .s_axi_awvalid(awvalid),
        .s_axi_awready(awready),
        .s_axi_wdata(wdata), .s_axi_wstrb(4'hF), .s_axi_wvalid(wvalid),
        .s_axi_wready(wready),
        .s_axi_bresp(bresp), .s_axi_bvalid(bvalid), .s_axi_bready(bready),
        .s_axi_araddr(araddr), .s_axi_arprot(3'd0), .s_axi_arvalid(arvalid),
        .s_axi_arready(arready),
        .s_axi_rdata(rdata), .s_axi_rresp(rresp), .s_axi_rvalid(rvalid),
        .s_axi_rready(rready),
        .s_axis_tdata(tdata), .s_axis_tkeep(4'hF), .s_axis_tlast(1'b0),
        .s_axis_tvalid(tvalid), .s_axis_tready(tready),
        .cfg_sck(cfg_sck), .cfg_cs_n(cfg_cs_n), .cfg_mosi(cfg_mosi), .cfg_miso(cfg_miso),
        .dac_sck(dac_sck), .dac_cs_n(dac_cs_n),
        .dac_sdio0(dac_sdio0), .dac_sdio1(dac_sdio1),
        .dac_sdio2(dac_sdio2), .dac_sdio3(dac_sdio3)
    );

    // =========================================================================
    // AXI4-Lite 쓰기
    // =========================================================================
    task axi_wr(input [11:0] a, input [31:0] d);
    begin
        @(posedge aclk);
        awaddr <= a; wdata <= d; awvalid <= 1; wvalid <= 1;
        wait (awready && wready);
        @(posedge aclk);
        awvalid <= 0; wvalid <= 0;
        wait (bvalid);
        @(posedge aclk);
    end
    endtask

    reg [31:0] rd_val;
    task axi_rd(input [11:0] a);
    begin
        @(posedge aclk);
        araddr <= a; arvalid <= 1;
        wait (arready);
        @(posedge aclk);
        arvalid <= 0;
        wait (rvalid);
        rd_val = rdata;
        @(posedge aclk);
    end
    endtask

    // =========================================================================
    // 스트림 소스 — 삼각파 흉내 (2점/beat)
    // =========================================================================
    localparam N = 20;                 // 시뮬레이션은 짧게. 격자 검증이 목적
    reg [15:0] tbl [0:N-1];
    integer ti;
    initial begin
        for (ti = 0; ti < N; ti = ti + 1)
            tbl[ti] = 16'h1000 + ti[15:0] * 16'h0101;   // 눈에 띄는 패턴
    end

    reg     src_stall = 0;      // 1 이면 상류가 데이터를 안 준다
    integer si = 0;
    always @(posedge aclk) begin
        if (!aresetn) begin
            tvalid <= 0; si <= 0;
        end else if (src_stall) begin
            tvalid <= 0;
        end else begin
            if (!tvalid) begin
                tdata  <= {tbl[(si+1) % N], tbl[si % N]};   // [15:0] 이 먼저
                tvalid <= 1;
            end else if (tready) begin
                si     <= (si + 2) % N;
                tdata  <= {tbl[(si+3) % N], tbl[(si+2) % N]};
            end
        end
    end

    // =========================================================================
    // SPI 슬레이브 모니터 — AD3552R 흉내
    // =========================================================================
    //  CS 하강 후 첫 8비트 = 명령, 이후 16비트씩 = 샘플.
    integer      nrise = 0;
    reg [15:0]   sh = 0;
    integer      phase_bits = 0;      // 현재 워드에서 받은 비트 수
    reg          got_instr = 0;
    reg [7:0]    instr_rx = 0;
    integer      nsample = 0;
    reg [15:0]   sample_rx [0:255];
    integer      errors = 0;

    //  ★ 2026-09-09 — 모니터 on/off.
    //    [무엇이 문제였나] 맨 끝 "통과 시험" 에서 cfg_cs_n=0 과 cfg_sck=1 을 같은
    //    시각에 걸었다. 그러면 dac_cs_n 하강과 dac_sck 상승이 동시에 일어나는데,
    //    got_instr 를 지우는 negedge 블록과 워드 시작을 기록하는 posedge 블록의
    //    실행 순서가 시뮬레이터마다 다르다. xsim 은 posedge 를 먼저 돌려
    //    가짜 워드 시작을 기록했고 워드 간격 최대값이 2410 ns 로 튀었다.
    //    (iverilog 는 반대 순서라 안 드러났다 — 시뮬레이터를 하나만 믿으면 안 된다)
    //    [고친 방법] 재생 구간이 끝나면 모니터를 꺼 버린다. 경합 자체가 없어진다.
    reg          mon_en = 1'b1;

    // 샘플 시작 시각(=워드의 첫 상승에지) 간격
    //  ★ 단위/정밀도 주의 : $time 은 **시간 단위(1 ns)로 반올림된 정수**를 준다.
    //    CLKP=7.576 (132 MHz) 같은 값에서는 60.608 ns 가 60 또는 61 로 튀어
    //    "간격 불균일" 오검출이 났다. 실수 시간이 필요하므로 $realtime 을 쓴다.
    real         t_word_start = 0.0, t_prev_word = 0.0;
    integer      ngap = 0;
    real         gap_min = 0.0, gap_max = 0.0;

    //  ★ SCK 주기는 **한 워드 안에서만** 잰다.
    //    처음에는 "간격이 3·DIV·CLKP 이하면 워드 내부" 라는 시간 임계값으로 걸렀는데,
    //    명령(8비트)과 첫 데이터 워드 사이의 간극이 (2·DIV+2) 클럭이라 DIV=3 에서
    //    80 ns, DIV=6 에서 140 ns 가 되어 임계값을 통과해 버렸다. 그래서 SCK 주기
    //    최대값이 60/120 ns 대신 80/140 ns 로 잡혔다 — RTL 문제가 아니라 측정 문제였다.
    //    (그 간극 자체는 무해하다. CS 를 내린 채 SCK 가 잠깐 쉬는 것뿐이다.)
    real         t_last_rise = 0.0, sck_per_min = 0.0, sck_per_max = 0.0;
    integer      nsckper = 0;

    always @(posedge dac_sck) begin
        if (mon_en && !dac_cs_n) begin
            nrise = nrise + 1;
            //  ★ 상위 IO 가 상위 비트 — quad 첫 클럭은 SDIO3=bit15 … SDIO0=bit12
            case (got_instr ? LANES : ILANES)
                4:       sh = {sh[11:0], sdio[3:0]};
                2:       sh = {sh[13:0], sdio[1:0]};
                default: sh = {sh[14:0], sdio[0]};
            endcase

            // ---- 워드 내부 SCK 주기 ----
            if (t_last_rise != 0.0) begin
                if (nsckper == 0) begin
                    sck_per_min = $realtime - t_last_rise;
                    sck_per_max = sck_per_min;
                end else begin
                    if (($realtime - t_last_rise) < sck_per_min) sck_per_min = $realtime - t_last_rise;
                    if (($realtime - t_last_rise) > sck_per_max) sck_per_max = $realtime - t_last_rise;
                end
                nsckper = nsckper + 1;
            end
            t_last_rise = $realtime;
            if (phase_bits == 0 && got_instr) begin
                t_prev_word  = t_word_start;
                t_word_start = $realtime;
                if (t_prev_word != 0.0) begin
                    if (ngap == 0) begin
                        gap_min = t_word_start - t_prev_word;
                        gap_max = gap_min;
                    end else begin
                        if ((t_word_start - t_prev_word) < gap_min) gap_min = t_word_start - t_prev_word;
                        if ((t_word_start - t_prev_word) > gap_max) gap_max = t_word_start - t_prev_word;
                    end
                    ngap = ngap + 1;
                end
            end
            phase_bits = phase_bits + (got_instr ? LANES : ILANES);

            if (!got_instr) begin
                if (phase_bits == 8) begin
                    instr_rx   = sh[7:0];
                    got_instr  = 1;
                    phase_bits = 0;
                    t_last_rise = 0.0;      // 경계 — 다음 상승은 새 워드의 첫 비트
                    $display("[%0t] instruction byte = 0x%02X (must be 0x2A)", $time, instr_rx);
                    if (instr_rx !== 8'h2A) begin
                        $display("  *** instruction byte mismatch");
                        errors = errors + 1;
                    end
                end
            end else if (phase_bits == 16) begin
                if (nsample < 256) sample_rx[nsample] = sh;
                nsample    = nsample + 1;
                phase_bits = 0;
                t_last_rise = 0.0;          // 경계
            end
        end
    end

    always @(negedge dac_cs_n) if (mon_en) begin
        nrise = 0; phase_bits = 0; got_instr = 0; sh = 0;
        t_cs_fall = $realtime; t2_done = 0; t_last_rise = 0.0;
        $display("[%0t] CS low - frame start", $time);
    end

    always @(posedge dac_sck) if (mon_en && !dac_cs_n && !t2_done) begin
        t2_meas = $realtime - t_cs_fall;
        t2_done = 1;
    end

    // ---- CS 하강 -> 첫 SCK 상승 (t2, 최소 5 ns) ----
    real t_cs_fall = 0.0, t2_meas = 0.0;
    reg  t2_done = 0;

    // =========================================================================
    // 시나리오
    // =========================================================================
    //  실수 시간 비교용 — 시뮬레이터 정밀도 1 ps 이므로 0.002 ns 면 충분하다.
    //  (== 로 비교하면 8 × 7.576 = 60.608000000000004 vs 측정 60.608 로 어긋난다)
    function automatic isclose(input real a, input real b);
        isclose = ((a - b) < 0.002) && ((b - a) < 0.002);
    endfunction

    integer k;
    integer nsample_at_stall;
    reg [15:0] held;
    real t2_play;
    initial begin
        $display("=================================================");
        $display(" dac_stream_spi testbench");
        $display("   aclk %0.2f MHz, PERIOD=%0d, SCK_DIV=%0d, LANES=%0d, ILANES=%0d",
                 1000.0 / CLKP, PERIOD, DIV, LANES, ILANES);
        $display("   SCK %0.2f MHz,  sample rate %0.3f MSPS",
                 1000.0 / (2.0 * DIV * CLKP), 1000.0 / (PERIOD * CLKP));
        $display("   one sample = %0d SCK = %0d aclk   (grid %0d)",
                 16 / LANES, (32 / LANES) * DIV, PERIOD);
        $display("=================================================");

        repeat (10) @(posedge aclk);
        aresetn = 1;
        repeat (10) @(posedge aclk);

        axi_wr(12'h008, (IX1 << 18) | (LCODE << 16) | (32'h2A << 8) | DIV);  // CFG
        axi_wr(12'h00C, PERIOD);                   // PERIOD
        axi_wr(12'h004, 32'h2);                    // CLR_STATUS
        axi_wr(12'h004, 32'h1);                    // EN

        // 샘플 40개 나올 만큼
        repeat (PERIOD * 45) @(posedge aclk);

        t2_play = t2_meas;      // 통과 시험이 덮어쓰기 전에 붙잡는다

        // ---- STATUS / SAMPCNT 를 AXI 로 읽어 본다 ----
        axi_rd(12'h010);
        $display("  STATUS  = 0x%08X  (RUNNING=%0d UNDERRUN=%0d OVERRUN=%0d CS_LOW=%0d)",
                 rd_val, rd_val[0], rd_val[1], rd_val[2], rd_val[3]);
        if (rd_val[0] !== 1'b1) begin $display("  *** RUNNING is 0"); errors = errors + 1; end
        if (rd_val[1] !== 1'b0) begin $display("  *** UNDERRUN asserted"); errors = errors + 1; end
        if (rd_val[2] !== 1'b0) begin $display("  *** OVERRUN asserted"); errors = errors + 1; end
        if (rd_val[3] !== 1'b1) begin $display("  *** CS_LOW is 0"); errors = errors + 1; end

        axi_rd(12'h014);
        $display("  SAMPCNT = %0d  (slave received %0d; must be within +-1)", rd_val, nsample);
        if (rd_val < nsample || rd_val > nsample + 1) begin
            $display("  *** SAMPCNT mismatch"); errors = errors + 1;
        end

        axi_rd(12'h000);
        $display("  ID      = 0x%08X  (must be 0x44414333)", rd_val);
        if (rd_val !== 32'h44414333) begin $display("  *** ID mismatch"); errors = errors + 1; end

        // =====================================================================
        // 언더런 시험 — 상류를 굶기면 UNDERRUN 이 서고 직전 값이 반복돼야 한다
        // =====================================================================
        $display("");
        $display("---- underrun test ----");
        src_stall = 1;
        //  ★ FSM 은 beat 하나(샘플 2개)를 선인출해 둔다. 굶기 시작한 순간에도
        //    그 2개는 정당한 데이터라 반복값이 아니다. 3 샘플분 흘려보낸 뒤부터
        //    비교한다.
        repeat (PERIOD * 3) @(posedge aclk);
        nsample_at_stall = nsample;
        repeat (PERIOD * 6) @(posedge aclk);
        axi_rd(12'h010);
        $display("  after starving, STATUS = 0x%08X  (UNDERRUN=%0d, must be 1)", rd_val, rd_val[1]);
        if (rd_val[1] !== 1'b1) begin
            $display("  *** starved but UNDERRUN did not assert"); errors = errors + 1;
        end
        // 그 뒤로 나간 샘플은 전부 같은 값(직전 값 유지)이어야 한다
        held = sample_rx[nsample_at_stall - 1];
        for (k = nsample_at_stall; k < nsample && k < 256; k = k + 1) begin
            if (sample_rx[k] !== held) begin
                $display("  *** during underrun sample[%0d]=0x%04X differs from held 0x%04X",
                         k, sample_rx[k], held);
                errors = errors + 1;
            end
        end
        $display("  %0d samples during underrun all held 0x%04X  (output voltage steady)",
                 nsample - nsample_at_stall, held);
        src_stall = 0;
        repeat (PERIOD * 3) @(posedge aclk);

        axi_wr(12'h004, 32'h2);                    // CLR_STATUS
        axi_rd(12'h010);
        $display("  after CLR_STATUS, STATUS = 0x%08X  (UNDERRUN=%0d, must be 0)", rd_val, rd_val[1]);
        if (rd_val[1] !== 1'b0) begin
            $display("  *** sticky bit not cleared"); errors = errors + 1;
        end

        axi_wr(12'h004, 32'h0);                    // 정지
        repeat (200) @(posedge aclk);

        // =====================================================================
        // 통과 경로 시험 — EN=0 이면 cfg_* 가 핀으로 그대로 나가야 한다
        // =====================================================================
        $display("");
        mon_en = 1'b0;          // ★ 여기부터는 SPI 모니터를 끈다 (위 주석 참조)
        $display("---- config-SPI passthrough test (EN=0) ----");
        //  ★ 2026-09-09 — 통과 경로도 이제 출력 플립플롭을 한 번 거친다
        //    (IOB packing 을 위해 출력단을 등록했다). 따라서 즉시 반영되지 않고
        //    aclk 한 에지가 걸린다. 여유 있게 두 에지를 기다린다.
        cfg_cs_n = 0; cfg_sck = 1; cfg_mosi = 1;
        repeat (2) @(posedge aclk); #1;
        if (dac_cs_n !== 1'b0 || dac_sck !== 1'b1 || dac_sdio0 !== 1'b1) begin
            $display("  *** passthrough failed: cs_n=%b sck=%b sdio0=%b (want 0/1/1)",
                     dac_cs_n, dac_sck, dac_sdio0);
            errors = errors + 1;
        end
        cfg_cs_n = 1; cfg_sck = 0; cfg_mosi = 0;
        repeat (2) @(posedge aclk); #1;
        if (dac_cs_n !== 1'b1 || dac_sck !== 1'b0 || dac_sdio0 !== 1'b0) begin
            $display("  *** passthrough failed (inverse state)"); errors = errors + 1;
        end

        //  ★ classic 읽기 경로 : EN=0 이면 sdio1 을 DUT 가 놓아 주어야 하고
        //    (DAC 의 SDO 와 맞붙으면 안 된다) cfg_miso 로 그대로 들어와야 한다.
        //  MISO 는 등록하지 않았다 (조합 통과). 대기가 필요 없다.
        slave_sdio1 = 1'b1;  #1;
        if (cfg_miso !== 1'b1) begin
            $display("  *** MISO passthrough failed (drove 1, cfg_miso=%b)", cfg_miso);
            errors = errors + 1;
        end
        slave_sdio1 = 1'b0;  #1;
        if (cfg_miso !== 1'b0) begin
            $display("  *** MISO passthrough failed (drove 0, cfg_miso=%b)", cfg_miso);
            errors = errors + 1;
        end
        slave_sdio1 = 1'bz;
        $display("  cfg_sck/cs_n/mosi passthrough OK,  sdio1 released so MISO OK");

        $display("");
        $display("---- results ----");
        $display("  samples received   : %0d", nsample);
        $display("  word interval min/max : %0.3f / %0.3f ns   (expect %0.3f)",
                 gap_min, gap_max, PERIOD * CLKP);
        if (!isclose(gap_min, gap_max)) begin
            $display("  *** sample interval is not uniform");
            errors = errors + 1;
        end
        if (!isclose(gap_min, PERIOD * CLKP)) begin
            $display("  *** sample interval differs from PERIOD");
            errors = errors + 1;
        end

        for (k = 0; k < 8 && k < nsample; k = k + 1) begin
            $display("  sample[%0d] = 0x%04X   (expect 0x%04X)", k, sample_rx[k], tbl[k % N]);
            if (sample_rx[k] !== tbl[k % N]) begin
                $display("      *** mismatch");
                errors = errors + 1;
            end
        end

        $display("  SCK period min/max : %0.3f / %0.3f ns   (expect %0.3f, n=%0d)",
                 sck_per_min, sck_per_max, 2 * DIV * CLKP, nsckper);
        if (!isclose(sck_per_min, sck_per_max) || !isclose(sck_per_min, 2.0 * DIV * CLKP)) begin
            $display("  *** SCK period does not match SCK_DIV");
            errors = errors + 1;
        end
        //  ★ 단위 주의 : `timescale 1ns/1ps 이므로 $time 의 **값**은 ns 단위인데
        //    %0t 는 정밀도(ps)로 찍는다. 90 ns 가 "90000" 으로 보인다.
        //    비교 상수는 반드시 ns 로 쓸 것 — 5000 으로 쓰면 90 ns 가 위반으로 잡힌다.
        $display("  t2 (CS fall -> 1st SCK rise) : %0.3f ns   (AD3552R min 5 ns)", t2_play);
        if (t2_play < 5.0) begin
            $display("  *** t2 violation");
            errors = errors + 1;
        end

        $display("");
        if (errors == 0) $display("  ==== ALL PASS ====");
        else             $display("  ==== FAIL: %0d ====", errors);
        $finish;
    end

    initial begin
        #2_000_000;
        $display("*** TIMEOUT");
        $finish;
    end

endmodule
