`timescale 1ns / 1ps
// =============================================================================
// tb_m0_gen.v  —  Mode 0 내부 루프백 히트 생성기 시험
// Generated by Claude Code, 2026-09-16
//
//  [무엇을 보나]
//    tdc_test_top 안의 히트 생성기(m0_hit)가 설정한 주기대로 히트를 만드는지 본다.
//    코어는 히트의 하강 에지에서 측정하므로(tdc_fmcw_core_co.v:267), 하강 에지 사이의
//    클럭 수가 곧 주기여야 한다. 앱(키 3)이 쓰는 주기 50 / 80 / 140 / 230 을 그대로 시험한다.
//    함께 보는 것 : HIT_SRC 가 10(DPS)이 아니면 멈추는가, 주기가 8 미만이면 멈추는가,
//    그리고 먹스가 RO / EXT 를 고를 때 DPS 펄스가 새어나가지 않는가.
//
//  [어떻게 관측하나]
//    먹스 출력인 dut.tdc_hit_in 을 계층 참조로 본다. 이 신호가 지연선 입구(CYINIT)로 간다.
//    sim/elab_stubs.v 의 LUT4/LUT5 스텁이 INIT 대로 동작하므로 먹스 논리까지 함께 시험된다.
//
//  [스텁이라 시험되지 않는 것]
//    clk_wiz_0 스텁은 입력 클럭을 그대로 내보낸다. 즉 clk_200_fixed 와 clk_200_shifted 가
//    같은 위상이다. **위상 시프트가 히트를 실제로 옮기는지는 여기서 확인되지 않는다** —
//    그것은 보드에서 키 3 으로 본다. 여기서 보는 것은 주기와 먹스 논리다.
//
//  ★ 화면 출력은 ASCII 다 (sim/tb_tdc_calib.v 와 같은 이유).
// =============================================================================
module tb_m0_gen;

    reg clk = 0;
    always #2.5 clk = ~clk;          // 200 MHz — 스텁 clk_wiz 가 그대로 넘긴다

    reg  [1:0]  hit_src = 2'b00;
    reg  [15:0] period  = 16'd0;
    reg         ext_hit = 1'b0;

    tdc_test_top #(.OPERATION_MODE(2), .CARRY4_STAGES(96)) dut (
        .clk_125(clk), .rst_n(1'b0), .btn_shift(1'b0), .ext_hit_in(ext_hit), .led(),
        .o_tdc_clk(), .o_locked(), .o_dna(), .o_dna_valid(), .o_phase_busy(),
        .o_meas_strobe(), .o_ro_cnt(), .o_die_temp(), .o_phase_cur(),
        .i_phase_tgt(9'd0), .i_histo_clr(1'b0),
        .i_ctrl_start(1'b0), .i_ctrl_stop(1'b0), .i_ctrl_hit_src(hit_src), .i_ctrl_cap_fmt(1'b0),
        .i_target_hits(32'd0), .i_settle_n(32'd0),
        .i_danger_lo(9'd40), .i_danger_hi(9'd220),
        .i_m0_period(period),
        .o_busy(), .o_done(), .o_state(), .o_hit_cnt(), .o_drop_cnt(),
        .o_ro_start(), .o_ro_end(), .o_temp_start(), .o_temp_end(), .o_snap_tgl(),
        .i_axi_clk(clk), .i_histo_addr(9'd0), .o_histo_data(),
        .i_cap_n(13'd0), .o_cap_cnt(), .i_cap_addr(12'd0), .i_cap_hi(1'b0), .o_cap_data(),
        .i_cal_we(1'b0), .i_cal_addr(9'd0), .i_cal_din(13'd0), .o_cal_dout()
    );

    // ---------------------------------------------------------------- 관측
    integer cyc = 0;                 // 클럭 수
    integer last_fall = -1;          // 직전 하강 에지의 클럭 번호
    integer gap = 0;                 // 마지막으로 잰 간격
    integer n_gap = 0;               // 잰 간격 수
    integer bad = 0;                 // 기대와 다른 간격 수
    integer expect_gap = 0;          // 0 이면 검사 안 함
    reg     hit_d = 1'b0;
    integer high_cnt = 0;            // 관측 구간에서 hit 이 1 이었던 클럭 수

    always @(posedge clk) begin
        cyc  <= cyc + 1;
        hit_d <= dut.tdc_hit_in;
        if (dut.tdc_hit_in) high_cnt <= high_cnt + 1;
        if (hit_d && !dut.tdc_hit_in) begin          // 하강 에지 = 측정 시점
            if (last_fall >= 0) begin
                gap   = cyc - last_fall;
                n_gap = n_gap + 1;
                if (expect_gap != 0 && gap != expect_gap) begin
                    bad = bad + 1;
                    if (bad <= 3) $display("  mismatch : gap %0d cycles, expected %0d", gap, expect_gap);
                end
            end
            last_fall = cyc;
        end
    end

    integer errors = 0;
    task check(input ok, input [8*48-1:0] name);
    begin
        if (!ok) begin errors = errors + 1; $display("*** FAIL : %0s", name); end
    end
    endtask

    // 주기 p 를 걸고 n 개의 간격을 재서 전부 p 인지 본다
    task run_period(input integer p, input integer n);
    begin
        hit_src    = 2'b10;          // DPS
        period     = p[15:0];
        @(posedge clk);
        last_fall  = -1; n_gap = 0; bad = 0; expect_gap = 0;
        repeat (3 * p + 40) @(posedge clk);   // 파이프라인과 첫 주기를 버린다
        last_fall  = -1; n_gap = 0; bad = 0; expect_gap = p;
        while (n_gap < n) @(posedge clk);
        check(bad == 0 && n_gap == n, "period gap");
        $display("period %0d cycles (%0d ps) : %0d gaps measured, %0d wrong", p, p * 5000, n_gap, bad);
    end
    endtask

    // 히트가 전혀 나오지 않아야 하는 경우
    task run_quiet(input [1:0] src, input integer p, input [8*32-1:0] what);
    begin
        hit_src = src; period = p[15:0];
        repeat (200) @(posedge clk);
        high_cnt = 0; n_gap = 0; last_fall = -1; expect_gap = 0;
        repeat (4 * (p > 8 ? p : 8) + 200) @(posedge clk);
        check(high_cnt == 0 && n_gap == 0, what);
        $display("%0s : hit high for %0d cycles, %0d falling edges (want 0, 0)", what, high_cnt, n_gap);
    end
    endtask

    initial begin
        repeat (50) @(posedge clk);

        $display("== periods used by key 3 ==");
        run_period(50,  10);
        run_period(80,  10);
        run_period(140, 10);
        run_period(230, 10);

        $display("== generator must stay quiet ==");
        run_quiet(2'b00, 50, "src=00 (off)");
        run_quiet(2'b01, 50, "src=01 (ring oscillator)");
        run_quiet(2'b11, 50, "src=11 (external)");
        run_quiet(2'b10,  4, "src=10 but period 4 (< 8)");

        $display("== back to a valid setting ==");
        run_period(50, 5);

        $display("==== RESULT : errors = %0d ====", errors);
        if (errors == 0) $display("ALL PASS");
        $finish;
    end

    initial begin #5_000_000; $display("*** TIMEOUT"); $finish; end
endmodule
