`timescale 1ns / 1ps
// =============================================================================
// tb_tdc_calib.v  —  4단계(교정표 RAM) 회귀 시험
// Generated by Claude Code, 2026-09-15
//
//  DUT : tdc_axi_regs + tdc_timestamp_calc (안에 tdc_calib_ram)
//  확인 :
//    T0 ID / BUILD (맵 버전 7, 384탭)
//    T1 초기값 = 선형 램프 round(i*5000/384), 0.5 는 짝수 쪽 (512칸 되읽기)
//    T2 무작위 32비트 쓰기 -> 하위 13비트만 남는지 (512칸)
//    T3 주소 겹침 : 0x2008 / 0x1008 에 써도 CTRL(0x08) 불변, DANGER 는 여전히 쓰임
//    T4 히스토그램(0x1000) / 캡처(0x8000) 읽기 먹스 회귀
//    T5 시퀀서 BUSY 중 교정표 쓰기 무시
//    T6 쓰기와 읽기를 같은 순간에 요청 (200회, 같은 칸 포함)
//    T7 timestamp_ps = coarse*5000 - 교정표[fine] — fine/coarse 를 매 사이클 바꿔
//       RAM 읽기 지연이 1클럭만 어긋나도 잡는다
//
//  ★ 화면 출력은 ASCII 다 (DAC 저장소 sim/run_iverilog.sh 와 같은 이유 : Windows 의
//    Vivado Tcl Console 이 UTF-8 한글을 CP949 로 읽어 깨뜨린다).
//  ★ -DCAL_LAT3_NEGATIVE_TEST 로 컴파일하면 tdc_calib_ram 이 일부러 지연 3 이 된다.
//    그때 T7 이 실패해야 이 테스트가 지연 어긋남을 잡는다는 증거가 된다.
// =============================================================================
module tb_tdc_calib;
    reg aclk = 0, tclk = 0;
    always #5 aclk = ~aclk;                              // 100 MHz (FCLK)
    initial begin #1.3; forever #2.5 tclk = ~tclk; end   // 200 MHz, 위상 1.3 ns 어긋남
    reg aresetn = 0, trst_n = 0;

    reg  [15:0] awaddr = 0, araddr = 0;
    reg         awvalid = 0, wvalid = 0, bready = 0, arvalid = 0, rready = 0;
    reg  [31:0] wdata = 0;
    reg  [3:0]  wstrb = 0;
    wire        awready, wready, bvalid, arready, rvalid;
    wire [1:0]  bresp, rresp;
    wire [31:0] rdata;

    reg         stat_busy = 0;
    wire [8:0]  histo_addr;
    wire [11:0] cap_addr;
    wire        cap_hi;
    wire        cal_we;
    wire [8:0]  cal_addr;
    wire [12:0] cal_din, cal_dout;

    tdc_axi_regs #(.C_S_AXI_ADDR_WIDTH(16), .CHAIN_STAGES(96)) dut_regs (
        .s_axi_aclk(aclk), .s_axi_aresetn(aresetn),
        .s_axi_awaddr(awaddr), .s_axi_awvalid(awvalid), .s_axi_awready(awready),
        .s_axi_wdata(wdata), .s_axi_wstrb(wstrb), .s_axi_wvalid(wvalid), .s_axi_wready(wready),
        .s_axi_bresp(bresp), .s_axi_bvalid(bvalid), .s_axi_bready(bready),
        .s_axi_araddr(araddr), .s_axi_arvalid(arvalid), .s_axi_arready(arready),
        .s_axi_rdata(rdata), .s_axi_rresp(rresp), .s_axi_rvalid(rvalid), .s_axi_rready(rready),
        .tdc_clk(tclk), .tdc_rst_n(trst_n),
        .stat_mmcm_locked(1'b1), .stat_dna(31'h0), .stat_dna_valid(1'b0), .stat_busy(stat_busy),
        .stat_done(1'b0), .stat_phase_busy(1'b0), .stat_meas_strobe(1'b0), .stat_ro_cnt(32'd0),
        .stat_die_temp(16'd0), .stat_phase_cur(9'd0),
        .stat_snap_tgl(1'b0), .stat_hit_cnt(32'd0), .stat_drop_cnt(32'd0),
        .stat_ro_start(32'd0), .stat_ro_end(32'd0), .stat_temp_start(16'd0), .stat_temp_end(16'd0),
        .stat_state(3'd0),
        // 히스토그램/캡처 BRAM 대신 주소를 그대로 돌려주는 가짜 데이터 (읽기 먹스만 본다)
        .histo_addr(histo_addr), .histo_data(32'hA500_0000 | {23'd0, histo_addr}),
        .cap_addr(cap_addr), .cap_hi(cap_hi), .cap_data(32'hC000_0000 | {19'd0, cap_hi, cap_addr}),
        .stat_cap_cnt(13'd0),
        .cal_we(cal_we), .cal_addr(cal_addr), .cal_din(cal_din), .cal_data(cal_dout),
        .ctrl_hit_src(), .ctrl_start(), .ctrl_stop(), .ctrl_histo_clr(), .ctrl_tdc_rst(),
        .ctrl_cap_fmt(), .ctrl_phase_tgt(), .ctrl_target_hits(), .ctrl_settle_n(),
        .ctrl_cap_n(), .ctrl_danger_lo(), .ctrl_danger_hi(), .ctrl_m0_period()
    );

    reg  [31:0] ts_coarse = 0;
    reg  [8:0]  ts_fine   = 0;
    reg         ts_valid  = 0;
    wire [63:0] ts_ps;
    wire        ts_v;
    wire [8:0]  fine_o;
    wire [31:0] coarse_o;

    tdc_timestamp_calc dut_ts (
        .clk(tclk), .rst_n(trst_n),
        .ts_coarse(ts_coarse), .ts_fine_idx(ts_fine), .ts_valid(ts_valid),
        .cal_clk(aclk), .cal_we(cal_we), .cal_addr(cal_addr), .cal_din(cal_din), .cal_dout(cal_dout),
        .timestamp_ps(ts_ps), .timestamp_valid(ts_v), .fine_idx_out(fine_o), .coarse_out(coarse_o)
    );

    // ---------------------------------------------------------------- AXI 태스크
    task axi_write(input [15:0] a, input [31:0] d);
    begin
        @(negedge aclk); awaddr = a; wdata = d; wstrb = 4'hF; awvalid = 1; wvalid = 1; bready = 1;
        @(posedge aclk); while (!awready) @(posedge aclk);
        @(negedge aclk); awvalid = 0; wvalid = 0;
        while (!bvalid) @(negedge aclk);
        @(negedge aclk);
    end
    endtask

    task axi_read(input [15:0] a, output [31:0] d);
    begin
        @(negedge aclk); araddr = a; arvalid = 1; rready = 1;
        @(posedge aclk); while (!arready) @(posedge aclk);
        @(negedge aclk); arvalid = 0;
        while (!rvalid) @(negedge aclk);
        d = rdata;
        @(negedge aclk);
    end
    endtask

    integer errors = 0;
    task check(input ok, input [8*48-1:0] name);
    begin
        if (!ok) begin errors = errors + 1; $display("*** FAIL : %0s  (t=%0t)", name, $time); end
    end
    endtask

    reg [12:0] model [0:511];
    integer i, k, n_fail, a1, a2;
    reg [31:0] d, v, expv;

    task readback_all(input [8*16-1:0] tag);
    begin
        n_fail = 0;
        for (i = 0; i < 512; i = i + 1) begin
            axi_read(16'h2000 + i * 4, d);
            if (d !== {19'd0, model[i]}) begin
                n_fail = n_fail + 1;
                if (n_fail <= 3) $display("  %0s : cal[%0d] = %0d, expected %0d", tag, i, d, model[i]);
            end
        end
        check(n_fail == 0, tag);
        $display("%0s : 512-entry readback mismatches %0d", tag, n_fail);
    end
    endtask

    // ---------------------------------------------------------------- T7 : 타임스탬프 검사
    reg        run_ts = 0;
    integer    sent = 0, got = 0, ts_err = 0, qh = 0, qt = 0;
    reg [63:0] q_ts [0:1023];
    reg [8:0]  q_f  [0:1023];
    reg [31:0] q_c  [0:1023];

    // fine/coarse 는 히트가 아닐 때도 매 사이클 바꾼다 — 지연이 1클럭만 어긋나도 다른 칸이 읽힌다
    always @(negedge tclk) begin
        if (run_ts) begin
            ts_fine   <= $random;
            ts_coarse <= $random;
            ts_valid  <= (($random & 3) == 0);
        end else begin
            ts_valid  <= 1'b0;
        end
    end

    always @(posedge tclk) begin
        if (trst_n && ts_valid) begin
            q_ts[qt] = {32'd0, ts_coarse} * 64'd5000 - {51'd0, model[ts_fine]};
            q_f[qt]  = ts_fine;
            q_c[qt]  = ts_coarse;
            qt = (qt + 1) % 1024;
            sent = sent + 1;
        end
        if (trst_n && ts_v) begin
            if (qh == qt) begin
                ts_err = ts_err + 1;
            end else begin
                if (ts_ps !== q_ts[qh] || fine_o !== q_f[qh] || coarse_o !== q_c[qh]) begin
                    ts_err = ts_err + 1;
                    if (ts_err <= 3)
                        $display("  T7 mismatch : fine=%0d coarse=%0d  ts=%0d  expected=%0d",
                                 q_f[qh], q_c[qh], ts_ps, q_ts[qh]);
                end
                qh = (qh + 1) % 1024;
                got = got + 1;
            end
        end
    end

    // ---------------------------------------------------------------- 시나리오
    initial begin
        repeat (5) @(posedge aclk);
        aresetn = 1; trst_n = 1;
        repeat (5) @(posedge aclk);

        // T0
        axi_read(16'h0000, d); check(d == 32'h5444_4302, "T0 ID");
        axi_read(16'h0004, d); check(d[7:0] == 8'd8 && d[31:16] == 16'd384, "T0 BUILD (map ver 8, 384 taps)");
        $display("T0 : ID/BUILD (BUILD=0x%08h)", d);

        // T1 : 초기값 = 선형 램프 (0.5 는 짝수 쪽으로 — RTL 과 독립적으로 여기서 다시 계산)
        for (i = 0; i < 512; i = i + 1) begin
            k = ((i < 384) ? i : 383) * 5000;
            v = k / 384;
            if ((2 * (k % 384) > 384) || ((2 * (k % 384) == 384) && v[0])) v = v + 1;
            model[i] = v[12:0];
        end
        check(model[24] == 13'd312 && model[25] == 13'd326 && model[383] == 13'd4987, "T1 model self-check");
        readback_all("T1 init ramp");

        // T2 : 무작위 32비트 쓰기 (상위 19비트는 버려져야 함)
        for (i = 0; i < 512; i = i + 1) begin
            v = $random;
            model[i] = v[12:0];
            axi_write(16'h2000 + i * 4, v);
        end
        readback_all("T2 random w/r");

        // T3 : 주소 겹침 — 0x2008 / 0x1008 에 써도 CTRL(0x08) 이 바뀌면 안 된다
        axi_read(16'h0008, expv);
        axi_write(16'h2008, 32'hFFFF_1ABC); model[2] = 13'h1ABC;
        axi_read(16'h0008, d); check(d == expv, "T3 write 0x2008 must not touch CTRL");
        axi_read(16'h2008, d); check(d == 32'h0000_1ABC, "T3 cal[2] written");
        axi_write(16'h1008, 32'h0000_0055);
        axi_read(16'h0008, d); check(d == expv, "T3 write 0x1008 must not touch CTRL");
        axi_write(16'h0044, 32'h0120_0033);
        axi_read(16'h0044, d); check(d == 32'h0120_0033, "T3 DANGER register still writable");
        // ★ 2026-09-16 : 새 M0PER 레지스터 (0x48). 상위 16비트는 버려져야 한다.
        axi_write(16'h0048, 32'hFFFF_00E6);
        axi_read(16'h0048, d); check(d == 32'h0000_00E6, "T3 M0PER register write/read");
        $display("T3 : address aliasing checks done");

        // T4 : 기존 읽기 창 회귀
        axi_read(16'h1000 + 7 * 4, d);     check(d == 32'hA500_0007, "T4 histogram read mux");
        axi_read(16'h8000 + 5 * 8 + 4, d); check(d == 32'hC000_1005, "T4 capture read mux");
        $display("T4 : histogram/capture read mux checks done");

        // T5 : BUSY 중 쓰기 무시
        stat_busy = 1; repeat (4) @(posedge aclk);
        axi_write(16'h2000 + 5 * 4, 32'h0000_0555);
        axi_read(16'h2000 + 5 * 4, d); check(d == {19'd0, model[5]}, "T5 write ignored while BUSY");
        stat_busy = 0; repeat (4) @(posedge aclk);
        axi_write(16'h2000 + 5 * 4, 32'h0000_0555); model[5] = 13'h0555;
        axi_read(16'h2000 + 5 * 4, d); check(d == 32'h0000_0555, "T5 write accepted after BUSY");
        $display("T5 : BUSY gate checks done");

        // T6 : 쓰기와 읽기를 같은 순간에 요청 (200회, 10회에 1번은 같은 칸)
        n_fail = 0;
        for (k = 0; k < 200; k = k + 1) begin
            a1 = {$random} % 512;
            a2 = (k % 10 == 0) ? a1 : ({$random} % 512);
            v  = $random;
            expv = (a2 == a1) ? {19'd0, v[12:0]} : {19'd0, model[a2]};
            fork
                axi_write(16'h2000 + a1 * 4, v);
                axi_read (16'h2000 + a2 * 4, d);
            join
            model[a1] = v[12:0];
            if (d !== expv) begin
                n_fail = n_fail + 1;
                if (n_fail <= 3) $display("  T6 : k=%0d w[%0d] r[%0d] got %0d exp %0d", k, a1, a2, d, expv);
            end
        end
        check(n_fail == 0, "T6 concurrent read during write");
        $display("T6 : 200 concurrent write+read, mismatches %0d", n_fail);
        readback_all("T6 after");

        // T7 : 타임스탬프 파이프라인 (표는 T2~T6 의 무작위 값)
        run_ts = 1;
        repeat (40000) @(posedge tclk);
        run_ts = 0;
        repeat (20) @(posedge tclk);
        check(ts_err == 0 && sent == got && sent > 0, "T7 timestamp = coarse*5000 - cal[fine]");
        $display("T7 : hits in %0d, out %0d, mismatches %0d", sent, got, ts_err);

        $display("==== RESULT : errors = %0d ====", errors);
        if (errors == 0) $display("ALL PASS");
        $finish;
    end

    initial begin #20_000_000; $display("*** TIMEOUT"); $finish; end
endmodule
