/* Generated by Claude Code, 2026-09-06
 * =============================================================================
 * tdc_app.c  —  ZedBoard TDC 를 PS(ARM)에서 조종하는 베어메탈 프로그램
 *
 *  [무엇을 하나]
 *  Vitis 에서 이 파일 하나만 넣고 빌드해 돌리면, TDC 측정을 처음부터 끝까지 한다.
 *  결과는 UART(115200-8-N-1)로 나온다. 터미널을 열어 텍스트를 그대로 복사해
 *  CSV 로 저장하면 python/ 의 분석 스크립트에 바로 넣을 수 있다.
 *
 *  [Vitis 설정 — 두 가지만 확인]
 *   1) 링커 스크립트의 메모리 영역을 **ps7_ram_0 (OCM)** 으로 둘 것.
 *      이 프로젝트의 블록 디자인은 DDR 파라미터를 ZedBoard 에 맞춰 넣지 않았다.
 *      (보드 파일이 없어 배선 지연 값을 손으로 넣으면 틀리기 쉽다)
 *      OCM 은 256 KB 이고 이 프로그램은 전역 배열이 40 KB 남짓이라 충분하다.
 *   2) stdout 이 ps7_uart_1 인지 확인 (BSP 설정). ZedBoard 의 USB-UART 가 MIO 48/49 다.
 *
 *  [메뉴]  ★ 2026-09-16 개편 (사용자 지정)
 *  프로그램이 뜨면 UART 로 한 글자를 받아 동작한다. 터미널에서 키를 누르면 된다.
 *    i  신원/상태 읽기
 *    1  Mode 1 (링오실레이터 코드밀도) 측정 -> CSV + danger 임계값 + 교정표 쓰기
 *    2  교정표 RAM 쓰기/되읽기 시험
 *    3  Mode 0 교정 확인 — 내부 루프백 위상 전면 스윕 (★ 2026-09-16 : 범위·발수를 'e' 로 바꿈)
 *    4  Mode 2 캡처 (timestamp_ps) -> CSV
 *    5  교정 전/후 INL·DNL 평가 — ★ 2026-09-17 (키 1 필요, 독립 히스토그램을 새로 받는다)
 *    6  온도별 탭 변화 기록 — ★ 2026-09-17 (일정 간격으로 히스토그램을 반복해 받는다)
 *  평소 사용 : 1 (코드밀도 -> danger -> 교정표 RAM 기록) 다음 4.
 *    h  도움말
 *
 *  [★ 2026-09-17 저녁 : 메뉴를 둘로 줄였다 (사용자 지정) — 위 목록은 옛 메뉴다]
 *  무엇이 문제였나 : 항목끼리 독립이 아니었다. 예) 1 없이 4 를 하면 DANGER 와 교정표가 전원 인가
 *    값이라 timestamp 가 틀어진다. 또 4 를 뺀 나머지는 모두 "TDC 성능 평가" 라는 한 가지 일이었다.
 *  지금 :
 *    1  Mode 2 캡처 (timestamp_ps). 이번 실행에서 교정이 안 됐거나, 교정 뒤 다이 온도가
 *       RECAL_DT_CENTI 이상 변했으면 **교정(코드밀도 -> DANGER -> 교정표)을 먼저 자동으로** 한다.
 *    2  TDC cal/val 보고서. 아래를 차례로 돌고 UART 에 보고서를 찍는다.
 *         [0] 신원/상태   [1] 교정표 RAM 쓰기/되읽기 시험   [2] 교정 (코드밀도, DANGER, 교정표)
 *         [3] 독립 히스토그램으로 INL/DNL 교정 전/후   [4] 내부 루프백 위상 스윕 교정 전/후
 *         [5] 단계별 다이 온도   [S] 요약
 *       옛 키 6(온도별 기록)은 따로 두지 않는다 — 보고서가 온도와 창·탭 폭·교정표를 함께 찍으므로
 *       온도를 바꿔 가며 2 를 돌리면 그것이 온도별 기록이다. 보고서가 끝나면 RAM 에는 코드밀도
 *       교정표가 들어 있어 바로 1 을 써도 된다.
 *    h  도움말
 *
 *  [★ 2026-09-16 : 화면 출력은 전부 ASCII 영문 (사용자 지정)]
 *  UART 를 받는 터미널(PuTTY / Vivado / Vitis)이 한글 인코딩을 제각각 처리해 깨졌다.
 *  주석은 저장소 관례대로 한글을 유지하고, xil_printf 로 나가는 문자열만 영문으로 쓴다.
 *
 *  [★ 2026-09-16 : 부팅하면 먼저 교정한다 (사용자 지정)]
 *  전원을 넣거나 앱을 다시 올리면 Mode 1 을 200만 발 돌려 danger 임계값과 교정표를
 *  계산해 RAM 에 쓴 뒤 메뉴를 띄운다. 창(히트가 찍히는 탭 범위)은 빌드마다 옮겨가므로
 *  이 두 가지는 매 빌드 반드시 다시 맞춰야 한다. 부팅 때는 CSV 를 찍지 않는다(384줄).
 *
 *  [★ 2026-09-17 : 위 부팅 자동 교정을 삭제했다 (사용자 지정)]
 *  무엇이 문제였나 : 앱이 뜨자마자 교정표를 써 버려, 교정 전(선형 램프) 상태로 잴 기회가
 *    없었다. 교정 전/후 비교는 논문에 반드시 필요한 숫자인데 그것을 막고 있었다.
 *  지금 : 앱이 뜨면 아무것도 쓰지 않는다. FPGA 를 새로 구웠다면 교정표 RAM 은 선형 램프
 *    (tdc_calib_ram.v 초기값), DANGER 는 전원 인가 기본값 40/220 이다. 키 1 을 눌러야
 *    교정된다. RTL 수정은 필요 없었다.
 *  ⚠ 기본 DANGER 40/220 은 이 빌드의 창(2~319 -> 42/280)과 맞지 않는다. 키 1 없이 키 3/4 를
 *    돌리면 5000 ps 급 coarse 오류가 섞일 수 있다 — 교정 전 측정에 교정표 효과와 다른 오차가
 *    섞인다는 뜻이다. 키 3 이 기본값을 감지하면 경고를 찍는다.
 *    (★ 2026-09-17 저녁 : 메뉴 개편으로 이 경고는 없어졌다 — 캡처가 필요하면 교정을 먼저 한다)
 *
 *  [★ 2026-09-15 — 교정표를 PS 가 계산해 PL RAM 에 쓴다]
 *  예전에는 python/Making_COE_Mode_0.py 로 COE 를 만들어 ROM 으로 재빌드해야 했고, 재빌드는
 *  창(히트가 찍히는 탭 범위)을 옮겨 표를 만든 조건을 깨뜨렸다. 이제 '1' 이 히스토그램 ->
 *  danger 임계값 -> 교정표 계산·쓰기·되읽기를 한 번에 하고, Mode 2 의 timestamp_ps 가 그 표를 쓴다.
 *
 *  [★ 반드시 알아야 할 것 — 측정 창은 빌드마다 움직인다]
 *  히트가 찍히는 탭 범위(창)는 히트 경로 지연에 따라 통째로 미끄러진다.
 *  2026-09-05 에 HIT_SRC 먹스(LUT 하나)가 들어가자 창이 탭 2~321 에서 24~348 로
 *  옮겨갔고, 같은 RTL 을 재빌드해도 349 -> 348 로 1탭 달라졌다.
 *  danger 임계값은 그 창의 양 끝에 있어야 하므로, **빌드할 때마다 'd' 를 한 번
 *  돌려 다시 맞춰야 한다.** 안 맞으면 coarse 가 5000 ps 틀리는 일이 생기는데
 *  히스토그램으로는 보이지 않는다.
 * =============================================================================
 */
#include <stdio.h>
#include "xil_printf.h"
#include "xil_io.h"
#include "xparameters.h"
#include "xuartps_hw.h"
#include "sleep.h"
#include "xtime_l.h"     /* ★ 2026-09-17 : 키 6 경과 시간 */

/* ---------------------------------------------------------------- 레지스터 맵 */
/* 맵 버전 7 (★ 2026-09-15 : 6 -> 7, 교정표 창 0x2000 추가). BUILD 레지스터의 하위 8비트로 확인할 수 있다. */
#define TDC_BASE      0x43C00000u

#define R_ID          (TDC_BASE + 0x00u)  /* R   0x54444302                     */
#define R_BUILD       (TDC_BASE + 0x04u)  /* R   {탭수16, 단수8, 맵버전8}        */
#define R_CTRL        (TDC_BASE + 0x08u)  /* RW  아래 비트 정의 참조             */
#define R_STATUS      (TDC_BASE + 0x0Cu)  /* R   아래 비트 정의 참조             */
#define R_DNA         (TDC_BASE + 0x10u)  /* R   [31]valid + DNA[30:0]          */
#define R_ROCNT       (TDC_BASE + 0x14u)  /* R   10 ms 게이트당 RO 에지 수       */
#define R_TEMP        (TDC_BASE + 0x18u)  /* R   [15:0] XADC 온도 raw           */
#define R_PHASE       (TDC_BASE + 0x1Cu)  /* RW  쓰기=목표, 읽기[24:16]=현재     */
#define R_TARGET      (TDC_BASE + 0x20u)  /* RW  목표 히트 수 (0 = 무제한)       */
#define R_HITCNT      (TDC_BASE + 0x24u)  /* R   실제 누적된 히트 수             */
#define R_SETTLE      (TDC_BASE + 0x28u)  /* RW  RO 안정화 대기 클럭 수          */
#define R_ROSTA       (TDC_BASE + 0x2Cu)  /* R   측정 시작 시 RO 카운트          */
#define R_ROEND       (TDC_BASE + 0x30u)  /* R   측정 종료 시 RO 카운트          */
#define R_TEMPSE      (TDC_BASE + 0x34u)  /* R   {끝 온도[31:16], 시작[15:0]}    */
#define R_DROP        (TDC_BASE + 0x38u)  /* R   버려진 히트 수                  */
#define R_CAPN        (TDC_BASE + 0x3Cu)  /* RW  캡처할 히트 수 (1..4096)        */
#define R_CAPCNT      (TDC_BASE + 0x40u)  /* R   지금까지 모인 수                */
#define R_DANGER      (TDC_BASE + 0x44u)  /* RW  {hi[24:16], lo[8:0]}           */

#define R_HISTO(i)    (TDC_BASE + 0x1000u + (u32)(i) * 4u)          /* i=0..383  */
#define R_CAP_LO(i)   (TDC_BASE + 0x8000u + (u32)(i) * 8u)          /* i=0..4095 */
#define R_CAP_HI(i)   (TDC_BASE + 0x8000u + (u32)(i) * 8u + 4u)
/* ★ 2026-09-15 : 교정표 RAM (맵 버전 7). 13비트, i = 0..511.
 *   fine 번호는 384비트 popcount 라 0..384 가 나올 수 있어 RTL 이 512칸을 잡았다. */
#define R_CAL(i)      (TDC_BASE + 0x2000u + (u32)(i) * 4u)          /* i=0..511  */
#define CAL_DEPTH     512
#define CAL_MAP_VER   7u          /* 이 버전 이상이어야 교정표 창이 있다          */
/* ★ 2026-09-16 : Mode 0 확인용 히트 생성기 주기 [tdc_clk 클럭 수], 0 = 정지 (맵 버전 8) */
#define R_M0PER       (TDC_BASE + 0x48u)  /* RW  [15:0]                          */

/* CTRL 비트 */
#define C_SRC_OFF     0x0u        /* 히트 소스 : 꺼짐                            */
#define C_SRC_RO      0x1u        /*             링오실레이터 (Mode 1)           */
#define C_SRC_DPS     0x2u        /*             위상시프트 (Mode 0, 미구현)     */
#define C_SRC_EXT     0x3u        /*             외부 입력 (Mode 2)              */
#define C_START       (1u << 2)
#define C_STOP        (1u << 3)
#define C_HISTO_CLR   (1u << 4)
#define C_TDC_RST     (1u << 5)   /* ※ 아직 하드웨어에 연결 안 됨 (2026-09-06)   */
#define C_CAP_FMT     (1u << 6)   /* 0 = timestamp_ps, 1 = raw {coarse,fine}     */

/* STATUS 비트 */
#define S_MMCM_LOCKED (1u << 0)
#define S_DNA_VALID   (1u << 2)
#define S_BUSY        (1u << 3)
#define S_DONE        (1u << 4)
#define S_PHASE_BUSY  (1u << 5)
#define S_STATE_SHIFT 8
#define S_STATE_MASK  0x7u

#define NUM_TAPS      384
#define CAP_MAX       4096

/* ★ 2026-09-15 : 교정표를 만들 창(유효 구간) 고르기
 *   기본     : 양 끝에서 "히트 있는 탭 평균의 5 % 미만" 인 탭을 뺀다
 *              (python/Making_COE_Mode_0.py 의 EDGE_TRIM_FRAC = 0.05 와 같은 규칙).
 *   덮어쓰기 : WIN_LO_MANUAL / WIN_HI_MANUAL 을 0 이상으로 두면 그 탭으로 고정한다.
 *   왜 남기나 : 집 보드(2026-08-24)에서 자동 검출(298칸) INL rms 19.93 ps, 상한 293 수동 지정
 *     10.00 ps 였다. 참 경계는 위상 스윕(Mode 0)으로만 알 수 있는데 ZedBoard 의 Mode 0 은 아직
 *     정해지지 않았다. 알게 되면 여기 넣고 앱만 다시 빌드한다 (비트스트림 재빌드 불필요). */
/* ★ 2026-09-16 : '1' 키가 쓰는 히트 수. 한곳에서 고친다. (부팅 자동 교정은 2026-09-17 삭제) */
#define MODE1_HITS    2000000u

/* ★ 2026-09-16 : Mode 0 내부 루프백 확인 (키 3) — 사용자 지정 조건
 *   [신호] PL 의 히트 생성기가 clk_200_shifted 에서 사각파를 만든다. 코어는 히트의 하강
 *     에지에서 측정하므로(tdc_fmcw_core_co.v:267) 하강 에지 간격 = 주기 = 아는 시간이다.
 *     주기 단위는 tdc_clk 클럭 수다 : 50 클럭 = 50 x 5000 ps = 250 ns.
 *   [위상] MMCM 동적 위상 시프트로 히트 위상을 옮긴다. 한 스텝 = 17.857 ps, 280 스텝 = 5000 ps.
 *     위상을 안 옮기면 히트가 늘 같은 fine 번호에 떨어져 탭 하나만 시험하게 된다.
 *
 *  [★ 2026-09-16 오후 : 위상 네 점 -> 전면 스윕 (사용자 지정)]
 *   [무엇이 모자랐나] 오전 판은 위상 0/70/140/210 네 점뿐이었다. 네 점으로는 전달함수의
 *     기울기(1 스텝이 몇 ps 인가)만 알 수 있고, 교정표가 탭마다 얼마나 틀리는지(INL)는
 *     볼 수 없다. 2026-09-16 보고서 §10-1 이 "교정표 품질을 아는 유일한 길" 로 꼽은 항목이다.
 *   [무엇으로 바꿨나] 시작 위상 / 간격 / 점 개수 / 단계당 발수 / 쓸 주기 개수 / CSV 여부를
 *     실행 중에 정한다. 기본은 0 부터 4 스텝(= 71.4 ps) 간격으로 70 점 — 0..276 전 구간이다.
 *   [왜 앱 변수인가] 위상 스윕은 PL 이 아니라 **PS 의 for 문**이다 (phase_shifter.v:7-15,
 *     2026-09-04 에 280스텝 자동 스윕을 없애고 "목표 위상으로 이동"만 남겼다). PL 에는 이
 *     값을 읽을 곳이 없으므로 AXI 레지스터로 만들 이유가 없고, 앱 변수로 두면 값을 바꿔도
 *     비트스트림 재빌드가 없다 — 재빌드는 탭 창을 밀어 교정 조건을 깨뜨린다.
 *
 *  [메모리 한계 — 넘을 수 있는 곳은 '단계당 발수' 하나뿐]
 *   이 명령은 한 단계(위상 x 주기)를 캡처해 곧바로 찍고 버린다. 그래서 전체 발수는 메모리와
 *   무관하고, 배열에 들어가는 것은 단계당 발수뿐이다. 한계는 둘 다 4096 이다 :
 *     PL 캡처 버퍼  4096 발 (RTL/tdc_capture.v 의 ADDR_WIDTH = 12)
 *     PS 배열       g_cap_lo[CAP_MAX] / g_cap_hi[CAP_MAX], CAP_MAX = 4096
 *   ★ 오전 판에는 이 검사가 없었다. cmd_mode2 는 capn 을 CAP_MAX 로 잘랐지만 이쪽은
 *     M0_HITS 로만 잘라서, M0_HITS 를 4096 초과로 두면 g_cap_lo[] 밖을 쓰는 상태였다.
 *     이제 m0_check() 가 먼저 막고, 되읽기 루프에서 한 번 더 자른다.
 *   [실제로 걸리는 것은 UART 시간이다] 한 줄 약 30자, 115200-8-N-1 은 초당 11520자이므로
 *     걸리는 시간 ~ 줄수/384 초. 70점 x 500발 = 35000줄 = 약 91초. 메모리는 8%만 쓴다. */
/* ★ 2026-09-17 저녁 : 보고서로 묶으면서 주기는 50 사이클 하나로 고정했다 (09-16 에 네 주기를 모두
 *   확인했고, 전달함수에는 한 주기면 충분하다). 주기 목록·주기 개수·CSV 여부·표 선택 설정은 없앴다 —
 *   보고서가 교정 전/후를 항상 둘 다 돈다. 시작/간격/점 개수/발수는 보고서 시작 때 'e' 로 바꾼다. */
#define M0_PERIOD     50u     /* 히트 생성기 주기 [tdc_clk 클럭 수] = 250 ns */
#define M0_MAP_VER    8u      /* 히트 생성기와 M0PER 레지스터가 있는 맵 버전 */
#define PHASE_STEPS   280u    /* 한 주기를 덮는 위상 스텝 수 (phase_shifter.v STEPS_PER_PERIOD) */
#define M0_MIN_HITS   2u      /* 이웃 간격을 재려면 최소 두 발이 있어야 한다 */

/* 스윕 설정. 보고서(키 2) 시작 때 'e' 를 누르면 UART 로 바꾼다 (전원을 끄면 이 기본값으로 돌아온다). */
/* ★ 2026-09-21 : 위상 목록을 고정했다 (사용자 지정, 키 4).
 *   50 / 100 / 150 / 200 / 250 스텝, 각 200발. 한 스텝 = 17.857 ps 이므로
 *   위상 간격 50 스텝 = 892.9 ps 다. 창 밖이 아닌 곳을 고르게 훑으려는 배치다. */
static const u16 M0_PHASES[] = { 50u, 100u, 150u, 200u, 250u };
#define M0_NPH    (u32)(sizeof(M0_PHASES) / sizeof(M0_PHASES[0]))
#define M0_HITS   200u          /* 한 위상에서 잡을 히트 수 (<= CAP_MAX) */

/* ★ 2026-09-17 저녁 : 캡처(키 1) 전에 다시 교정하는 온도 변화 [0.01 C].
 *   300 = 3 C. 근거 : 탭 지연 온도계수 304~546 ppm/C (2026-08-03 정정값, 한 번 뒤집힌 적 있는 잠정값)
 *   이면 체인 끝 오차가 LSB 의 절반(약 8 ps)에 이르는 온도 변화가 약 3~6 C 다 (2026-09-17 특허 전략
 *   문서 4-2). 보수적으로 아래쪽 값을 썼다. ZedBoard 에서 온도를 바꿔 다시 재면 고칠 것. */
#define RECAL_DT_CENTI 300

#define EDGE_TRIM_PCT 5
#define WIN_LO_MANUAL (-1)
#define WIN_HI_MANUAL (-1)

static u32 g_histo[NUM_TAPS];
static u32 g_cap_lo[CAP_MAX];
static u32 g_cap_hi[CAP_MAX];
static u16 g_cal[CAL_DEPTH];      /* ★ 2026-09-15 : 마지막으로 계산한 교정표 [ps]             */
static int g_cal_valid = 0;       /* 1 = g_cal 을 RAM 에 쓰고 되읽기까지 통과했다              */
static int g_histo_ok  = 0;       /* 1 = g_histo 가 HIT_CNT 와 일치하는 히스토그램이다          */
static int g_print_csv = 1;       /* ★ 2026-09-16 : 0 이면 CSV 를 찍지 않는다 (당시 부팅 자동 교정용, 09-17 삭제) */

/* ★ 2026-09-17 : 교정 전/후 INL·DNL 평가(키 5)와 온도별 탭 변화 기록(키 6)에 쓰는 상태.
 *   g_histo      : 키 1 이 교정표를 만든 히스토그램 ("교정용", cal)
 *   g_histo_val  : 키 5·6 이 새로 받은 히스토그램 ("검증용", val). cal 과 섞지 않는다 —
 *                  교정표를 만든 데이터로 그 표를 평가하면 자기 일치도만 잰다 (CLAUDE.md).
 *   g_lin        : 교정 전 표 = 키 1 과 같은 창에 맞춘 선형 램프 (build_linear_table 주석 참조)
 *   g_win_lo/hi  : 키 1 이 교정표를 만든 창. 키 1 전에는 -1
 *   g_cal_temp   : 키 1 교정표의 온도 = 그 히스토그램의 시작·끝 온도 평균 [0.01 C]
 *                  (계산 시점의 R_TEMP 가 아니다 — 히스토그램을 받는 동안 온도가 변하면 다르다) */
static u32 g_histo_val[NUM_TAPS];
static u16 g_lin[CAL_DEPTH];
static int g_win_lo = -1, g_win_hi = -1;
static int g_cal_temp = 0;
static int g_histo_temp = 0;     /* 키 1 히스토그램의 시작·끝 온도 평균 [0.01 C] — 교정 온도로 쓴다 */

typedef struct {
    u32 hitcnt, sum, first, last, drop, ro0, ro1;
    int t0, t1;                   /* 히스토그램 시작/끝 다이 온도 [0.01 C] */
} histo_info_t;

static int  cmd_set_danger(void);  /* ★ 2026-09-15 : cmd_mode1 이 이어서 부른다 (09-17 : 성공 여부 반환) */
static void cmd_calibrate(void);
static void cmd_mode1(u32 target, int print_csv);

static const char *STATE_NAME[8] = {
    "S_IDLE", "S_RO_ENABLE", "S_MEAS_FREQ", "S_STABILIZE",
    "S_ACQ", "S_DONE", "?", "?"
};

#define RD(a)     Xil_In32((a))
#define WR(a, v)  Xil_Out32((a), (u32)(v))

/* ---------------------------------------------------------------- 도우미 */

/* XADC 온도 raw -> 섭씨. UG480 식 (2-6).
 * 정수 연산으로 0.01 도 단위를 만든다 (베어메탈에서 float printf 는 무겁다). */
static int temp_centi(u32 raw)
{
    /* T[C] = raw/65536 * 503.975 - 273.15  ->  100배 해서 정수로 */
    return (int)(((s64)(raw & 0xFFFFu) * 50397) / 65536) - 27315;
}

static void print_centi(const char *name, int c)
{
    xil_printf("%s%s%d.%02d C\r\n", name, (c < 0 ? "-" : ""),
               (c < 0 ? -c : c) / 100, (c < 0 ? -c : c) % 100);
}

/* RO 에지 수 -> 주파수 [kHz].
 *   ro_divider_cnt 는 RO 상승엣지마다 +1, 측정 탭이 [1] 이라 4번 증가마다 한 주기,
 *   ro_edge 는 상승엣지만 세므로 RO 4주기당 1카운트다. 게이트는 10 ms.
 *     f_RO [Hz] = RO_CNT x 4 / 0.01 s     ->  [kHz] = RO_CNT x 4 / 10
 *   ※ 이 식이 코드에 없어서 2026-09-04 문서가 2배 틀린 값을 실은 적이 있다. */
static u32 ro_khz(u32 cnt) { return (cnt * 4u) / 10u; }

static int wait_done(int timeout_ms)
{
    int i;
    for (i = 0; i < timeout_ms; i++) {
        if (RD(R_STATUS) & S_DONE) return 1;
        usleep(1000);
    }
    return 0;
}

/* ---------------------------------------------------------------- 명령들 */

static void cmd_info(void)
{
    u32 build = RD(R_BUILD);
    u32 st    = RD(R_STATUS);
    u32 dna   = RD(R_DNA);
    u32 dg    = RD(R_DANGER);

    xil_printf("\r\n===== IDENTITY / STATUS =====\r\n");
    xil_printf("ID       = 0x%08X   (expect 0x54444302)\r\n", RD(R_ID));
    xil_printf("BUILD    = 0x%08X   taps %d, carry4 stages %d, regmap ver %d\r\n",
               build, (build >> 16) & 0xFFFF, (build >> 8) & 0xFF, build & 0xFF);
    xil_printf("DNA      = 0x%08X   valid=%d   (board identity)\r\n", dna, (dna >> 31) & 1u);
    xil_printf("STATUS   = 0x%08X   MMCM=%d BUSY=%d DONE=%d PHASE_BUSY=%d  state=%s\r\n",
               st, st & 1u, (st >> 3) & 1u, (st >> 4) & 1u, (st >> 5) & 1u,
               STATE_NAME[(st >> S_STATE_SHIFT) & S_STATE_MASK]);
    xil_printf("RO_CNT   = %d   (approx %d kHz, ring oscillator edges per 10 ms gate)\r\n",
               RD(R_ROCNT), ro_khz(RD(R_ROCNT)));
    print_centi("DIE_TEMP = ", temp_centi(RD(R_TEMP)));
    /* ★ 2026-09-16 : DANGER 가 무엇인지 화면에서 바로 알 수 있게 설명을 붙인다 (사용자 지정). */
    xil_printf("DANGER   = lo %d, hi %d   (tap numbers)\r\n", dg & 0x1FFu, (dg >> 16) & 0x1FFu);
    xil_printf("           A fine index outside [lo,hi] means the hit landed near a clock edge,\r\n");
    xil_printf("           so the core takes the 180-degree shadow coarse counter instead of the\r\n");
    xil_printf("           0-degree one. This avoids latching a coarse count while it changes.\r\n");
    xil_printf("           Calibration (key 1 when needed, key 2 always) recomputes it; 40/220 are the power-up\r\n");
    xil_printf("           defaults and are usually wrong for a given build.\r\n");
    /* ★ 2026-09-15 : 교정표 상태. 앱을 다시 띄우면 g_cal_valid 는 0 이지만 RAM 은 FPGA 를
     *   새로 굽기 전까지 이전 표를 들고 있을 수 있다. */
    xil_printf("CAL TBL  = %s\r\n",
               g_cal_valid ? "written in this run (code density from Mode 1)"
                           : "not written in this run (a freshly loaded FPGA holds the linear ramp)");
    /* ★ 2026-09-16 : 세 레지스터가 무엇인지 한 줄씩 설명한다 (사용자 지정). */
    xil_printf("CAP_N    = %d   hits to collect in one Mode 2 capture (max %d)\r\n",
               RD(R_CAPN), CAP_MAX);
    xil_printf("TARGET   = %d   hits to accumulate in Mode 1 (0 = no limit; calibration sets %d)\r\n",
               RD(R_TARGET), MODE1_HITS);
    xil_printf("SETTLE_N = %d   clocks to wait after enabling the ring oscillator\r\n",
               RD(R_SETTLE));
    xil_printf("           (%d clocks = %d us at 200 MHz; not measured, chosen with margin)\r\n",
               RD(R_SETTLE), RD(R_SETTLE) / 200u);

    if ((st & S_MMCM_LOCKED) == 0)
        xil_printf("!! MMCM is not locked. Check FCLK_CLK0 from the PS.\r\n");
}

/* Mode 1 : 링오실레이터 코드밀도 히스토그램 */
/* ★ 2026-09-17 : Mode 1 히스토그램 한 번 받기 (키 1·5·6 공용). cmd_mode1 에서 떼어 냈다.
 *   돌려주는 값 : 1 = 성공(HIT_CNT 와 탭 합이 같다), 0 = 불일치, -1 = 시간 초과.
 *   끝에 반드시 CTRL 을 0 으로 내린다 (START 를 내려야 S_IDLE 로 돌아간다).
 *   히스토그램은 fine 번호만 쓰므로 DANGER 와 교정표 RAM 에 영향을 받지도 주지도 않는다. */
static int acquire_histo(u32 target, u32 *h, histo_info_t *inf)
{
    u32 i, tse;

    inf->hitcnt = 0; inf->sum = 0; inf->drop = 0; inf->ro0 = 0; inf->ro1 = 0;
    inf->first = 0xFFFFFFFFu; inf->last = 0; inf->t0 = 0; inf->t1 = 0;

    WR(R_TARGET, target);
    WR(R_CTRL, C_SRC_RO | C_START);
    if (!wait_done(120000)) {           /* 최대 2분 */
        xil_printf("!! timeout. state=%s\r\n",
                   STATE_NAME[(RD(R_STATUS) >> S_STATE_SHIFT) & S_STATE_MASK]);
        WR(R_CTRL, 0);
        return -1;
    }
    inf->hitcnt = RD(R_HITCNT);
    for (i = 0; i < NUM_TAPS; i++) {
        h[i] = RD(R_HISTO(i));
        inf->sum += h[i];
        if (h[i]) { if (inf->first == 0xFFFFFFFFu) inf->first = i; inf->last = i; }
    }
    inf->drop = RD(R_DROP);
    inf->ro0  = RD(R_ROSTA);
    inf->ro1  = RD(R_ROEND);
    tse       = RD(R_TEMPSE);
    inf->t0   = temp_centi(tse & 0xFFFFu);
    inf->t1   = temp_centi((tse >> 16) & 0xFFFFu);
    WR(R_CTRL, 0);
    return (inf->hitcnt == inf->sum && inf->sum > 0) ? 1 : 0;
}

static void cmd_mode1(u32 target, int print_csv)
{
    int i, r;
    histo_info_t inf;

    xil_printf("\r\n===== Mode 1 : code density histogram =====\r\n");
    xil_printf("target %d hits, starting ...\r\n", target);
    g_histo_ok = 0;                     /* ★ 2026-09-15 : 끝까지 성공해야 1 */

    g_print_csv = print_csv;        /* ★ 2026-09-16 : 이어지는 cmd_calibrate 의 CSV 출력도 함께 정한다 */

    /* ★ 2026-09-17 : 받는 부분을 acquire_histo() 로 옮겼다 (키 5·6 이 같이 쓴다). 화면 출력은 그대로다. */
    r = acquire_histo(target, g_histo, &inf);
    if (r < 0) return;

    xil_printf("\r\nHIT_CNT = %d,  sum of %d taps = %d,  difference = %d\r\n",
               inf.hitcnt, NUM_TAPS, inf.sum, (int)inf.hitcnt - (int)inf.sum);
    g_histo_ok = (r == 1);              /* ★ 2026-09-15 : 교정표 계산의 전제 */
    if (r != 1)
        xil_printf("!! mismatch: the total hit count H cannot be trusted.\r\n");
    else
        xil_printf("OK  exact match -> H in w[i] = h[i]/H x 5000 ps is trustworthy\r\n");

    xil_printf("taps with hits = %d ~ %d,  spare taps to end of chain = %d\r\n",
               inf.first, inf.last, NUM_TAPS - 1 - (int)inf.last);
    if ((int)(NUM_TAPS - 1 - (int)inf.last) < 20)
        xil_printf("!! less than 20 spare taps. A warmer die may run past the end of the chain.\r\n");

    xil_printf("DROP_CNT = %d  (hits dropped during the histogram dead time)\r\n", inf.drop);
    xil_printf("RO  start %d (%d kHz) -> end %d (%d kHz)\r\n",
               inf.ro0, ro_khz(inf.ro0), inf.ro1, ro_khz(inf.ro1));
    print_centi("die temp start ", inf.t0);
    print_centi("die temp end   ", inf.t1);
    g_histo_temp = (inf.t0 + inf.t1) / 2;

    /* ★ 2026-09-16 : 부팅 자동 교정에서는 CSV 를 찍지 않았다 (384줄이라 배너가 밀린다). */
    if (print_csv) {
        xil_printf("\r\n----- CSV BEGIN (save as tap_histogram.csv) -----\r\n");
        xil_printf("Tap_Index,Hit_Count\r\n");
        for (i = 0; i < NUM_TAPS; i++) xil_printf("%d,%d\r\n", i, g_histo[i]);
        xil_printf("----- CSV END -----\r\n");
    }

    /* ★ 2026-09-15 : 이어서 danger 임계값과 교정표를 한 번에 처리한다 (사용자 결정).
     *   둘 다 빌드마다(창이 옮겨가므로), 그리고 온도가 바뀌면 다시 해야 하는 일이다.
     *   순서는 상관없다 — danger 는 coarse 선택만, 교정표는 fine -> ps 변환만 바꾼다. */
    /* ★ 2026-09-17 저녁 : DANGER 를 못 맞추면 교정도 무효로 본다 — coarse 가 틀린 timestamp 를 막는다 */
    if (!cmd_set_danger()) {
        g_cal_valid = 0;
        xil_printf("!! DANGER not set -> calibration skipped.\r\n");
        return;
    }
    cmd_calibrate();
}

/* 히스토그램에서 danger 임계값을 계산해 설정한다.
 *
 *  danger 는 "히트가 클럭 에지 근처인가" 를 fine 탭 번호로 판단하는 경계다.
 *  에지는 창의 양 끝 두 곳이므로 양끝에서 같은 시간만큼을 가드로 잡는다.
 *  목표 630 ps 는 2026-09-05 에 상수 40 이 만들던 아래 가드 폭이다 —
 *  "예전과 같은 여유를 창이 어디로 가든 유지한다" 는 뜻이지 630 ps 가 옳다는
 *  뜻은 아니다. coarse 카운터의 실제 불안정 구간은 아직 측정된 적이 없다.
 *
 *  ※ 반드시 cmd_mode1 을 먼저 돌려 g_histo 를 채운 뒤 호출할 것.
 */
static int cmd_set_danger(void)
{
    const u32 GUARD_PS = 630u;
    u32 H = 0, acc, i, first = 0xFFFFFFFFu, last = 0, lo = 0, hi = 0;

    for (i = 0; i < NUM_TAPS; i++) {
        H += g_histo[i];
        if (g_histo[i]) { if (first == 0xFFFFFFFFu) first = i; last = i; }
    }
    if (H == 0) { xil_printf("!! histogram is empty.\r\n"); return 0; }

    /* w[i] = h[i]/H x 5000 ps 를 누적한다. 정수로 하려고 순서를 바꿔 곱셈을 먼저 한다. */
    acc = 0;
    for (i = first; i <= last; i++) {
        acc += (u32)(((u64)g_histo[i] * 5000u) / H);
        if (acc >= GUARD_PS) { lo = i + 1; break; }
    }
    acc = 0;
    for (i = last; i > first; i--) {
        acc += (u32)(((u64)g_histo[i] * 5000u) / H);
        if (acc >= GUARD_PS) { hi = i - 1; break; }
    }
    if (lo == 0 || hi == 0 || lo >= hi) {
        xil_printf("!! could not place the guards (lo=%d hi=%d). Check the histogram.\r\n", lo, hi);
        return 0;
    }

    xil_printf("\r\nwindow %d~%d  ->  DANGER lo=%d hi=%d  (guard %d ps at each end)\r\n",
               first, last, lo, hi, GUARD_PS);
    WR(R_DANGER, ((u32)hi << 16) | (u32)lo);
    {
        u32 rb = RD(R_DANGER);
        xil_printf("readback = 0x%08X  (lo=%d hi=%d)  %s\r\n",
                   rb, rb & 0x1FFu, (rb >> 16) & 0x1FFu,
                   ((rb & 0x1FFu) == lo && ((rb >> 16) & 0x1FFu) == hi) ? "OK" : "!! write did not take");
        return ((rb & 0x1FFu) == lo && ((rb >> 16) & 0x1FFu) == hi);
    }
}

/* ★ 2026-09-15 : 교정표 RAM 이 있는 비트스트림인지, 지금 써도 되는지 */
static int cal_ready_to_write(void)
{
    u32 ver = RD(R_BUILD) & 0xFFu;
    if (ver < CAL_MAP_VER) {
        xil_printf("!! regmap ver %d. The calibration window needs %d or newer (old bitstream).\r\n",
                   ver, CAL_MAP_VER);
        return 0;
    }
    if (RD(R_STATUS) & S_BUSY) {
        xil_printf("!! sequencer is BUSY, so the hardware ignores calibration writes.\r\n");
        return 0;
    }
    return 1;
}

/* ★ 2026-09-15 : 512칸을 쓰고 전부 되읽어 비교한다. 불일치 칸 수를 돌려준다. */
static u32 cal_write_verify(const u16 *tab)
{
    u32 i, rb, bad = 0;
    for (i = 0; i < CAL_DEPTH; i++) WR(R_CAL(i), tab[i]);
    for (i = 0; i < CAL_DEPTH; i++) {
        rb = RD(R_CAL(i)) & 0x1FFFu;
        if (rb != tab[i]) {
            if (bad < 5) xil_printf("   entry %d : wrote %d, read %d\r\n", i, tab[i], rb);
            bad++;
        }
    }
    return bad;
}

/* ★ 2026-09-17 : 창 찾기 (cmd_calibrate 에서 떼어 냄, 키 6 이 같이 쓴다). 화면 출력은 없다.
 *   규칙은 그대로 : 양 끝에서 "히트 있는 탭 평균의 EDGE_TRIM_PCT % 미만" 인 탭을 뺀다.
 *   WIN_LO/HI_MANUAL 이 0 이상이면 그 값을 쓴다. 성공하면 1. */
static int find_window(const u32 *h, int *plo, int *phi)
{
    u32 i, n_nz = 0;
    u64 sum_nz = 0;
    int lo, hi;

    for (i = 0; i < NUM_TAPS; i++)
        if (h[i]) { n_nz++; sum_nz += h[i]; }
    if (n_nz == 0) return 0;

    /* h < (sum_nz / n_nz) x 5 % 인 양 끝 탭을 뺀다. 나눗셈 없이 h*100*n_nz < 5*sum_nz 로 비교 */
    lo = 0;
    while (lo < NUM_TAPS && (u64)h[lo] * 100u * n_nz < (u64)EDGE_TRIM_PCT * sum_nz) lo++;
    hi = NUM_TAPS - 1;
    while (hi > lo && (u64)h[hi] * 100u * n_nz < (u64)EDGE_TRIM_PCT * sum_nz) hi--;
    if (WIN_LO_MANUAL >= 0) lo = WIN_LO_MANUAL;
    if (WIN_HI_MANUAL >= 0) hi = WIN_HI_MANUAL;
    if (lo < 0 || hi >= NUM_TAPS || lo >= hi) return 0;
    *plo = lo;
    *phi = hi;
    return 1;
}

/* ★ 2026-09-17 : 코드밀도 교정표 계산 (cmd_calibrate 에서 떼어 냄). 식은 cmd_calibrate 주석과 같다.
 *   창 아래 = 0, 창 위 = 창 끝 값. 창 안 히트 합 H 를 돌려준다 (0 이면 실패, 표는 건드리지 않음). */
static u64 build_cd_table(const u32 *h, int lo, int hi, u16 *tab)
{
    u64 H = 0, C = 0;
    int i;

    for (i = lo; i <= hi; i++) H += h[i];
    if (H == 0) return 0;
    for (i = 0; i < CAL_DEPTH; i++) {
        if (i < lo) {
            tab[i] = 0;
        } else if (i <= hi) {
            tab[i] = (u16)(((2u * C + h[i]) * 5000u + H) / (2u * H));
            C += h[i];
        } else {
            tab[i] = tab[hi];
        }
    }
    return H;
}

/* ★ 2026-09-17 : 교정 전 표 — 창에 맞춘 선형 램프 (사용자 지정).
 *   뜻 : "창 안의 탭은 폭이 모두 같다" 고만 알 때의 표. 창의 N 칸이 5000 ps 를 똑같이 나눈다.
 *   식 : 표[i] = floor(((2*(i-lo) + 1) * 5000 + N) / (2N))  — 코드밀도 표와 같은 '칸 중심' 규칙.
 *   왜 RTL 초기값(384칸 램프)을 쓰지 않나 : 그 램프는 창 밖 탭까지 5000 ps 안에 넣어 눈금이
 *     약 17 % 틀린다 (2026-09-16 창 2~319 기준, 표[2]~표[319] 폭 4128 ps 대 실제 4992 ps).
 *     그러면 교정 효과에 눈금 오차가 섞인다. 창에 맞추면 남는 차이는 "칸마다 폭이 다르다" 하나다. */
static void build_linear_table(int lo, int hi, u16 *tab)
{
    u32 N = (u32)(hi - lo + 1);
    int i;

    for (i = 0; i < CAL_DEPTH; i++) {
        if (i < lo)       tab[i] = 0;
        else if (i <= hi) tab[i] = (u16)(((2u * (u32)(i - lo) + 1u) * 5000u + N) / (2u * N));
        else              tab[i] = tab[hi];
    }
}

/* ★ 2026-09-15 : 히스토그램(g_histo)으로 교정표를 계산해 RAM 에 쓴다.
 *
 *  뜻 : fine 번호 i 로 찍힌 히트가 클럭 에지보다 몇 ps 먼저 왔는가 — 그 탭 폭의 가운데 값.
 *  식 : 교정표[i] = floor( ((2*C_i + h_i) * 5000 + H) / (2*H) )
 *         h_i = 탭 i 히트 수, C_i = 창 시작 ~ 탭 i-1 의 h 합, H = 창 전체 h 합
 *       = 5000/H * (C_i + h_i/2) 를 반올림한 값. python/Making_COE_Mode_0.py §3 과 같은 정의다.
 *       창 아래 = 0, 창 위(최대 511) = 창 끝 값. h >= 0 이라 식 자체가 단조 증가다.
 *  대조 : 2026-09-06 ZedBoard Mode 1 히스토그램(200만 발)에서 파이썬 결과와 최대 1 ps,
 *         384칸 중 1칸 차이 (반올림 규칙 차이로 추정).
 *  정수 범위 : (2H + h) * 5000 은 H = 200만에서 약 3e10 이라 u64 로 계산한다.
 *  ★ 2026-09-17 : 창 찾기·표 계산을 find_window() / build_cd_table() 로 떼어 냈다. 규칙은 그대로.
 *    성공하면 창과 온도를 기억하고, 같은 창으로 교정 전 표(g_lin)도 만든다 (키 3·5 가 쓴다).
 */
static void cmd_calibrate(void)
{
    u32 i, bad, step, max_step = 0, min_step = 0xFFFFFFFFu, max_at = 0;
    u64 sum_all = 0, H;
    int lo, hi;

    xil_printf("\r\n===== calibration table : compute and write =====\r\n");
    if (!g_histo_ok) {
        xil_printf("!! no trustworthy histogram (histogram failed, or HIT_CNT mismatched). Skipped.\r\n");
        return;
    }
    if (!find_window(g_histo, &lo, &hi)) {
        xil_printf("!! could not find a window in the histogram. Skipped.\r\n");
        return;
    }
    xil_printf("window (drop end taps below %d%% of the mean%s) : %d ~ %d (%d entries)\r\n",
               EDGE_TRIM_PCT,
               (WIN_LO_MANUAL >= 0 || WIN_HI_MANUAL >= 0) ? ", hand override applied" : "",
               lo, hi, hi - lo + 1);

    for (i = 0; i < NUM_TAPS; i++) sum_all += g_histo[i];
    H = build_cd_table(g_histo, lo, hi, g_cal);
    if (H == 0) { xil_printf("!! no hits inside the window. Skipped.\r\n"); return; }

    for (i = (u32)lo + 1; i <= (u32)hi; i++) {
        step = (u32)(g_cal[i] - g_cal[i - 1]);
        if (step > max_step) { max_step = step; max_at = i; }
        if (step < min_step) min_step = step;
    }
    xil_printf("H (hits inside window) = %d,  hits trimmed off the ends = %d\r\n",
               (u32)H, (u32)(sum_all - H));
    xil_printf("table[%d] = %d ps,  table[%d] = %d ps  (the last entry sits near 5000 ps)\r\n",
               lo, g_cal[lo], hi, g_cal[hi]);
    xil_printf("step between neighbours : max %d ps (tap %d), min %d ps  (0 = missing code)\r\n",
               max_step, max_at, min_step);
    g_cal_temp = g_histo_temp;          /* ★ 2026-09-17 : 표를 만든 히스토그램의 온도 */
    print_centi("die temp when computed = ", temp_centi(RD(R_TEMP)));

    g_cal_valid = 0;
    if (!cal_ready_to_write()) return;
    bad = cal_write_verify(g_cal);
    if (bad) {
        xil_printf("!! readback mismatch in %d entries. Do not trust this table.\r\n", bad);
        return;
    }
    g_cal_valid = 1;
    g_win_lo = lo;                      /* ★ 2026-09-17 : 교정 전 표가 같은 창을 쓴다 */
    g_win_hi = hi;
    build_linear_table(lo, hi, g_lin);
    xil_printf("OK  %d entries written and read back identical. timestamp_ps now uses this table.\r\n",
               CAL_DEPTH);
    xil_printf("    (the 'before' table for report [3]/[4] = equal-width taps over the same window, %d.%02d ps each)\r\n",
               (500000u / (u32)(hi - lo + 1)) / 100u, (500000u / (u32)(hi - lo + 1)) % 100u);

    if (g_print_csv) {
        xil_printf("\r\n----- CSV BEGIN (save as calib_table.csv) -----\r\n");
        xil_printf("Tap_Index,Calib_ps\r\n");
        for (i = 0; i < NUM_TAPS; i++) xil_printf("%d,%d\r\n", i, g_cal[i]);
        xil_printf("----- CSV END -----\r\n");
    }
}

/* ★ 2026-09-15 : 4단계 보드 검증 — "램프 write -> read 일치" (2026-09-04 보고서 진행 순서 표).
 *   A : 선형 램프 round(i*5000/384), 0.5 는 짝수 쪽으로, i >= 384 는 383 의 값 — RTL 초기값과 같은 식
 *       (tdc_calib_ram.v [초기값] 주석 : 09-06 빌드의 COE 가 이 반올림 규칙이었다)
 *   B : 8191 - A — 각 칸의 13비트가 A 와 전부 반대가 되어, 붙어 버린 비트를 잡는다
 *   끝나면 되돌린다 : 이번 실행에서 교정표를 썼으면 그것, 아니면 A. */
static int cmd_cal_test(void)
{
    static u16 pat[CAL_DEPTH];
    u32 i, bad_a, bad_b, bad_r;

    xil_printf("\r\n===== calibration RAM write / readback test =====\r\n");
    if (!cal_ready_to_write()) return 0;

    for (i = 0; i < CAL_DEPTH; i++) {
        u32 num = ((i < NUM_TAPS) ? i : (NUM_TAPS - 1u)) * 5000u;
        u32 q = num / NUM_TAPS, r = num % NUM_TAPS;
        if (2u * r > NUM_TAPS || (2u * r == NUM_TAPS && (q & 1u))) q++;
        pat[i] = (u16)q;
    }
    bad_a = cal_write_verify(pat);
    xil_printf("A linear ramp   : %d / %d entries mismatched  %s\r\n", bad_a, CAL_DEPTH, bad_a ? "!!" : "OK");

    for (i = 0; i < CAL_DEPTH; i++) pat[i] = (u16)(0x1FFFu - pat[i]);
    bad_b = cal_write_verify(pat);
    xil_printf("B bit-inverted  : %d / %d entries mismatched  %s\r\n", bad_b, CAL_DEPTH, bad_b ? "!!" : "OK");

    if (g_cal_valid) {
        bad_r = cal_write_verify(g_cal);
        xil_printf("restore (this run's table) : %d entries mismatched\r\n", bad_r);
        if (bad_r) g_cal_valid = 0;
    } else {
        for (i = 0; i < CAL_DEPTH; i++) pat[i] = (u16)(0x1FFFu - pat[i]);
        bad_r = cal_write_verify(pat);
        xil_printf("restore (linear ramp)      : %d entries mismatched\r\n", bad_r);
    }
    return (bad_a == 0u && bad_b == 0u && bad_r == 0u);   /* ★ 2026-09-17 : 보고서가 쓴다 */
}

/* Mode 2 : 외부 신호 캡처. raw != 0 이면 {coarse, fine} 형식 */
static void cmd_mode2(u32 capn, int raw)
{
    u32 i, ctrl;

    if (capn > CAP_MAX) capn = CAP_MAX;
    xil_printf("\r\n===== Mode 2 : external hit capture (%s) =====\r\n",
               raw ? "raw {coarse,fine}" : "timestamp_ps");

    WR(R_CAPN, capn);
    ctrl = C_SRC_EXT | C_START | (raw ? C_CAP_FMT : 0u);
    WR(R_CTRL, ctrl);

    if (!wait_done(30000)) {
        xil_printf("!! timeout. CAP_CNT = %d / %d\r\n", RD(R_CAPCNT), capn);
        xil_printf("   if no hits arrive, check in this order:\r\n");
        /* ★ 2026-09-15 : HIT_INPUT(PMOD Y11 / FMC LVDS) 항목 삭제 — 히트 입력은 FMC LVDS
         *   하나뿐이다. J18 을 첫 번째로 올렸다 : 같은 보드를 DAC 프로젝트와 공유해서
         *   DAC 작업 뒤에는 1.8 V 에 가 있고, 그때 빌드·UART·Mode 1 은 멀쩡해 헷갈린다. */
        xil_printf("   1) J18 jumper at 2.5V  (after DAC work it sits at 1.8V)\r\n");
        xil_printf("   2) comparator really driving (scope)\r\n");
        xil_printf("   3) GND connected\r\n");
        xil_printf("   4) E21/D21 (LA27_P/N) polarity not swapped\r\n");
        WR(R_CTRL, 0);
        return;
    }

    for (i = 0; i < capn; i++) {
        g_cap_lo[i] = RD(R_CAP_LO(i));
        g_cap_hi[i] = RD(R_CAP_HI(i));
    }
    xil_printf("CAP_CNT = %d,  DROP_CNT = %d\r\n", RD(R_CAPCNT), RD(R_DROP));

    xil_printf("\r\n----- CSV BEGIN -----\r\n");
    if (raw) {
        /* capture_raw.csv 와 같은 형식 -> python/analyze_chirp_capture.py 에 그대로 */
        xil_printf("Index,Coarse,Fine\r\n");
        for (i = 0; i < capn; i++)
            xil_printf("%d,%u,%d\r\n", i, g_cap_lo[i], g_cap_hi[i] & 0x1FFu);
    } else {
        /* timestamp_ps 는 48비트라 32비트 두 개로 나눠 찍는다.
         * 파이썬에서 ts = hi * 2^32 + lo 로 합치면 된다. */
        xil_printf("Index,TS_Lo,TS_Hi\r\n");
        for (i = 0; i < capn; i++)
            xil_printf("%d,%u,%u\r\n", i, g_cap_lo[i], g_cap_hi[i]);
    }
    xil_printf("----- CSV END -----\r\n");

    WR(R_CTRL, 0);
}

/* ---------------------------------------------------------------- UART 입력 */

static u8 read_key(void)
{
    u8 c;
    while (!XUartPs_IsReceiveData(STDIN_BASEADDRESS)) { }
    c = XUartPs_ReadReg(STDIN_BASEADDRESS, XUARTPS_FIFO_OFFSET);
    xil_printf("%c\r\n", c);
    return c;
}

/* ---------------------------------------------------------------- 평가 도우미 (★ 2026-09-17) */

static u64 isqrt64(u64 v)
{
    u64 r = 0, b = (u64)1 << 62;
    while (b > v) b >>= 2;
    while (b) {
        if (v >= r + b) { v -= r + b; r = (r >> 1) + b; }
        else            { r >>= 1; }
        b >>= 2;
    }
    return r;
}

/* v 를 소수 dec 자리(2 또는 3)로 찍는다. v 는 이미 10^dec 배 한 정수다 (베어메탈 printf 에 %f 가 없다) */
static void print_fix(s64 v, int dec)
{
    s64 a = (v < 0) ? -v : v;
    if (dec == 3) xil_printf("%s%d.%03d", v < 0 ? "-" : "", (int)(a / 1000), (int)(a % 1000));
    else          xil_printf("%s%d.%02d", v < 0 ? "-" : "", (int)(a / 100),  (int)(a % 100));
}

/* 한 지표의 통계 : 최대 |값|(어느 탭), 최소·최대, 탭을 똑같이 센 RMS, 히트 수로 가중한 RMS */
typedef struct {
    s64 vmin, vmax, amax;
    int at;
    u64 ss, wss, w;
    u32 n;
} stat_t;

static void st_init(stat_t *t)
{
    t->vmin = 0; t->vmax = 0; t->amax = 0; t->at = -1;
    t->ss = 0; t->wss = 0; t->w = 0; t->n = 0;
}

static void st_add(stat_t *t, s64 v, int tap, u32 weight)
{
    s64 a = (v < 0) ? -v : v;
    if (t->n == 0 || v < t->vmin) t->vmin = v;
    if (t->n == 0 || v > t->vmax) t->vmax = v;
    if (t->at < 0 || a > t->amax) { t->amax = a; t->at = tap; }
    t->ss  += (u64)(a * a);
    t->wss += (u64)(a * a) * weight;
    t->w   += weight;
    t->n++;
}

static s64 st_rms(const stat_t *t)  { return t->n ? (s64)isqrt64(t->ss / t->n) : 0; }
static s64 st_wrms(const stat_t *t) { return t->w ? (s64)isqrt64(t->wss / t->w) : 0; }

/* ================================================================ 보고서 [3] INL / DNL
 *
 *  교정 전/후 INL·DNL (★ 2026-09-17, 사용자 지정)
 *
 *  [무엇을 비교하나]
 *    교정 전 = g_lin : 교정과 같은 창에 맞춘 선형 램프 (창 안 탭 폭이 모두 같다고 가정)
 *    교정 후 = g_cal : 보고서 [2] 의 히스토그램(cal)으로 만든 코드밀도 표
 *  [무엇을 참값으로 쓰나]
 *    새로 받는 독립 히스토그램(val) 에서 구한 각 탭의 실제 폭·중심.
 *    교정표를 만든 cal 로 평가하면 교정 후 오차가 반올림 수준으로만 나와 의미가 없다
 *    (CLAUDE.md "cal/val split is mandatory").
 *  [정의]  창 = 교정 창 lo~hi, N = 탭 수, LSB = 5000/N ps (창 안 평균 탭 폭)
 *    실제 폭    w_i = h_i/H x 5000                   (val)
 *    실제 중심  c_i = (C_i + h_i/2)/H x 5000         (val, C_i = 창 시작 ~ i-1 합)
 *    DNL 전 = w_i/LSB - 1                  [LSB]  선형 램프는 모든 탭을 LSB 로 본다
 *    DNL 후 = (w_i(cal) - w_i(val))/LSB    [LSB]  교정표가 가정한 폭과 실제 폭의 차
 *    INL 전 = g_lin[i] - c_i               [ps]   표가 준 시각 - 실제 시각
 *    INL 후 = g_cal[i] - c_i               [ps]
 *  [통계]
 *    min/max (DNL), max|.| 와 그 탭 (INL), RMS = 탭을 똑같이 센 것,
 *    가중 RMS = 탭마다 val 히트 수로 가중 = 히트가 그 탭에 떨어질 확률(=탭 폭)로 가중 —
 *    "실제 측정 하나가 평균적으로 겪는 오차". 창 끝 탭이 max 를 좌우하는지 보려고 양 끝을
 *    0/2/5/10 탭씩 빼고 각각 찍는다 (CLAUDE.md "Do not let edge artifacts become headline numbers").
 *    요약에는 5 탭을 뺀 값을 올리고, 네 경우는 모두 [3] 에 남긴다.
 *  [잡음 바닥 — 이보다 작은 값은 통계 흔들림과 구분되지 않는다]
 *    DNL : 히스토그램 하나당 약 1/sqrt(H/N) LSB (탭마다 푸아송), 교정 후는 두 개의 차라 x sqrt(2)
 *    INL : 창 가운데에서 약 2500/sqrt(H) ps (이항분포), 교정 후는 x sqrt(2)
 *    교정표가 정수 ps 라서 생기는 반올림 오차(약 0.29 ps RMS)도 교정 후 값에 섞인다.
 *  [RAM] 교정표 RAM 은 건드리지 않는다.
 */
static const int EVAL_TRIMS[] = { 0, 2, 5, 10 };
#define N_TRIMS     (int)(sizeof(EVAL_TRIMS) / sizeof(EVAL_TRIMS[0]))
#define SUMMARY_TRIM 2              /* EVAL_TRIMS[2] = 5 탭 */

typedef struct {
    int ok, temp;                   /* temp : val 히스토그램 평균 온도 [0.01 C] */
    u32 hv;                         /* val 창 안 히트 수 */
    s64 nf_dnl, nf_inl;             /* 잡음 바닥 (교정 전 기준) : mLSB, 0.01 ps */
    stat_t db, da, ib, ia;          /* SUMMARY_TRIM 기준 */
} eval_res_t;

static void eval_inl(int detail, eval_res_t *er)
{
    histo_info_t inf;
    int lo = g_win_lo, hi = g_win_hi, i, t, r, vlo, vhi;
    u32 N;
    u64 Hc = 0, Hv = 0, Cv;
    stat_t db, da, ib, ia;

    er->ok = 0;
    xil_printf("\r\n[3] ===== INL / DNL : before vs after calibration =====\r\n");
    xil_printf("before = equal-width taps over the calibration window\r\n");
    xil_printf("after  = code-density table from [2]\r\n");
    xil_printf("truth  = a NEW independent histogram (never the one the table was built from)\r\n");
    if (!g_cal_valid || lo < 0) { xil_printf("!! no calibration. Skipped.\r\n"); return; }
    N = (u32)(hi - lo + 1);

    xil_printf("acquiring the independent histogram (%d hits) ...\r\n", MODE1_HITS);
    r = acquire_histo(MODE1_HITS, g_histo_val, &inf);
    if (r != 1) {
        xil_printf("!! histogram %s. Skipped.\r\n", r < 0 ? "timed out" : "failed (HIT_CNT mismatch)");
        return;
    }
    for (i = lo; i <= hi; i++) { Hc += g_histo[i]; Hv += g_histo_val[i]; }
    if (Hc == 0 || Hv == 0) { xil_printf("!! empty window. Skipped.\r\n"); return; }
    er->hv   = (u32)Hv;
    er->temp = (inf.t0 + inf.t1) / 2;

    xil_printf("window %d~%d : N = %d taps, LSB = ", lo, hi, N);
    print_fix((s64)(500000u / N), 2);
    xil_printf(" ps (mean tap width)\r\n");
    xil_printf("cal : %d hits in window, die ", (u32)Hc);  print_centi("", g_cal_temp);
    xil_printf("val : %d hits in window, die ", (u32)Hv);  print_centi("", er->temp);
    if (find_window(g_histo_val, &vlo, &vhi) && (vlo != lo || vhi != hi))
        xil_printf("note: the val histogram alone would pick window %d~%d. The window moved;\r\n"
                   "      the calibration window is still used so both tables are judged on the same taps.\r\n",
                   vlo, vhi);

    er->nf_dnl = (s64)isqrt64(1000000u * (u64)N / Hv);         /* mLSB */
    er->nf_inl = (s64)(250000000u / isqrt64(Hv * 1000000u));   /* 0.01 ps : 2500/sqrt(H) x 100 */
    xil_printf("noise floor : DNL ");  print_fix(er->nf_dnl, 3);
    xil_printf(" LSB (after ");        print_fix(er->nf_dnl * 1414 / 1000, 3);
    xil_printf(")   INL ");            print_fix(er->nf_inl, 2);
    xil_printf(" ps (after ");         print_fix(er->nf_inl * 1414 / 1000, 2);
    xil_printf(") at mid window\r\n");

    for (t = 0; t < N_TRIMS; t++) {
        int a = lo + EVAL_TRIMS[t], b = hi - EVAL_TRIMS[t];
        st_init(&db); st_init(&da); st_init(&ib); st_init(&ia);
        Cv = 0;
        for (i = lo; i <= hi; i++) {
            u64 hv = g_histo_val[i], hc = g_histo[i];
            s64 c100 = (s64)(((2u * Cv + hv) * 500000u + Hv) / (2u * Hv));
            s64 wv   = (s64)((hv * N * 1000u + Hv / 2u) / Hv);    /* w/LSB x 1000 */
            s64 wc   = (s64)((hc * N * 1000u + Hc / 2u) / Hc);
            Cv += hv;
            if (i < a || i > b) continue;
            st_add(&db, wv - 1000, i, (u32)hv);
            st_add(&da, wc - wv,   i, (u32)hv);
            st_add(&ib, (s64)g_lin[i] * 100 - c100, i, (u32)hv);
            st_add(&ia, (s64)g_cal[i] * 100 - c100, i, (u32)hv);
        }
        if (t == SUMMARY_TRIM) { er->db = db; er->da = da; er->ib = ib; er->ia = ia; }
        xil_printf("# trim %d taps each end (taps %d~%d)\r\n", EVAL_TRIMS[t], a, b);
        xil_printf("#   DNL [LSB]  before  min ");  print_fix(db.vmin, 3);
        xil_printf("  max ");                        print_fix(db.vmax, 3);
        xil_printf("  rms ");                        print_fix(st_rms(&db), 3);
        xil_printf("\r\n#              after   min ");  print_fix(da.vmin, 3);
        xil_printf("  max ");                        print_fix(da.vmax, 3);
        xil_printf("  rms ");                        print_fix(st_rms(&da), 3);
        xil_printf("\r\n#   INL [ps]   before  max|.| "); print_fix(ib.amax, 2);
        xil_printf(" (tap %d, ", ib.at);             print_fix(ib.amax * (s64)N / 500, 3);
        xil_printf(" LSB)  p-p ");                   print_fix(ib.vmax - ib.vmin, 2);
        xil_printf("  rms ");                        print_fix(st_rms(&ib), 2);
        xil_printf("  weighted rms ");               print_fix(st_wrms(&ib), 2);
        xil_printf("\r\n#              after   max|.| "); print_fix(ia.amax, 2);
        xil_printf(" (tap %d, ", ia.at);             print_fix(ia.amax * (s64)N / 500, 3);
        xil_printf(" LSB)  p-p ");                   print_fix(ia.vmax - ia.vmin, 2);
        xil_printf("  rms ");                        print_fix(st_rms(&ia), 2);
        xil_printf("  weighted rms ");               print_fix(st_wrms(&ia), 2);
        xil_printf("\r\n");
    }

    if (detail) {
        xil_printf("\r\n----- CSV BEGIN (save as val_histogram.csv) -----\r\n");
        xil_printf("Tap_Index,Hit_Count\r\n");
        for (i = 0; i < NUM_TAPS; i++) xil_printf("%d,%d\r\n", i, g_histo_val[i]);
        xil_printf("----- CSV END -----\r\n");
        xil_printf("\r\n----- CSV BEGIN (save as inl_dnl_eval.csv) -----\r\n");
        xil_printf("Tap,Hits_cal,Hits_val,Before_ps,After_ps,True_ps_x100,"
                   "DNL_before_mLSB,DNL_after_mLSB,INL_before_ps_x100,INL_after_ps_x100\r\n");
        Cv = 0;
        for (i = lo; i <= hi; i++) {
            u64 hv = g_histo_val[i], hc = g_histo[i];
            s64 c100 = (s64)(((2u * Cv + hv) * 500000u + Hv) / (2u * Hv));
            s64 wv   = (s64)((hv * N * 1000u + Hv / 2u) / Hv);
            s64 wc   = (s64)((hc * N * 1000u + Hc / 2u) / Hc);
            Cv += hv;
            xil_printf("%d,%d,%d,%d,%d,%d,%d,%d,%d,%d\r\n", i, (u32)hc, (u32)hv, g_lin[i], g_cal[i],
                       (int)c100, (int)(wv - 1000), (int)(wc - wv),
                       (int)((s64)g_lin[i] * 100 - c100), (int)((s64)g_cal[i] * 100 - c100));
        }
        xil_printf("----- CSV END -----\r\n");
    }
    er->ok = 1;
}

/* ================================================================ 보고서 [4] 위상 스윕
 *
 *  ★ 2026-09-16 : Mode 0 교정 확인 — 내부 루프백 위상 스윕
 *
 *  [무엇을 보나] 교정표를 적용한 timestamp_ps 가 "아는 시간"과 맞는지 본다. 아는 시간은 둘이다.
 *      (1) 히트 간격 = 주기(클럭 수) x 5000 ps — 이웃 타임스탬프 차이가 이 값이어야 한다.
 *      (2) 위상 이동 = 위상 스텝 x 17.857 ps — 위상을 옮기면 타임스탬프가 그만큼 움직여야 한다.
 *    (1)은 coarse 계수와 파이프라인을, (2)는 fine 과 교정표를 시험한다.
 *  [알 수 있는 것 / 없는 것] 간격과 선형성은 검증된다. 생성 경로의 고정 지연은 상수라
 *    간격에서 상쇄된다. 절대 시각(원점)과 클럭의 ppm 오차는 이 방법으로 검증되지 않는다.
 *    시간 기준이 같은 MMCM 이라 교정표 오차와 MMCM 위상 스텝 불균일이 구분되지 않는다.
 *  [산포의 뜻] 흔들림에는 히트 생성 경로의 지터가 섞여 있다. TDC 자체 정밀도로 읽으면 안 된다
 *    (2026-08-03 보고서 §11-3). 이 절의 숫자는 상한이다.
 *  [위상점 하나] ts mod 5000 의 평균 — 위상 전달함수의 한 점. 첫 값 기준으로 +-2500 안에 접어서
 *    평균한다 (지터가 클럭 경계를 걸치면 0 과 5000 이 섞이기 때문, 2026-09-16).
 *  [★ 2026-09-17 저녁 : 판에서 직접 직선 적합]
 *    위상점들을 언랩해 최소제곱 직선 y = a + b x (x = 위상 스텝) 로 맞추고,
 *      기울기 오차 [ppm] = (b / (1000/56) - 1) x 1e6
 *      잔차 = y - (a + b x) 의 RMS (자유도 n-2) 와 최대 |값|
 *    를 찍는다. 2026-09-16 에 Orin 에서 한 계산(기울기 비 1.00048, 잔차 RMS 9.54 ps)과 같은 정의다.
 *    제곱근은 libm 없이 isqrt64 로 한다 (standalone 링크에 libm 이 없다).
 */
typedef struct {
    int ok;
    u32 npts;
    s32 mean100[PHASE_STEPS];       /* 위상점별 ts mod 5000 평균 [0.01 ps] */
    u32 spread[PHASE_STEPS];        /* 위상점별 최대-최소 [ps] */
    u32 n_int, max_abs, coarse_err;
    s64 sum_err;
    u64 sum_err2;
    int t0, t1;                     /* 스윕 시작/끝 다이 온도 [0.01 C] */
    s64 slope_ppm, res_rms100, res_max100;
    int res_max_ph;
} sweep_res_t;

static sweep_res_t g_sw[2];         /* [0] = 교정 전, [1] = 교정 후 */

static void sweep_fit(sweep_res_t *r)
{
    double sx = 0, sy = 0, sxx = 0, sxy = 0, a, b, e, ss = 0, off = 0, y, prev = 0;
    double xs[PHASE_STEPS], ys[PHASE_STEPS];
    u32 i, n = r->npts;
    int maxat = 0;
    double maxe = 0;

    r->slope_ppm = 0; r->res_rms100 = 0; r->res_max100 = 0; r->res_max_ph = -1;
    if (n < 3u) return;
    for (i = 0; i < n; i++) {
        y = r->mean100[i] / 100.0;
        if (i > 0) {                               /* 5000 ps 경계 언랩 */
            while (y + off - prev < -2500.0) off += 5000.0;
            while (y + off - prev >  2500.0) off -= 5000.0;
        }
        y += off;
        prev = y;
        xs[i] = (double)M0_PHASES[i];
        ys[i] = y;
        sx += xs[i]; sy += y; sxx += xs[i] * xs[i]; sxy += xs[i] * y;
    }
    b = (n * sxy - sx * sy) / (n * sxx - sx * sx);
    a = (sy - b * sx) / n;
    for (i = 0; i < n; i++) {
        e = ys[i] - (a + b * xs[i]);
        ss += e * e;
        if ((e < 0 ? -e : e) > maxe) { maxe = (e < 0 ? -e : e); maxat = (int)xs[i]; }
    }
    r->slope_ppm  = (s64)((b / (1000.0 / 56.0) - 1.0) * 1.0e6 + (b >= 1000.0 / 56.0 ? 0.5 : -0.5));
    r->res_rms100 = (s64)isqrt64((u64)(ss / (double)(n - 2u) * 10000.0));
    r->res_max100 = (s64)(maxe * 100.0 + 0.5);
    r->res_max_ph = maxat;
}

/* 스윕 한 번. tab 은 CSV 에 붙는 표 번호 (1 = 교정 전, 2 = 교정 후). 실패하면 0 */
static int m0_sweep_run(u32 tab, sweep_res_t *r, int detail)
{
    u32 ip, i, cur, spin, got, ph, ref, per = M0_PERIOD;
    u64 ts, prev, d, exp_ps = (u64)M0_PERIOD * 5000u;
    s64 err, sum_rel;
    s32 rel, rel_lo, rel_hi;

    r->ok = 0; r->npts = 0; r->n_int = 0; r->max_abs = 0; r->coarse_err = 0;
    r->sum_err = 0; r->sum_err2 = 0;
    r->t0 = temp_centi(RD(R_TEMP));

    for (ip = 0; ip < M0_NPH; ip++) {
        ph = M0_PHASES[ip];

        WR(R_PHASE, ph);
        for (spin = 0; spin < 1000000u; spin++)
            if ((RD(R_STATUS) & S_PHASE_BUSY) == 0) break;
        cur = (RD(R_PHASE) >> 16) & 0x1FFu;
        if (cur != ph) {
            xil_printf("!! phase %d requested, %d reported. The phase shifter did not settle.\r\n", ph, cur);
            return 0;
        }

        WR(R_M0PER, per);
        WR(R_CAPN,  M0_HITS);
        WR(R_CTRL,  C_SRC_DPS | C_START);        /* CAP_FMT = 0 -> timestamp_ps */
        if (!wait_done(2000)) {
            got = RD(R_CAPCNT);
            WR(R_CTRL, 0);
            xil_printf("!! timeout at phase %d.  CAP_CNT = %d / %d\r\n", ph, got, M0_HITS);
            if (got == 0)
                xil_printf("   no hits : check regmap ver (needs %d), MMCM lock, M0PER readback %d\r\n",
                           M0_MAP_VER, RD(R_M0PER));
            return 0;
        }
        got = RD(R_CAPCNT);
        if (got > M0_HITS) got = M0_HITS;
        if (got > (u32)CAP_MAX)   got = (u32)CAP_MAX;   /* ★ 배열 밖 쓰기를 두 겹으로 막는다 */
        for (i = 0; i < got; i++) {
            g_cap_lo[i] = RD(R_CAP_LO(i));
            g_cap_hi[i] = RD(R_CAP_HI(i));
        }
        WR(R_CTRL, 0);
        if (got < 2u) { xil_printf("!! phase %d : only %d hits\r\n", ph, got); return 0; }

        /* 이웃 간격 오차 — 5000 ps 의 절반 이상 틀리면 coarse 오류로 센다 */
        prev = ((u64)g_cap_hi[0] << 32) | g_cap_lo[0];
        ref  = (u32)(prev % 5000u);
        for (i = 1; i < got; i++) {
            ts   = ((u64)g_cap_hi[i] << 32) | g_cap_lo[i];
            d    = ts - prev;
            prev = ts;
            err  = (s64)d - (s64)exp_ps;
            r->sum_err  += err;
            r->sum_err2 += (u64)(err * err);
            r->n_int++;
            if ((u32)(err < 0 ? -err : err) > r->max_abs) r->max_abs = (u32)(err < 0 ? -err : err);
            if (err >= 2500 || err <= -2500) r->coarse_err++;
        }
        /* ts mod 5000 을 첫 값 기준으로 +-2500 안에 접어 넣고 평균한다 */
        sum_rel = 0; rel_lo = 0; rel_hi = 0;
        for (i = 0; i < got; i++) {
            ts  = ((u64)g_cap_hi[i] << 32) | g_cap_lo[i];
            rel = (s32)(u32)(ts % 5000u) - (s32)ref;
            if (rel >  2500) rel -= 5000;
            if (rel < -2500) rel += 5000;
            sum_rel += (s64)rel;
            if (rel < rel_lo) rel_lo = rel;
            if (rel > rel_hi) rel_hi = rel;
        }
        r->mean100[ip] = (s32)((((s64)ref * 100 + sum_rel * 100 / (s64)got) + 500000) % 500000);
        r->spread[ip]  = (u32)(rel_hi - rel_lo);
        r->npts = ip + 1u;
        if (detail >= 2)                 /* ★ 2026-09-21 : 키 4 는 히트마다 한 줄 */
            for (i = 0; i < got; i++)
                xil_printf("%d,%d,%u,%u\r\n", ph, i, g_cap_lo[i], g_cap_hi[i]);
        if (detail == 1)
            xil_printf("%d,%d,%d,%d,%d\r\n", tab, ph, got, r->mean100[ip], r->spread[ip]);
    }
    r->t1 = temp_centi(RD(R_TEMP));
    sweep_fit(r);
    r->ok = 1;
    return 1;
}

/* ================================================================ 키 4 : DPS 위상 스윕
 *
 *  ★ 2026-09-21 (사용자 지정) : 위상 50 / 100 / 150 / 200 / 250 스텝에서 각 200발.
 *  [무엇을 보나]
 *    (1) 위상 단계 사이의 간격 — 위상을 50 스텝 옮기면 타임스탬프가 50 x 17.857 = 892.86 ps
 *        움직여야 한다. 이것이 fine 과 교정표를 시험한다.
 *    (2) 이웃 히트 간격 — 생성기 주기(50 클럭 = 250000 ps)와 같아야 한다. coarse 계수를 시험한다.
 *  [쓰는 표] RAM 에 지금 있는 표를 그대로 쓴다. 키 1 뒤라면 코드밀도 표다.
 *  [주의] 흔들림에는 히트 생성 경로의 지터가 섞여 있어 TDC 자체 정밀도로 읽으면 안 된다
 *    (2026-08-03 보고서 §11-3). 시간 기준이 같은 MMCM 이라 교정표 오차와 MMCM 스텝 불균일도
 *    구분되지 않는다. 이 절의 숫자는 상한이다.
 */
static void cmd_phase_sweep(void)
{
    sweep_res_t *r = &g_sw[0];
    u32 i;
    s64 prev = 0, cur, d, expect100 = (s64)(M0_PHASES[1] - M0_PHASES[0]) * 100000 / 56;

    xil_printf("\r\n===== DPS phase sweep =====\r\n");
    if ((RD(R_BUILD) & 0xFFu) < M0_MAP_VER) {
        xil_printf("!! regmap ver %d has no hit generator (need %d). Rebuild with the current RTL.\r\n",
                   RD(R_BUILD) & 0xFFu, M0_MAP_VER);
        return;
    }
    if (!g_cal_valid)
        xil_printf("WARNING: key 1 was not run in this session. The RAM holds whatever table was there\r\n"
                   "         (a freshly programmed FPGA holds the linear ramp) and DANGER may be the\r\n"
                   "         power-up default 40/220, which can add 5000 ps coarse errors.\r\n");
    xil_printf("phases :");
    for (i = 0; i < M0_NPH; i++) xil_printf(" %d", M0_PHASES[i]);
    xil_printf(" steps,  %d hits each,  period %d cycles (%d ps)\r\n",
               M0_HITS, M0_PERIOD, M0_PERIOD * 5000u);
    xil_printf("one phase step = 17.857 ps, so %d steps = ", M0_PHASES[1] - M0_PHASES[0]);
    print_fix(expect100, 2);
    xil_printf(" ps\r\n");

    xil_printf("\r\n----- CSV BEGIN (save as dps_sweep.csv) -----\r\n");
    xil_printf("Phase_Step,Index,TS_Lo,TS_Hi\r\n");
    if (!m0_sweep_run(0u, r, 2)) {
        xil_printf("----- CSV END -----\r\n");
        WR(R_M0PER, 0); WR(R_PHASE, 0); WR(R_CTRL, 0);
        return;
    }
    xil_printf("----- CSV END -----\r\n");
    WR(R_M0PER, 0);
    WR(R_PHASE, 0);

    /* 위상 단계별 간격 : ts mod 5000 의 평균을 언랩해 이웃 차이를 본다 */
    xil_printf("\r\n# phase, ts mod 5000 mean [ps], step from previous [ps], error vs expected [ps], spread [ps]\r\n");
    for (i = 0; i < r->npts; i++) {
        cur = r->mean100[i];
        if (i > 0) {
            while (cur - prev < -250000) cur += 500000;   /* 5000 ps 경계 언랩 */
            while (cur - prev >  250000) cur -= 500000;
        }
        xil_printf("# %d  ", M0_PHASES[i]);
        print_fix(r->mean100[i], 2);
        if (i > 0) {
            d = cur - prev;
            xil_printf("   step ");   print_fix(d, 2);
            xil_printf("   error ");  print_fix(d - expect100, 2);
        } else {
            xil_printf("   step    -         error    -     ");
        }
        xil_printf("   spread %d\r\n", r->spread[i]);
        prev = cur;
    }

    xil_printf("\r\nlinear fit over %d points : slope error %d ppm, residual rms ", r->npts, (int)r->slope_ppm);
    print_fix(r->res_rms100, 2);
    xil_printf(" ps, max ");
    print_fix(r->res_max100, 2);
    xil_printf(" ps (phase %d)\r\n", r->res_max_ph);
    {
        s64 n = (s64)r->n_int;
        s64 mean100 = n ? r->sum_err * 100 / n : 0;
        s64 sd100 = (n > 1) ? (s64)isqrt64((r->sum_err2 * 10000u
                       - (u64)(mean100 * mean100) * (u64)n) / (u64)(n - 1)) : 0;
        xil_printf("hit intervals : n %d, mean ", (int)n); print_fix(mean100, 2);
        xil_printf(" ps, sd ");  print_fix(sd100, 2);
        xil_printf(" ps, max|err| %d ps, coarse errors (>= 2500 ps) %d\r\n", r->max_abs, r->coarse_err);
    }
    xil_printf("die temperature : ");  print_fix(r->t0, 2);
    xil_printf(" -> ");                print_fix(r->t1, 2);
    xil_printf(" C\r\n");
    xil_printf("done. generator stopped, phase back to 0.  DROP_CNT = %d\r\n", RD(R_DROP));
}

/* ================================================================ 키 2 : 외부 LVDS 신호 측정
 *  ★ 2026-09-21 (사용자 지정) : 키 1 없이 하면 경고만 찍고 진행한다 (막지는 않는다).
 *  교정 없이 재면 두 가지가 전원 인가 값이다 —
 *    교정표 RAM = 선형 램프 (FPGA 를 새로 구운 경우)  -> fine 이 약 17 % 줄어 나온다
 *    DANGER = 40/220                                  -> 5000 ps 급 coarse 오류가 섞일 수 있다
 */
static void cmd_ext_measure(void)
{
    xil_printf("\r\n===== external LVDS signal measurement =====\r\n");
    if (!g_cal_valid) {
        xil_printf("WARNING: key 1 (code density) was not run in this session.\r\n");
        xil_printf("         calibration table = whatever the RAM holds (linear ramp on a fresh FPGA)\r\n");
        xil_printf("         DANGER = ");
        xil_printf("%d/%d", RD(R_DANGER) & 0x1FFu, (RD(R_DANGER) >> 16) & 0x1FFu);
        if (RD(R_DANGER) == ((220u << 16) | 40u))
            xil_printf("  <- power-up default, usually wrong for this build");
        xil_printf("\r\n         timestamps will be off. Run key 1 first for trustworthy values.\r\n");
    }
    cmd_mode2(1024u, 0);
}

/* ================================================================ 키 3 : 교정 전/후 INL·DNL */
static void cmd_inl_test(void)
{
    eval_res_t er;

    xil_printf("\r\n===== INL / DNL : before vs after calibration (for the paper) =====\r\n");
    if (!g_cal_valid || g_win_lo < 0) {
        xil_printf("!! run key 1 first (it builds the calibration table and the window).\r\n");
        return;
    }
    eval_inl(1, &er);                    /* 1 = 원자료 CSV 도 찍는다 (논문용) */
}

static void help(void)
{
    /* ★ 2026-09-21 : 메뉴 재편 (사용자 지정) */
    xil_printf("\r\n===== COMMANDS =====\r\n");
    xil_printf("  i : identity / status\r\n");
    xil_printf("  1 : Mode 1 code density (%d hits) -> CSV, danger thresholds, calibration table\r\n",
               MODE1_HITS);
    xil_printf("      RAM write/readback test first, then the table is computed here and written\r\n");
    xil_printf("      into the PL calibration RAM\r\n");
    xil_printf("  2 : external LVDS signal measurement (Mode 2 capture, timestamp_ps) -> CSV\r\n");
    xil_printf("      warns when key 1 was not run in this session\r\n");
    xil_printf("  3 : INL / DNL before vs after calibration -> CSV (code density, for the paper)\r\n");
    xil_printf("      takes a second independent histogram; needs key 1\r\n");
    xil_printf("  4 : DPS phase sweep : phases");
    { u32 i; for (i = 0; i < M0_NPH; i++) xil_printf(" %d", M0_PHASES[i]); }
    xil_printf(", %d hits each -> CSV\r\n", M0_HITS);
    xil_printf("  h : this help\r\n");
}

int main(void)
{
    xil_printf("\r\n\r\n############################################\r\n");
    xil_printf("  ZedBoard TDC controller\r\n");
    xil_printf("  Generated by Claude Code, 2026-09-06\r\n");
    xil_printf("############################################\r\n");

    /* ★ 2026-09-17 : 부팅 자동 교정 없음. 교정 전 상태로 잴 수 있어야 하기 때문이다 (키 3).
     *   ★ 2026-09-21 : 키 2/3/4 는 키 1 없이 돌리면 경고하거나 거부한다. */
    xil_printf("\r\n[boot] calibration NOT run yet. Press 1 before measuring (keys 2 and 4 warn, key 3 refuses).\r\n");
    xil_printf("       a freshly programmed FPGA holds the linear ramp and DANGER 40/220.\r\n");

    cmd_info();
    help();

    for (;;) {
        u8 c;
        xil_printf("\r\n> ");
        c = read_key();

        switch (c) {                                  /* ★ 2026-09-21 : 메뉴 재편 */
        case 'i': cmd_info();               break;
        /* ★ 2026-09-21 : 표를 쓰기 전에 RAM 이 멀쩡한지 먼저 본다 (A 램프 / B 비트반전 / 되돌리기).
         *   키 1 이 이어서 교정표를 덮어쓰므로 시험 패턴이 남지 않는다. */
        case '1': (void)cmd_cal_test(); cmd_mode1(MODE1_HITS, 1); break;
        case '2': cmd_ext_measure();        break;
        case '3': cmd_inl_test();           break;
        case '4': cmd_phase_sweep();        break;
        case 'h': help();                   break;
        default:  xil_printf("unknown key. Press 'h' for help.\r\n"); break;
        }
    }
    return 0;
}
