#!/usr/bin/env python3
# Generated by Claude Code, 2026-09-22
# ---------------------------------------------------------------------------
# plot_phase_sweep.py — 키 4(DPS 위상 스윕) 13점을 그린다.
#
#  [왜 그리나] "기울기를 못 정한다" 는 말이 표로는 안 와닿는다. 그림 두 장이면 끝난다 :
#    (위) 측정점과 적합 직선 — 완벽한 직선으로 보인다. 이 그림으로는 아무것도 못 본다.
#    (아래) 직선을 뺀 잔차 — 여기서 비로소 흔들림이 보이고, 우리가 재려는 기울기 차이가
#           그 흔들림보다 작다는 것이 드러난다.
#
#  [입력] 보드 로그의 "# <위상>  <평균>   step ..." 요약 줄. 로그 경로를 인자로 준다.
#  [출력] Markdown/fig/2026-09-22_phase_sweep.png
# ---------------------------------------------------------------------------
import re
import sys

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

STEP_PS = 1000.0 / 56.0          # phase_shifter.v 의 설계값 17.857 ps/step

# 한글 글꼴. Orin 에는 Noto Sans CJK 가 깔려 있는데, matplotlib 의 목록에는
# .ttc 안의 한 얼굴만 (JP 로) 잡히는 경우가 있다. CJK 글꼴은 한글도 담고 있으므로
# 이름이 JP 여도 한글이 제대로 나온다. 없으면 경고만 내고 기본 글꼴로 간다.
_have = {f.name for f in matplotlib.font_manager.fontManager.ttflist}
for _f in ('Noto Sans CJK KR', 'Noto Sans CJK JP', 'NanumGothic',
           'Noto Serif CJK KR', 'Noto Serif CJK JP'):
    if _f in _have:
        plt.rcParams['font.family'] = _f
        break
else:
    print("[!] 한글 글꼴을 못 찾았다. 글자가 네모로 나온다.")
plt.rcParams['axes.unicode_minus'] = False


def read_points(path):
    ph, mean = [], []
    for l in open(path, encoding='utf-8', errors='replace'):
        m = re.match(r'^#\s+(\d+)\s+([\d.]+)\s+step', l)
        if m:
            ph.append(float(m.group(1)))
            mean.append(float(m.group(2)))
    return np.array(ph), np.array(mean)


def unwrap(y):
    """5000 ps 경계 언랩. 보드(m0_fit)와 같은 규칙."""
    out, off = [y[0]], 0.0
    for v in y[1:]:
        w = v + off
        while w - out[-1] < -2500:
            off += 5000
            w = v + off
        while w - out[-1] > 2500:
            off -= 5000
            w = v + off
        out.append(w)
    return np.array(out)


def main(path, out_png):
    ph, mean = read_points(path)
    if len(ph) < 3:
        print(f"요약 줄을 {len(ph)}개밖에 못 찾았다: {path}")
        return 1
    y = unwrap(mean)
    b, a = np.polyfit(ph, y, 1)
    res = y - (a + b * ph)
    n = len(ph)
    s = np.sqrt((res ** 2).sum() / (n - 2))
    se_b = s / np.sqrt(((ph - ph.mean()) ** 2).sum())
    ppm = (b / STEP_PS - 1) * 1e6
    ppm_se = se_b / STEP_PS * 1e6
    span = ph.max() - ph.min()

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(9, 8), height_ratios=[1, 1.15])

    ax1.plot(ph, y, 'o', ms=7, color='#2b6cb0', label='측정 (한 점 = 200발 평균)')
    xs = np.linspace(ph.min(), ph.max(), 100)
    ax1.plot(xs, a + b * xs, '-', lw=1.2, color='#e53e3e',
             label=f'최소제곱 직선 ({b:.4f} ps/step)')
    ax1.set_ylabel('타임스탬프 (언랩) [ps]')
    ax1.set_title('위상 스윕 13점 — 이 그림으로는 아무것도 판단할 수 없다', fontsize=11)
    ax1.legend(fontsize=9)
    ax1.grid(alpha=.3)

    ax2.axhline(0, color='#888', lw=.8)
    ax2.plot(ph, res, 'o-', ms=7, lw=1, color='#2b6cb0', label='직선을 뺀 잔차')
    # 기울기 후보들이 잔차 그림에서 어떤 기울기로 보이는가
    for cand, col, ls in ((228, '#38a169', ':'), (480, '#d69e2e', '-.'), (812, '#e53e3e', '--')):
        tilt = (cand - ppm) * 1e-6 * STEP_PS * (ph - ph.mean())
        ax2.plot(ph, tilt, ls, lw=1.4, color=col, label=f'{cand:+d} ppm 이면 이 기울기')
    ax2.fill_between(ph, -s, s, color='#2b6cb0', alpha=.12,
                     label=f'잔차 1σ = ±{s:.1f} ps')
    ax2.set_xlabel('MMCM 위상 스텝')
    ax2.set_ylabel('잔차 [ps]')
    ax2.set_title(f'잔차 — 재려는 기울기 차이({span * STEP_PS * 812e-6:.1f} ps)가 '
                  f'흔들림(±{s:.1f} ps)보다 작다', fontsize=11)
    ax2.legend(fontsize=8, ncol=2)
    ax2.grid(alpha=.3)

    fig.suptitle(f'기울기 오차 {ppm:+.0f} ± {ppm_se:.0f} ppm (1σ)  →  0 에서 '
                 f'{abs(ppm) / ppm_se:.2f}σ,  구별되지 않는다', fontsize=12)
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    fig.savefig(out_png, dpi=130)
    print(f"기울기 {b:.4f} ps/step ({ppm:+.0f} ppm), 잔차 rms {s:.2f} ps, SE ±{ppm_se:.0f} ppm")
    print(f"전체 구간 {span:.0f} 스텝 = {span * STEP_PS:.0f} ps 에서 {ppm:+.0f} ppm 이 만드는 차이"
          f" = {span * STEP_PS * ppm * 1e-6:.2f} ps")
    print(f"saved: {out_png}")
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2
                  else 'Markdown/fig/2026-09-22_phase_sweep.png'))
