#!/usr/bin/env python3
# Generated by Claude Code, 2026-09-22
# ---------------------------------------------------------------------------
# tdc_repeatability.py — UART 로그에서 Mode 1 히스토그램을 전부 뽑아
#   "같은 방법으로 여러 번 재면 같은 교정표가 나오는가" 를 잰다.
#
#  [왜 이게 필요한가]
#    보드가 찍는 "교정 후 INL 가중 RMS" 는 사실 **재현성 숫자**다. 표를 cal 히스토그램으로
#    만들고 val 히스토그램으로 채점하므로, 두 번 잰 것이 얼마나 같은지를 재는 것이다.
#    (2026-09-21 단독 TDC 로그에서 확인 : 원자료로 다시 계산한 cal↔val 표 차이의 히트 가중
#     rms 가 1.53 ps 로, 보드가 찍은 1.56 ps 와 같은 양이었다.)
#    그래서 "정확도" 가 아니다. 진짜 재현성을 보려면 런을 여러 번 모아야 한다.
#
#  [무엇을 세는가]  세 가지를 구분해서 낸다.
#    (1) 칸 폭 재현성   : w[i] = h[i]/H x 5000 ps 의 런 간 표준편차
#    (2) 교정표 재현성  : 표[i] = (앞칸합 + h[i]/2)/H x 5000 ps 의 런 간 표준편차
#                         ★ 이것이 "교정을 다시 하면 타임스탬프가 얼마나 달라지나" 다
#    (3) 산탄잡음 기대치 : 같은 히스토그램을 푸아송으로 다시 뽑아 (2)를 재계산한다.
#                         관측이 이보다 크면 히트 수를 늘려도 안 줄어드는 성분이 있다는 뜻이다.
#
#  [왜 표를 따로 보나] 칸 폭 오차는 표에서 누적된다. 폭이 0.36 ps 씩 흔들려도 표는 그 누적이라
#    훨씬 커질 수 있다. 실제로 타임스탬프에 쓰이는 값은 표다.
#
#  [주의 — 같은 빌드의 로그만 섞을 것]
#    빌드가 바뀌면 지연선 배치가 달라져 창이 옮겨간다 (2026-09-21 : 단독 2~319, 통합 2~321).
#    다른 빌드의 히스토그램을 한 묶음으로 넣으면 "재현성" 이 아니라 "빌드 차이" 를 재게 된다.
#
#  [사용법]  python3 python/tdc_repeatability.py <로그.csv> [로그2.csv ...] [--win LO HI]
#    로그 안의 "----- CSV BEGIN (save as tap_histogram.csv) -----" 과 val_histogram 블록을
#    전부 찾는다. 키 1 을 한 번, 키 3 을 N 번 누르면 독립 히스토그램이 N+1 개 모인다.
#    창은 로그의 "window A~B" 줄에서 읽는다. 없으면 히트가 있는 칸 범위를 쓰고,
#    --win 으로 직접 줄 수도 있다.
# ---------------------------------------------------------------------------
import re
import sys

import numpy as np


def parse(path):
    """로그에서 (이름, 히스토그램, 온도) 목록과 창을 뽑는다."""
    lines = open(path, encoding='utf-8', errors='replace').read().splitlines()
    out, temp, t_start, win = [], None, None, None
    for i, l in enumerate(lines):
        m = re.search(r'window\s+(\d+)~(\d+)', l)
        if m:
            win = (int(m.group(1)), int(m.group(2)))
        # 온도 줄이 세 가지 형태로 찍힌다. 키 1 은 start/end 두 줄(평균을 쓴다),
        # 키 3 은 "val : ... die 45.53 C" 한 줄이다. 블록 바로 앞의 값을 쓴다.
        m = re.search(r'die temp start\s*([-\d.]+)\s*C', l)
        if m:
            t_start = float(m.group(1))
            temp = t_start
        m = re.search(r'die temp end\s*([-\d.]+)\s*C', l)
        if m and t_start is not None:
            temp = (t_start + float(m.group(1))) / 2
        m = re.search(r'^\s*(?:cal|val) :.*die\s*([-\d.]+)\s*C', l)
        if m:
            temp = float(m.group(1))

        m = re.search(r'CSV BEGIN \(save as (\w+)\.csv\)', l)
        if not m or m.group(1) not in ('tap_histogram', 'val_histogram'):
            continue
        j = next((k for k in range(i + 1, len(lines)) if 'CSV END' in lines[k]), len(lines))
        rows = [(int(a), int(b)) for a, b in
                (mm.groups() for mm in
                 (re.match(r'^\s*(\d+),(\d+)\s*$', x) for x in lines[i + 1:j]) if mm)]
        if rows:
            d = dict(rows)
            h = np.array([d[k] for k in sorted(d)], float)
            out.append((f"{path.split('/')[-1]}:{i + 1}:{m.group(1)}", h, temp))
    return out, win


def widths(h):
    return h / h.sum() * 5000.0


def table(h):
    """칸 가운데 누적표. 보드(cmd_calibrate)와 같은 정의다."""
    C = np.concatenate([[0.0], np.cumsum(h)[:-1]])
    return (C + h / 2) / h.sum() * 5000.0


def main(argv):
    paths, win = [], None
    i = 0
    while i < len(argv):
        if argv[i] == '--win':
            win = (int(argv[i + 1]), int(argv[i + 2]))
            i += 3
        else:
            paths.append(argv[i])
            i += 1
    if not paths:
        print(__doc__ or "사용법: tdc_repeatability.py <로그.csv> [...] [--win LO HI]")
        return 2

    runs, autowin = [], None
    for p in paths:
        r, w = parse(p)
        runs += r
        autowin = autowin or w
    if len(runs) < 2:
        print(f"히스토그램이 {len(runs)}개뿐이다. 최소 2개가 있어야 재현성을 말할 수 있다.")
        print("키 1 을 한 번, 키 3 을 여러 번 누른 로그가 필요하다.")
        return 1

    if win is None:
        win = autowin
    if win is None:                       # 로그에 window 줄이 없으면 히트 범위로 정한다
        nz = np.nonzero(sum(h for _, h, _ in runs))[0]
        win = (int(nz[0]), int(nz[-1]))
        print(f"[!] 로그에 window 줄이 없어 히트가 있는 칸 범위를 창으로 썼다: {win[0]}~{win[1]}")
    LO, HI = win

    print(f"히스토그램 {len(runs)}개,  창 {LO}~{HI} ({HI - LO + 1}칸)")
    W, T = [], []
    for name, h, temp in runs:
        w = h[LO:HI + 1]
        t = float('nan') if temp is None else temp
        print(f"  {name:>46s}  창 안 {w.sum():>9,.0f}발  다이 {t:.2f} C")
        W.append(w)
        T.append(temp)
    W = np.array(W)

    t_all = np.array([table(w) for w in W])
    w_all = np.array([widths(w) for w in W])
    hits = W.mean(axis=0)

    w_sd = w_all.std(axis=0, ddof=1)
    t_sd = t_all.std(axis=0, ddof=1)
    wrms = np.sqrt((t_sd ** 2 * hits).sum() / hits.sum())
    obs = np.sqrt((t_sd ** 2).mean())

    print(f"\n[1] 칸 폭 재현성  : 런 간 sd  rms {np.sqrt((w_sd ** 2).mean()):.3f} ps, "
          f"최대 {w_sd.max():.3f} ps (탭 {LO + int(w_sd.argmax())})")
    print(f"[2] 교정표 재현성 : 런 간 sd  rms {obs:.3f} ps, "
          f"최대 {t_sd.max():.3f} ps (탭 {LO + int(t_sd.argmax())})")
    print(f"    히트 가중 rms = {wrms:.3f} ps   <- 실제 측정 하나가 평균적으로 겪는 재교정 차이")

    rng = np.random.default_rng(0)
    sim = [np.sqrt((np.array([table(rng.poisson(w).astype(float)) for w in W])
                    .std(axis=0, ddof=1) ** 2).mean()) for _ in range(200)]
    sim = np.array(sim)
    print(f"[3] 산탄잡음만이라면 : {sim.mean():.3f} +- {sim.std():.3f} ps   "
          f"(관측/기대 = {obs / sim.mean():.2f} 배)")
    if obs > sim.mean() + 2 * sim.std():
        print("    -> 산탄잡음보다 크다. 히트를 늘려도 안 줄어드는 성분이 있다 (온도 드리프트 의심).")
    else:
        print("    -> 산탄잡음 수준이다. 링오실레이터 히트가 무작위가 아니라 규칙적으로 훑으면")
        print("       기대치보다 작게 나올 수 있다 (2026-09-21 단독 데이터에서 0.65 배였다).")

    # 표 차이의 모양 — 무작위면 0 근처를 오가고, 온도 드리프트면 매끄러운 활 모양이다.
    dev = t_all - t_all.mean(axis=0)
    N = HI - LO + 1
    step = max(1, N // 10)
    print("\n[4] 런별 표 편차의 모양 (탭 구간 평균, ps) — 활 모양이면 드리프트를 의심한다")
    hdr = "        " + "".join(f"{LO + a:>8d}" for a in range(0, N, step))
    print(hdr)
    for k, (name, _, _) in enumerate(runs):
        row = "".join(f"{dev[k][a:a + step].mean():+8.2f}" for a in range(0, N, step))
        print(f"  run{k + 1:<3d} {row}")

    if all(t is not None for t in T) and len(runs) >= 3:
        Tv = np.array(T, float)
        if Tv.ptp() > 0.05:
            m = (dev @ hits) / hits.sum()          # 런별 표 평균 편차 [ps]
            r = np.corrcoef(Tv, m)[0, 1]
            print(f"\n[5] 온도 {Tv.min():.2f}~{Tv.max():.2f} C 와 표 평균편차의 상관 r = {r:+.2f}"
                  f"  ({'온도 의존 있음' if abs(r) > 0.7 else '뚜렷하지 않음'})")
        else:
            print(f"\n[5] 온도 변화가 {Tv.ptp():.2f} C 뿐이라 온도 의존은 판정하지 않는다.")
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
